#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/30/2020(m/d/y) 06:26:36 UTC from "Harvest" data

auto_ah = [
	"Abandoned Wealth",
	"Alchemy Shard",
	"Alluring Bounty",
	"Alteration Shard",
	"Ancient Orb",
	"Armourer's Scrap",
	"Awakened Sextant",
	"Binding Shard",
	"Blacksmith's Whetstone",
	"Blessed Orb",
	"Cartographer's Chisel",
	"Chaos Orb",
	"Chaos Shard",
	"Chaotic Disposition",
	"Chromatic Orb",
	"Coveted Possession",
	"Demigod's Wager",
	"Divine Orb",
	"Emperor's Luck",
	"Engineer's Orb",
	"Engineer's Shard",
	"Exalted Orb",
	"Gemcutter's Prism",
	"Glassblower's Bauble",
	"Harmony of Souls",
	"Horizon Shard",
	"House of Mirrors",
	"Loyalty",
	"Lucky Connections",
	"Lucky Deck",
	"Monochrome",
	"No Traces",
	"Orb of Alchemy",
	"Orb of Alteration",
	"Orb of Annulment",
	"Orb of Augmentation",
	"Orb of Binding",
	"Orb of Chance",
	"Orb of Fusing",
	"Orb of Horizons",
	"Orb of Regret",
	"Orb of Scouring",
	"Orb of Transmutation",
	"Perandus Coin",
	"Prime Sextant",
	"Rain of Chaos",
	"Regal Orb",
	"Regal Shard",
	"Seven Years Bad Luck",
	"Silver Coin",
	"Simple Sextant",
	"The Cacophony",
	"The Cartographer",
	"The Catalyst",
	"The Fishmonger",
	"The Fool",
	"The Gemcutter",
	"The Heroic Shot",
	"The Hoarder",
	"The Innocent",
	"The Inventor",
	"The Journey",
	"The Long Con",
	"The Master Artisan",
	"The Puzzle",
	"The Saint's Treasure",
	"The Scholar",
	"The Seeker",
	"The Sephirot",
	"The Survivalist",
	"The Tinkerer's Table",
	"The Union",
	"The Wrath",
	"Three Faces in the Dark",
	"Three Voices",
	"Underground Forest",
	"Vaal Orb",
	"Vinia's Token"
]
