#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/30/2020(m/d/y) 06:26:36 UTC from "Harvest" data

desc = "Challenge Autogen"

# Base type : settings pair
items = {
	"0 Complete Rare Unidentified Maps - Tier 1": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 1'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 10": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 10'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 11": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 11'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 12": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 12'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 13": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 13'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 14": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 14'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 15": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 15'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 16": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 16'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 2": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 2'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 3": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 3'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 4": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 4'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 6": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 6'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 8": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 8'], 'type': 'challenge high'},
	"0 Complete Rare Unidentified Maps - Tier 9": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 9'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 1": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 1'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 10": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 10'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 11": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 11'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 12": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 12'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 13": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 13'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 14": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 14'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 15": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 15'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 16": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 16'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 5": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 5'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 6": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 6'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 7": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 7'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 8": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 8'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 9": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 9'], 'type': 'challenge high'},
	"0 Complete Unique Maps - Acton's Nightmare": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Overgrown Shrine Map'},
	"0 Complete Unique Maps - Caer Blaidd, Wolfpack's Den": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Underground River Map'},
	"0 Complete Unique Maps - Death and Taxes": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Necropolis Map'},
	"0 Complete Unique Maps - Doryani's Machinarium": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Maze Map'},
	"0 Complete Unique Maps - Hall of Grandmasters": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Promenade Map'},
	"0 Complete Unique Maps - Hallowed Ground": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Cemetery Map'},
	"0 Complete Unique Maps - Maelström of Chaos": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Atoll Map'},
	"0 Complete Unique Maps - Mao Kun": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Shore Map'},
	"0 Complete Unique Maps - Oba's Cursed Trove": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Underground Sea Map'},
	"0 Complete Unique Maps - Olmec's Sanctum": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Bone Crypt Map'},
	"0 Complete Unique Maps - Perandus Manor": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Chateau Map'},
	"0 Complete Unique Maps - Pillars of Arun": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Dunes Map'},
	"0 Complete Unique Maps - Poorjoy's Asylum": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Temple Map'},
	"0 Complete Unique Maps - The Coward's Trial": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Cursed Crypt Map'},
	"0 Complete Unique Maps - The Putrid Cloister": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Museum Map'},
	"0 Complete Unique Maps - The Vinktar Square": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Courtyard Map'},
	"0 Complete Unique Maps - Vaults of Atziri": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Vaal Pyramid Map'},
	"0 Complete Unique Maps - Whakawairua Tuahu": {'other': ['Rarity Unique'], 'type': 'challenge high', 'baseexact': 'Strand Map'},
	"0 Turn in Divination Cards - A Familiar Call": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'A Familiar Call'},
	"0 Turn in Divination Cards - A Mother's Parting Gift": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "A Mother's Parting Gift"},
	"0 Turn in Divination Cards - A Note in the Wind": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'A Note in the Wind'},
	"0 Turn in Divination Cards - Akil's Prophecy": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Akil's Prophecy"},
	"0 Turn in Divination Cards - Arrogance of the Vaal": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Arrogance of the Vaal'},
	"0 Turn in Divination Cards - Azyran's Reward": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Azyran's Reward"},
	"0 Turn in Divination Cards - Beauty Through Death": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Beauty Through Death'},
	"0 Turn in Divination Cards - Dark Dreams": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Dark Dreams'},
	"0 Turn in Divination Cards - Deathly Designs": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Deathly Designs'},
	"0 Turn in Divination Cards - Dialla's Subjugation": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Dialla's Subjugation"},
	"0 Turn in Divination Cards - Echoes of Love": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Echoes of Love'},
	"0 Turn in Divination Cards - Etched in Blood": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Etched in Blood'},
	"0 Turn in Divination Cards - Friendship": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Friendship'},
	"0 Turn in Divination Cards - Gemcutter's Promise": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Gemcutter's Promise"},
	"0 Turn in Divination Cards - Gift of Asenath": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Gift of Asenath'},
	"0 Turn in Divination Cards - Gift of the Gemling Queen": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Gift of the Gemling Queen'},
	"0 Turn in Divination Cards - Grave Knowledge": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Grave Knowledge'},
	"0 Turn in Divination Cards - Immortal Resolve": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Immortal Resolve'},
	"0 Turn in Divination Cards - Nook's Crown": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Nook's Crown"},
	"0 Turn in Divination Cards - Peaceful Moments": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Peaceful Moments'},
	"0 Turn in Divination Cards - Perfection": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Perfection'},
	"0 Turn in Divination Cards - Prometheus' Armoury": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "Prometheus' Armoury"},
	"0 Turn in Divination Cards - Shard of Fate": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Shard of Fate'},
	"0 Turn in Divination Cards - The Artist": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Artist'},
	"0 Turn in Divination Cards - The Awakened": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Awakened'},
	"0 Turn in Divination Cards - The Bones": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Bones'},
	"0 Turn in Divination Cards - The Cataclysm": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Cataclysm'},
	"0 Turn in Divination Cards - The Celestial Stone": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Celestial Stone'},
	"0 Turn in Divination Cards - The Cheater": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Cheater'},
	"0 Turn in Divination Cards - The Craving": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Craving'},
	"0 Turn in Divination Cards - The Demon": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Demon'},
	"0 Turn in Divination Cards - The Doppelganger": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Doppelganger'},
	"0 Turn in Divination Cards - The Dragon's Heart": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "The Dragon's Heart"},
	"0 Turn in Divination Cards - The Endurance": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Endurance'},
	"0 Turn in Divination Cards - The Enlightened": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Enlightened'},
	"0 Turn in Divination Cards - The Eye of the Dragon": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Eye of the Dragon'},
	"0 Turn in Divination Cards - The Fox": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Fox'},
	"0 Turn in Divination Cards - The Garish Power": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Garish Power'},
	"0 Turn in Divination Cards - The Greatest Intentions": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Greatest Intentions'},
	"0 Turn in Divination Cards - The Hale Heart": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Hale Heart'},
	"0 Turn in Divination Cards - The Hive of Knowledge": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Hive of Knowledge'},
	"0 Turn in Divination Cards - The Iron Bard": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Iron Bard'},
	"0 Turn in Divination Cards - The Jeweller's Boon": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "The Jeweller's Boon"},
	"0 Turn in Divination Cards - The Lord of Celebration": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Lord of Celebration'},
	"0 Turn in Divination Cards - The Mad King": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Mad King'},
	"0 Turn in Divination Cards - The Mountain": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Mountain'},
	"0 Turn in Divination Cards - The Old Man": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Old Man'},
	"0 Turn in Divination Cards - The Price of Loyalty": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Price of Loyalty'},
	"0 Turn in Divination Cards - The Primordial": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Primordial'},
	"0 Turn in Divination Cards - The Realm": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Realm'},
	"0 Turn in Divination Cards - The Rite of Elements": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Rite of Elements'},
	"0 Turn in Divination Cards - The Samurai's Eye": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': "The Samurai's Eye"},
	"0 Turn in Divination Cards - The Side Quest": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Side Quest'},
	"0 Turn in Divination Cards - The Skeleton": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Skeleton'},
	"0 Turn in Divination Cards - The Strategist": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Strategist'},
	"0 Turn in Divination Cards - The Summoner": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Summoner'},
	"0 Turn in Divination Cards - The Sustenance": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Sustenance'},
	"0 Turn in Divination Cards - The Undisputed": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Undisputed'},
	"0 Turn in Divination Cards - The Valley of Steel Boxes": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Valley of Steel Boxes'},
	"0 Turn in Divination Cards - The White Knight": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The White Knight'},
	"0 Turn in Divination Cards - The Wilted Rose": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'The Wilted Rose'},
	"0 Turn in Divination Cards - Turn the Other Cheek": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Turn the Other Cheek'},
	"0 Turn in Divination Cards - Vile Power": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Vile Power'},
	"0 Turn in Divination Cards - Void of the Elements": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Void of the Elements'},
	"0 Turn in Divination Cards - Volatile Power": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Volatile Power'},
	"0 Turn in Divination Cards - Wealth and Power": {'class': 'Divination Card', 'type': 'challenge high', 'baseexact': 'Wealth and Power'},
}
