clusternames = {
	"Area Damage": ['10% increased Area Damage'],
	"Armour": ['15% increased Armour'],
	"Attack Damage": ['10% increased Attack Damage'],
	"Attack Damage while Dual Wielding": ['12% increased Attack Damage while Dual Wielding'],
	"Attack Damage while holding a Shield": ['12% increased Attack Damage while holding a Shield'],
	"Aura Effect": ['3% increased effect of Non-Curse Auras from your Skills'],
	"Axe and Sword Damage": ['Axe Attacks deal 12% increased Damage with Hits and Ailments', 'Sword Attacks deal 12% increased Damage with Hits and Ailments'],
	"Bow Damage": ['12% increased Damage with Bows', '12% increased Damage Over Time with Bow Skills'],
	"Brand Damage": ['12% increased Brand Damage'],
	"Chance to Block Attack Damage": ['1% Chance to Block Attack Damage'],
	"Chance to Block Spell Damage": ['1% Chance to Block Spell Damage'],
	"Chance to Suppress Spell Damage": ['2% chance to Suppress Spell Damage'],
	"Channelling Skill Damage": ['Channelling Skills deal 12% increased Damage'],
	"Chaos Damage": ['12% increased Chaos Damage'],
	"Chaos Damage over Time": ['12% increased Chaos Damage over Time'],
	"Chaos Resistance": ['12% to Chaos Resistance'],
	"Cold Damage": ['12% increased Cold Damage'],
	"Cold Damage over Time": ['12% increased Cold Damage over Time'],
	"Cold Resistance": ['15% to Cold Resistance'],
	"Critical Chance": ['15% increased Critical Strike Chance'],
	"Curse Effect": ['3% increased Effect of your Curses'],
	"Dagger and Claw Damage": ['Claw Attacks deal 12% increased Damage with Hits and Ailments', 'Dagger Attacks deal 12% increased Damage with Hits and Ailments'],
	"Damage over Time": ['10% increased Damage over Time'],
	"Damage while you have a Herald": ['10% increased Damage while affected by a Herald'],
	"Damage with Two Handed Melee Weapons": ['12% increased Damage with Two Handed Weapons'],
	"Effect of Non-Damaging Ailments": ['10% increased Effect of Non-Damaging Ailments'],
	"Elemental Damage": ['10% increased Elemental Damage'],
	"Energy Shield": ['6% increased maximum Energy Shield'],
	"Evasion": ['15% increased Evasion Rating'],
	"Exerted Attack Damage": ['Exerted Attacks deal 20% increased Damage'],
	"Fire Damage": ['12% increased Fire Damage'],
	"Fire Damage over Time": ['12% increased Burning Damage'],
	"Fire Resistance": ['15% to Fire Resistance'],
	"Flask Duration": ['6% increased Flask Effect Duration'],
	"Life": ['4% increased maximum Life'],
	"Life and Mana recovery from Flasks": ['10% increased Life Recovery from Flasks', '10% increased Mana Recovery from Flasks'],
	"Lightning Damage": ['12% increased Lightning Damage'],
	"Lightning Resistance": ['15% to Lightning Resistance'],
	"Mace and Staff Damage": ['Mace or Sceptre Attacks deal 12% increased Damage with Hits and Ailments', 'Staff Attacks deal 12% increased Damage with Hits and Ailments'],
	"Mana": ['6% increased maximum Mana'],
	"Minion Damage": ['Minions deal 10% increased Damage'],
	"Minion Damage while you have a Herald": ['Minions deal 10% increased Damage while you are affected by a Herald'],
	"Minion Life": ['Minions have 12% increased maximum Life'],
	"Physical Damage": ['12% increased Physical Damage'],
	"Physical Damage over Time": ['12% increased Physical Damage over Time'],
	"Projectile Damage": ['10% increased Projectile Damage'],
	"Reservation Efficiency": ['6% increased Mana Reservation Efficiency of Skills'],
	"Spell Damage": ['10% increased Spell Damage'],
	"Totem Damage": ['12% increased Totem Damage'],
	"Trap and Mine Damage": ['12% increased Mine Damage', '12% increased Trap Damage'],
	"Wand Damage": ['Wand Attacks deal 12% increased Damage with Hits and Ailments'],
}