#!/usr/bin/python
# -*- coding: utf-8 -*-
# Author: Jeremy Parks
# Note: Requires Python 3.3.x or higher
desc = "Crafting Bases"

# Base type : settings pair
items = {
	"0 Void Sceptre": {"base": "Void Sceptre", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Opal Sceptre": {"base": "Opal Sceptre", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Profane Wand": {"base": "Profane Wand", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Opal Wand": {"base": "Opal Wand", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Imbued Wand": {"base": "Imbued Wand", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Vaal Regalia": {"base": "Vaal Regalia", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Hubris Circlet": {"base": "Hubris Circlet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Saintly Chainmail": {"base": "Saintly Chainmail", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Harmonic Spirit Shield": {"base": "Harmonic Spirit Shield", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Slink Gloves": {"base": "Slink Gloves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Lion Pelt": {"base": "Lion Pelt", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Titan Greaves": {"base": "Titan Greaves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Slink Boots": {"base": "Slink Boots", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare high"},
	"0 Bone Helmet": {"base": "Bone Helmet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Spiked Gloves": {"base": "Spiked Gloves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Gripped Gloves": {"base": "Gripped Gloves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Fingerless Silk Gloves": {"base": "Fingerless Silk Gloves", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},

	"0 Coral Ring": {"base": "Coral Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Ruby Ring": {"base": "Ruby Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Sapphire Ring": {"base": "Sapphire Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Topaz Ring": {"base": "Topaz Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Diamond Ring": {"base": "Diamond Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Prismatic Ring": {"base": "Prismatic Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Unset Ring": {"base": "Unset Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Gold Ring": {"base": "Gold Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Moonstone Ring": {"base": "Moonstone Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Onyx Amulet": {"base": "Onyx Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Gold Amulet": {"base": "Gold Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Citrine Amulet": {"base": "Citrine Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Agate Amulet": {"base": "Agate Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Amber Amulet": {"base": "Amber Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Jade Amulet": {"base": "Jade Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Lapis Amulet": {"base": "Lapis Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Leather Belt": {"base": "Leather Belt", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Heavy Belt": {"base": "Heavy Belt", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Rustic Sash": {"base": "Rustic Sash", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Marble Amulet": {"base": "Marble Amulet", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Vanguard Belt": {"base": "Vanguard Belt", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},
	"0 Crystal Belt": {"base": "Crystal Belt", "other": ["ItemLevel >= 84"], "type": "t1 83/84 rare highlight"},

	"0 Lion Sword": {"base": "Lion Sword", "other": ["ItemLevel >= 83"], "type": "ignore"},
	"0 Vaal Greatsword": {"base": "Vaal Greatsword", "other": ["ItemLevel >= 83"], "type": "ignore"},
	"0 Vaal Axe": {"base": "Vaal Axe", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Coronal Maul": {"base": "Coronal Maul", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Exquisite Blade": {"base": "Exquisite Blade", "other": ["ItemLevel >= 83"], "type": "ignore"},
	"0 Fleshripper": {"base": "Fleshripper", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Harbinger Bow": {"base": "Harbinger Bow", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Gemini Claw": {"base": "Gemini Claw", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Ambusher": {"base": "Ambusher", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Platinum Kris": {"base": "Platinum Kris", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Demon Dagger": {"base": "Demon Dagger", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Imperial Skean": {"base": "Imperial Skean", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Vaal Hatchet": {"base": "Vaal Hatchet", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Runic Hatchet": {"base": "Runic Hatchet", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Behemoth Mace": {"base": "Behemoth Mace", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Eternal Sword": {"base": "Eternal Sword", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Tiger Hook": {"base": "Tiger Hook", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Eclipse Staff": {"base": "Eclipse Staff", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Maelström Staff": {"base": "Maelström Staff", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Judgement Staff": {"base": "Judgement Staff", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Jewelled Foil": {"base": "Jewelled Foil", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Dragoon Sword": {"base": "Dragoon Sword", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},
	"0 Sai": {"base": "Sai", "class": "Dagger", "other": ["ItemLevel >= 83"], "type": "t1 83/84 rare high"},

	"9 Other bases": {"type": "ignore"}
}