#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 12/15/2019(m/d/y) 05:21:43 UTC from "Metamorph" data

auto_ah = [
	"Alchemy Shard",
	"Alteration Shard",
	"Ancient Orb",
	"Armourer's Scrap",
	"Awakened Sextant",
	"Binding Shard",
	"Blacksmith's Whetstone",
	"Blessed Orb",
	"Cartographer's Chisel",
	"Chaos Orb",
	"Chaos Shard",
	"Chromatic Orb",
	"Divine Orb",
	"Engineer's Orb",
	"Engineer's Shard",
	"Exalted Orb",
	"Gemcutter's Prism",
	"Glassblower's Bauble",
	"Horizon Shard",
	"Jeweller's Orb",
	"Orb of Alchemy",
	"Orb of Alteration",
	"Orb of Annulment",
	"Orb of Augmentation",
	"Orb of Binding",
	"Orb of Chance",
	"Orb of Fusing",
	"Orb of Horizons",
	"Orb of Regret",
	"Orb of Scouring",
	"Orb of Transmutation",
	"Perandus Coin",
	"Prime Sextant",
	"Regal Orb",
	"Regal Shard",
	"Silver Coin",
	"Simple Sextant",
	"Vaal Orb"
]
