#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 10/20/2019(m/d/y) 06:11:41 UTC from "Blight" data

auto_ah = [
	"Alchemy Shard",
	"Alteration Shard",
	"Ancient Orb",
	"Apprentice Cartographer's Sextant",
	"Armourer's Scrap",
	"Binding Shard",
	"Blacksmith's Whetstone",
	"Blessed Orb",
	"Cartographer's Chisel",
	"Chaos Orb",
	"Chaos Shard",
	"Chromatic Orb",
	"Engineer's Orb",
	"Engineer's Shard",
	"Exalted Orb",
	"Gemcutter's Prism",
	"Glassblower's Bauble",
	"Horizon Shard",
	"Jeweller's Orb",
	"Journeyman Cartographer's Sextant",
	"Master Cartographer's Sextant",
	"Orb of Alchemy",
	"Orb of Alteration",
	"Orb of Annulment",
	"Orb of Augmentation",
	"Orb of Binding",
	"Orb of Chance",
	"Orb of Fusing",
	"Orb of Horizons",
	"Orb of Regret",
	"Orb of Scouring",
	"Orb of Transmutation",
	"Perandus Coin",
	"Portal Scroll",
	"Regal Orb",
	"Regal Shard",
	"Scroll of Wisdom",
	"Silver Coin",
	"Vaal Orb"
]
