#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 11/24/2018(m/d/y) 01:08:08 UTC from "Standard" data

desc = "Bases"

# Base type : settings pair
items = {
	"0 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Amethyst Ring": {"base": "Amethyst Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Chain Belt": {"base": "Chain Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Cloth Belt": {"base": "Cloth Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Corsair Sword": {"base": "Corsair Sword", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Dragonbone Rapier": {"base": "Dragonbone Rapier", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fancy Foil": {"base": "Fancy Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Gold Ring": {"base": "Gold Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Goliath Greaves": {"base": "Goliath Greaves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Harpy Rapier": {"base": "Harpy Rapier", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Necromancer Circlet": {"base": "Necromancer Circlet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Noble Claw": {"base": "Noble Claw", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Ring": {"base": "Opal Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Rustic Sash": {"base": "Rustic Sash", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Samite Helmet": {"base": "Samite Helmet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Shagreen Boots": {"base": "Shagreen Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Siege Axe": {"base": "Siege Axe", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slaughter Knife": {"base": "Slaughter Knife", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Spiraled Foil": {"base": "Spiraled Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Studded Belt": {"base": "Studded Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Thicket Bow": {"base": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Axe": {"base": "Vaal Axe", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Chain Belt": {"base": "Chain Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Dragonbone Rapier": {"base": "Dragonbone Rapier", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Imbued Wand": {"base": "Imbued Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Jewelled Foil": {"base": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Regicide Mask": {"base": "Regicide Mask", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Rustic Sash": {"base": "Rustic Sash", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Siege Axe": {"base": "Siege Axe", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Steel Ring": {"base": "Steel Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Thicket Bow": {"base": "Thicket Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Ursine Pelt": {"base": "Ursine Pelt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vaal Regalia": {"base": "Vaal Regalia", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Wyrmscale Boots": {"base": "Wyrmscale Boots", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Bone Helmet": {"base": "Bone Helmet", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Crystal Belt": {"base": "Crystal Belt", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Fingerless Silk Gloves": {"base": "Fingerless Silk Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Ghastly Eye Jewel": {"base": "Ghastly Eye Jewel", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Gripped Gloves": {"base": "Gripped Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Hydrascale Boots": {"base": "Hydrascale Boots", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Hypnotic Eye Jewel": {"base": "Hypnotic Eye Jewel", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Jewelled Foil": {"base": "Jewelled Foil", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Marble Amulet": {"base": "Marble Amulet", "other": ["ItemLevel >= 86"], "type": "base extremely high"},
	"0 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel >= 86"], "type": "base extremely high"},
	"0 Onyx Amulet": {"base": "Onyx Amulet", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel >= 86"], "type": "base extremely high"},
	"0 Prismatic Ring": {"base": "Prismatic Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Slink Boots": {"base": "Slink Boots", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Spiked Gloves": {"base": "Spiked Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Stygian Vise": {"base": "Stygian Vise", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"1 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Amethyst Ring": {"base": "Amethyst Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ancient Gauntlets": {"base": "Ancient Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Assassin's Garb": {"base": "Assassin's Garb", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Astral Plate": {"base": "Astral Plate", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Chain Belt": {"base": "Chain Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Citadel Bow": {"base": "Citadel Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Cloth Belt": {"base": "Cloth Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Corsair Sword": {"base": "Corsair Sword", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Crusader Buckler": {"base": "Crusader Buckler", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Dragonbone Rapier": {"base": "Dragonbone Rapier", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Eagle Claw": {"base": "Eagle Claw", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Exquisite Blade": {"base": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ezomyte Dagger": {"base": "Ezomyte Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fire Arrow Quiver": {"base": "Fire Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gemstone Sword": {"base": "Gemstone Sword", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gold Ring": {"base": "Gold Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Golden Plate": {"base": "Golden Plate", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Great White Claw": {"base": "Great White Claw", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gutting Knife": {"base": "Gutting Knife", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Harbinger Bow": {"base": "Harbinger Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Harpy Rapier": {"base": "Harpy Rapier", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Hydrascale Boots": {"base": "Hydrascale Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Hydrascale Gauntlets": {"base": "Hydrascale Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imperial Claw": {"base": "Imperial Claw", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Karui Axe": {"base": "Karui Axe", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lacquered Helmet": {"base": "Lacquered Helmet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Legion Gloves": {"base": "Legion Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Noble Claw": {"base": "Noble Claw", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Paua Ring": {"base": "Paua Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Burgonet": {"base": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Skean": {"base": "Royal Skean", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Runic Hatchet": {"base": "Runic Hatchet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Rustic Sash": {"base": "Rustic Sash", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sai": {"base": "Sai", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Samite Helmet": {"base": "Samite Helmet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Shagreen Boots": {"base": "Shagreen Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Siege Axe": {"base": "Siege Axe", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Slaughter Knife": {"base": "Slaughter Knife", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Solaris Circlet": {"base": "Solaris Circlet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Soldier Gloves": {"base": "Soldier Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Spiraled Foil": {"base": "Spiraled Foil", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Studded Belt": {"base": "Studded Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Terror Claw": {"base": "Terror Claw", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Thicket Bow": {"base": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titan Greaves": {"base": "Titan Greaves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ursine Pelt": {"base": "Ursine Pelt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vaal Axe": {"base": "Vaal Axe", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Apex Rapier": {"base": "Apex Rapier", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Assassin's Garb": {"base": "Assassin's Garb", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Behemoth Mace": {"base": "Behemoth Mace", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Branded Kite Shield": {"base": "Branded Kite Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Carnal Mitts": {"base": "Carnal Mitts", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Chain Belt": {"base": "Chain Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Colossal Tower Shield": {"base": "Colossal Tower Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Coronal Maul": {"base": "Coronal Maul", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Corsair Sword": {"base": "Corsair Sword", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Crusader Buckler": {"base": "Crusader Buckler", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Decimation Bow": {"base": "Decimation Bow", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Demon's Horn": {"base": "Demon's Horn", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Destiny Leather": {"base": "Destiny Leather", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Dragonscale Boots": {"base": "Dragonscale Boots", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eclipse Staff": {"base": "Eclipse Staff", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Eye Gouger": {"base": "Eye Gouger", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Fancy Foil": {"base": "Fancy Foil", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Fiend Dagger": {"base": "Fiend Dagger", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Fleshripper": {"base": "Fleshripper", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gemini Claw": {"base": "Gemini Claw", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gemstone Sword": {"base": "Gemstone Sword", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder General's Brigandine": {"base": "General's Brigandine", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gold Amulet": {"base": "Gold Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Great Crown": {"base": "Great Crown", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Harbinger Bow": {"base": "Harbinger Bow", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Harmonic Spirit Shield": {"base": "Harmonic Spirit Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Hydrascale Boots": {"base": "Hydrascale Boots", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Hydrascale Gauntlets": {"base": "Hydrascale Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Imbued Wand": {"base": "Imbued Wand", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Imperial Claw": {"base": "Imperial Claw", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Imperial Skean": {"base": "Imperial Skean", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Infernal Axe": {"base": "Infernal Axe", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Ironwood Buckler": {"base": "Ironwood Buckler", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Jewelled Foil": {"base": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Karui Sceptre": {"base": "Karui Sceptre", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lacquered Helmet": {"base": "Lacquered Helmet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Legion Boots": {"base": "Legion Boots", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Legion Gloves": {"base": "Legion Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lion Pelt": {"base": "Lion Pelt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Magistrate Crown": {"base": "Magistrate Crown", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Platinum Kris": {"base": "Platinum Kris", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Praetor Crown": {"base": "Praetor Crown", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Rustic Sash": {"base": "Rustic Sash", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Saintly Chainmail": {"base": "Saintly Chainmail", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Siege Axe": {"base": "Siege Axe", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Siege Helmet": {"base": "Siege Helmet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Slaughter Knife": {"base": "Slaughter Knife", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Slink Boots": {"base": "Slink Boots", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Slink Gloves": {"base": "Slink Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Solaris Circlet": {"base": "Solaris Circlet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Titan Greaves": {"base": "Titan Greaves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Tornado Wand": {"base": "Tornado Wand", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Vaal Axe": {"base": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Vaal Regalia": {"base": "Vaal Regalia", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Void Sceptre": {"base": "Void Sceptre", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Wyrmscale Gauntlets": {"base": "Wyrmscale Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Ambusher": {"base": "Ambusher", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Ancient Gauntlets": {"base": "Ancient Gauntlets", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Ghastly Eye Jewel": {"base": "Ghastly Eye Jewel", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Hypnotic Eye Jewel": {"base": "Hypnotic Eye Jewel", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Imbued Wand": {"base": "Imbued Wand", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Imperial Claw": {"base": "Imperial Claw", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Imperial Skean": {"base": "Imperial Skean", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Karui Sceptre": {"base": "Karui Sceptre", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Legion Gloves": {"base": "Legion Gloves", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Marble Amulet": {"base": "Marble Amulet", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel 85"], "type": "base extremely high"},
	"1 Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Slaughter Knife": {"base": "Slaughter Knife", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Vanguard Belt": {"base": "Vanguard Belt", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Void Sceptre": {"base": "Void Sceptre", "other": ["ItemLevel 85"], "type": "base very high"},
	"2 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Amethyst Ring": {"base": "Amethyst Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Cloth Belt": {"base": "Cloth Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Corsair Sword": {"base": "Corsair Sword", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Demon's Horn": {"base": "Demon's Horn", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fancy Foil": {"base": "Fancy Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Gemini Claw": {"base": "Gemini Claw", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Gold Ring": {"base": "Gold Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Harpy Rapier": {"base": "Harpy Rapier", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Hydrascale Gauntlets": {"base": "Hydrascale Gauntlets", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Legion Gloves": {"base": "Legion Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Platinum Sceptre": {"base": "Platinum Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Prophecy Wand": {"base": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Royal Burgonet": {"base": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Rustic Sash": {"base": "Rustic Sash", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Samite Helmet": {"base": "Samite Helmet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Serrated Foil": {"base": "Serrated Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Shagreen Boots": {"base": "Shagreen Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Siege Axe": {"base": "Siege Axe", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Slink Boots": {"base": "Slink Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Slink Gloves": {"base": "Slink Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Thicket Bow": {"base": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Vaal Sceptre": {"base": "Vaal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Assassin's Garb": {"base": "Assassin's Garb", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Behemoth Mace": {"base": "Behemoth Mace", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Carnal Armour": {"base": "Carnal Armour", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Chain Belt": {"base": "Chain Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Cloth Belt": {"base": "Cloth Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Coral Amulet": {"base": "Coral Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Crusader Gloves": {"base": "Crusader Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Destiny Leather": {"base": "Destiny Leather", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Gemini Claw": {"base": "Gemini Claw", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Gladiator Plate": {"base": "Gladiator Plate", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Harbinger Bow": {"base": "Harbinger Bow", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Jewelled Foil": {"base": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Legion Gloves": {"base": "Legion Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Lion Pelt": {"base": "Lion Pelt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Magistrate Crown": {"base": "Magistrate Crown", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Necromancer Circlet": {"base": "Necromancer Circlet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Noble Tricorne": {"base": "Noble Tricorne", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Rustic Sash": {"base": "Rustic Sash", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Shagreen Boots": {"base": "Shagreen Boots", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sharkskin Gloves": {"base": "Sharkskin Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Slink Boots": {"base": "Slink Boots", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Solaris Circlet": {"base": "Solaris Circlet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Thicket Bow": {"base": "Thicket Bow", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Titan Greaves": {"base": "Titan Greaves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Vaal Axe": {"base": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Void Sceptre": {"base": "Void Sceptre", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Wyrmscale Gauntlets": {"base": "Wyrmscale Gauntlets", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Arcanist Gloves": {"base": "Arcanist Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Ezomyte Dagger": {"base": "Ezomyte Dagger", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Fingerless Silk Gloves": {"base": "Fingerless Silk Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Gripped Gloves": {"base": "Gripped Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Hypnotic Eye Jewel": {"base": "Hypnotic Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Imperial Claw": {"base": "Imperial Claw", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Lacquered Buckler": {"base": "Lacquered Buckler", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Marble Amulet": {"base": "Marble Amulet", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Ruby Ring": {"base": "Ruby Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel 84"], "type": "base extremely high"},
	"2 Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Sharkskin Gloves": {"base": "Sharkskin Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Soldier Gloves": {"base": "Soldier Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Spiked Gloves": {"base": "Spiked Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Unset Ring": {"base": "Unset Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Vaal Greaves": {"base": "Vaal Greaves", "other": ["ItemLevel 84"], "type": "base very high"},
	"3 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Ambusher": {"base": "Ambusher", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Astral Plate": {"base": "Astral Plate", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Carnal Mitts": {"base": "Carnal Mitts", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Corsair Sword": {"base": "Corsair Sword", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Demon's Horn": {"base": "Demon's Horn", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Dragonbone Rapier": {"base": "Dragonbone Rapier", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Fancy Foil": {"base": "Fancy Foil", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Gold Ring": {"base": "Gold Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Great White Claw": {"base": "Great White Claw", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Harbinger Bow": {"base": "Harbinger Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Harpy Rapier": {"base": "Harpy Rapier", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Imperial Claw": {"base": "Imperial Claw", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Noble Claw": {"base": "Noble Claw", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Platinum Sceptre": {"base": "Platinum Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Royal Burgonet": {"base": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Royal Skean": {"base": "Royal Skean", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Rustic Sash": {"base": "Rustic Sash", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sai": {"base": "Sai", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Slink Boots": {"base": "Slink Boots", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Slink Gloves": {"base": "Slink Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Studded Belt": {"base": "Studded Belt", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Terror Claw": {"base": "Terror Claw", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Vaal Sceptre": {"base": "Vaal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Chain Belt": {"base": "Chain Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Cloth Belt": {"base": "Cloth Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Coral Amulet": {"base": "Coral Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Fiend Dagger": {"base": "Fiend Dagger", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Fleshripper": {"base": "Fleshripper", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gemini Claw": {"base": "Gemini Claw", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gold Amulet": {"base": "Gold Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Great Crown": {"base": "Great Crown", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Imperial Claw": {"base": "Imperial Claw", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jewelled Foil": {"base": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Karui Sceptre": {"base": "Karui Sceptre", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Murder Mitts": {"base": "Murder Mitts", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Rustic Sash": {"base": "Rustic Sash", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sai": {"base": "Sai", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sharkskin Tunic": {"base": "Sharkskin Tunic", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Siege Axe": {"base": "Siege Axe", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Solaris Circlet": {"base": "Solaris Circlet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Void Sceptre": {"base": "Void Sceptre", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Hypnotic Eye Jewel": {"base": "Hypnotic Eye Jewel", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Imperial Claw": {"base": "Imperial Claw", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Legion Gloves": {"base": "Legion Gloves", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Marble Amulet": {"base": "Marble Amulet", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel 83"], "type": "base very high"},
	"3 Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ItemLevel 83"], "type": "base very high"},
	"4 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Amethyst Ring": {"base": "Amethyst Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Chain Belt": {"base": "Chain Belt", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Ezomyte Dagger": {"base": "Ezomyte Dagger", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Great White Claw": {"base": "Great White Claw", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Harlequin Mask": {"base": "Harlequin Mask", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Legion Gloves": {"base": "Legion Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Platinum Sceptre": {"base": "Platinum Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Siege Axe": {"base": "Siege Axe", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Tenderizer": {"base": "Tenderizer", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Tornado Wand": {"base": "Tornado Wand", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Ursine Pelt": {"base": "Ursine Pelt", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Cloth Belt": {"base": "Cloth Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Gemini Claw": {"base": "Gemini Claw", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Lion Pelt": {"base": "Lion Pelt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Magistrate Crown": {"base": "Magistrate Crown", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Regicide Mask": {"base": "Regicide Mask", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Studded Belt": {"base": "Studded Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Ursine Pelt": {"base": "Ursine Pelt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Void Sceptre": {"base": "Void Sceptre", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Ancient Gauntlets": {"base": "Ancient Gauntlets", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Spiraled Foil": {"base": "Spiraled Foil", "other": ["ItemLevel 82"], "type": "base very high"},
	"4 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel 82"], "type": "base very high"},

}
