#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 12/16/2019(m/d/y) 00:30:30 UTC from "Metamorph" data

desc = "Challenge Autogen"

# Base type : settings pair
items = {
	"0 Complete Twinned Maps - Tier 1 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 1', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 10 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 10', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 11 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 11', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 12 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 12', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 13 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 13', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 14 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 14', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 15 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 15', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 16 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 16', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 2 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 2', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 3 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 3', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 4 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 4', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 5 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 5', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 6 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 6', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 7 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 7', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 8 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 8', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 9 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 9', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 1 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 1', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 10 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 10', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 11 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 11', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 12 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 12', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 13 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 13', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 14 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 14', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 15 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 15', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 16 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 16', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 2 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 2', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 3 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 3', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 4 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 4', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 5 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 5', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 6 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 6', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 7 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 7', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 8 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 8', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 9 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 9', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unique Maps - Acton's Nightmare - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Overgrown Shrine Map'},
	"0 Complete Unique Maps - Caer Blaidd, Wolfpack's Den - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Underground River Map'},
	"0 Complete Unique Maps - Death and Taxes - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Necropolis Map'},
	"0 Complete Unique Maps - Doryani's Machinarium - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Maze Map'},
	"0 Complete Unique Maps - Hall of Grandmasters - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Promenade Map'},
	"0 Complete Unique Maps - Hallowed Ground - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Cemetery Map'},
	"0 Complete Unique Maps - Maelström of Chaos - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Atoll Map'},
	"0 Complete Unique Maps - Mao Kun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Shore Map'},
	"0 Complete Unique Maps - Oba's Cursed Trove - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Underground Sea Map'},
	"0 Complete Unique Maps - Olmec's Sanctum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Bone Crypt Map'},
	"0 Complete Unique Maps - Perandus Manor - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Chateau Map'},
	"0 Complete Unique Maps - Pillars of Arun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Dunes Map'},
	"0 Complete Unique Maps - Poorjoy's Asylum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Temple Map'},
	"0 Complete Unique Maps - The Coward's Trial - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Cursed Crypt Map'},
	"0 Complete Unique Maps - The Putrid Cloister - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Museum Map'},
	"0 Complete Unique Maps - The Twilight Temple - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Moon Temple Map'},
	"0 Complete Unique Maps - The Vinktar Square - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Courtyard Map'},
	"0 Complete Unique Maps - Vaults of Atziri - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Vaal Pyramid Map'},
	"0 Complete Unique Maps - Whakawairua Tuahu - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Strand Map'},
	"0 Turn in Divination Cards - Bow - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Imperial Legacy'},
	"0 Turn in Divination Cards - Bow - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Porcupine'},
	"0 Turn in Divination Cards - Bow - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Blazing Fire'},
	"0 Turn in Divination Cards - Bow - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Thunderous Skies'},
	"0 Turn in Divination Cards - Bow - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Tranquillity'},
	"0 Turn in Divination Cards - Bow - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Anarchy's Price"},
	"0 Turn in Divination Cards - Bow - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': "Hunter's Resolve"},
	"0 Turn in Divination Cards - Corrupted Gem - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "The Dragon's Heart"},
	"0 Turn in Divination Cards - Corrupted Gem - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Artist'},
	"0 Turn in Divination Cards - Corrupted Gem - 10": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Volatile Power'},
	"0 Turn in Divination Cards - Corrupted Gem - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Wealth and Power'},
	"0 Turn in Divination Cards - Corrupted Gem - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Skeleton'},
	"0 Turn in Divination Cards - Corrupted Gem - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Wilted Rose'},
	"0 Turn in Divination Cards - Corrupted Gem - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Rite of Elements'},
	"0 Turn in Divination Cards - Corrupted Gem - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Cataclysm'},
	"0 Turn in Divination Cards - Corrupted Gem - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Bones'},
	"0 Turn in Divination Cards - Corrupted Gem - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Deathly Designs'},
	"0 Turn in Divination Cards - Corrupted Gem - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': "Dialla's Subjugation"},
	"0 Turn in Divination Cards - Divination Card - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Gambler'},
	"0 Turn in Divination Cards - Essence - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Harmony of Souls'},
	"0 Turn in Divination Cards - Essence - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Cacophony'},
	"0 Turn in Divination Cards - Essence - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Three Voices'},
	"0 Turn in Divination Cards - Gem - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Volatile Power'},
	"0 Turn in Divination Cards - Gem - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Dialla's Subjugation"},
	"0 Turn in Divination Cards - Gem - 10": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Doppelganger'},
	"0 Turn in Divination Cards - Gem - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': "Gemcutter's Promise"},
	"0 Turn in Divination Cards - Gem - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Summoner'},
	"0 Turn in Divination Cards - Gem - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Cataclysm'},
	"0 Turn in Divination Cards - Gem - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Gift of the Gemling Queen'},
	"0 Turn in Divination Cards - Gem - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Fox'},
	"0 Turn in Divination Cards - Gem - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Skeleton'},
	"0 Turn in Divination Cards - Gem - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Grave Knowledge'},
	"0 Turn in Divination Cards - Gem - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Realm'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Imperial Legacy'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Celestial Stone'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 10": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Undisputed'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 11": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Jester'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 12": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Merciless Armament'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 13": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Tyrant'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 14": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Spoiled Prince'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 15": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "The Archmage's Right Hand"},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 16": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Road to Power'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 17": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Void of the Elements'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Sacrifice'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Dapper Prodigy'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': "Nook's Crown"},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Destined to Crumble'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Hale Heart'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Perfection'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Opulent'},
	"0 Turn in Divination Cards - Itemlevel 100 Item - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Golden Era'},
	"0 Turn in Divination Cards - Jewel - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Mountain'},
	"0 Turn in Divination Cards - Jewel - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Azyran's Reward"},
	"0 Turn in Divination Cards - Jewel - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Garish Power'},
	"0 Turn in Divination Cards - Jewel - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Eye of the Dragon'},
	"0 Turn in Divination Cards - Jewel - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Primordial'},
	"0 Turn in Divination Cards - Jewel - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Endurance'},
	"0 Turn in Divination Cards - Jewel - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Shard of Fate'},
	"0 Turn in Divination Cards - Map - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Rain Tempter'},
	"0 Turn in Divination Cards - Map - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Boundless Realms'},
	"0 Turn in Divination Cards - Map - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Surveyor'},
	"0 Turn in Divination Cards - Map - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': "Cartographer's Delight"},
	"0 Turn in Divination Cards - Map - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Scholar of the Seas'},
	"0 Turn in Divination Cards - Map - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Dreamland'},
	"0 Turn in Divination Cards - Map - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Twilight Moon'},
	"0 Turn in Divination Cards - Map - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': "The Wolf's Legacy"},
	"0 Turn in Divination Cards - Map - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Treasure Hunter'},
	"0 Turn in Divination Cards - Map - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Encroaching Darkness'},
	"0 Turn in Divination Cards - Prophecy - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Friendship'},
	"0 Turn in Divination Cards - Prophecy - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Side Quest'},
	"0 Turn in Divination Cards - Prophecy - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Vile Power'},
	"0 Turn in Divination Cards - Prophecy - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Immortal Resolve'},
	"0 Turn in Divination Cards - Prophecy - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Valley of Steel Boxes'},
	"0 Turn in Divination Cards - Prophecy - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "The Jeweller's Boon"},
	"0 Turn in Divination Cards - Prophecy - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Mad King'},
	"0 Turn in Divination Cards - Prophecy - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Iron Bard'},
	"0 Turn in Divination Cards - Prophecy - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Beauty Through Death'},
	"0 Turn in Divination Cards - Rare Item - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': "Nook's Crown"},
	"0 Turn in Divination Cards - Rare Item - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Destined to Crumble'},
	"0 Turn in Divination Cards - Rare Item - 10": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Explorer'},
	"0 Turn in Divination Cards - Rare Item - 11": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Trial'},
	"0 Turn in Divination Cards - Rare Item - 12": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Left to Fate'},
	"0 Turn in Divination Cards - Rare Item - 13": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Call to the First Ones'},
	"0 Turn in Divination Cards - Rare Item - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Hale Heart'},
	"0 Turn in Divination Cards - Rare Item - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Perfection'},
	"0 Turn in Divination Cards - Rare Item - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Opulent'},
	"0 Turn in Divination Cards - Rare Item - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Dark Dreams'},
	"0 Turn in Divination Cards - Rare Item - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Lingering Remnants'},
	"0 Turn in Divination Cards - Rare Item - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Lantador's Lost Love"},
	"0 Turn in Divination Cards - Rare Item - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Warden'},
	"0 Turn in Divination Cards - Rare Item - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Lover'},
	"0 Turn in Divination Cards - Ring - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "The Metalsmith's Gift"},
	"0 Turn in Divination Cards - Ring - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Lantador's Lost Love"},
	"0 Turn in Divination Cards - Ring - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Opulent'},
	"0 Turn in Divination Cards - Ring - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Glimmer of Hope'},
	"0 Turn in Divination Cards - Ring - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Penitent'},
	"0 Turn in Divination Cards - Ring - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Hubris'},
	"0 Turn in Divination Cards - Ring - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Blind Venture'},
	"0 Turn in Divination Cards - Ring - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Prosperity'},
}
