#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 12/14/2019(m/d/y) 00:06:39 UTC from "Metamorph" data

desc = "Challenge Autogen"

# Base type : settings pair
items = {
	"0 Complete Twinned Maps - Tier 1 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 1', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 10 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 10', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 11 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 11', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 12 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 12', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 13 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 13', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 14 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 14', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 15 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 15', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 16 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 16', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 2 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 2', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 3 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 3', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 4 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 4', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 5 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 5', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 6 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 6', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 7 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 7', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 8 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 8', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 9 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 9', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 1 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 1', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 10 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 10', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 11 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 11', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 12 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 12', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 13 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 13', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 14 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 14', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 15 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 15', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 16 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 16', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 2 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 2', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 3 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 3', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 4 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 4', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 5 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 5', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 6 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 6', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 7 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 7', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 8 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 8', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Unidentified Maps - Tier 9 - 0": {'class': 'Maps', 'other': ['Rarity Rare', 'Identified False', 'MapTier = 9', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unique Maps - Acton's Nightmare - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Overgrown Shrine Map'},
	"0 Complete Unique Maps - Caer Blaidd, Wolfpack's Den - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Underground River Map'},
	"0 Complete Unique Maps - Death and Taxes - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Necropolis Map'},
	"0 Complete Unique Maps - Doryani's Machinarium - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Maze Map'},
	"0 Complete Unique Maps - Hall of Grandmasters - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Promenade Map'},
	"0 Complete Unique Maps - Hallowed Ground - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Cemetery Map'},
	"0 Complete Unique Maps - Maelström of Chaos - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Atoll Map'},
	"0 Complete Unique Maps - Mao Kun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Shore Map'},
	"0 Complete Unique Maps - Oba's Cursed Trove - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Underground Sea Map'},
	"0 Complete Unique Maps - Olmec's Sanctum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Bone Crypt Map'},
	"0 Complete Unique Maps - Perandus Manor - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Chateau Map'},
	"0 Complete Unique Maps - Pillars of Arun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Dunes Map'},
	"0 Complete Unique Maps - Poorjoy's Asylum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Temple Map'},
	"0 Complete Unique Maps - The Coward's Trial - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Cursed Crypt Map'},
	"0 Complete Unique Maps - The Putrid Cloister - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Museum Map'},
	"0 Complete Unique Maps - The Twilight Temple - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Moon Temple Map'},
	"0 Complete Unique Maps - The Vinktar Square - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Courtyard Map'},
	"0 Complete Unique Maps - Vaults of Atziri - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Vaal Pyramid Map'},
	"0 Complete Unique Maps - Whakawairua Tuahu - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Strand Map'},
	"0 Turn in Divination Cards - Map - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Rain Tempter'},
	"0 Turn in Divination Cards - Map - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Boundless Realms'},
	"0 Turn in Divination Cards - Map - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Surveyor'},
	"0 Turn in Divination Cards - Map - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': "Cartographer's Delight"},
	"0 Turn in Divination Cards - Map - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Scholar of the Seas'},
	"0 Turn in Divination Cards - Map - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Dreamland'},
	"0 Turn in Divination Cards - Map - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Twilight Moon'},
	"0 Turn in Divination Cards - Map - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': "The Wolf's Legacy"},
	"0 Turn in Divination Cards - Map - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Treasure Hunter'},
	"0 Turn in Divination Cards - Map - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Encroaching Darkness'},
}
