#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/28/2020(m/d/y) 00:56:18 UTC from "Harvest" data

desc = "Challenge Autogen"

# Base type : settings pair
items = {
	"0 Complete Twinned Maps - Tier 1 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 1', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 10 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 10', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 11 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 11', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 12 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 12', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 13 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 13', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 14 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 14', 'CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 15 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 15', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 16 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 16', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 5 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 5', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 6 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 6', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 7 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 7', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 8 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 8', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high'},
	"0 Complete Twinned Maps - Tier 9 - 0": {'class': 'Maps', 'other': ['HasExplicitMod Twinned', 'MapTier = 9', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high'},
	"0 Complete Unique Maps - Acton's Nightmare - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Overgrown Shrine Map'},
	"0 Complete Unique Maps - Caer Blaidd, Wolfpack's Den - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Underground River Map'},
	"0 Complete Unique Maps - Death and Taxes - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Necropolis Map'},
	"0 Complete Unique Maps - Doryani's Machinarium - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Maze Map'},
	"0 Complete Unique Maps - Hall of Grandmasters - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Promenade Map'},
	"0 Complete Unique Maps - Hallowed Ground - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Cemetery Map'},
	"0 Complete Unique Maps - Maelström of Chaos - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Atoll Map'},
	"0 Complete Unique Maps - Mao Kun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Shore Map'},
	"0 Complete Unique Maps - Oba's Cursed Trove - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Underground Sea Map'},
	"0 Complete Unique Maps - Olmec's Sanctum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Bone Crypt Map'},
	"0 Complete Unique Maps - Perandus Manor - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Chateau Map'},
	"0 Complete Unique Maps - Pillars of Arun - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Dunes Map'},
	"0 Complete Unique Maps - Poorjoy's Asylum - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Temple Map'},
	"0 Complete Unique Maps - The Coward's Trial - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Cursed Crypt Map'},
	"0 Complete Unique Maps - The Putrid Cloister - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Museum Map'},
	"0 Complete Unique Maps - The Vinktar Square - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Courtyard Map'},
	"0 Complete Unique Maps - Vaults of Atziri - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Vaal Pyramid Map'},
	"0 Complete Unique Maps - Whakawairua Tuahu - 0": {'other': ['Rarity Unique', 'CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Strand Map'},
	"0 Turn in Divination Cards - Gem - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Volatile Power'},
	"0 Turn in Divination Cards - Gem - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "Dialla's Subjugation"},
	"0 Turn in Divination Cards - Gem - 10": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Doppelganger'},
	"0 Turn in Divination Cards - Gem - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': "Gemcutter's Promise"},
	"0 Turn in Divination Cards - Gem - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Summoner'},
	"0 Turn in Divination Cards - Gem - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Cataclysm'},
	"0 Turn in Divination Cards - Gem - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Gift of the Gemling Queen'},
	"0 Turn in Divination Cards - Gem - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Fox'},
	"0 Turn in Divination Cards - Gem - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Skeleton'},
	"0 Turn in Divination Cards - Gem - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Grave Knowledge'},
	"0 Turn in Divination Cards - Gem - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Realm'},
	"0 Turn in Divination Cards - Jewel - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Mountain'},
	"0 Turn in Divination Cards - Jewel - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': "Azyran's Reward"},
	"0 Turn in Divination Cards - Jewel - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Garish Power'},
	"0 Turn in Divination Cards - Jewel - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Eye of the Dragon'},
	"0 Turn in Divination Cards - Jewel - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'The Primordial'},
	"0 Turn in Divination Cards - Jewel - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Endurance'},
	"0 Turn in Divination Cards - Jewel - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge13.wav"'], 'type': 'challenge high', 'baseexact': 'Shard of Fate'},
	"0 Turn in Divination Cards - Prophecy - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': "Akil's Prophecy"},
	"0 Turn in Divination Cards - Prophecy - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Friendship'},
	"0 Turn in Divination Cards - Prophecy - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'The Side Quest'},
	"0 Turn in Divination Cards - Prophecy - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Vile Power'},
	"0 Turn in Divination Cards - Prophecy - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'Immortal Resolve'},
	"0 Turn in Divination Cards - Prophecy - 5": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Valley of Steel Boxes'},
	"0 Turn in Divination Cards - Prophecy - 6": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': "The Jeweller's Boon"},
	"0 Turn in Divination Cards - Prophecy - 7": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Mad King'},
	"0 Turn in Divination Cards - Prophecy - 8": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'The Iron Bard'},
	"0 Turn in Divination Cards - Prophecy - 9": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Beauty Through Death'},
	"0 Turn in Divination Cards - Two-Implicit Unique Item - 0": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge11.wav"'], 'type': 'challenge high', 'baseexact': 'Echoes of Love'},
	"0 Turn in Divination Cards - Two-Implicit Unique Item - 1": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'The Demon'},
	"0 Turn in Divination Cards - Two-Implicit Unique Item - 2": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge12.wav"'], 'type': 'challenge high', 'baseexact': 'The Price of Loyalty'},
	"0 Turn in Divination Cards - Two-Implicit Unique Item - 3": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge14.wav"'], 'type': 'challenge high', 'baseexact': 'Arrogance of the Vaal'},
	"0 Turn in Divination Cards - Two-Implicit Unique Item - 4": {'class': 'Divination Card', 'other': ['CustomAlertSound "75_challenge15.wav"'], 'type': 'challenge high', 'baseexact': 'Etched in Blood'},
}
