#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 10/06/2018(m/d/y) 21:17:02 UTC from "Hardcore" data

desc = "Divination Card"

# Base type : settings pair
items = {
	"1 Bowyer's Dream": {"base": "Bowyer's Dream", "class": "Divination Card", "type": "divination extremely high"},
	"1 House of Mirrors": {"base": "House of Mirrors", "class": "Divination Card", "type": "divination extremely high"},
	"1 The Doctor": {"base": "The Doctor", "class": "Divination Card", "type": "divination extremely high"},
	"1 The Hunger": {"base": "The Hunger", "class": "Divination Card", "type": "divination extremely high"},
	"2 Audacity": {"base": "Audacity", "class": "Divination Card", "type": "divination very high"},
	"2 The King's Heart": {"base": "The King's Heart", "class": "Divination Card", "type": "divination very high"},
	"2 The Last One Standing": {"base": "The Last One Standing", "class": "Divination Card", "type": "divination very high"},
	"2 The Porcupine": {"base": "The Porcupine", "class": "Divination Card", "type": "divination very high"},
	"2 The Sephirot": {"base": "The Sephirot", "class": "Divination Card", "type": "divination very high"},
	"2 The Undaunted": {"base": "The Undaunted", "class": "Divination Card", "type": "divination very high"},
	"3 Doedre's Madness": {"base": "Doedre's Madness", "class": "Divination Card", "type": "divination high"},
	"3 The Warden": {"base": "The Warden", "class": "Divination Card", "type": "divination high"},
	"3 The Watcher": {"base": "The Watcher", "class": "Divination Card", "type": "divination high"},
	"3 The Wind": {"base": "The Wind", "class": "Divination Card", "type": "divination high"},
	"3 Treasure Hunter": {"base": "Treasure Hunter", "class": "Divination Card", "type": "divination high"},
	"3 Volatile Power": {"base": "Volatile Power", "class": "Divination Card", "type": "divination high"},
	"4 A Mother's Parting Gift": {"base": "A Mother's Parting Gift", "class": "Divination Card", "type": "divination low"},
	"4 Anarchy's Price": {"base": "Anarchy's Price", "class": "Divination Card", "type": "divination low"},
	"4 Lantador's Lost Love": {"base": "Lantador's Lost Love", "class": "Divination Card", "type": "divination low"},
	"4 Shard of Fate": {"base": "Shard of Fate", "class": "Divination Card", "type": "divination low"},
	"4 The Betrayal": {"base": "The Betrayal", "class": "Divination Card", "type": "divination low"},
	"4 The Endurance": {"base": "The Endurance", "class": "Divination Card", "type": "divination low"},
	"4 The Feast": {"base": "The Feast", "class": "Divination Card", "type": "divination low"},
	"4 The Hermit": {"base": "The Hermit", "class": "Divination Card", "type": "divination low"},
	"4 The Incantation": {"base": "The Incantation", "class": "Divination Card", "type": "divination low"},
	"4 The Lover": {"base": "The Lover", "class": "Divination Card", "type": "divination low"},
	"4 The Ruthless Ceinture": {"base": "The Ruthless Ceinture", "class": "Divination Card", "type": "divination low"},
	"4 The Scholar": {"base": "The Scholar", "class": "Divination Card", "type": "divination low"},
	"7 Blessing of God": {"base": "Blessing of God", "class": "Divination Card", "type": "hide"},
	"7 Destined to Crumble": {"base": "Destined to Crumble", "class": "Divination Card", "type": "hide"},
	"7 Dying Anguish": {"base": "Dying Anguish", "class": "Divination Card", "type": "hide"},
	"7 Merciless Armament": {"base": "Merciless Armament", "class": "Divination Card", "type": "hide"},
	"7 Prosperity": {"base": "Prosperity", "class": "Divination Card", "type": "hide"},
	"7 Rain Tempter": {"base": "Rain Tempter", "class": "Divination Card", "type": "hide"},
	"7 Struck by Lightning": {"base": "Struck by Lightning", "class": "Divination Card", "type": "hide"},
	"7 The Carrion Crow": {"base": "The Carrion Crow", "class": "Divination Card", "type": "hide"},
	"7 The Inoculated": {"base": "The Inoculated", "class": "Divination Card", "type": "hide"},
	"7 The Jester": {"base": "The Jester", "class": "Divination Card", "type": "hide"},
	"7 The King's Blade": {"base": "The King's Blade", "class": "Divination Card", "type": "hide"},
	"7 The Lord in Black": {"base": "The Lord in Black", "class": "Divination Card", "type": "hide"},
	"7 The Metalsmith's Gift": {"base": "The Metalsmith's Gift", "class": "Divination Card", "type": "hide"},
	"7 The Rabid Rhoa": {"base": "The Rabid Rhoa", "class": "Divination Card", "type": "hide"},
	"7 The Road to Power": {"base": "The Road to Power", "class": "Divination Card", "type": "hide"},
	"7 The Scarred Meadow": {"base": "The Scarred Meadow", "class": "Divination Card", "type": "hide"},
	"7 The Sigil": {"base": "The Sigil", "class": "Divination Card", "type": "hide"},
	"7 The Spoiled Prince": {"base": "The Spoiled Prince", "class": "Divination Card", "type": "hide"},
	"7 The Surgeon": {"base": "The Surgeon", "class": "Divination Card", "type": "hide"},
	"7 The Twins": {"base": "The Twins", "class": "Divination Card", "type": "hide"},
	"7 The Tyrant": {"base": "The Tyrant", "class": "Divination Card", "type": "hide"},
	"7 The Undisputed": {"base": "The Undisputed", "class": "Divination Card", "type": "hide"},
	"7 The Web": {"base": "The Web", "class": "Divination Card", "type": "hide"},
	"7 Thunderous Skies": {"base": "Thunderous Skies", "class": "Divination Card", "type": "hide"},
	"9 Other Divination Cards": {"class": "Divination Card", "type": "divination normal"}
}
