#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:17:17 UTC from "Hardcore" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 Enchantment Flame Surge Vs Burning Enemies 1": {"enchant": "Enchantment Flame Surge Vs Burning Enemies 1", "type": "ignore"},
	"1 Enchantment Incinerate Damage Per Stage 3": {"enchant": "Enchantment Incinerate Damage Per Stage 3", "type": "currency very high"},
	"1 Enchantment Contagion Radius 2": {"enchant": "Enchantment Contagion Radius 2", "type": "currency very high"},
	"1 Enchantment Reave Area Of Effect 2": {"enchant": "Enchantment Reave Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Fire Beam Cast Speed 2": {"enchant": "Enchantment Fire Beam Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Area Of Effect 2": {"enchant": "Enchantment Tectonic Slam Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Double Strike Attack Speed 2": {"enchant": "Enchantment Double Strike Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Attack Speed 2": {"enchant": "Enchantment Elemental Hit Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Stone Golem Granted Buff Effect 2": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Storm Call Duration 1": {"enchant": "Enchantment Storm Call Duration 1", "type": "currency very high"},
	"1 Enchantment Discharge Consume Charges 2": {"enchant": "Enchantment Discharge Consume Charges 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Duration 2": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "currency very high"},
	"1 Enchantment Despair Effect 2": {"enchant": "Enchantment Despair Effect 2", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Projectile Speed 2": {"enchant": "Enchantment Ethereal Knives Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Projectile Speed 2": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Spark Projectile Speed 2": {"enchant": "Enchantment Spark Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Curse Effect 2": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Vortex Duration 2": {"enchant": "Enchantment Vortex Duration 2", "type": "currency very high"},
	"1 Enchantment Earthquake Duration 2": {"enchant": "Enchantment Earthquake Duration 2", "type": "currency very high"},
	"1 Enchantment Lightning Warp Duration 2": {"enchant": "Enchantment Lightning Warp Duration 2", "type": "currency very high"},
	"1 Enchantment Spectral Throw Projectile Deceleration 2": {"enchant": "Enchantment Spectral Throw Projectile Deceleration 2", "type": "currency very high"},
	"1 Enchantment Storm Call Duration 2": {"enchant": "Enchantment Storm Call Duration 2", "type": "currency extremely high"},
	"1 Enchantment Arctic Breath Damage 2": {"enchant": "Enchantment Arctic Breath Damage 2", "type": "currency very high"},
	"1 Enchantment Blade Flurry Damage 2": {"enchant": "Enchantment Blade Flurry Damage 2", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Damage 2": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Cyclone Damage 2": {"enchant": "Enchantment Cyclone Damage 2", "type": "currency very high"},
	"1 Enchantment Essence Drain Damage 2": {"enchant": "Enchantment Essence Drain Damage 2", "type": "currency very high"},
	"1 Enchantment Fireball Damage 2": {"enchant": "Enchantment Fireball Damage 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage 2": {"enchant": "Enchantment Flicker Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Damage 2": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "currency very high"},
	"1 Enchantment Frost Blades Damage 2": {"enchant": "Enchantment Frost Blades Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Damage 2": {"enchant": "Enchantment Glacial Cascade Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Damage 2": {"enchant": "Enchantment Ice Nova Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Shot Damage 2": {"enchant": "Enchantment Ice Shot Damage 2", "type": "currency very high"},
	"1 Enchantment Lacerate Damage 2": {"enchant": "Enchantment Lacerate Damage 2", "type": "currency very high"},
	"1 Enchantment Orb Of Storms Damage 2": {"enchant": "Enchantment Orb Of Storms Damage 2", "type": "currency very high"},
	"1 Enchantment Righteous Fire Damage 2": {"enchant": "Enchantment Righteous Fire Damage 2", "type": "currency very high"},
	"1 Enchantment Spark Damage 2": {"enchant": "Enchantment Spark Damage 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Damage 2": {"enchant": "Enchantment Tectonic Slam Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Area Of Effect 1": {"enchant": "Enchantment Glacial Cascade Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage Per Frenzy Charge 2": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 Enchantment Arc Num Of Additional Projectiles In Chain 1": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "currency very high"},
	"1 Enchantment Bane Damage 2": {"enchant": "Enchantment Bane Damage 2", "type": "currency very high"},
	"1 Enchantment Barrage Num Of Additional Projectiles 1": {"enchant": "Enchantment Barrage Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Blood Rage Attack Speed 2": {"enchant": "Enchantment Blood Rage Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Enchantment Consecrated Path Damage 2": {"enchant": "Enchantment Consecrated Path Damage 2", "type": "currency very high"},
	"1 Enchantment Discipline Mana Reservation 2": {"enchant": "Enchantment Discipline Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2": {"enchant": "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Damage 2": {"enchant": "Enchantment Divine Ire Damage 2", "type": "currency very high"},
	"1 Enchantment Double Strike Double Damage Vs Bleeding 2": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 2", "type": "currency very high"},
	"1 Enchantment Dread Banner Effect 2": {"enchant": "Enchantment Dread Banner Effect 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Damage 2": {"enchant": "Enchantment Elemental Hit Damage 2", "type": "currency very high"},
	"1 Enchantment Hatred Mana Reservation 2": {"enchant": "Enchantment Hatred Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Heavy Strike Double Damage 2": {"enchant": "Enchantment Heavy Strike Double Damage 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 1": {"enchant": "Enchantment Herald Of Agony Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 2": {"enchant": "Enchantment Herald Of Agony Mana Reservation 2", "type": "currency extremely high"},
	"1 Enchantment Flame Totem Damage 2": {"enchant": "Enchantment Flame Totem Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Num Of Additional Projectiles 2": {"enchant": "Enchantment Flame Totem Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Projectile Speed 2": {"enchant": "Enchantment Flame Totem Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Summon Ice Golem Damage 2": {"enchant": "Enchantment Summon Ice Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Additional Projectile 1": {"enchant": "Enchantment Ice Spear Additional Projectile 1", "type": "currency extremely high"},
	"1 Enchantment Incinerate Maximum Stages 2": {"enchant": "Enchantment Incinerate Maximum Stages 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Penetration 2": {"enchant": "Enchantment Lightning Trap Penetration 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Additional Pierce 2": {"enchant": "Enchantment Lightning Trap Additional Pierce 2", "type": "currency very high"},
	"1 Enchantment Magma Orb Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 2": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 1": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Purifying Flame Damage 2": {"enchant": "Enchantment Purifying Flame Damage 2", "type": "currency very high"},
	"1 Enchantment Purity Of Fire Mana Reservation 2": {"enchant": "Enchantment Purity Of Fire Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Scourge Arrow Additional Spore 1": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "currency very high"},
	"1 Enchantment Soulrend Damage 2": {"enchant": "Enchantment Soulrend Damage 2", "type": "currency very high"},
	"1 Enchantment Soulrend Number Of Additional Projectiles 1": {"enchant": "Enchantment Soulrend Number Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Spark Num Of Additional Projectiles 2": {"enchant": "Enchantment Spark Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Storm Brand Attached Target Lightning Penetration 2": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "currency very high"},
	"1 Enchantment Storm Brand Damage 2": {"enchant": "Enchantment Storm Brand Damage 2", "type": "currency very high"},
	"1 Enchantment Storm Burst Additional Object Chance 2": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Num Of Secondary Projectiles 1": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Chance To Charged Slam 2": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 2": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 1": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 1", "type": "currency very high"},
	"1 Enchantment Toxic Rain Damage 2": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "currency very high"},
	"1 Enchantment Toxic Rain Num Of Additional Projectiles 1": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Wild Strike Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 1": {"enchant": "Enchantment Winter Orb Damage 1", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 2": {"enchant": "Enchantment Winter Orb Damage 2", "type": "currency extremely high"},
	"1 Enchantment Frost Fury Additional Max Number Of Stages 1": {"enchant": "Enchantment Frost Fury Additional Max Number Of Stages 1", "type": "currency extremely high"},
	"1 Enchantment Zealotry Mana Reservation 2": {"enchant": "Enchantment Zealotry Mana Reservation 2", "type": "currency very high"},
}
