#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:07:58 UTC from "Standard" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 40% increased Flame Surge Damage against Burning Enemies": {"enchant": "40% increased Flame Surge Damage against Burning Enemies", "type": "ignore"},
	"1 +1 to maximum number of Sentinels of Purity": {"enchant": "+1 to maximum number of Sentinels of Purity", "type": "currency very high"},
	"1 +30% Sweep Knockback Chance": {"enchant": "+30% Sweep Knockback Chance", "type": "currency very high"},
	"1 +36% to Animated Guardian Elemental Resistances": {"enchant": "+36% to Animated Guardian Elemental Resistances", "type": "currency very high"},
	"1 +36% to Ice Golem Elemental Resistances": {"enchant": "+36% to Ice Golem Elemental Resistances", "type": "currency very high"},
	"1 +36% to Lightning Golem Elemental Resistances": {"enchant": "+36% to Lightning Golem Elemental Resistances", "type": "currency very high"},
	"1 +36% to Raised Spectre Elemental Resistances": {"enchant": "+36% to Raised Spectre Elemental Resistances", "type": "currency very high"},
	"1 +36% to Raised Zombie Elemental Resistances": {"enchant": "+36% to Raised Zombie Elemental Resistances", "type": "currency very high"},
	"1 +36% to increased Flame Golem Elemental Resistances": {"enchant": "+36% to increased Flame Golem Elemental Resistances", "type": "currency very high"},
	"1 10% increased Barrage Attack Speed": {"enchant": "10% increased Barrage Attack Speed", "type": "currency very high"},
	"1 10% increased Cyclone Attack Speed": {"enchant": "10% increased Cyclone Attack Speed", "type": "currency very high"},
	"1 10% increased Dual Strike Attack Speed": {"enchant": "10% increased Dual Strike Attack Speed", "type": "currency very high"},
	"1 10% increased Elemental Hit Attack Speed": {"enchant": "10% increased Elemental Hit Attack Speed", "type": "currency very high"},
	"1 10% increased Incinerate Damage for each stage": {"enchant": "10% increased Incinerate Damage for each stage", "type": "currency extremely high"},
	"1 100% increased Effect of the Buff granted by your Chaos Golems": {"enchant": "100% increased Effect of the Buff granted by your Chaos Golems", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Ice Golems": {"enchant": "100% increased Effect of the Buff granted by your Ice Golems", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Lightning Golems": {"enchant": "100% increased Effect of the Buff granted by your Lightning Golems", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Stone Golems": {"enchant": "100% increased Effect of the Buff granted by your Stone Golems", "type": "currency very high"},
	"1 12% increased Ancestral Warchief Totem Area of Effect": {"enchant": "12% increased Ancestral Warchief Totem Area of Effect", "type": "currency very high"},
	"1 12% increased Arctic Breath Area of Effect": {"enchant": "12% increased Arctic Breath Area of Effect", "type": "currency very high"},
	"1 12% increased Ball Lightning Area of Effect": {"enchant": "12% increased Ball Lightning Area of Effect", "type": "currency very high"},
	"1 12% increased Blade Flurry Area of Effect": {"enchant": "12% increased Blade Flurry Area of Effect", "type": "currency very high"},
	"1 12% increased Blade Vortex Area of Effect": {"enchant": "12% increased Blade Vortex Area of Effect", "type": "currency very high"},
	"1 12% increased Blast Rain Area of Effect": {"enchant": "12% increased Blast Rain Area of Effect", "type": "currency very high"},
	"1 12% increased Blight Area of Effect": {"enchant": "12% increased Blight Area of Effect", "type": "currency very high"},
	"1 12% increased Bodyswap Cast Speed": {"enchant": "12% increased Bodyswap Cast Speed", "type": "currency extremely high"},
	"1 12% increased Caustic Arrow Area of Effect": {"enchant": "12% increased Caustic Arrow Area of Effect", "type": "currency very high"},
	"1 12% increased Cleave Area of Effect": {"enchant": "12% increased Cleave Area of Effect", "type": "currency very high"},
	"1 12% increased Cold Snap Area of Effect": {"enchant": "12% increased Cold Snap Area of Effect", "type": "currency very high"},
	"1 12% increased Contagion Area of Effect": {"enchant": "12% increased Contagion Area of Effect", "type": "currency very high"},
	"1 12% increased Cremation Cast Speed": {"enchant": "12% increased Cremation Cast Speed", "type": "currency very high"},
	"1 12% increased Dark Pact Area of Effect": {"enchant": "12% increased Dark Pact Area of Effect", "type": "currency very high"},
	"1 12% increased Dark Pact Cast Speed": {"enchant": "12% increased Dark Pact Cast Speed", "type": "currency very high"},
	"1 12% increased Detonate Dead Area of Effect": {"enchant": "12% increased Detonate Dead Area of Effect", "type": "currency very high"},
	"1 12% increased Earthquake Area of Effect": {"enchant": "12% increased Earthquake Area of Effect", "type": "currency very high"},
	"1 12% increased Explosive Arrow Area of Effect": {"enchant": "12% increased Explosive Arrow Area of Effect", "type": "currency very high"},
	"1 12% increased Fireball Cast Speed": {"enchant": "12% increased Fireball Cast Speed", "type": "currency very high"},
	"1 12% increased Firestorm explosion Area of Effect": {"enchant": "12% increased Firestorm explosion Area of Effect", "type": "currency very high"},
	"1 12% increased Flameblast Area of Effect": {"enchant": "12% increased Flameblast Area of Effect", "type": "currency very high"},
	"1 12% increased Freeze Mine Area of Effect": {"enchant": "12% increased Freeze Mine Area of Effect", "type": "currency very high"},
	"1 12% increased Freezing Pulse Cast Speed": {"enchant": "12% increased Freezing Pulse Cast Speed", "type": "currency very high"},
	"1 12% increased Frost Bomb Area of Effect": {"enchant": "12% increased Frost Bomb Area of Effect", "type": "currency very high"},
	"1 12% increased Glacial Cascade Area of Effect": {"enchant": "12% increased Glacial Cascade Area of Effect", "type": "currency very high"},
	"1 12% increased Ground Slam Area of Effect": {"enchant": "12% increased Ground Slam Area of Effect", "type": "currency very high"},
	"1 12% increased Ice Crash Area of Effect": {"enchant": "12% increased Ice Crash Area of Effect", "type": "currency very high"},
	"1 12% increased Ice Nova Area of Effect": {"enchant": "12% increased Ice Nova Area of Effect", "type": "currency very high"},
	"1 12% increased Ice Shot Area of Effect": {"enchant": "12% increased Ice Shot Area of Effect", "type": "currency very high"},
	"1 12% increased Ice Trap Area of Effect": {"enchant": "12% increased Ice Trap Area of Effect", "type": "currency very high"},
	"1 12% increased Infernal Blow Area of Effect": {"enchant": "12% increased Infernal Blow Area of Effect", "type": "currency very high"},
	"1 12% increased Kinetic Blast Area of Effect": {"enchant": "12% increased Kinetic Blast Area of Effect", "type": "currency very high"},
	"1 12% increased Lacerate Area of Effect": {"enchant": "12% increased Lacerate Area of Effect", "type": "currency very high"},
	"1 12% increased Leap Slam Area of Effect": {"enchant": "12% increased Leap Slam Area of Effect", "type": "currency very high"},
	"1 12% increased Lightning Arrow Area of Effect": {"enchant": "12% increased Lightning Arrow Area of Effect", "type": "currency very high"},
	"1 12% increased Lightning Tendrils Area of Effect": {"enchant": "12% increased Lightning Tendrils Area of Effect", "type": "currency very high"},
	"1 12% increased Magma Orb Area of Effect": {"enchant": "12% increased Magma Orb Area of Effect", "type": "currency very high"},
	"1 12% increased Molten Strike Area of Effect": {"enchant": "12% increased Molten Strike Area of Effect", "type": "currency very high"},
	"1 12% increased Rain of Arrows Area of Effect": {"enchant": "12% increased Rain of Arrows Area of Effect", "type": "currency very high"},
	"1 12% increased Reave Radius": {"enchant": "12% increased Reave Radius", "type": "currency very high"},
	"1 12% increased Righteous Fire Area of Effect": {"enchant": "12% increased Righteous Fire Area of Effect", "type": "currency very high"},
	"1 12% increased Scorching Ray Cast Speed": {"enchant": "12% increased Scorching Ray Cast Speed", "type": "currency very high"},
	"1 12% increased Shock Nova Area of Effect": {"enchant": "12% increased Shock Nova Area of Effect", "type": "currency very high"},
	"1 12% increased Shockwave Totem Area of Effect": {"enchant": "12% increased Shockwave Totem Area of Effect", "type": "currency very high"},
	"1 12% increased Shrapnel Shot Area of Effect": {"enchant": "12% increased Shrapnel Shot Area of Effect", "type": "currency very high"},
	"1 12% increased Static Strike Area of Effect": {"enchant": "12% increased Static Strike Area of Effect", "type": "currency very high"},
	"1 12% increased Storm Burst Area of Effect": {"enchant": "12% increased Storm Burst Area of Effect", "type": "currency very high"},
	"1 12% increased Storm Call Area of Effect": {"enchant": "12% increased Storm Call Area of Effect", "type": "currency very high"},
	"1 12% increased Sunder Area of Effect": {"enchant": "12% increased Sunder Area of Effect", "type": "currency very high"},
	"1 12% increased Sweep Area of Effect": {"enchant": "12% increased Sweep Area of Effect", "type": "currency very high"},
	"1 12% increased Tectonic Slam Area of Effect": {"enchant": "12% increased Tectonic Slam Area of Effect", "type": "currency very high"},
	"1 12% increased Unearth Cast Speed": {"enchant": "12% increased Unearth Cast Speed", "type": "currency very high"},
	"1 12% increased Volatile Dead Cast Speed": {"enchant": "12% increased Volatile Dead Cast Speed", "type": "currency very high"},
	"1 15% Chance to gain a Power Charge on Critical Strike with Ice Spear": {"enchant": "15% Chance to gain a Power Charge on Critical Strike with Ice Spear", "type": "currency very high"},
	"1 15% increased Barrage Attack Speed": {"enchant": "15% increased Barrage Attack Speed", "type": "currency very high"},
	"1 15% increased Bear Trap Cooldown Recovery Speed": {"enchant": "15% increased Bear Trap Cooldown Recovery Speed", "type": "currency very high"},
	"1 15% increased Cleave Attack Speed": {"enchant": "15% increased Cleave Attack Speed", "type": "currency very high"},
	"1 15% increased Cyclone Attack Speed": {"enchant": "15% increased Cyclone Attack Speed", "type": "currency extremely high"},
	"1 15% increased Double Strike Attack Speed": {"enchant": "15% increased Double Strike Attack Speed", "type": "currency extremely high"},
	"1 15% increased Dual Strike Attack Speed": {"enchant": "15% increased Dual Strike Attack Speed", "type": "currency very high"},
	"1 15% increased Elemental Hit Attack Speed": {"enchant": "15% increased Elemental Hit Attack Speed", "type": "currency extremely high"},
	"1 15% increased Explosive Arrow Attack Speed": {"enchant": "15% increased Explosive Arrow Attack Speed", "type": "currency very high"},
	"1 15% increased Frostbolt Cast Speed": {"enchant": "15% increased Frostbolt Cast Speed", "type": "currency very high"},
	"1 15% increased Heavy Strike Attack Speed": {"enchant": "15% increased Heavy Strike Attack Speed", "type": "currency very high"},
	"1 15% increased Leap Slam Attack Speed": {"enchant": "15% increased Leap Slam Attack Speed", "type": "currency very high"},
	"1 15% increased Power Siphon Attack Speed": {"enchant": "15% increased Power Siphon Attack Speed", "type": "currency very high"},
	"1 15% increased Rain of Arrows Attack Speed": {"enchant": "15% increased Rain of Arrows Attack Speed", "type": "currency very high"},
	"1 15% increased Scorching Ray beam length": {"enchant": "15% increased Scorching Ray beam length", "type": "currency very high"},
	"1 15% increased Shield Charge Attack Speed": {"enchant": "15% increased Shield Charge Attack Speed", "type": "currency very high"},
	"1 15% increased Shockwave Totem Cast Speed": {"enchant": "15% increased Shockwave Totem Cast Speed", "type": "currency very high"},
	"1 15% increased Siege Ballista Attack Speed": {"enchant": "15% increased Siege Ballista Attack Speed", "type": "currency very high"},
	"1 15% increased Sunder Attack Speed": {"enchant": "15% increased Sunder Attack Speed", "type": "currency very high"},
	"1 15% increased Whirling Blades Attack Speed": {"enchant": "15% increased Whirling Blades Attack Speed", "type": "currency very high"},
	"1 15% of Burning Arrow Physical Damage gained as Extra Fire Damage": {"enchant": "15% of Burning Arrow Physical Damage gained as Extra Fire Damage", "type": "currency very high"},
	"1 15% of Glacial Hammer Physical Damage gained as Extra Cold Damage": {"enchant": "15% of Glacial Hammer Physical Damage gained as Extra Cold Damage", "type": "currency very high"},
	"1 15% of Ice Crash Physical Damage gained as Extra Cold Damage": {"enchant": "15% of Ice Crash Physical Damage gained as Extra Cold Damage", "type": "currency very high"},
	"1 15% of Infernal Blow Physical Damage gained as Extra Fire Damage": {"enchant": "15% of Infernal Blow Physical Damage gained as Extra Fire Damage", "type": "currency very high"},
	"1 15% of Shrapnel Shot Physical Damage gained as extra Lightning Damage": {"enchant": "15% of Shrapnel Shot Physical Damage gained as extra Lightning Damage", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Flame Golems": {"enchant": "150% increased Effect of the Buff granted by your Flame Golems", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Ice Golems": {"enchant": "150% increased Effect of the Buff granted by your Ice Golems", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Lightning Golems": {"enchant": "150% increased Effect of the Buff granted by your Lightning Golems", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Stone Golems": {"enchant": "150% increased Effect of the Buff granted by your Stone Golems", "type": "currency very high"},
	"1 150% increased Molten Shell Buff Effect": {"enchant": "150% increased Molten Shell Buff Effect", "type": "currency very high"},
	"1 20% chance for Discharge to deal Damage without removing Charges": {"enchant": "20% chance for Discharge to deal Damage without removing Charges", "type": "currency very high"},
	"1 20% chance for Phase Run to increase Duration without removing Frenzy Charges": {"enchant": "20% chance for Phase Run to increase Duration without removing Frenzy Charges", "type": "currency very high"},
	"1 20% increased Blade Vortex Duration": {"enchant": "20% increased Blade Vortex Duration", "type": "currency very high"},
	"1 20% increased Frost Blades Projectile Speed": {"enchant": "20% increased Frost Blades Projectile Speed", "type": "currency very high"},
	"1 20% increased Warlord's Mark Curse Effect": {"enchant": "20% increased Warlord's Mark Curse Effect", "type": "currency very high"},
	"1 20% reduced Earthquake Duration": {"enchant": "20% reduced Earthquake Duration", "type": "currency very high"},
	"1 20% reduced Lightning Warp Duration": {"enchant": "20% reduced Lightning Warp Duration", "type": "currency very high"},
	"1 24% chance to create an additional Animate Weapon copy": {"enchant": "24% chance to create an additional Animate Weapon copy", "type": "currency extremely high"},
	"1 24% increased Incinerate Damage": {"enchant": "24% increased Incinerate Damage", "type": "currency very high"},
	"1 24% increased Wild Strike Area of Effect": {"enchant": "24% increased Wild Strike Area of Effect", "type": "currency very high"},
	"1 25% increased Ancestral Warchief Totem Damage": {"enchant": "25% increased Ancestral Warchief Totem Damage", "type": "currency very high"},
	"1 25% increased Arc Damage": {"enchant": "25% increased Arc Damage", "type": "currency very high"},
	"1 25% increased Barrage Damage": {"enchant": "25% increased Barrage Damage", "type": "currency very high"},
	"1 25% increased Blade Flurry Damage": {"enchant": "25% increased Blade Flurry Damage", "type": "currency very high"},
	"1 25% increased Blade Vortex Spell Damage": {"enchant": "25% increased Blade Vortex Spell Damage", "type": "currency very high"},
	"1 25% increased Blast Rain Damage": {"enchant": "25% increased Blast Rain Damage", "type": "currency very high"},
	"1 25% increased Cyclone Damage": {"enchant": "25% increased Cyclone Damage", "type": "currency very high"},
	"1 25% increased Dark Pact Damage": {"enchant": "25% increased Dark Pact Damage", "type": "currency very high"},
	"1 25% increased Double Strike Damage": {"enchant": "25% increased Double Strike Damage", "type": "currency very high"},
	"1 25% increased Earthquake Damage": {"enchant": "25% increased Earthquake Damage", "type": "currency very high"},
	"1 25% increased Ethereal Knives Damage": {"enchant": "25% increased Ethereal Knives Damage", "type": "currency very high"},
	"1 25% increased Explosive Arrow Damage": {"enchant": "25% increased Explosive Arrow Damage", "type": "currency very high"},
	"1 25% increased Fire Nova Mine Damage": {"enchant": "25% increased Fire Nova Mine Damage", "type": "currency very high"},
	"1 25% increased Frost Blades Damage": {"enchant": "25% increased Frost Blades Damage", "type": "currency very high"},
	"1 25% increased Frostbolt Damage": {"enchant": "25% increased Frostbolt Damage", "type": "currency very high"},
	"1 25% increased Herald of Ice Damage": {"enchant": "25% increased Herald of Ice Damage", "type": "currency very high"},
	"1 25% increased Ice Shot Damage": {"enchant": "25% increased Ice Shot Damage", "type": "currency very high"},
	"1 25% increased Kinetic Blast Damage": {"enchant": "25% increased Kinetic Blast Damage", "type": "currency very high"},
	"1 25% increased Lacerate Damage": {"enchant": "25% increased Lacerate Damage", "type": "currency very high"},
	"1 25% increased Lightning Arrow Damage": {"enchant": "25% increased Lightning Arrow Damage", "type": "currency very high"},
	"1 25% increased Molten Strike Damage": {"enchant": "25% increased Molten Strike Damage", "type": "currency very high"},
	"1 25% increased Reave Damage": {"enchant": "25% increased Reave Damage", "type": "currency very high"},
	"1 25% increased Righteous Fire Damage": {"enchant": "25% increased Righteous Fire Damage", "type": "currency very high"},
	"1 25% increased Spectral Throw Damage": {"enchant": "25% increased Spectral Throw Damage", "type": "currency very high"},
	"1 25% increased Tornado Shot Damage": {"enchant": "25% increased Tornado Shot Damage", "type": "currency very high"},
	"1 25% increased Volatile Dead Damage": {"enchant": "25% increased Volatile Dead Damage", "type": "currency very high"},
	"1 30% Chance for Puncture to Maim on hit": {"enchant": "30% Chance for Puncture to Maim on hit", "type": "currency very high"},
	"1 30% Chance on Frenzy to gain an additional Frenzy Charge": {"enchant": "30% Chance on Frenzy to gain an additional Frenzy Charge", "type": "currency very high"},
	"1 30% chance for Discharge to deal Damage without removing Charges": {"enchant": "30% chance for Discharge to deal Damage without removing Charges", "type": "currency extremely high"},
	"1 30% chance for Immortal Call to increase Duration without removing Endurance Charges": {"enchant": "30% chance for Immortal Call to increase Duration without removing Endurance Charges", "type": "currency very high"},
	"1 30% increased Animate Weapon Duration": {"enchant": "30% increased Animate Weapon Duration", "type": "currency very high"},
	"1 30% increased Assassin's Mark Curse Effect": {"enchant": "30% increased Assassin's Mark Curse Effect", "type": "currency very high"},
	"1 30% increased Blade Vortex Duration": {"enchant": "30% increased Blade Vortex Duration", "type": "currency extremely high"},
	"1 30% increased Blink Arrow Cooldown Recovery Speed": {"enchant": "30% increased Blink Arrow Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Bone Offering Duration": {"enchant": "30% increased Bone Offering Duration", "type": "currency very high"},
	"1 30% increased Caustic Arrow Duration": {"enchant": "30% increased Caustic Arrow Duration", "type": "currency very high"},
	"1 30% increased Cold Snap Cooldown Recovery Speed": {"enchant": "30% increased Cold Snap Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Conductivity Curse Effect": {"enchant": "30% increased Conductivity Curse Effect", "type": "currency very high"},
	"1 30% increased Contagion Duration": {"enchant": "30% increased Contagion Duration", "type": "currency very high"},
	"1 30% increased Conversion Trap Cooldown Recovery Speed": {"enchant": "30% increased Conversion Trap Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Convocation Cooldown Recovery Speed": {"enchant": "30% increased Convocation Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Desecrate Cooldown Recovery Speed": {"enchant": "30% increased Desecrate Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Despair Curse Effect": {"enchant": "30% increased Despair Curse Effect", "type": "currency very high"},
	"1 30% increased Elemental Weakness Curse Effect": {"enchant": "30% increased Elemental Weakness Curse Effect", "type": "currency very high"},
	"1 30% increased Elemental Weakness Duration": {"enchant": "30% increased Elemental Weakness Duration", "type": "currency very high"},
	"1 30% increased Enduring Cry Cooldown Recovery Speed": {"enchant": "30% increased Enduring Cry Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Enfeeble Curse Effect": {"enchant": "30% increased Enfeeble Curse Effect", "type": "currency very high"},
	"1 30% increased Essence Drain Duration": {"enchant": "30% increased Essence Drain Duration", "type": "currency very high"},
	"1 30% increased Ethereal Knives Projectile Speed": {"enchant": "30% increased Ethereal Knives Projectile Speed", "type": "currency very high"},
	"1 30% increased Fire Nova Cast Speed": {"enchant": "30% increased Fire Nova Cast Speed", "type": "currency very high"},
	"1 30% increased Firestorm Duration": {"enchant": "30% increased Firestorm Duration", "type": "currency very high"},
	"1 30% increased Flame Dash Cooldown Recovery Speed": {"enchant": "30% increased Flame Dash Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Flammability Curse Effect": {"enchant": "30% increased Flammability Curse Effect", "type": "currency very high"},
	"1 30% increased Flicker Strike Cooldown Recovery Speed": {"enchant": "30% increased Flicker Strike Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Freezing Pulse Projectile Speed": {"enchant": "30% increased Freezing Pulse Projectile Speed", "type": "currency very high"},
	"1 30% increased Frost Blades Projectile Speed": {"enchant": "30% increased Frost Blades Projectile Speed", "type": "currency very high"},
	"1 30% increased Frost Bomb Cooldown Recovery Speed": {"enchant": "30% increased Frost Bomb Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Frost Wall Cooldown Recovery Speed": {"enchant": "30% increased Frost Wall Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Frostbite Curse Effect": {"enchant": "30% increased Frostbite Curse Effect", "type": "currency very high"},
	"1 30% increased Incinerate Damage": {"enchant": "30% increased Incinerate Damage", "type": "currency very high"},
	"1 30% increased Mirror Arrow Cooldown Recovery Speed": {"enchant": "30% increased Mirror Arrow Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Poacher's Mark Curse Effect": {"enchant": "30% increased Poacher's Mark Curse Effect", "type": "currency very high"},
	"1 30% increased Projectile Weakness Curse Effect": {"enchant": "30% increased Projectile Weakness Curse Effect", "type": "currency very high"},
	"1 30% increased Puncture Duration": {"enchant": "30% increased Puncture Duration", "type": "currency very high"},
	"1 30% increased Punishment Curse Effect": {"enchant": "30% increased Punishment Curse Effect", "type": "currency very high"},
	"1 30% increased Reckoning Cooldown Recovery Speed": {"enchant": "30% increased Reckoning Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Sentinel of Dominance Duration": {"enchant": "30% increased Sentinel of Dominance Duration", "type": "currency very high"},
	"1 30% increased Smoke Mine Duration": {"enchant": "30% increased Smoke Mine Duration", "type": "currency very high"},
	"1 30% increased Spark Projectile Speed": {"enchant": "30% increased Spark Projectile Speed", "type": "currency extremely high"},
	"1 30% increased Spectral Shield Throw Projectile Speed": {"enchant": "30% increased Spectral Shield Throw Projectile Speed", "type": "currency very high"},
	"1 30% increased Spectral Throw Projectile Speed": {"enchant": "30% increased Spectral Throw Projectile Speed", "type": "currency very high"},
	"1 30% increased Summon Raging Spirit Duration": {"enchant": "30% increased Summon Raging Spirit Duration", "type": "currency very high"},
	"1 30% increased Temporal Chains Curse Effect": {"enchant": "30% increased Temporal Chains Curse Effect", "type": "currency extremely high"},
	"1 30% increased Temporal Chains Duration": {"enchant": "30% increased Temporal Chains Duration", "type": "currency very high"},
	"1 30% increased Vengeance Cooldown Recovery Speed": {"enchant": "30% increased Vengeance Cooldown Recovery Speed", "type": "currency extremely high"},
	"1 30% increased Viper Strike Duration": {"enchant": "30% increased Viper Strike Duration", "type": "currency very high"},
	"1 30% increased Vortex Duration": {"enchant": "30% increased Vortex Duration", "type": "currency very high"},
	"1 30% increased Vulnerability Curse Effect": {"enchant": "30% increased Vulnerability Curse Effect", "type": "currency very high"},
	"1 30% increased Warlord's Mark Curse Effect": {"enchant": "30% increased Warlord's Mark Curse Effect", "type": "currency very high"},
	"1 30% of Glacial Cascade Physical Damage Converted to Cold Damage": {"enchant": "30% of Glacial Cascade Physical Damage Converted to Cold Damage", "type": "currency very high"},
	"1 30% reduced Earthquake Duration": {"enchant": "30% reduced Earthquake Duration", "type": "currency extremely high"},
	"1 30% reduced Lightning Warp Duration": {"enchant": "30% reduced Lightning Warp Duration", "type": "currency extremely high"},
	"1 30% reduced Spectral Throw Projectile Deceleration": {"enchant": "30% reduced Spectral Throw Projectile Deceleration", "type": "currency very high"},
	"1 30% reduced Storm Call Duration": {"enchant": "30% reduced Storm Call Duration", "type": "currency extremely high"},
	"1 300% increased Ice Spear Critical Strike Chance in second form": {"enchant": "300% increased Ice Spear Critical Strike Chance in second form", "type": "currency very high"},
	"1 34% increased Immortal Call Duration": {"enchant": "34% increased Immortal Call Duration", "type": "currency very high"},
	"1 36% increased Abyssal Cry Duration": {"enchant": "36% increased Abyssal Cry Duration", "type": "currency very high"},
	"1 36% increased Arctic Armour Buff Effect": {"enchant": "36% increased Arctic Armour Buff Effect", "type": "currency very high"},
	"1 36% increased Arctic Breath Duration": {"enchant": "36% increased Arctic Breath Duration", "type": "currency very high"},
	"1 36% increased Convocation Buff Effect": {"enchant": "36% increased Convocation Buff Effect", "type": "currency very high"},
	"1 36% increased Enduring Cry Buff Effect": {"enchant": "36% increased Enduring Cry Buff Effect", "type": "currency very high"},
	"1 36% increased Frost Wall Duration": {"enchant": "36% increased Frost Wall Duration", "type": "currency very high"},
	"1 36% increased Ice Shot Duration": {"enchant": "36% increased Ice Shot Duration", "type": "currency very high"},
	"1 36% increased Immortal Call Duration": {"enchant": "36% increased Immortal Call Duration", "type": "currency very high"},
	"1 36% increased Phase Run Duration": {"enchant": "36% increased Phase Run Duration", "type": "currency very high"},
	"1 36% increased Searing Bond Totem Elemental Resistances": {"enchant": "36% increased Searing Bond Totem Elemental Resistances", "type": "currency very high"},
	"1 36% increased Wild Strike Area of Effect": {"enchant": "36% increased Wild Strike Area of Effect", "type": "currency very high"},
	"1 40% chance to Summon an additional Skeleton Warrior with Summon Skeleton": {"enchant": "40% chance to Summon an additional Skeleton Warrior with Summon Skeleton", "type": "currency very high"},
	"1 40% increased Abyssal Cry Damage": {"enchant": "40% increased Abyssal Cry Damage", "type": "currency very high"},
	"1 40% increased Ancestral Warchief Totem Damage": {"enchant": "40% increased Ancestral Warchief Totem Damage", "type": "currency very high"},
	"1 40% increased Arc Damage": {"enchant": "40% increased Arc Damage", "type": "currency extremely high"},
	"1 40% increased Arctic Breath Damage": {"enchant": "40% increased Arctic Breath Damage", "type": "currency very high"},
	"1 40% increased Ball Lightning Damage": {"enchant": "40% increased Ball Lightning Damage", "type": "currency very high"},
	"1 40% increased Barrage Damage": {"enchant": "40% increased Barrage Damage", "type": "currency very high"},
	"1 40% increased Bear Trap Damage": {"enchant": "40% increased Bear Trap Damage", "type": "currency very high"},
	"1 40% increased Blade Flurry Damage": {"enchant": "40% increased Blade Flurry Damage", "type": "currency extremely high"},
	"1 40% increased Blade Vortex Spell Damage": {"enchant": "40% increased Blade Vortex Spell Damage", "type": "currency extremely high"},
	"1 40% increased Bladefall Damage": {"enchant": "40% increased Bladefall Damage", "type": "currency very high"},
	"1 40% increased Blast Rain Damage": {"enchant": "40% increased Blast Rain Damage", "type": "currency very high"},
	"1 40% increased Blight Damage": {"enchant": "40% increased Blight Damage", "type": "currency very high"},
	"1 40% increased Bodyswap Damage": {"enchant": "40% increased Bodyswap Damage", "type": "currency very high"},
	"1 40% increased Burning Arrow Damage": {"enchant": "40% increased Burning Arrow Damage", "type": "currency very high"},
	"1 40% increased Caustic Arrow Damage": {"enchant": "40% increased Caustic Arrow Damage", "type": "currency extremely high"},
	"1 40% increased Charged Dash Damage": {"enchant": "40% increased Charged Dash Damage", "type": "currency very high"},
	"1 40% increased Cleave Damage": {"enchant": "40% increased Cleave Damage", "type": "currency very high"},
	"1 40% increased Cold Snap Damage": {"enchant": "40% increased Cold Snap Damage", "type": "currency very high"},
	"1 40% increased Contagion Damage": {"enchant": "40% increased Contagion Damage", "type": "currency very high"},
	"1 40% increased Cremation Damage": {"enchant": "40% increased Cremation Damage", "type": "currency very high"},
	"1 40% increased Cyclone Damage": {"enchant": "40% increased Cyclone Damage", "type": "currency extremely high"},
	"1 40% increased Dark Pact Damage": {"enchant": "40% increased Dark Pact Damage", "type": "currency very high"},
	"1 40% increased Detonate Dead Damage": {"enchant": "40% increased Detonate Dead Damage", "type": "currency very high"},
	"1 40% increased Discharge Damage": {"enchant": "40% increased Discharge Damage", "type": "currency very high"},
	"1 40% increased Double Strike Damage": {"enchant": "40% increased Double Strike Damage", "type": "currency very high"},
	"1 40% increased Dual Strike Damage": {"enchant": "40% increased Dual Strike Damage", "type": "currency very high"},
	"1 40% increased Earthquake Damage": {"enchant": "40% increased Earthquake Damage", "type": "currency very high"},
	"1 40% increased Essence Drain Damage": {"enchant": "40% increased Essence Drain Damage", "type": "currency extremely high"},
	"1 40% increased Ethereal Knives Damage": {"enchant": "40% increased Ethereal Knives Damage", "type": "currency extremely high"},
	"1 40% increased Explosive Arrow Damage": {"enchant": "40% increased Explosive Arrow Damage", "type": "currency very high"},
	"1 40% increased Fire Nova Mine Damage": {"enchant": "40% increased Fire Nova Mine Damage", "type": "currency very high"},
	"1 40% increased Fire Trap Burning Damage": {"enchant": "40% increased Fire Trap Burning Damage", "type": "currency very high"},
	"1 40% increased Fire Trap Damage": {"enchant": "40% increased Fire Trap Damage", "type": "currency very high"},
	"1 40% increased Fireball Damage": {"enchant": "40% increased Fireball Damage", "type": "currency very high"},
	"1 40% increased Firestorm Damage": {"enchant": "40% increased Firestorm Damage", "type": "currency very high"},
	"1 40% increased Flame Dash Damage": {"enchant": "40% increased Flame Dash Damage", "type": "currency very high"},
	"1 40% increased Flame Surge Damage": {"enchant": "40% increased Flame Surge Damage", "type": "currency very high"},
	"1 40% increased Flameblast Damage": {"enchant": "40% increased Flameblast Damage", "type": "currency very high"},
	"1 40% increased Flicker Strike Damage": {"enchant": "40% increased Flicker Strike Damage", "type": "currency extremely high"},
	"1 40% increased Freezing Pulse Damage": {"enchant": "40% increased Freezing Pulse Damage", "type": "currency very high"},
	"1 40% increased Frenzy Damage": {"enchant": "40% increased Frenzy Damage", "type": "currency very high"},
	"1 40% increased Frost Blades Damage": {"enchant": "40% increased Frost Blades Damage", "type": "currency extremely high"},
	"1 40% increased Frost Bomb Damage": {"enchant": "40% increased Frost Bomb Damage", "type": "currency very high"},
	"1 40% increased Frostbolt Damage": {"enchant": "40% increased Frostbolt Damage", "type": "currency very high"},
	"1 40% increased Glacial Cascade Damage": {"enchant": "40% increased Glacial Cascade Damage", "type": "currency extremely high"},
	"1 40% increased Glacial Hammer Damage": {"enchant": "40% increased Glacial Hammer Damage", "type": "currency very high"},
	"1 40% increased Ground Slam Damage": {"enchant": "40% increased Ground Slam Damage", "type": "currency very high"},
	"1 40% increased Heavy Strike Damage": {"enchant": "40% increased Heavy Strike Damage", "type": "currency extremely high"},
	"1 40% increased Herald of Ash Damage": {"enchant": "40% increased Herald of Ash Damage", "type": "currency very high"},
	"1 40% increased Herald of Ice Damage": {"enchant": "40% increased Herald of Ice Damage", "type": "currency extremely high"},
	"1 40% increased Herald of Thunder Damage": {"enchant": "40% increased Herald of Thunder Damage", "type": "currency very high"},
	"1 40% increased Ice Crash Damage": {"enchant": "40% increased Ice Crash Damage", "type": "currency very high"},
	"1 40% increased Ice Nova Damage": {"enchant": "40% increased Ice Nova Damage", "type": "currency extremely high"},
	"1 40% increased Ice Shot Damage": {"enchant": "40% increased Ice Shot Damage", "type": "currency very high"},
	"1 40% increased Ice Spear Damage": {"enchant": "40% increased Ice Spear Damage", "type": "currency very high"},
	"1 40% increased Ice Trap Damage": {"enchant": "40% increased Ice Trap Damage", "type": "currency very high"},
	"1 40% increased Incinerate Damage": {"enchant": "40% increased Incinerate Damage", "type": "currency very high"},
	"1 40% increased Infernal Blow Damage": {"enchant": "40% increased Infernal Blow Damage", "type": "currency very high"},
	"1 40% increased Kinetic Blast Damage": {"enchant": "40% increased Kinetic Blast Damage", "type": "currency very high"},
	"1 40% increased Lacerate Damage": {"enchant": "40% increased Lacerate Damage", "type": "currency extremely high"},
	"1 40% increased Leap Slam Damage": {"enchant": "40% increased Leap Slam Damage", "type": "currency very high"},
	"1 40% increased Lightning Arrow Damage": {"enchant": "40% increased Lightning Arrow Damage", "type": "currency very high"},
	"1 40% increased Lightning Strike Damage": {"enchant": "40% increased Lightning Strike Damage", "type": "currency very high"},
	"1 40% increased Lightning Tendrils Damage": {"enchant": "40% increased Lightning Tendrils Damage", "type": "currency very high"},
	"1 40% increased Lightning Trap Damage": {"enchant": "40% increased Lightning Trap Damage", "type": "currency very high"},
	"1 40% increased Lightning Trap Shock Effect": {"enchant": "40% increased Lightning Trap Shock Effect", "type": "currency very high"},
	"1 40% increased Lightning Warp Damage": {"enchant": "40% increased Lightning Warp Damage", "type": "currency very high"},
	"1 40% increased Magma Orb Damage": {"enchant": "40% increased Magma Orb Damage", "type": "currency very high"},
	"1 40% increased Molten Shell Damage": {"enchant": "40% increased Molten Shell Damage", "type": "currency very high"},
	"1 40% increased Molten Strike Damage": {"enchant": "40% increased Molten Strike Damage", "type": "currency very high"},
	"1 40% increased Orb of Storms Damage": {"enchant": "40% increased Orb of Storms Damage", "type": "currency very high"},
	"1 40% increased Power Siphon Damage": {"enchant": "40% increased Power Siphon Damage", "type": "currency very high"},
	"1 40% increased Puncture Damage": {"enchant": "40% increased Puncture Damage", "type": "currency very high"},
	"1 40% increased Rain of Arrows Damage": {"enchant": "40% increased Rain of Arrows Damage", "type": "currency very high"},
	"1 40% increased Reave Damage": {"enchant": "40% increased Reave Damage", "type": "currency very high"},
	"1 40% increased Reckoning Damage": {"enchant": "40% increased Reckoning Damage", "type": "currency very high"},
	"1 40% increased Righteous Fire Damage": {"enchant": "40% increased Righteous Fire Damage", "type": "currency very high"},
	"1 40% increased Riposte Damage": {"enchant": "40% increased Riposte Damage", "type": "currency very high"},
	"1 40% increased Scorching Ray Damage": {"enchant": "40% increased Scorching Ray Damage", "type": "currency very high"},
	"1 40% increased Shield Charge Damage": {"enchant": "40% increased Shield Charge Damage", "type": "currency very high"},
	"1 40% increased Shock Nova Damage": {"enchant": "40% increased Shock Nova Damage", "type": "currency very high"},
	"1 40% increased Shockwave Totem Damage": {"enchant": "40% increased Shockwave Totem Damage", "type": "currency very high"},
	"1 40% increased Shrapnel Shot Damage": {"enchant": "40% increased Shrapnel Shot Damage", "type": "currency very high"},
	"1 40% increased Siege Ballista Damage": {"enchant": "40% increased Siege Ballista Damage", "type": "currency very high"},
	"1 40% increased Spark Damage": {"enchant": "40% increased Spark Damage", "type": "currency very high"},
	"1 40% increased Spectral Shield Throw Damage": {"enchant": "40% increased Spectral Shield Throw Damage", "type": "currency very high"},
	"1 40% increased Spectral Throw Damage": {"enchant": "40% increased Spectral Throw Damage", "type": "currency very high"},
	"1 40% increased Split Arrow Damage": {"enchant": "40% increased Split Arrow Damage", "type": "currency very high"},
	"1 40% increased Static Strike Damage": {"enchant": "40% increased Static Strike Damage", "type": "currency very high"},
	"1 40% increased Storm Burst Damage": {"enchant": "40% increased Storm Burst Damage", "type": "currency very high"},
	"1 40% increased Storm Call Damage": {"enchant": "40% increased Storm Call Damage", "type": "currency very high"},
	"1 40% increased Sunder Damage": {"enchant": "40% increased Sunder Damage", "type": "currency extremely high"},
	"1 40% increased Sweep Damage": {"enchant": "40% increased Sweep Damage", "type": "currency very high"},
	"1 40% increased Tectonic Slam Damage": {"enchant": "40% increased Tectonic Slam Damage", "type": "currency extremely high"},
	"1 40% increased Tempest Shield Damage": {"enchant": "40% increased Tempest Shield Damage", "type": "currency very high"},
	"1 40% increased Tornado Shot Damage": {"enchant": "40% increased Tornado Shot Damage", "type": "currency extremely high"},
	"1 40% increased Unearth Damage": {"enchant": "40% increased Unearth Damage", "type": "currency very high"},
	"1 40% increased Vengeance Damage": {"enchant": "40% increased Vengeance Damage", "type": "currency very high"},
	"1 40% increased Vigilant Strike Damage": {"enchant": "40% increased Vigilant Strike Damage", "type": "currency very high"},
	"1 40% increased Viper Strike Damage": {"enchant": "40% increased Viper Strike Damage", "type": "currency very high"},
	"1 40% increased Volatile Dead Damage": {"enchant": "40% increased Volatile Dead Damage", "type": "currency very high"},
	"1 40% increased Vortex Damage": {"enchant": "40% increased Vortex Damage", "type": "currency very high"},
	"1 40% increased Whirling Blades Damage": {"enchant": "40% increased Whirling Blades Damage", "type": "currency very high"},
	"1 40% increased Wild Strike Damage": {"enchant": "40% increased Wild Strike Damage", "type": "currency very high"},
	"1 40% of Glacial Cascade Physical Damage Converted to Cold Damage": {"enchant": "40% of Glacial Cascade Physical Damage Converted to Cold Damage", "type": "currency very high"},
	"1 45% Chance to gain an additional Power Charge on Kill with Power Siphon": {"enchant": "45% Chance to gain an additional Power Charge on Kill with Power Siphon", "type": "currency very high"},
	"1 45% increased Assassin's Mark Duration": {"enchant": "45% increased Assassin's Mark Duration", "type": "currency very high"},
	"1 45% increased Bone Offering Duration": {"enchant": "45% increased Bone Offering Duration", "type": "currency very high"},
	"1 45% increased Conductivity Duration": {"enchant": "45% increased Conductivity Duration", "type": "currency very high"},
	"1 45% increased Despair Duration": {"enchant": "45% increased Despair Duration", "type": "currency very high"},
	"1 45% increased Elemental Weakness Duration": {"enchant": "45% increased Elemental Weakness Duration", "type": "currency very high"},
	"1 45% increased Enfeeble Duration": {"enchant": "45% increased Enfeeble Duration", "type": "currency very high"},
	"1 45% increased Flammability Duration": {"enchant": "45% increased Flammability Duration", "type": "currency very high"},
	"1 45% increased Flesh Offering Duration": {"enchant": "45% increased Flesh Offering Duration", "type": "currency very high"},
	"1 45% increased Frostbite Duration": {"enchant": "45% increased Frostbite Duration", "type": "currency very high"},
	"1 45% increased Poacher's Mark Duration": {"enchant": "45% increased Poacher's Mark Duration", "type": "currency very high"},
	"1 45% increased Projectile Weakness Duration": {"enchant": "45% increased Projectile Weakness Duration", "type": "currency very high"},
	"1 45% increased Puncture Duration": {"enchant": "45% increased Puncture Duration", "type": "currency very high"},
	"1 45% increased Punishment Duration": {"enchant": "45% increased Punishment Duration", "type": "currency very high"},
	"1 45% increased Rallying Cry Duration": {"enchant": "45% increased Rallying Cry Duration", "type": "currency very high"},
	"1 45% increased Siege Ballista Totem Placement Speed": {"enchant": "45% increased Siege Ballista Totem Placement Speed", "type": "currency very high"},
	"1 45% increased Spirit Offering Duration": {"enchant": "45% increased Spirit Offering Duration", "type": "currency very high"},
	"1 45% increased Static Strike Duration": {"enchant": "45% increased Static Strike Duration", "type": "currency very high"},
	"1 45% increased Temporal Chains Duration": {"enchant": "45% increased Temporal Chains Duration", "type": "currency very high"},
	"1 45% increased Vigilant Strike Fortify Duration": {"enchant": "45% increased Vigilant Strike Fortify Duration", "type": "currency very high"},
	"1 45% increased Vulnerability Duration": {"enchant": "45% increased Vulnerability Duration", "type": "currency very high"},
	"1 45% increased Warlord's Mark Duration": {"enchant": "45% increased Warlord's Mark Duration", "type": "currency very high"},
	"1 6% chance to Dodge Attack Hits while at maximum Blade Flurry stages": {"enchant": "6% chance to Dodge Attack Hits while at maximum Blade Flurry stages", "type": "currency very high"},
	"1 6% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "6% increased Flicker Strike Damage per Frenzy Charge", "type": "currency very high"},
	"1 6% increased Frenzy Damage per Frenzy Charge": {"enchant": "6% increased Frenzy Damage per Frenzy Charge", "type": "currency very high"},
	"1 60% increased Chance to consume an additional Corpse with Devouring Totem": {"enchant": "60% increased Chance to consume an additional Corpse with Devouring Totem", "type": "currency very high"},
	"1 60% increased Decoy Totem Life": {"enchant": "60% increased Decoy Totem Life", "type": "currency very high"},
	"1 60% increased Fire Trap Burning Damage": {"enchant": "60% increased Fire Trap Burning Damage", "type": "currency very high"},
	"1 60% increased Flame Surge Damage against Burning Enemies": {"enchant": "60% increased Flame Surge Damage against Burning Enemies", "type": "currency very high"},
	"1 60% increased Lacerate Critical Strike Chance": {"enchant": "60% increased Lacerate Critical Strike Chance", "type": "currency very high"},
	"1 60% increased Lightning Tendrils Critical Strike Chance": {"enchant": "60% increased Lightning Tendrils Critical Strike Chance", "type": "currency very high"},
	"1 60% increased Tornado Shot Critical Strike Chance": {"enchant": "60% increased Tornado Shot Critical Strike Chance", "type": "currency very high"},
	"1 75% increased Rallying Cry Buff Effect": {"enchant": "75% increased Rallying Cry Buff Effect", "type": "currency very high"},
	"1 8% increased Ancestral Warchief Totem Area of Effect": {"enchant": "8% increased Ancestral Warchief Totem Area of Effect", "type": "currency very high"},
	"1 8% increased Blade Flurry Area of Effect": {"enchant": "8% increased Blade Flurry Area of Effect", "type": "currency very high"},
	"1 8% increased Blade Vortex Area of Effect": {"enchant": "8% increased Blade Vortex Area of Effect", "type": "currency very high"},
	"1 8% increased Discharge Radius": {"enchant": "8% increased Discharge Radius", "type": "currency very high"},
	"1 8% increased Explosive Arrow Area of Effect": {"enchant": "8% increased Explosive Arrow Area of Effect", "type": "currency very high"},
	"1 8% increased Magma Orb Area of Effect": {"enchant": "8% increased Magma Orb Area of Effect", "type": "currency very high"},
	"1 9% chance to Dodge Attack Hits while at maximum Blade Flurry stages": {"enchant": "9% chance to Dodge Attack Hits while at maximum Blade Flurry stages", "type": "currency very high"},
	"1 9% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "9% increased Flicker Strike Damage per Frenzy Charge", "type": "currency extremely high"},
	"1 9% increased Frenzy Damage per Frenzy Charge": {"enchant": "9% increased Frenzy Damage per Frenzy Charge", "type": "currency very high"},
	"1 90% increased Bladefall Critical Strike Chance": {"enchant": "90% increased Bladefall Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Double Strike Critical Strike Chance": {"enchant": "90% increased Double Strike Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Dual Strike Critical Strike Chance": {"enchant": "90% increased Dual Strike Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Flame Surge Critical Strike Chance": {"enchant": "90% increased Flame Surge Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Flameblast Critical Strike Chance": {"enchant": "90% increased Flameblast Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Orb of Storms Critical Strike Chance": {"enchant": "90% increased Orb of Storms Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Split Arrow Critical Strike Chance": {"enchant": "90% increased Split Arrow Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Tornado Shot Critical Strike Chance": {"enchant": "90% increased Tornado Shot Critical Strike Chance", "type": "currency very high"},
	"1 90% increased Viper Strike Critical Strike Chance": {"enchant": "90% increased Viper Strike Critical Strike Chance", "type": "currency very high"},
	"1 Ancestral Protector Totem deals 40% increased Damage": {"enchant": "Ancestral Protector Totem deals 40% increased Damage", "type": "currency very high"},
	"1 Ancestral Protector Totem grants 12% increased Attack Speed while Active": {"enchant": "Ancestral Protector Totem grants 12% increased Attack Speed while Active", "type": "currency very high"},
	"1 Ancestral Protector Totem grants 18% increased Attack Speed while Active": {"enchant": "Ancestral Protector Totem grants 18% increased Attack Speed while Active", "type": "currency very high"},
	"1 Ancestral Warchief Totem grants 20% increased Melee Damage while Active": {"enchant": "Ancestral Warchief Totem grants 20% increased Melee Damage while Active", "type": "currency very high"},
	"1 Ancestral Warchief Totem grants 30% increased Melee Damage while Active": {"enchant": "Ancestral Warchief Totem grants 30% increased Melee Damage while Active", "type": "currency very high"},
	"1 Anger has 15% reduced Mana Reservation": {"enchant": "Anger has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Animated Guardians deal 40% increased Damage": {"enchant": "Animated Guardians deal 40% increased Damage", "type": "currency very high"},
	"1 Animated Weapons deal 40% increased Damage": {"enchant": "Animated Weapons deal 40% increased Damage", "type": "currency very high"},
	"1 Arc Chains an additional time": {"enchant": "Arc Chains an additional time", "type": "currency extremely high"},
	"1 Arc deals 12% increased Damage for each time it has Chained": {"enchant": "Arc deals 12% increased Damage for each time it has Chained", "type": "currency very high"},
	"1 Arc deals 8% increased Damage for each time it has Chained": {"enchant": "Arc deals 8% increased Damage for each time it has Chained", "type": "currency very high"},
	"1 Arc has +30% chance to Shock": {"enchant": "Arc has +30% chance to Shock", "type": "currency extremely high"},
	"1 Arctic Armour has 30% reduced Mana Reservation": {"enchant": "Arctic Armour has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Armageddon Brand Damage Penetrates 12% of Branded Enemy's Fire Resistance": {"enchant": "Armageddon Brand Damage Penetrates 12% of Branded Enemy's Fire Resistance", "type": "currency extremely high"},
	"1 Armageddon Brand deals 40% increased Damage": {"enchant": "Armageddon Brand deals 40% increased Damage", "type": "currency extremely high"},
	"1 Armageddon Brand has 12% increased Activation Frequency": {"enchant": "Armageddon Brand has 12% increased Activation Frequency", "type": "currency very high"},
	"1 Ball Lightning fires an additional Projectile": {"enchant": "Ball Lightning fires an additional Projectile", "type": "currency very high"},
	"1 Bane deals 40% increased Damage": {"enchant": "Bane deals 40% increased Damage", "type": "currency extremely high"},
	"1 Bane has 15% increased Area of Effect": {"enchant": "Bane has 15% increased Area of Effect", "type": "currency extremely high"},
	"1 Barrage fires an additional Projectile": {"enchant": "Barrage fires an additional Projectile", "type": "currency extremely high"},
	"1 Blade Vortex has +2% to Critical Strike Multiplier for each blade": {"enchant": "Blade Vortex has +2% to Critical Strike Multiplier for each blade", "type": "currency very high"},
	"1 Blade Vortex has +3% to Critical Strike Multiplier for each blade": {"enchant": "Blade Vortex has +3% to Critical Strike Multiplier for each blade", "type": "currency extremely high"},
	"1 Bladefall has an additional Volley": {"enchant": "Bladefall has an additional Volley", "type": "currency extremely high"},
	"1 Blast Rain has a 50% chance for an additional blast": {"enchant": "Blast Rain has a 50% chance for an additional blast", "type": "currency very high"},
	"1 Blast Rain has a 75% chance for an additional blast": {"enchant": "Blast Rain has a 75% chance for an additional blast", "type": "currency very high"},
	"1 Blight has 30% increased Hinder Duration": {"enchant": "Blight has 30% increased Hinder Duration", "type": "currency very high"},
	"1 Blink Arrow and Blink Arrow Clones have 15% increased Attack Speed": {"enchant": "Blink Arrow and Blink Arrow Clones have 15% increased Attack Speed", "type": "currency very high"},
	"1 Blink Arrow and Blink Arrow Clones have 40% increased Damage": {"enchant": "Blink Arrow and Blink Arrow Clones have 40% increased Damage", "type": "currency extremely high"},
	"1 Blood Rage grants additional 12% increased Attack Speed": {"enchant": "Blood Rage grants additional 12% increased Attack Speed", "type": "currency extremely high"},
	"1 Blood Rage grants additional 30% chance to gain a Frenzy Charge on Kill": {"enchant": "Blood Rage grants additional 30% chance to gain a Frenzy Charge on Kill", "type": "currency very high"},
	"1 Blood Rage grants additional 8% increased Attack Speed": {"enchant": "Blood Rage grants additional 8% increased Attack Speed", "type": "currency very high"},
	"1 Bone Offering grants an additional +9% Chance to Block Attack Damage": {"enchant": "Bone Offering grants an additional +9% Chance to Block Attack Damage", "type": "currency very high"},
	"1 Burning Arrow has +30% chance to Ignite": {"enchant": "Burning Arrow has +30% chance to Ignite", "type": "currency very high"},
	"1 Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration": {"enchant": "Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration", "type": "currency very high"},
	"1 Chaos Golems deal 40% increased Damage": {"enchant": "Chaos Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Charged Dash has +6 to Radius of each Wave's last damage Area": {"enchant": "Charged Dash has +6 to Radius of each Wave's last damage Area", "type": "currency very high"},
	"1 Charged Dash has 15% more Movement Speed": {"enchant": "Charged Dash has 15% more Movement Speed", "type": "currency very high"},
	"1 Clarity has 30% reduced Mana Reservation": {"enchant": "Clarity has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies": {"enchant": "Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies", "type": "currency very high"},
	"1 Consecrated Path deals 40% increased Damage": {"enchant": "Consecrated Path deals 40% increased Damage", "type": "currency extremely high"},
	"1 Consecrated Path has 12% increased Area of Effect": {"enchant": "Consecrated Path has 12% increased Area of Effect", "type": "currency very high"},
	"1 Consecrated Path has 15% increased teleport range": {"enchant": "Consecrated Path has 15% increased teleport range", "type": "currency very high"},
	"1 Converted Enemies have 40% increased Damage": {"enchant": "Converted Enemies have 40% increased Damage", "type": "currency very high"},
	"1 Cremation can have up to 1 additional Geyser at a time": {"enchant": "Cremation can have up to 1 additional Geyser at a time", "type": "currency very high"},
	"1 Desecrate summons 2 additional corpses": {"enchant": "Desecrate summons 2 additional corpses", "type": "currency very high"},
	"1 Desecrate summons 3 additional corpses": {"enchant": "Desecrate summons 3 additional corpses", "type": "currency very high"},
	"1 Determination has 15% reduced Mana Reservation": {"enchant": "Determination has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Detonate Dead has a 45% chance to detonate an additional Corpse": {"enchant": "Detonate Dead has a 45% chance to detonate an additional Corpse", "type": "currency very high"},
	"1 Discipline has 20% reduced Mana Reservation": {"enchant": "Discipline has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Divine Ire Damages 2 additional nearby Enemies when gaining Stages": {"enchant": "Divine Ire Damages 2 additional nearby Enemies when gaining Stages", "type": "currency extremely high"},
	"1 Divine Ire deals 40% increased Damage": {"enchant": "Divine Ire deals 40% increased Damage", "type": "currency extremely high"},
	"1 Divine Ire's beam has 15% increased width": {"enchant": "Divine Ire's beam has 15% increased width", "type": "currency extremely high"},
	"1 Dominating Blow can summon 3 additional Magic Sentinels of Dominance": {"enchant": "Dominating Blow can summon 3 additional Magic Sentinels of Dominance", "type": "currency very high"},
	"1 Dominating Blow can summon an additional Rare Sentinel of Dominance": {"enchant": "Dominating Blow can summon an additional Rare Sentinel of Dominance", "type": "currency very high"},
	"1 Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies", "type": "currency very high"},
	"1 Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies", "type": "currency extremely high"},
	"1 Dread Banner has 40% increased Aura Effect": {"enchant": "Dread Banner has 40% increased Aura Effect", "type": "currency very high"},
	"1 Elemental Hit deals 25% increased Damage": {"enchant": "Elemental Hit deals 25% increased Damage", "type": "currency very high"},
	"1 Elemental Hit deals 40% increased Damage": {"enchant": "Elemental Hit deals 40% increased Damage", "type": "currency extremely high"},
	"1 Elemental Hit has +20% chance to Freeze, Shock and Ignite": {"enchant": "Elemental Hit has +20% chance to Freeze, Shock and Ignite", "type": "currency very high"},
	"1 Elemental Hit has +30% chance to Freeze, Shock and Ignite": {"enchant": "Elemental Hit has +30% chance to Freeze, Shock and Ignite", "type": "currency very high"},
	"1 Ethereal Knives Pierces an additional Target ": {"enchant": "Ethereal Knives Pierces an additional Target ", "type": "currency very high"},
	"1 Explosive Trap causes 2 additional smaller explosions": {"enchant": "Explosive Trap causes 2 additional smaller explosions", "type": "currency very high"},
	"1 Explosive Trap deals 40% increased Damage": {"enchant": "Explosive Trap deals 40% increased Damage", "type": "currency very high"},
	"1 Explosive Trap has 12% increased Area of Effect": {"enchant": "Explosive Trap has 12% increased Area of Effect", "type": "currency very high"},
	"1 Fire Nova Mine repeats an additional 2 times": {"enchant": "Fire Nova Mine repeats an additional 2 times", "type": "currency extremely high"},
	"1 Flame Golems have 25% increased Damage": {"enchant": "Flame Golems have 25% increased Damage", "type": "currency very high"},
	"1 Flame Golems have 40% increased Damage": {"enchant": "Flame Golems have 40% increased Damage", "type": "currency extremely high"},
	"1 Flamethrower Trap deals 40% increased Damage": {"enchant": "Flamethrower Trap deals 40% increased Damage", "type": "currency very high"},
	"1 Flamethrower Trap has 12% increased Cast Speed": {"enchant": "Flamethrower Trap has 12% increased Cast Speed", "type": "currency very high"},
	"1 Flamethrower Trap has 2 additional Flames": {"enchant": "Flamethrower Trap has 2 additional Flames", "type": "currency very high"},
	"1 Flamethrower Trap has 30% increased Skill Effect Duration": {"enchant": "Flamethrower Trap has 30% increased Skill Effect Duration", "type": "currency very high"},
	"1 Flesh Offering grants an additional 21% increased Attack Speed": {"enchant": "Flesh Offering grants an additional 21% increased Attack Speed", "type": "currency very high"},
	"1 Freeze Mine causes Enemies to lose an additional 12% Cold Resistance while Frozen": {"enchant": "Freeze Mine causes Enemies to lose an additional 12% Cold Resistance while Frozen", "type": "currency very high"},
	"1 Frostbolt has +15% chance to Freeze": {"enchant": "Frostbolt has +15% chance to Freeze", "type": "currency very high"},
	"1 Gain 15% of Rejuvenation Totem Life Regeneration as extra Mana Regeneration": {"enchant": "Gain 15% of Rejuvenation Totem Life Regeneration as extra Mana Regeneration", "type": "currency very high"},
	"1 Glacial Hammer has +30% chance to Freeze": {"enchant": "Glacial Hammer has +30% chance to Freeze", "type": "currency very high"},
	"1 Grace has 10% reduced Mana Reservation": {"enchant": "Grace has 10% reduced Mana Reservation", "type": "currency very high"},
	"1 Grace has 15% reduced Mana Reservation": {"enchant": "Grace has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Haste has 15% reduced Mana Reservation": {"enchant": "Haste has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Hatred has 15% reduced Mana Reservation": {"enchant": "Hatred has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Heavy Strike has a 12% chance to deal Double Damage": {"enchant": "Heavy Strike has a 12% chance to deal Double Damage", "type": "currency very high"},
	"1 Herald of Agony has 20% reduced Mana Reservation": {"enchant": "Herald of Agony has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Agony has 30% reduced Mana Reservation": {"enchant": "Herald of Agony has 30% reduced Mana Reservation", "type": "currency extremely high"},
	"1 Herald of Ash has 30% reduced Mana Reservation": {"enchant": "Herald of Ash has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Ice has 20% reduced Mana Reservation": {"enchant": "Herald of Ice has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Ice has 30% reduced Mana Reservation": {"enchant": "Herald of Ice has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Purity has 30% reduced Mana Reservation": {"enchant": "Herald of Purity has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Thunder has 20% reduced Mana Reservation": {"enchant": "Herald of Thunder has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Thunder has 30% reduced Mana Reservation": {"enchant": "Herald of Thunder has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Holy Flame Totem deals 40% increased Damage": {"enchant": "Holy Flame Totem deals 40% increased Damage", "type": "currency very high"},
	"1 Holy Flame Totem fires 2 additional Projectiles": {"enchant": "Holy Flame Totem fires 2 additional Projectiles", "type": "currency very high"},
	"1 Holy Flame Totem has 30% increased Projectile Speed": {"enchant": "Holy Flame Totem has 30% increased Projectile Speed", "type": "currency extremely high"},
	"1 Ice Golems deal 40% increased Damage": {"enchant": "Ice Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Ice Nova has +30% chance to Freeze": {"enchant": "Ice Nova has +30% chance to Freeze", "type": "currency very high"},
	"1 Ice Spear fires an additional Projectile": {"enchant": "Ice Spear fires an additional Projectile", "type": "currency extremely high"},
	"1 Ice Spear travels 30% reduced distance before changing forms": {"enchant": "Ice Spear travels 30% reduced distance before changing forms", "type": "currency very high"},
	"1 Ice Trap Damage Penetrates 10% Cold Resistance": {"enchant": "Ice Trap Damage Penetrates 10% Cold Resistance", "type": "currency very high"},
	"1 Incinerate has +2 to maximum stages": {"enchant": "Incinerate has +2 to maximum stages", "type": "currency very high"},
	"1 Incinerate has 12% increased Area of Effect": {"enchant": "Incinerate has 12% increased Area of Effect", "type": "currency very high"},
	"1 Infernal Blow Debuff deals an additional 5% of Damage per Charge": {"enchant": "Infernal Blow Debuff deals an additional 5% of Damage per Charge", "type": "currency extremely high"},
	"1 Kinetic Blast has a 50% chance for an additional explosion": {"enchant": "Kinetic Blast has a 50% chance for an additional explosion", "type": "currency very high"},
	"1 Kinetic Blast has a 75% chance for an additional explosion": {"enchant": "Kinetic Blast has a 75% chance for an additional explosion", "type": "currency extremely high"},
	"1 Lacerate deals 14 to 25 added Physical Damage against Bleeding Enemies": {"enchant": "Lacerate deals 14 to 25 added Physical Damage against Bleeding Enemies", "type": "currency very high"},
	"1 Lancing Steel deals 40% increased Damage": {"enchant": "Lancing Steel deals 40% increased Damage", "type": "currency very high"},
	"1 Lancing Steel's additional Projectiles have +30% chance to Impale Enemies": {"enchant": "Lancing Steel's additional Projectiles have +30% chance to Impale Enemies", "type": "currency very high"},
	"1 Lancing Steel's primary Projectile Pierces 5 additional Targets": {"enchant": "Lancing Steel's primary Projectile Pierces 5 additional Targets", "type": "currency very high"},
	"1 Lightning Arrow hits 2 additional Enemies": {"enchant": "Lightning Arrow hits 2 additional Enemies", "type": "currency very high"},
	"1 Lightning Arrow hits an additional Enemy": {"enchant": "Lightning Arrow hits an additional Enemy", "type": "currency very high"},
	"1 Lightning Golems deal 40% increased Damage": {"enchant": "Lightning Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Lightning Spire Trap deals 40% increased Damage": {"enchant": "Lightning Spire Trap deals 40% increased Damage", "type": "currency very high"},
	"1 Lightning Spire Trap has 30% increased Skill Effect Duration": {"enchant": "Lightning Spire Trap has 30% increased Skill Effect Duration", "type": "currency very high"},
	"1 Lightning Spire Trap strikes an additional area": {"enchant": "Lightning Spire Trap strikes an additional area", "type": "currency very high"},
	"1 Lightning Strike fires 3 additional Projectiles": {"enchant": "Lightning Strike fires 3 additional Projectiles", "type": "currency very high"},
	"1 Lightning Strike pierces 3 additional Targets": {"enchant": "Lightning Strike pierces 3 additional Targets", "type": "currency very high"},
	"1 Lightning Trap Damage Penetrates 10% Lightning Resistance": {"enchant": "Lightning Trap Damage Penetrates 10% Lightning Resistance", "type": "currency very high"},
	"1 Lightning Trap pierces 3 additional Targets": {"enchant": "Lightning Trap pierces 3 additional Targets", "type": "currency very high"},
	"1 Magma Orb Chains an additional 2 times": {"enchant": "Magma Orb Chains an additional 2 times", "type": "currency extremely high"},
	"1 Magma Orb Chains an additional time": {"enchant": "Magma Orb Chains an additional time", "type": "currency very high"},
	"1 Mirror Arrow and Mirror Arrow Clones have 15% increased Attack Speed": {"enchant": "Mirror Arrow and Mirror Arrow Clones have 15% increased Attack Speed", "type": "currency very high"},
	"1 Molten Strike fires 2 additional Projectiles": {"enchant": "Molten Strike fires 2 additional Projectiles", "type": "currency extremely high"},
	"1 Molten Strike fires an additional Projectile": {"enchant": "Molten Strike fires an additional Projectile", "type": "currency extremely high"},
	"1 Orb of Storms has 30% increased Cast Speed": {"enchant": "Orb of Storms has 30% increased Cast Speed", "type": "currency very high"},
	"1 Power Siphon fires 2 additional Projectiles": {"enchant": "Power Siphon fires 2 additional Projectiles", "type": "currency very high"},
	"1 Purifying Flame deals 40% increased Damage": {"enchant": "Purifying Flame deals 40% increased Damage", "type": "currency extremely high"},
	"1 Purity of Elements has 20% reduced Mana Reservation": {"enchant": "Purity of Elements has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Purity of Fire has 20% reduced Mana Reservation": {"enchant": "Purity of Fire has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Purity of Ice has 20% reduced Mana Reservation": {"enchant": "Purity of Ice has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Purity of Lightning has 20% reduced Mana Reservation": {"enchant": "Purity of Lightning has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Raging Spirits have 25% increased Damage": {"enchant": "Raging Spirits have 25% increased Damage", "type": "currency very high"},
	"1 Raging Spirits have 40% increased Damage": {"enchant": "Raging Spirits have 40% increased Damage", "type": "currency very high"},
	"1 Rain of Arrows has 15% chance to fire an additional sequence of arrows": {"enchant": "Rain of Arrows has 15% chance to fire an additional sequence of arrows", "type": "currency extremely high"},
	"1 Righteous Fire grants 20% increased Spell Damage": {"enchant": "Righteous Fire grants 20% increased Spell Damage", "type": "currency very high"},
	"1 Righteous Fire grants 30% increased Spell Damage": {"enchant": "Righteous Fire grants 30% increased Spell Damage", "type": "currency very high"},
	"1 Scourge Arrow creates an additional spore pod at Maximum Stages": {"enchant": "Scourge Arrow creates an additional spore pod at Maximum Stages", "type": "currency extremely high"},
	"1 Scourge Arrow deals 40% increased Damage": {"enchant": "Scourge Arrow deals 40% increased Damage", "type": "currency extremely high"},
	"1 Scourge Arrow has 8% chance to Poison per Stage": {"enchant": "Scourge Arrow has 8% chance to Poison per Stage", "type": "currency very high"},
	"1 Seismic Trap deals 40% increased Damage": {"enchant": "Seismic Trap deals 40% increased Damage", "type": "currency very high"},
	"1 Seismic Trap has 15% increased Cooldown Recovery Speed": {"enchant": "Seismic Trap has 15% increased Cooldown Recovery Speed", "type": "currency very high"},
	"1 Seismic Trap has 30% increased Skill Effect Duration": {"enchant": "Seismic Trap has 30% increased Skill Effect Duration", "type": "currency very high"},
	"1 Seismic Trap releases an additional Wave": {"enchant": "Seismic Trap releases an additional Wave", "type": "currency very high"},
	"1 Shattering Steel deals 40% increased Damage": {"enchant": "Shattering Steel deals 40% increased Damage", "type": "currency very high"},
	"1 Shattering Steel fires an additional Projectile": {"enchant": "Shattering Steel fires an additional Projectile", "type": "currency extremely high"},
	"1 Shattering Steel grants Fortify on Hitting an Enemy at Close Range": {"enchant": "Shattering Steel grants Fortify on Hitting an Enemy at Close Range", "type": "currency extremely high"},
	"1 Shock Nova ring deals 60% increased Damage": {"enchant": "Shock Nova ring deals 60% increased Damage", "type": "currency very high"},
	"1 Siphoning Trap deals 40% increased Damage": {"enchant": "Siphoning Trap deals 40% increased Damage", "type": "currency very high"},
	"1 Siphoning Trap has 45% increased Skill Effect Duration": {"enchant": "Siphoning Trap has 45% increased Skill Effect Duration", "type": "currency extremely high"},
	"1 Skeletons deal 40% increased Damage": {"enchant": "Skeletons deal 40% increased Damage", "type": "currency very high"},
	"1 Smite deals 40% increased Damage": {"enchant": "Smite deals 40% increased Damage", "type": "currency very high"},
	"1 Smite has 30% increased Aura Effect": {"enchant": "Smite has 30% increased Aura Effect", "type": "currency very high"},
	"1 Smite has a 15% chance for lightning to strike another target": {"enchant": "Smite has a 15% chance for lightning to strike another target", "type": "currency very high"},
	"1 Smoke Mine grants additional 30% increased Movement Speed": {"enchant": "Smoke Mine grants additional 30% increased Movement Speed", "type": "currency very high"},
	"1 Soulrend also Hinders Enemies, with 40% reduced Movement Speed": {"enchant": "Soulrend also Hinders Enemies, with 40% reduced Movement Speed", "type": "currency extremely high"},
	"1 Soulrend deals 40% increased Damage": {"enchant": "Soulrend deals 40% increased Damage", "type": "currency very high"},
	"1 Soulrend fires an additional Projectile": {"enchant": "Soulrend fires an additional Projectile", "type": "currency extremely high"},
	"1 Spark fires 2 additional Projectiles": {"enchant": "Spark fires 2 additional Projectiles", "type": "currency very high"},
	"1 Spark fires 3 additional Projectiles": {"enchant": "Spark fires 3 additional Projectiles", "type": "currency extremely high"},
	"1 Spectral Shield Throw fires 5 additional Shard Projectiles": {"enchant": "Spectral Shield Throw fires 5 additional Shard Projectiles", "type": "currency very high"},
	"1 Spectres have 12% increased Attack and Cast Speed": {"enchant": "Spectres have 12% increased Attack and Cast Speed", "type": "currency very high"},
	"1 Spectres have 40% increased Damage": {"enchant": "Spectres have 40% increased Damage", "type": "currency very high"},
	"1 Spirit Offering grants +12% of Physical Damage as Extra Chaos Damage": {"enchant": "Spirit Offering grants +12% of Physical Damage as Extra Chaos Damage", "type": "currency very high"},
	"1 Split Arrow fires 2 additional Projectiles": {"enchant": "Split Arrow fires 2 additional Projectiles", "type": "currency very high"},
	"1 Split Arrow fires 3 additional Projectiles": {"enchant": "Split Arrow fires 3 additional Projectiles", "type": "currency very high"},
	"1 Static Strike has +2 maximum Beam Targets": {"enchant": "Static Strike has +2 maximum Beam Targets", "type": "currency very high"},
	"1 Stone Golems deal 40% increased Damage": {"enchant": "Stone Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance", "type": "currency extremely high"},
	"1 Storm Brand Damage Penetrates 8% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Damage Penetrates 8% of Branded Enemy's Lightning Resistance", "type": "currency extremely high"},
	"1 Storm Brand deals 40% increased Damage": {"enchant": "Storm Brand deals 40% increased Damage", "type": "currency extremely high"},
	"1 Storm Brand has a 18% chance to Chain an additional time": {"enchant": "Storm Brand has a 18% chance to Chain an additional time", "type": "currency extremely high"},
	"1 Storm Burst has a 15% chance to create an additional Orb": {"enchant": "Storm Burst has a 15% chance to create an additional Orb", "type": "currency very high"},
	"1 Summon Raging Spirit has 18% chance to summon an extra Minion": {"enchant": "Summon Raging Spirit has 18% chance to summon an extra Minion", "type": "currency very high"},
	"1 Summoned Agony Crawler fires 2 additional Projectiles": {"enchant": "Summoned Agony Crawler fires 2 additional Projectiles", "type": "currency extremely high"},
	"1 Summoned Holy Relics deal 40% increased Damage": {"enchant": "Summoned Holy Relics deal 40% increased Damage", "type": "currency very high"},
	"1 Summoned Holy Relics have 100% increased Buff Effect": {"enchant": "Summoned Holy Relics have 100% increased Buff Effect", "type": "currency very high"},
	"1 Tectonic Slam has 20% chance to create a Charged Slam": {"enchant": "Tectonic Slam has 20% chance to create a Charged Slam", "type": "currency extremely high"},
	"1 Tempest Shield chains an additional 3 times": {"enchant": "Tempest Shield chains an additional 3 times", "type": "currency very high"},
	"1 Tornado Shot fires 2 additional secondary Projectiles": {"enchant": "Tornado Shot fires 2 additional secondary Projectiles", "type": "currency extremely high"},
	"1 Tornado Shot fires an additional secondary Projectile": {"enchant": "Tornado Shot fires an additional secondary Projectile", "type": "currency extremely high"},
	"1 Toxic Rain deals 40% increased Damage": {"enchant": "Toxic Rain deals 40% increased Damage", "type": "currency very high"},
	"1 Toxic Rain fires 1 additional Arrow": {"enchant": "Toxic Rain fires 1 additional Arrow", "type": "currency extremely high"},
	"1 Toxic Rain gains 10% of Physical Damage as Extra Chaos Damage": {"enchant": "Toxic Rain gains 10% of Physical Damage as Extra Chaos Damage", "type": "currency very high"},
	"1 Unearth Creates Corpses with +5 Level": {"enchant": "Unearth Creates Corpses with +5 Level", "type": "currency very high"},
	"1 Vitality has 20% reduced Mana Reservation": {"enchant": "Vitality has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Volatile Dead destroys up to 1 additional Corpse": {"enchant": "Volatile Dead destroys up to 1 additional Corpse", "type": "currency extremely high"},
	"1 Vortex has 30% increased Cooldown Recovery Speed": {"enchant": "Vortex has 30% increased Cooldown Recovery Speed", "type": "currency extremely high"},
	"1 Vortex has 45% increased Area of Effect when Cast on Frostbolt": {"enchant": "Vortex has 45% increased Area of Effect when Cast on Frostbolt", "type": "currency very high"},
	"1 Wave of Conviction's Exposure applies -6% Elemental Resistance": {"enchant": "Wave of Conviction's Exposure applies -6% Elemental Resistance", "type": "currency extremely high"},
	"1 Wild Strike Chains an additional 4 times": {"enchant": "Wild Strike Chains an additional 4 times", "type": "currency very high"},
	"1 Wild Strike Chains an additional 6 times": {"enchant": "Wild Strike Chains an additional 6 times", "type": "currency very high"},
	"1 Winter Orb deals 25% increased Damage": {"enchant": "Winter Orb deals 25% increased Damage", "type": "currency very high"},
	"1 Winter Orb deals 40% increased Damage": {"enchant": "Winter Orb deals 40% increased Damage", "type": "currency extremely high"},
	"1 Winter Orb has +2 Maximum Stages": {"enchant": "Winter Orb has +2 Maximum Stages", "type": "currency extremely high"},
	"1 Winter Orb has 3% increased Area of Effect per Stage": {"enchant": "Winter Orb has 3% increased Area of Effect per Stage", "type": "currency very high"},
	"1 Wither has 12% increased Area of Effect": {"enchant": "Wither has 12% increased Area of Effect", "type": "currency very high"},
	"1 Wrath has 15% reduced Mana Reservation": {"enchant": "Wrath has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Zealotry has 15% reduced Mana Reservation": {"enchant": "Zealotry has 15% reduced Mana Reservation", "type": "currency extremely high"},
	"1 Zombies deal 40% increased Damage": {"enchant": "Zombies deal 40% increased Damage", "type": "currency very high"},
	"1 Zombies have 15% increased Attack Speed": {"enchant": "Zombies have 15% increased Attack Speed", "type": "currency very high"},
}
