#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 03/13/2020(m/d/y) 20:00:34 UTC from "Standard" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"1 +1 to maximum number of Bladestorms": {"enchant": "Enchantment Bladestorm Maximum Number Of Storms Allowed 1", "type": "base very high"},
	"1 +1 to maximum number of Sentinels of Purity": {"enchant": "Enchantment Herald Of Purity Additional Minion 1", "type": "base very high"},
	"1 +24% to Animated Guardian Elemental Resistances": {"enchant": "Enchantment Animate Guardian Elemental Resistances 1", "type": "base very high"},
	"1 +36% to Chaos Golem Elemental Resistances": {"enchant": "Enchantment Chaos Golem Elemental Resistances 2", "type": "base very high"},
	"1 10% increased Cyclone Attack Speed": {"enchant": "Enchantment Cyclone Attack Speed 1", "type": "base very high"},
	"1 10% increased Double Strike Attack Speed": {"enchant": "Enchantment Double Strike Attack Speed 1", "type": "base very high"},
	"1 10% increased Incinerate Damage for each stage": {"enchant": "Enchantment Incinerate Damage Per Stage 3", "type": "base very high"},
	"1 12% increased Dark Pact Cast Speed": {"enchant": "Enchantment Dack Pact Cast Speed 2", "type": "base very high"},
	"1 12% increased Fireball Cast Speed": {"enchant": "Enchantment Fireball Cast Speed 2", "type": "base very high"},
	"1 12% increased Freezing Pulse Cast Speed": {"enchant": "Enchantment Freezing Pulse Cast Speed 2", "type": "base very high"},
	"1 12% increased Icicle Mine Throwing Speed": {"enchant": "Enchantment Icicle Mine Throwing Speed 2", "type": "base very high"},
	"1 12% increased Scorching Ray Cast Speed": {"enchant": "Enchantment Fire Beam Cast Speed 2", "type": "base very high"},
	"1 15% Chance to gain a Power Charge on Critical Strike with Ice Spear": {"enchant": "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 2", "type": "base very high"},
	"1 15% increased Barrage Attack Speed": {"enchant": "Enchantment Barrage Attack Speed 2", "type": "base very high"},
	"1 15% increased Cleave Attack Speed": {"enchant": "Enchantment Cleave Attack Speed 2", "type": "base very high"},
	"1 15% increased Cyclone Attack Speed": {"enchant": "Enchantment Cyclone Attack Speed 2", "type": "base extremely high"},
	"1 15% increased Double Strike Attack Speed": {"enchant": "Enchantment Double Strike Attack Speed 2", "type": "base very high"},
	"1 15% increased Dual Strike Attack Speed": {"enchant": "Enchantment Dual Strike Attack Speed 2", "type": "base very high"},
	"1 15% increased Effect of Curses applied by Bane": {"enchant": "Enchantment Bane Linked Curse Effect 2", "type": "base very high"},
	"1 15% increased Elemental Hit Attack Speed": {"enchant": "Enchantment Elemental Hit Attack Speed 2", "type": "base very high"},
	"1 15% increased Heavy Strike Attack Speed": {"enchant": "Enchantment Heavy Strike Attack Speed 2", "type": "base very high"},
	"1 15% increased Leap Slam Attack Speed": {"enchant": "Enchantment Leap Slam Attack Speed 2", "type": "base very high"},
	"1 15% increased Power Siphon Attack Speed": {"enchant": "Enchantment Power Siphon Attack Speed 2", "type": "base very high"},
	"1 15% increased Rain of Arrows Attack Speed": {"enchant": "Enchantment Rain Of Arrows Attack Speed 2", "type": "base very high"},
	"1 15% increased Scorching Ray beam length": {"enchant": "Enchantment Fire Beam Length 2", "type": "base very high"},
	"1 15% increased Shield Charge Attack Speed": {"enchant": "Enchantment Shield Charge Attack Speed 2", "type": "base very high"},
	"1 15% increased Sunder Attack Speed": {"enchant": "Enchantment Sunder Attack Speed 2", "type": "base very high"},
	"1 15% increased Whirling Blades Attack Speed": {"enchant": "Enchantment Whirling Blades Attack Speed 2", "type": "base very high"},
	"1 15% of Burning Arrow Physical Damage gained as Extra Fire Damage": {"enchant": "Enchantment Burning Arrow Physical Damage Percent To Add As Fire Damage 2", "type": "base very high"},
	"1 15% of Galvanic Arrow Physical Damage gained as extra Lightning Damage": {"enchant": "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2", "type": "base very high"},
	"1 15% of Glacial Hammer Physical Damage gained as Extra Cold Damage": {"enchant": "Enchantment Glacial Hammer Physical Damage Percent To Add As Cold Damage 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Carrion Golems": {"enchant": "Enchantment Summon Carrion Golem Granted Buff Effect 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Flame Golems": {"enchant": "Enchantment Flame Golem Granted Buff Effect 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Ice Golems": {"enchant": "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Lightning Golems": {"enchant": "Enchantment Lightning Golem Granted Buff Effect 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Stone Golems": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "base very high"},
	"1 150% increased Molten Shell Buff Effect": {"enchant": "Enchantment Molten Shell Armour 2", "type": "base very high"},
	"1 16% increased Sweep Area of Effect": {"enchant": "Enchantment Sweep Area Of Effect 1", "type": "base very high"},
	"1 20% increased Blade Vortex Duration": {"enchant": "Enchantment Blade Vortex Duration 1", "type": "base very high"},
	"1 20% increased Poacher's Mark Curse Effect": {"enchant": "Enchantment Poachers Mark Curse Effect 1", "type": "base very high"},
	"1 20% increased Temporal Chains Curse Effect": {"enchant": "Enchantment Temporal Chains Curse Effect 1", "type": "base very high"},
	"1 20% reduced Lightning Warp Duration": {"enchant": "Enchantment Lightning Warp Duration 1", "type": "base very high"},
	"1 20% reduced Storm Call Duration": {"enchant": "Enchantment Storm Call Duration 1", "type": "base very high"},
	"1 24% chance to create an additional Animate Weapon copy": {"enchant": "Enchantment Animate Weapon Chance To Create Additional Copy 2", "type": "base very high"},
	"1 24% increased Ancestral Warchief Totem Area of Effect": {"enchant": "Enchantment Ancestor Warchief Area Of Effect 2", "type": "base very high"},
	"1 24% increased Ball Lightning Area of Effect": {"enchant": "Enchantment Ball Lightning Area Of Effect 2", "type": "base very high"},
	"1 24% increased Caustic Arrow Area of Effect": {"enchant": "Enchantment Caustic Arrow Area Of Effect 2", "type": "base very high"},
	"1 24% increased Dark Pact Area of Effect": {"enchant": "Enchantment Dark Pact Area Of Effect 2", "type": "base very high"},
	"1 24% increased Detonate Dead Area of Effect": {"enchant": "Enchantment Detonate Dead Area Of Effect 2", "type": "base very high"},
	"1 24% increased Discharge Radius": {"enchant": "Enchantment Discharge Area of Effect 2", "type": "base very high"},
	"1 24% increased Frost Bomb Area of Effect": {"enchant": "Enchantment Frost Bomb Area Of Effect 2", "type": "base very high"},
	"1 24% increased Glacial Cascade Area of Effect": {"enchant": "Enchantment Glacial Cascade Area Of Effect 2", "type": "base very high"},
	"1 24% increased Ground Slam Area of Effect": {"enchant": "Enchantment Ground Slam Area Of Effect 2", "type": "base very high"},
	"1 24% increased Ice Crash Area of Effect": {"enchant": "Enchantment Ice Crash Area Of Effect 2", "type": "base very high"},
	"1 24% increased Ice Nova Area of Effect": {"enchant": "Enchantment Ice Nova Area Of Effect 2", "type": "base very high"},
	"1 24% increased Ice Shot Area of Effect": {"enchant": "Enchantment Ice Shot Area Of Effect 2", "type": "base very high"},
	"1 24% increased Incinerate Damage": {"enchant": "Enchantment Incinerate Damage Per Stage 2", "type": "base very high"},
	"1 24% increased Leap Slam Area of Effect": {"enchant": "Enchantment Leap Slam Area Of Effect 2", "type": "base very high"},
	"1 24% increased Lightning Arrow Area of Effect": {"enchant": "Enchantment Lightning Arrow Area Of Effect 2", "type": "base very high"},
	"1 24% increased Reave Radius": {"enchant": "Enchantment Reave Area Of Effect 2", "type": "base very high"},
	"1 24% increased Shock Nova Area of Effect": {"enchant": "Enchantment Shock Nova Area Of Effect 2", "type": "base very high"},
	"1 24% increased Storm Burst Area of Effect": {"enchant": "Enchantment Storm Burst Area Of Effect 2", "type": "base very high"},
	"1 24% increased Sweep Area of Effect": {"enchant": "Enchantment Sweep Area Of Effect 2", "type": "base very high"},
	"1 25% increased Cyclone Damage": {"enchant": "Enchantment Cyclone Damage 1", "type": "base very high"},
	"1 25% increased Ice Nova Damage": {"enchant": "Enchantment Ice Nova Damage 1", "type": "base very high"},
	"1 30% Chance on Frenzy to gain an additional Frenzy Charge": {"enchant": "Enchantment Frenzy Percent Chance To Gain Additional Frenzy Charge 2", "type": "base very high"},
	"1 30% chance for Discharge to deal Damage without removing Charges": {"enchant": "Enchantment Discharge Consume Charges 2", "type": "base very high"},
	"1 30% increased Animate Weapon Duration": {"enchant": "Enchantment Animate Weapon Duration 2", "type": "base very high"},
	"1 30% increased Assassin's Mark Curse Effect": {"enchant": "Enchantment Assassins Mark Curse Effect 2", "type": "base very high"},
	"1 30% increased Blade Vortex Duration": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "base extremely high"},
	"1 30% increased Blink Arrow Cooldown Recovery Speed": {"enchant": "Enchantment Blink Arrow Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Caustic Arrow Duration": {"enchant": "Enchantment Caustic Arrow Duration 2", "type": "base very high"},
	"1 30% increased Cold Snap Cooldown Recovery Speed": {"enchant": "Enchantment Cold Snap Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Conductivity Curse Effect": {"enchant": "Enchantment Conductivity Curse Effect 2", "type": "base very high"},
	"1 30% increased Desecrate Duration": {"enchant": "Enchantment Desecrate Duration 2", "type": "base very high"},
	"1 30% increased Despair Curse Effect": {"enchant": "Enchantment Despair Effect 2", "type": "base very high"},
	"1 30% increased Elemental Weakness Curse Effect": {"enchant": "Enchantment Elemental Weakness Curse Effect 2", "type": "base very high"},
	"1 30% increased Enfeeble Curse Effect": {"enchant": "Enchantment Enfeeble Curse Effect 2", "type": "base very high"},
	"1 30% increased Essence Drain Duration": {"enchant": "Enchantment Essence Drain Duration 2", "type": "base very high"},
	"1 30% increased Ethereal Knives Projectile Speed": {"enchant": "Enchantment Ethereal Knives Projectile Speed 2", "type": "base very high"},
	"1 30% increased Flame Dash Cooldown Recovery Speed": {"enchant": "Enchantment Flame Dash Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Flammability Curse Effect": {"enchant": "Enchantment Flammability Curse Effect 2", "type": "base very high"},
	"1 30% increased Freezing Pulse Projectile Speed": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "base very high"},
	"1 30% increased Frost Blades Projectile Speed": {"enchant": "Enchantment Frost Blades Projectile Speed 2", "type": "base very high"},
	"1 30% increased Frostbite Curse Effect": {"enchant": "Enchantment Frostbite Curse Effect 2", "type": "base very high"},
	"1 30% increased Ice Trap Damage": {"enchant": "Enchantment Ice Trap Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Incinerate Damage": {"enchant": "Enchantment Incinerate Projectile Speed 2", "type": "base very high"},
	"1 30% increased Poacher's Mark Curse Effect": {"enchant": "Enchantment Poachers Mark Curse Effect 2", "type": "base very high"},
	"1 30% increased Projectile Weakness Curse Effect": {"enchant": "Enchantment Projectile Weakness Curse Effect 2", "type": "base very high"},
	"1 30% increased Reckoning Cooldown Recovery Speed": {"enchant": "Enchantment Reckoning Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Spark Projectile Speed": {"enchant": "Enchantment Spark Projectile Speed 2", "type": "base very high"},
	"1 30% increased Spectral Throw Projectile Speed": {"enchant": "Enchantment Spectral Throw Projectile Speed 2", "type": "base very high"},
	"1 30% increased Temporal Chains Curse Effect": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "base extremely high"},
	"1 30% increased Vengeance Cooldown Recovery Speed": {"enchant": "Enchantment Vengeance Cooldown Speed 2", "type": "base very high"},
	"1 30% increased Viper Strike Duration": {"enchant": "Enchantment Viper Strike Poison Duration 2", "type": "base very high"},
	"1 30% increased Vulnerability Curse Effect": {"enchant": "Enchantment Vulnerability Curse Effect 2", "type": "base very high"},
	"1 30% increased Warlord's Mark Curse Effect": {"enchant": "Enchantment Warlords Mark Curse Effect 2", "type": "base very high"},
	"1 30% reduced Earthquake Duration": {"enchant": "Enchantment Earthquake Duration 2", "type": "base very high"},
	"1 30% reduced Lightning Warp Duration": {"enchant": "Enchantment Lightning Warp Duration 2", "type": "base extremely high"},
	"1 30% reduced Spectral Throw Projectile Deceleration": {"enchant": "Enchantment Spectral Throw Projectile Deceleration 2", "type": "base very high"},
	"1 30% reduced Storm Call Duration": {"enchant": "Enchantment Storm Call Duration 2", "type": "base extremely high"},
	"1 300% increased Ice Spear Critical Strike Chance in second form": {"enchant": "Enchantment Ice Spear Second Form Critical Strike Chance 2", "type": "base very high"},
	"1 36% increased Abyssal Cry Duration": {"enchant": "Enchantment Abyssal Cry Duration 2", "type": "base very high"},
	"1 36% increased Arctic Armour Buff Effect": {"enchant": "Enchantment Arctic Armour Buff Effect 2", "type": "base very high"},
	"1 36% increased Arctic Breath Duration": {"enchant": "Enchantment Arctic Breath Duration 2", "type": "base very high"},
	"1 36% increased Frost Wall Duration": {"enchant": "Enchantment Frost Wall Duration 2", "type": "base very high"},
	"1 36% increased Ice Shot Damage": {"enchant": "Enchantment Ice Shot Damage 2", "type": "base very high"},
	"1 36% increased Phase Run Duration": {"enchant": "Enchantment Phase Run Duration 2", "type": "base very high"},
	"1 36% increased Wild Strike Area of Effect": {"enchant": "Enchantment Wild Strike Area Of Effect 2", "type": "base very high"},
	"1 40% increased Ancestral Warchief Totem Damage": {"enchant": "Enchantment Ancestral Warchief Damage 2", "type": "base very high"},
	"1 40% increased Arc Damage": {"enchant": "Enchantment Arc Damage 2", "type": "base very high"},
	"1 40% increased Arctic Breath Damage": {"enchant": "Enchantment Arctic Breath Damage 2", "type": "base very high"},
	"1 40% increased Ball Lightning Damage": {"enchant": "Enchantment Ball Lightning Damage 2", "type": "base very high"},
	"1 40% increased Barrage Damage": {"enchant": "Enchantment Barrage Damage 2", "type": "base very high"},
	"1 40% increased Blade Flurry Damage": {"enchant": "Enchantment Blade Flurry Damage 2", "type": "base very high"},
	"1 40% increased Blade Vortex Spell Damage": {"enchant": "Enchantment Blade Vortex Damage 2", "type": "base extremely high"},
	"1 40% increased Bladefall Damage": {"enchant": "Enchantment Bladefall Damage 2", "type": "base very high"},
	"1 40% increased Blight Damage": {"enchant": "Enchantment Blight Damage 2", "type": "base very high"},
	"1 40% increased Bodyswap Damage": {"enchant": "Enchantment Body Swap Damage 2", "type": "base very high"},
	"1 40% increased Burning Arrow Damage": {"enchant": "Enchantment Burning Arrow Damage 2", "type": "base very high"},
	"1 40% increased Caustic Arrow Damage": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "base extremely high"},
	"1 40% increased Charged Dash Damage": {"enchant": "Enchantment Charged Dash Damage 2", "type": "base very high"},
	"1 40% increased Cleave Damage": {"enchant": "Enchantment Cleave Damage 2", "type": "base very high"},
	"1 40% increased Cold Snap Damage": {"enchant": "Enchantment Cold Snap Damage 2", "type": "base very high"},
	"1 40% increased Cyclone Damage": {"enchant": "Enchantment Cyclone Damage 2", "type": "base extremely high"},
	"1 40% increased Dark Pact Damage": {"enchant": "Enchantment Dark Pact Damage 2", "type": "base very high"},
	"1 40% increased Detonate Dead Damage": {"enchant": "Enchantment Detonate Dead Damage 2", "type": "base very high"},
	"1 40% increased Discharge Damage": {"enchant": "Enchantment Discharge Damage 2", "type": "base very high"},
	"1 40% increased Double Strike Damage": {"enchant": "Enchantment Double Strike Damage 2", "type": "base very high"},
	"1 40% increased Dual Strike Damage": {"enchant": "Enchantment Dual Strike Damage 2", "type": "base very high"},
	"1 40% increased Earthquake Damage": {"enchant": "Enchantment Earthquake Damage 2", "type": "base very high"},
	"1 40% increased Essence Drain Damage": {"enchant": "Enchantment Essence Drain Damage 2", "type": "base very high"},
	"1 40% increased Ethereal Knives Damage": {"enchant": "Enchantment Ethereal Knives Damage 2", "type": "base very high"},
	"1 40% increased Fire Trap Damage": {"enchant": "Enchantment Fire Trap Damage 2", "type": "base very high"},
	"1 40% increased Fireball Damage": {"enchant": "Enchantment Fireball Damage 2", "type": "base very high"},
	"1 40% increased Firestorm Damage": {"enchant": "Enchantment Firestorm Damage 2", "type": "base very high"},
	"1 40% increased Flame Dash Damage": {"enchant": "Enchantment Flame Dash Damage 2", "type": "base very high"},
	"1 40% increased Flame Surge Damage": {"enchant": "Enchantment Flame Surge Damage 2", "type": "base very high"},
	"1 40% increased Flameblast Damage": {"enchant": "Enchantment Flameblast Damage 2", "type": "base very high"},
	"1 40% increased Flicker Strike Damage": {"enchant": "Enchantment Flicker Strike Damage 2", "type": "base extremely high"},
	"1 40% increased Freezing Pulse Damage": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "base very high"},
	"1 40% increased Frost Blades Damage": {"enchant": "Enchantment Frost Blades Damage 2", "type": "base extremely high"},
	"1 40% increased Frost Bomb Damage": {"enchant": "Enchantment Frost Bomb Damage 2", "type": "base very high"},
	"1 40% increased Frostbolt Damage": {"enchant": "Enchantment Frost Bolt Damage 2", "type": "base very high"},
	"1 40% increased Galvanic Arrow Damage": {"enchant": "Enchantment Shrapnel Shot Damage 2", "type": "base very high"},
	"1 40% increased Glacial Cascade Damage": {"enchant": "Enchantment Glacial Cascade Damage 2", "type": "base very high"},
	"1 40% increased Glacial Hammer Damage": {"enchant": "Enchantment Glacial Hammer Damage 2", "type": "base very high"},
	"1 40% increased Ground Slam Damage": {"enchant": "Enchantment Ground Slam Damage 2", "type": "base very high"},
	"1 40% increased Heavy Strike Damage": {"enchant": "Enchantment Heavy Strike Damage 2", "type": "base very high"},
	"1 40% increased Herald of Ash Damage": {"enchant": "Enchantment Herald Of Ash Damage 2", "type": "base very high"},
	"1 40% increased Herald of Ice Damage": {"enchant": "Enchantment Herald Of Ice Damage 2", "type": "base very high"},
	"1 40% increased Herald of Thunder Damage": {"enchant": "Enchantment Herald Of Thunder Damage 2", "type": "base very high"},
	"1 40% increased Ice Crash Damage": {"enchant": "Enchantment Ice Crash Damage 2", "type": "base very high"},
	"1 40% increased Ice Nova Damage": {"enchant": "Enchantment Ice Nova Damage 2", "type": "base extremely high"},
	"1 40% increased Ice Shot Damage": {"enchant": "Enchantment Ice Shot Damage 2", "type": "base extremely high"},
	"1 40% increased Ice Spear Damage": {"enchant": "Enchantment Ice Spear Damage 2", "type": "base very high"},
	"1 40% increased Incinerate Damage": {"enchant": "Enchantment Incinerate Damage 2", "type": "base very high"},
	"1 40% increased Infernal Blow Damage": {"enchant": "Enchantment Infernal Blow Damage 2", "type": "base very high"},
	"1 40% increased Kinetic Blast Damage": {"enchant": "Enchantment Kinetic Blast Damage 2", "type": "base very high"},
	"1 40% increased Lacerate Damage": {"enchant": "Enchantment Lacerate Damage 2", "type": "base extremely high"},
	"1 40% increased Lightning Arrow Damage": {"enchant": "Enchantment Lightning Arrow Damage 2", "type": "base very high"},
	"1 40% increased Lightning Strike Damage": {"enchant": "Enchantment Lightning Strike Damage 2", "type": "base very high"},
	"1 40% increased Magma Orb Damage": {"enchant": "Enchantment Magma Orb Damage 2", "type": "base very high"},
	"1 40% increased Molten Strike Damage": {"enchant": "Enchantment Molten Strike Damage 2", "type": "base very high"},
	"1 40% increased Power Siphon Damage": {"enchant": "Enchantment Power Siphon Damage 2", "type": "base very high"},
	"1 40% increased Puncture Damage": {"enchant": "Enchantment Puncture Damage 2", "type": "base very high"},
	"1 40% increased Rain of Arrows Damage": {"enchant": "Enchantment Rain Of Arrows Damage 2", "type": "base very high"},
	"1 40% increased Reave Damage": {"enchant": "Enchantment Reave Damage 2", "type": "base very high"},
	"1 40% increased Reckoning Damage": {"enchant": "Enchantment Reckoning Damage 2", "type": "base very high"},
	"1 40% increased Righteous Fire Damage": {"enchant": "Enchantment Righteous Fire Damage 2", "type": "base very high"},
	"1 40% increased Scorching Ray Damage": {"enchant": "Enchantment Scorching Ray Damage 2", "type": "base very high"},
	"1 40% increased Shock Nova Damage": {"enchant": "Enchantment Shock Nova Damage 2", "type": "base very high"},
	"1 40% increased Shockwave Totem Damage": {"enchant": "Enchantment Shockwave Totem Damage 2", "type": "base very high"},
	"1 40% increased Spark Damage": {"enchant": "Enchantment Spark Damage 2", "type": "base very high"},
	"1 40% increased Spectral Shield Throw Damage": {"enchant": "Enchantment Spectral Shield Throw Damage 2", "type": "base very high"},
	"1 40% increased Spectral Throw Damage": {"enchant": "Enchantment Spectral Throw Damage 2", "type": "base very high"},
	"1 40% increased Split Arrow Damage": {"enchant": "Enchantment Split Arrow Damage 2", "type": "base very high"},
	"1 40% increased Storm Burst Damage": {"enchant": "Enchantment Storm Burst Damage 2", "type": "base very high"},
	"1 40% increased Storm Call Damage": {"enchant": "Enchantment Storm Call Damage 2", "type": "base very high"},
	"1 40% increased Sunder Damage": {"enchant": "Enchantment Sunder Damage 2", "type": "base very high"},
	"1 40% increased Sweep Damage": {"enchant": "Enchantment Sweep Damage 2", "type": "base very high"},
	"1 40% increased Tectonic Slam Damage": {"enchant": "Enchantment Tectonic Slam Damage 2", "type": "base very high"},
	"1 40% increased Tornado Shot Damage": {"enchant": "Enchantment Tornado Shot Damage 2", "type": "base very high"},
	"1 40% increased Unearth Damage": {"enchant": "Enchantment Unearth Damage 2", "type": "base very high"},
	"1 40% increased Viper Strike Damage": {"enchant": "Enchantment Viper Strike Damage 2", "type": "base very high"},
	"1 40% increased Volatile Dead Damage": {"enchant": "Enchantment Volatile Dead Damage 2", "type": "base very high"},
	"1 40% increased Vortex Damage": {"enchant": "Enchantment Vortex Damage 2", "type": "base very high"},
	"1 40% increased Wild Strike Damage": {"enchant": "Enchantment Wild Strike Damage 2", "type": "base very high"},
	"1 40% of Glacial Cascade Physical Damage Converted to Cold Damage": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2", "type": "base very high"},
	"1 45% increased Despair Duration": {"enchant": "Enchantment Despair Duration 2", "type": "base very high"},
	"1 45% increased Elemental Weakness Duration": {"enchant": "Enchantment Elemental Weakness Duration 2", "type": "base very high"},
	"1 45% increased Enfeeble Duration": {"enchant": "Enchantment Enfeeble Duration 2", "type": "base very high"},
	"1 45% increased Flesh Offering Duration": {"enchant": "Enchantment Flesh Offering Duration 2", "type": "base very high"},
	"1 45% increased Spirit Offering Duration": {"enchant": "Enchantment Spirit Offering Duration 2", "type": "base very high"},
	"1 45% increased Static Strike Duration": {"enchant": "Enchantment Static Strike Duration 2", "type": "base very high"},
	"1 45% increased Temporal Chains Duration": {"enchant": "Enchantment Temporal Chains Duration 2", "type": "base very high"},
	"1 6% chance to Dodge Attack Hits if you have finished Channelling Charged Dash Recently": {"enchant": "Enchantment Charged Dash Dodge When Finished Channelling 2", "type": "base very high"},
	"1 60% increased Fire Trap Burning Damage": {"enchant": "Enchantment Fire Trap Burning Damage 2", "type": "base very high"},
	"1 60% increased Lacerate Critical Strike Chance": {"enchant": "Enchantment Double Slash Critical Strikes 2", "type": "base very high"},
	"1 60% increased Lightning Tendrils Critical Strike Chance": {"enchant": "Enchantment Lightning Tendrils Critical Strike Chance 2", "type": "base very high"},
	"1 8% increased Icicle Mine Throwing Speed": {"enchant": "Enchantment Icicle Mine Throwing Speed 1", "type": "base very high"},
	"1 9% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 2", "type": "base extremely high"},
	"1 9% increased Frenzy Damage per Frenzy Charge": {"enchant": "Enchantment Frenzy Damage Per Frenzy Charge 2", "type": "base very high"},
	"1 90% increased Bladefall Critical Strike Chance": {"enchant": "Enchantment Bladefall Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Double Strike Critical Strike Chance": {"enchant": "Enchantment Double Strike Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Dual Strike Critical Strike Chance": {"enchant": "Enchantment Dual Strike Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Flame Surge Critical Strike Chance": {"enchant": "Enchantment Flame Surge Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Orb of Storms Critical Strike Chance": {"enchant": "Enchantment Orb of Storms Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Split Arrow Critical Strike Chance": {"enchant": "Enchantment Split Arrow Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Tornado Shot Critical Strike Chance": {"enchant": "Enchantment Tornado Shot Critical Strike Chance 2", "type": "base very high"},
	"1 90% increased Viper Strike Critical Strike Chance": {"enchant": "Enchantment Viper Strike Critical Strike Chance 2", "type": "base very high"},
	"1 Ancestral Warchief Totem grants 30% increased Melee Damage while Active": {"enchant": "Enchantment Ancestor Warchief Melee Damage 2", "type": "base very high"},
	"1 Anger has 15% reduced Mana Reservation": {"enchant": "Enchantment Anger Reservation 2", "type": "base very high"},
	"1 Animated Guardians deal 40% increased Damage": {"enchant": "Enchantment Animate Guardian Damage 2", "type": "base very high"},
	"1 Arc Chains an additional time": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "base extremely high"},
	"1 Arc deals 12% increased Damage for each time it has Chained": {"enchant": "Enchantment Arc Damage Per Chain 2", "type": "base very high"},
	"1 Arc has +30% chance to Shock": {"enchant": "Enchantment Arc Shock Chance 2", "type": "base very high"},
	"1 Armageddon Brand Damage Penetrates 12% of Branded Enemy's Fire Resistance": {"enchant": "Armageddon Brand Attached Target Fire Penetration 2", "type": "base very high"},
	"1 Armageddon Brand deals 40% increased Damage": {"enchant": "Enchantment Armageddon Brand Damage 2", "type": "base very high"},
	"1 Artillery Ballista Projectiles fall in two perpendicular lines instead": {"enchant": "Enchantment Artillery Ballista Cross Pattern 1", "type": "base very high"},
	"1 Ball Lightning fires an additional Projectile": {"enchant": "Enchantment Ball Lightning Additional Projectiles 1", "type": "base very high"},
	"1 Bane deals 40% increased Damage": {"enchant": "Enchantment Bane Damage 2", "type": "base very high"},
	"1 Bane has 24% increased Area of Effect": {"enchant": "Enchantment Bane Area Of Effect 2", "type": "base very high"},
	"1 Barrage fires an additional Projectile": {"enchant": "Enchantment Barrage Num Of Additional Projectiles 1", "type": "base extremely high"},
	"1 Berserk has 30% increased Buff Effect": {"enchant": "Enchantment Berserk Effect 2", "type": "base very high"},
	"1 Berserk has 40% reduced Rage loss per second": {"enchant": "Enchantment Berserk Rage Loss 2", "type": "base very high"},
	"1 Blade Vortex has +3% to Critical Strike Multiplier for each blade": {"enchant": "Enchantment Blade Vortex Crit Multi Per Blade 2", "type": "base very high"},
	"1 Bladefall has an additional Volley": {"enchant": "Enchantment Bladefall Additional Volley", "type": "base very high"},
	"1 Bladestorm deals 40% increased Damage": {"enchant": "Enchantment Bladestorm Damage 2", "type": "base very high"},
	"1 Blast Rain deals 40% increased Damage": {"enchant": "Enchantment Blast Rain Damage 2", "type": "base very high"},
	"1 Blast Rain fires an additional Arrow": {"enchant": "Enchantment Blast Rain Additional Blast 2", "type": "base very high"},
	"1 Blast Rain has a 50% chance to fire an additional Arrow": {"enchant": "Enchantment Blast Rain Additional Blast 1", "type": "base very high"},
	"1 Blight has 30% increased Hinder Duration": {"enchant": "Enchantment Blight Secondary Skill Duration 2", "type": "base very high"},
	"1 Blood Rage grants additional 12% increased Attack Speed": {"enchant": "Enchantment Blood Rage Attack Speed 2", "type": "base very high"},
	"1 Blood and Sand has 40% increased Buff Effect": {"enchant": "Enchantment Blood and Sand Buff Effect 2", "type": "base very high"},
	"1 Bone Offering grants an additional +9% Chance to Block Attack Damage": {"enchant": "Enchantment Bone Offering Block Chance 2", "type": "base very high"},
	"1 Burning Arrow has 24% increased Debuff Effect": {"enchant": "Enchantment Burning Arrow Debuff Effect 2", "type": "base very high"},
	"1 Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration": {"enchant": "Enchantment Caustic Arrow Wither On Hit 2", "type": "base very high"},
	"1 Chain Hook has +1 Radius per 12 Rage": {"enchant": "Enchantment Chain Hook Cone Radius Per 12 Rage 1", "type": "base very high"},
	"1 Chain Hook has a 40% chance to grant +1 Rage if it Hits Enemies": {"enchant": "Enchantment Chain Hook Gain Rage On Hit Chance 2", "type": "base very high"},
	"1 Charged Dash has +6 to Radius of each Wave's last damage Area": {"enchant": "Enchantment Charged Dash Radius Final Explosion 2", "type": "base very high"},
	"1 Charged Dash has 15% more Movement Speed": {"enchant": "Enchantment Charged Dash Movement Speed 2", "type": "base very high"},
	"1 Chills from Ice Nova Hits always reduce Action Speed by at least 8%": {"enchant": "Enchantment Ice Nova Minimum Chill 2", "type": "base very high"},
	"1 Cobra Lash Chains 2 additional times": {"enchant": "Enchantment Cobra Lash Number Of Additional Chains 1", "type": "base very high"},
	"1 Cobra Lash Chains 3 additional times": {"enchant": "Enchantment Cobra Lash Number Of Additional Chains 2", "type": "base very high"},
	"1 Consecrated Ground from Purifying Flame applies 6% increased Damage taken to Enemies": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 1", "type": "base very high"},
	"1 Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "base very high"},
	"1 Consecrated Path deals 40% increased Damage": {"enchant": "Enchantment Consecrated Path Damage 2", "type": "base very high"},
	"1 Consecrated Path has 24% increased Area of Effect": {"enchant": "Enchantment Consecrated Path Area Of Effect 2", "type": "base very high"},
	"1 Converted Enemies have 40% increased Damage": {"enchant": "Enchantment Conversion Trap Damage 2", "type": "base very high"},
	"1 Cremation can have up to 1 additional Geyser at a time": {"enchant": "Enchantment Cremation Maximum Geysers 1", "type": "base very high"},
	"1 Dash has +2 Cooldowns": {"enchant": "Enchantment Dash Cooldown Count 2", "type": "base very high"},
	"1 Dash travels 100% increased distance": {"enchant": "Enchantment Dash Travel Distance 2", "type": "base very high"},
	"1 Desecrate Spawns 3 additional corpses": {"enchant": "Enchantment Desecrate Additional Corpse 2", "type": "base very high"},
	"1 Determination has 15% reduced Mana Reservation": {"enchant": "Enchantment Determination Mana Reservation 2", "type": "base very high"},
	"1 Detonate Dead has a 45% chance to detonate an additional corpse": {"enchant": "Enchantment Detonate Dead Percent Chance To Detonate Additional Corpse 2", "type": "base very high"},
	"1 Discipline has 20% reduced Mana Reservation": {"enchant": "Enchantment Discipline Mana Reservation 2", "type": "base very high"},
	"1 Divine Ire Damages 2 additional nearby Enemies when gaining Stages": {"enchant": "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2", "type": "base very high"},
	"1 Divine Ire deals 40% increased Damage": {"enchant": "Enchantment Divine Ire Damage 2", "type": "base very high"},
	"1 Divine Ire's beam has 15% increased width": {"enchant": "Enchantment Divine Ire Beam Width 2", "type": "base very high"},
	"1 Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 1", "type": "base very high"},
	"1 Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 2", "type": "base very high"},
	"1 Dread Banner has 40% increased Aura Effect": {"enchant": "Enchantment Dread Banner Effect 2", "type": "base very high"},
	"1 Elemental Hit deals 40% increased Damage": {"enchant": "Enchantment Elemental Hit Damage 2", "type": "base very high"},
	"1 Ensnaring Arrow has 30% increased Debuff Effect": {"enchant": "Enchantment Ensnaring Arrow Debuff Effect 2", "type": "base very high"},
	"1 Explosive Arrow deals 40% increased Damage": {"enchant": "Enchantment Explosive Arrow Damage 2", "type": "base very high"},
	"1 Explosive Arrow has 15% increased Attack Speed": {"enchant": "Enchantment Explosive Arrow Attack Speed 2", "type": "base very high"},
	"1 Explosive Arrow has 24% increased Area of Effect": {"enchant": "Enchantment Explosive Arrow Area Of Effect 2", "type": "base very high"},
	"1 Explosive Arrow has 40% increased Duration": {"enchant": "Enchantment Explosive Arrow Increased Duration 2", "type": "base very high"},
	"1 Explosive Trap causes 2 additional smaller explosions": {"enchant": "Enchantment Shrapnel Trap Secondary Explosions 2", "type": "base very high"},
	"1 Explosive Trap deals 40% increased Damage": {"enchant": "Enchantment Shrapnel Trap Damage 2", "type": "base very high"},
	"1 Fireball has +30% chance to Ignite": {"enchant": "Enchantment Fireball Ignite Chance 2", "type": "base very high"},
	"1 Flame Golems have 40% increased Damage": {"enchant": "Enchantment Summon Flame Golem Damage 2", "type": "base very high"},
	"1 Flamethrower Trap has 12% increased Cast Speed": {"enchant": "Enchantment Flamethrower Trap Cast Speed 2", "type": "base very high"},
	"1 Flamethrower Trap has 2 additional Flames": {"enchant": "Enchantment Flamethrower Additional Flamethrowers 2", "type": "base very high"},
	"1 Flamethrower Trap has 30% increased Skill Effect Duration": {"enchant": "Enchantment Flamethrower Trap Duration 2", "type": "base very high"},
	"1 Flesh Offering grants an additional 21% increased Attack Speed": {"enchant": "Enchantment Flesh Offering Attack Speed 2", "type": "base very high"},
	"1 Frostblink has 100% increased maximum travel distance": {"enchant": "Enchantment Frostblink Travel Distance 2", "type": "base very high"},
	"1 Frostblink has 30% increased Cooldown Recovery Speed": {"enchant": "Enchantment Frostblink Cooldown Speed 2", "type": "base very high"},
	"1 Grace has 15% reduced Mana Reservation": {"enchant": "Enchantment Grace Mana Reservation 2", "type": "base very high"},
	"1 Haste has 15% reduced Mana Reservation": {"enchant": "Enchantment Haste Mana Reservation 2", "type": "base very high"},
	"1 Hatred has 15% reduced Mana Reservation": {"enchant": "Enchantment Hatred Mana Reservation 2", "type": "base very high"},
	"1 Heavy Strike has a 12% chance to deal Double Damage": {"enchant": "Enchantment Heavy Strike Double Damage 2", "type": "base very high"},
	"1 Herald of Agony has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Agony Mana Reservation 2", "type": "base very high"},
	"1 Herald of Ash has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Ash Mana Reservation 2", "type": "base very high"},
	"1 Herald of Ice has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Ice Mana Reservation 2", "type": "base very high"},
	"1 Herald of Purity has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Purity Mana Reservation 2", "type": "base very high"},
	"1 Herald of Thunder has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Thunder Mana Reservation 2", "type": "base very high"},
	"1 Holy Flame Totem deals 40% increased Damage": {"enchant": "Enchantment Flame Totem Damage 2", "type": "base very high"},
	"1 Holy Flame Totem fires 2 additional Projectiles": {"enchant": "Enchantment Flame Totem Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Holy Flame Totem has 30% increased Projectile Speed": {"enchant": "Enchantment Flame Totem Projectile Speed 2", "type": "base very high"},
	"1 Ice Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Ice Golem Damage 2", "type": "base very high"},
	"1 Ice Nova has +30% chance to Freeze": {"enchant": "Enchantment Ice Nova Freeze Chance 2", "type": "base very high"},
	"1 Ice Shot has 60% increased Area of Effect angle": {"enchant": "Enchantment Ice Shot Cone Angle 2", "type": "base very high"},
	"1 Ice Spear fires an additional Projectile": {"enchant": "Enchantment Ice Spear Additional Projectile 1", "type": "base very high"},
	"1 Ice Spear travels 30% reduced distance before changing forms": {"enchant": "Enchantment Ice Spear Distance Before Form Change 2", "type": "base very high"},
	"1 Icicle Mine deals 40% increased Damage": {"enchant": "Enchantment Icicle Mine Damage 2", "type": "base very high"},
	"1 Icicle Mine has +30% to Critical Strike Multiplier": {"enchant": "Enchantment Icicle Mine Critical Multiplier 2", "type": "base very high"},
	"1 Icicle Mine has 12% increased Throwing Speed": {"enchant": "Enchantment Icicle Mine Throwing Speed 2", "type": "base very high"},
	"1 Icicle Mine has 15% increased Throwing Speed": {"enchant": "Enchantment Icicle MineThrowing Speed 2", "type": "base very high"},
	"1 Immortal Call has 30% increased Buff Duration per Endurance Charge removed": {"enchant": "Enchantment Immortal Call Percent Chance To Not Consume Endurance Charges 2", "type": "base very high"},
	"1 Incinerate has +2 to maximum stages": {"enchant": "Enchantment Incinerate Maximum Stages 2", "type": "base very high"},
	"1 Incinerate has 16% increased Area of Effect": {"enchant": "Enchantment Incinerate Area Of Effect 1", "type": "base very high"},
	"1 Infernal Blow Debuff deals an additional 5% of Damage per Charge": {"enchant": "Enchantment Infernal Blow Increased Damage Per Stack 2", "type": "base very high"},
	"1 Kinetic Blast has a 75% chance for an additional explosion": {"enchant": "Enchantment Kinetic Blast Explosions 2", "type": "base very high"},
	"1 Lacerate deals 14 to 25 added Physical Damage against Bleeding Enemies": {"enchant": "Enchantment Double Slash Added Phys To Bleeding 2", "type": "base very high"},
	"1 Lancing Steel deals 40% increased Damage": {"enchant": "Enchantment Lancing Steel Damage 2", "type": "base very high"},
	"1 Lancing Steel's primary Projectile Pierces 5 additional Targets": {"enchant": "Enchantment Lancing Steel Primary Proj Pierce Num 2", "type": "base very high"},
	"1 Lightning Arrow hits 2 additional Enemies": {"enchant": "Enchantment Lightning Arrow Extra Targets 2", "type": "base very high"},
	"1 Lightning Spire Trap deals 40% increased Damage": {"enchant": "Enchantment Lightning Tower Trap Damage 2", "type": "base very high"},
	"1 Lightning Spire Trap has 15% increased Cooldown Recovery Speed": {"enchant": "Enchantment Lightning Tower Trap Cooldown Speed 2", "type": "base very high"},
	"1 Lightning Strike fires 3 additional Projectiles": {"enchant": "Enchantment Lightning Strike Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Lightning Strike pierces 3 additional Targets": {"enchant": "Enchantment Lightning Strike Additional Pierce 2", "type": "base very high"},
	"1 Lightning Trap Damage Penetrates 10% Lightning Resistance": {"enchant": "Enchantment Lightning Trap Penetration 2", "type": "base very high"},
	"1 Lightning Trap pierces 3 additional Targets": {"enchant": "Enchantment Lightning Trap Additional Pierce 2", "type": "base very high"},
	"1 Magma Orb Chains an additional 2 times": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2", "type": "base extremely high"},
	"1 Malevolence has 15% reduced Mana Reservation": {"enchant": "Enchantment Malevolence Mana Reservation 2", "type": "base very high"},
	"1 Molten Strike fires 2 additional Projectiles": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 2", "type": "base extremely high"},
	"1 Molten Strike fires an additional Projectile": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 1", "type": "base very high"},
	"1 Perforate creates +2 Spikes": {"enchant": "Enchantment Perforate Number Of Spikes 2", "type": "base very high"},
	"1 Perforate deals 40% increased Damage": {"enchant": "Enchantment Perforate Damage 2", "type": "base very high"},
	"1 Perforate has 24% increased Area of Effect": {"enchant": "Enchantment Perforate Area Of Effect 2", "type": "base very high"},
	"1 Pestilent Strike has 40% increased Duration": {"enchant": "Enchantment Pestilent Strike Duration 2", "type": "base very high"},
	"1 Plague Bearer deals Damage based on an additional 5% of Plague Value": {"enchant": "Enchantment Plague Bearer Stored Poison Damage To Deal Per Second 2", "type": "base very high"},
	"1 Power Siphon fires 2 additional Projectiles": {"enchant": "Enchantment Power Siphon Additional Projectiles 2", "type": "base extremely high"},
	"1 Pride has 15% reduced Mana Reservation": {"enchant": "Enchantment Pride Mana Reservation 2", "type": "base very high"},
	"1 Purifying Flame deals 25% increased Damage": {"enchant": "Enchantment Purifying Flame Damage 1", "type": "base very high"},
	"1 Purifying Flame deals 40% increased Damage": {"enchant": "Enchantment Purifying Flame Damage 2", "type": "base very high"},
	"1 Purifying Flame has 30% increased Area of Effect if targeting Consecrated Ground": {"enchant": "Enchantment Purifying Flame Area Of Effect When Targeting Consecrated Ground 2", "type": "base very high"},
	"1 Purity of Lightning has 20% reduced Mana Reservation": {"enchant": "Enchantment Purity Of Lightning Mana Reservation 2", "type": "base very high"},
	"1 Pyroclast Mine fires 2 additional Projectiles": {"enchant": "Enchantment Pyroclast Mine Additional Projectiles 2", "type": "base extremely high"},
	"1 Pyroclast Mine fires an additional Projectile": {"enchant": "Enchantment Pyroclast Mine Additional Projectiles 1", "type": "base very high"},
	"1 Pyroclast Mine has 15% increased Throwing Speed": {"enchant": "Enchantment Pyroclast Mine Throwing Speed 2", "type": "base very high"},
	"1 Rain of Arrows has 15% chance to fire an additional sequence of arrows": {"enchant": "Enchantment Rain Of Arrows Repeat Count 2", "type": "base very high"},
	"1 Raised Zombies deal 40% increased Damage": {"enchant": "Enchantment Raise Zombie Damage 2", "type": "base very high"},
	"1 Righteous Fire grants 30% increased Spell Damage": {"enchant": "Enchantment Righteous Fire Spell Damage 2", "type": "base very high"},
	"1 Sand Bladestorms move with 50% increased speed": {"enchant": "Enchantment Bladestorm Sandstorm Speed 1", "type": "base very high"},
	"1 Sand Bladestorms move with 75% increased speed": {"enchant": "Enchantment Bladestorm Sandstorm Speed 2", "type": "base very high"},
	"1 Scourge Arrow creates an additional spore pod at Maximum Stages": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "base extremely high"},
	"1 Scourge Arrow deals 40% increased Damage": {"enchant": "Enchantment Scourge Arrow Damage 2", "type": "base very high"},
	"1 Seismic Trap deals 40% increased Damage": {"enchant": "Enchantment Physical Cascade Trap Damage 2", "type": "base very high"},
	"1 Seismic Trap has 30% increased Skill Effect Duration": {"enchant": "Enchantment Physical Cascade Trap Duration 2", "type": "base very high"},
	"1 Seismic Trap releases an additional Wave": {"enchant": "Enchantment Physical Cascade Additional Cascades 1", "type": "base very high"},
	"1 Shattering Steel fires an additional Projectile": {"enchant": "Enchantment Shattering Steel Additional Projectile 1", "type": "base very high"},
	"1 Shattering Steel grants Fortify on Hitting an Enemy at Close Range": {"enchant": "Enchantment Shattering Steel Fortify On Hit Close Range 1", "type": "base very high"},
	"1 Shrapnel Ballista fires an additional Arrow": {"enchant": "Enchantment Shrapnel Ballista Additional Arrows 1", "type": "base very high"},
	"1 Siege Ballista has 45% increased Totem Placement Speed": {"enchant": "Enchantment Siege Ballista Totem Placement Speed 2", "type": "base very high"},
	"1 Siphoning Trap deals 40% increased Damage": {"enchant": "Enchantment Ice Siphon Trap Damage 2", "type": "base very high"},
	"1 Siphoning Trap has 45% increased Skill Effect Duration": {"enchant": "Enchantment Ice Siphon Trap Duration 2", "type": "base very high"},
	"1 Skeletons deal 40% increased Damage": {"enchant": "Enchantment Summon Skeletons Damage 2", "type": "base very high"},
	"1 Smite has 30% increased Aura Effect": {"enchant": "Enchantment Smite Aura Effect 2", "type": "base very high"},
	"1 Smoke Mine grants additional 30% increased Movement Speed": {"enchant": "Enchantment Smoke Mine Movement Speed 2", "type": "base very high"},
	"1 Soulrend also Hinders Enemies, with 40% reduced Movement Speed": {"enchant": "Enchantment Soulrend Applies Hinder Movement Speed 2", "type": "base very high"},
	"1 Soulrend deals 40% increased Damage": {"enchant": "Enchantment Soulrend Damage 2", "type": "base very high"},
	"1 Soulrend fires an additional Projectile": {"enchant": "Enchantment Soulrend Number Of Additional Projectiles 1", "type": "base very high"},
	"1 Spark fires 3 additional Projectiles": {"enchant": "Enchantment Spark Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Spectral Shield Throw fires 5 additional Shard Projectiles": {"enchant": "Enchantment Spectral Shield Throw Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Spectres have 12% increased Attack and Cast Speed": {"enchant": "Enchantment Spectre Attack And Cast Speed 2", "type": "base very high"},
	"1 Spectres have 40% increased Damage": {"enchant": "Enchantment Raise Spectre Damage 2", "type": "base very high"},
	"1 Spirit Offering grants +12% of Physical Damage as Extra Chaos Damage": {"enchant": "Enchantment Spirit Offering Physical Added As Chaos 2", "type": "base very high"},
	"1 Split Arrow fires 3 additional Projectiles": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Static Strike has +2 maximum Beam Targets": {"enchant": "Enchantment Static Strike Maximum Beam Targets 2", "type": "base very high"},
	"1 Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "base very high"},
	"1 Storm Brand deals 25% increased Damage": {"enchant": "Enchantment Storm Brand Damage 1", "type": "base very high"},
	"1 Storm Brand deals 40% increased Damage": {"enchant": "Enchantment Storm Brand Damage 2", "type": "base very high"},
	"1 Storm Brand has a 18% chance to Chain an additional time": {"enchant": "Storm Brand Additional Chain Chance 2", "type": "base very high"},
	"1 Storm Burst has a 10% chance to create an additional Orb": {"enchant": "Enchantment Storm Burst Additional Object Chance 1", "type": "base very high"},
	"1 Storm Burst has a 15% chance to create an additional Orb": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "base very high"},
	"1 Stormblast Mine deals 40% increased Damage": {"enchant": "Enchantment Stormblast Mine Damage 2", "type": "base very high"},
	"1 Summon Raging Spirit has 18% chance to summon an extra Minion": {"enchant": "Enchantment Summoned Raging Spirit Additional 2", "type": "base very high"},
	"1 Summon Raging Spirit has 30% increased Duration": {"enchant": "Enchantment Summoned Raging Spirit Duration 2", "type": "base very high"},
	"1 Summon Skitterbots has 20% reduced Mana Reservation": {"enchant": "Enchantment Summon Skitterbots Mana Reservation 2", "type": "base very high"},
	"1 Summoned Agony Crawler fires 2 additional Projectiles": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "base very high"},
	"1 Summoned Carrion Golems deal 25% increased Damage": {"enchant": "Enchantment Summon Carrion Golem Damage 1", "type": "base very high"},
	"1 Summoned Carrion Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Carrion Golem Damage 2", "type": "base very high"},
	"1 Summoned Holy Relics deal 40% increased Damage": {"enchant": "Enchantment Holy Relic Damage 2", "type": "base very high"},
	"1 Summoned Raging Spirits deal 40% increased Damage": {"enchant": "Enchantment Summon Raging Spirit Damage 2", "type": "base very high"},
	"1 Tectonic Slam has 12% chance to create a Charged Slam": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 1", "type": "base very high"},
	"1 Tectonic Slam has 20% chance to create a Charged Slam": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 2", "type": "base extremely high"},
	"1 0 Tornado Shot fires an additional secondary Projectile": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 1", "type": "base very high"},
	"1 1 Tornado Shot fires an additional secondary Projectile": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 2", "type": "base very high"},
	"1 Toxic Rain deals 40% increased Damage": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "base very high"},
	"1 Toxic Rain fires 1 additional Arrow": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "base extremely high"},
	"1 Toxic Rain gains 10% of Physical Damage as Extra Chaos Damage": {"enchant": "Enchantment Toxic Rain Physical Added As Chaos 2", "type": "base very high"},
	"1 Unearth Spawns corpses with +5 Level": {"enchant": "Enchantment Unearth Corpse Level 2", "type": "base very high"},
	"1 Venom Gyre deals 40% increased Damage": {"enchant": "Enchantment Venom Gyre Damage 2", "type": "base very high"},
	"1 Venom Gyre has a 35% chance to keep caught Projectiles fired by using Whirling Blades": {"enchant": "Enchantment Venom Gyre Chance To Retain Projectile On Release 2", "type": "base very high"},
	"1 Vitality has 20% reduced Mana Reservation": {"enchant": "Enchantment Vitality Mana Reservation 2", "type": "base very high"},
	"1 0 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 1", "type": "base extremely high"},
	"1 1 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 2", "type": "base extremely high"},
	"1 2 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 3", "type": "base extremely high"},
	"1 Vortex has 30% increased Cooldown Recovery Speed": {"enchant": "Enchantment Vortex Cooldown Recovery 2", "type": "base very high"},
	"1 Vortex has 45% increased Area of Effect when Cast on Frostbolt": {"enchant": "Enchantment Vortex AoE On Frostbolt 2", "type": "base very high"},
	"1 Wave of Conviction's Exposure applies -4% Elemental Resistance": {"enchant": "Enchantment Wave Of Conviction Additional Enemy Resistance 1", "type": "base very high"},
	"1 Wave of Conviction's Exposure applies -6% Elemental Resistance": {"enchant": "Enchantment Wave Of Conviction Additional Enemy Resistance 2", "type": "base very high"},
	"1 Wild Strike's Beam Chains an additional 6 times": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "base extremely high"},
	"1 Winter Orb deals 40% increased Damage": {"enchant": "Enchantment Winter Orb Damage 2", "type": "base very high"},
	"1 Winter Orb has +2 Maximum Stages": {"enchant": "Enchantment Frost Fury Additional Max Number Of Stages 1", "type": "base extremely high"},
	"1 Winter Orb has 3% increased Area of Effect per Stage": {"enchant": "Enchantment Frost Fury Area Of Effect Per Stage 2", "type": "base very high"},
	"1 Wither has 16% increased Area of Effect": {"enchant": "Enchantment Wither Area Of Effect 1", "type": "base very high"},
	"1 Wither has 24% increased Area of Effect": {"enchant": "Enchantment Wither Area Of Effect 2", "type": "base very high"},
	"1 Withering Step has 30% increased Elusive Effect": {"enchant": "Enchantment Withering Step Elusive Effect 2", "type": "base very high"},
	"1 Wrath has 15% reduced Mana Reservation": {"enchant": "Enchantment Wrath Mana Reservation 2", "type": "base very high"},
	"1 Zealotry has 15% reduced Mana Reservation": {"enchant": "Enchantment Zealotry Mana Reservation 2", "type": "base very high"},
	"7 enchant default": {"class": "Helmet", "other": ["AnyEnchantment True"], "type": "item mod"}
}
