#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:17:17 UTC from "Standard" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 Enchantment Flame Surge Vs Burning Enemies 1": {"enchant": "Enchantment Flame Surge Vs Burning Enemies 1", "type": "ignore"},
	"1 Enchantment Herald Of Purity Additional Minion 1": {"enchant": "Enchantment Herald Of Purity Additional Minion 1", "type": "currency very high"},
	"1 Enchantment Sweep Knockback Chance 2": {"enchant": "Enchantment Sweep Knockback Chance 2", "type": "currency very high"},
	"1 Enchantment Animate Guardian Elemental Resistances 2": {"enchant": "Enchantment Animate Guardian Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Ice Golem Elemental Resistances 2": {"enchant": "Enchantment Ice Golem Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Lightning Golem Elemental Resistances 2": {"enchant": "Enchantment Lightning Golem Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Spectre Elemental Resistances 2": {"enchant": "Enchantment Spectre Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Zombie Elemental Resistances 2": {"enchant": "Enchantment Zombie Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Flame Golem Elemental Resistances 2": {"enchant": "Enchantment Flame Golem Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Barrage Attack Speed 1": {"enchant": "Enchantment Barrage Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Cyclone Attack Speed 1": {"enchant": "Enchantment Cyclone Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Dual Strike Attack Speed 1": {"enchant": "Enchantment Dual Strike Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Elemental Hit Attack Speed 1": {"enchant": "Enchantment Elemental Hit Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Incinerate Damage Per Stage 3": {"enchant": "Enchantment Incinerate Damage Per Stage 3", "type": "currency extremely high"},
	"1 Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2": {"enchant": "Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2", "type": "currency very high"},
	"1 Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 1": {"enchant": "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 1", "type": "currency very high"},
	"1 Enchantment Lightning Golem Granted Buff Effect 1": {"enchant": "Enchantment Lightning Golem Granted Buff Effect 1", "type": "currency very high"},
	"1 Enchantment Stone Golem Granted Buff Effect 1": {"enchant": "Enchantment Stone Golem Granted Buff Effect 1", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Area Of Effect 2": {"enchant": "Enchantment Ancestor Warchief Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Arctic Breath Area Of Effect 2": {"enchant": "Enchantment Arctic Breath Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ball Lightning Area Of Effect 2": {"enchant": "Enchantment Ball Lightning Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blade Flurry Area Of Effect 2": {"enchant": "Enchantment Blade Flurry Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Area Of Effect 2": {"enchant": "Enchantment Blade Vortex Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blast Rain Area Of Effect 2": {"enchant": "Enchantment Blast Rain Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blight Area Of Effect 2": {"enchant": "Enchantment Blight Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Body Swap Cast Speed 2": {"enchant": "Enchantment Body Swap Cast Speed 2", "type": "currency extremely high"},
	"1 Enchantment Caustic Arrow Area Of Effect 2": {"enchant": "Enchantment Caustic Arrow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Cleave Area Of Effect 2": {"enchant": "Enchantment Cleave Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Cold Snap Area Of Effect 2": {"enchant": "Enchantment Cold Snap Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Contagion Radius 2": {"enchant": "Enchantment Contagion Radius 2", "type": "currency very high"},
	"1 Enchantment Cremation Cast Speed 2": {"enchant": "Enchantment Cremation Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Dark Pact Area Of Effect 2": {"enchant": "Enchantment Dark Pact Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Dack Pact Cast Speed 2": {"enchant": "Enchantment Dack Pact Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Detonate Dead Area Of Effect 2": {"enchant": "Enchantment Detonate Dead Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Earthquake Area Of Effect 2": {"enchant": "Enchantment Earthquake Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Explosive Arrow Area Of Effect 2": {"enchant": "Enchantment Explosive Arrow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Fireball Cast Speed 2": {"enchant": "Enchantment Fireball Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Firestorm Explosion Area Of Effect 2": {"enchant": "Enchantment Firestorm Explosion Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Flameblast Area Of Effect 2": {"enchant": "Enchantment Flameblast Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Freeze Mine Area Of Effect 2": {"enchant": "Enchantment Freeze Mine Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Cast Speed 2": {"enchant": "Enchantment Freezing Pulse Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Bomb Area Of Effect 2": {"enchant": "Enchantment Frost Bomb Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Area Of Effect 2": {"enchant": "Enchantment Glacial Cascade Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ground Slam Area Of Effect 2": {"enchant": "Enchantment Ground Slam Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ice Crash Area Of Effect 2": {"enchant": "Enchantment Ice Crash Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Area Of Effect 2": {"enchant": "Enchantment Ice Nova Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ice Shot Area Of Effect 2": {"enchant": "Enchantment Ice Shot Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Ice Trap Area Of Effect 2": {"enchant": "Enchantment Ice Trap Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Infernal Blow Area Of Effect 2": {"enchant": "Enchantment Infernal Blow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Area Of Effect 2": {"enchant": "Enchantment Kinetic Blast Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Double Slash Area Of Effect 2": {"enchant": "Enchantment Double Slash Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Leap Slam Area Of Effect 2": {"enchant": "Enchantment Leap Slam Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Area Of Effect 2": {"enchant": "Enchantment Lightning Arrow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Lightning Tendrils Area Of Effect 2": {"enchant": "Enchantment Lightning Tendrils Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Magma Orb Area Of Effect 2": {"enchant": "Enchantment Magma Orb Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Area Of Effect 2": {"enchant": "Enchantment Molten Strike Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Area Of Effect 2": {"enchant": "Enchantment Rain Of Arrows Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Reave Area Of Effect 2": {"enchant": "Enchantment Reave Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Righteous Fire Area Of Effect 2": {"enchant": "Enchantment Righteous Fire Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Fire Beam Cast Speed 2": {"enchant": "Enchantment Fire Beam Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Shock Nova Area Of Effect 2": {"enchant": "Enchantment Shock Nova Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Shockwave Totem Radius 2": {"enchant": "Enchantment Shockwave Totem Radius 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Shot Radius 2": {"enchant": "Enchantment Shrapnel Shot Radius 2", "type": "currency very high"},
	"1 Enchantment Static Strike Area Of Effect 2": {"enchant": "Enchantment Static Strike Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Storm Burst Area Of Effect 2": {"enchant": "Enchantment Storm Burst Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Storm Call Area Of Effect 2": {"enchant": "Enchantment Storm Call Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Sunder Radius 2": {"enchant": "Enchantment Sunder Radius 2", "type": "currency very high"},
	"1 Enchantment Sweep Area Of Effect 2": {"enchant": "Enchantment Sweep Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Area Of Effect 2": {"enchant": "Enchantment Tectonic Slam Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Unearth Cast Speed 2": {"enchant": "Enchantment Unearth Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Volatile Dead Cast Speed 2": {"enchant": "Enchantment Volatile Dead Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 2": {"enchant": "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 2", "type": "currency very high"},
	"1 Enchantment Barrage Attack Speed 2": {"enchant": "Enchantment Barrage Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Bear Trap Cooldown Speed 2": {"enchant": "Enchantment Bear Trap Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Cleave Attack Speed 2": {"enchant": "Enchantment Cleave Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Cyclone Attack Speed 2": {"enchant": "Enchantment Cyclone Attack Speed 2", "type": "currency extremely high"},
	"1 Enchantment Double Strike Attack Speed 2": {"enchant": "Enchantment Double Strike Attack Speed 2", "type": "currency extremely high"},
	"1 Enchantment Dual Strike Attack Speed 2": {"enchant": "Enchantment Dual Strike Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Attack Speed 2": {"enchant": "Enchantment Elemental Hit Attack Speed 2", "type": "currency extremely high"},
	"1 Enchantment Explosive Arrow Attack Speed 2": {"enchant": "Enchantment Explosive Arrow Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Bolt Cast Speed 2": {"enchant": "Enchantment Frost Bolt Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Heavy Strike Attack Speed 2": {"enchant": "Enchantment Heavy Strike Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Leap Slam Attack Speed 2": {"enchant": "Enchantment Leap Slam Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Attack Speed 2": {"enchant": "Enchantment Power Siphon Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Attack Speed 2": {"enchant": "Enchantment Rain Of Arrows Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Fire Beam Length 2": {"enchant": "Enchantment Fire Beam Length 2", "type": "currency very high"},
	"1 Enchantment Shield Charge Attack Speed 2": {"enchant": "Enchantment Shield Charge Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Shockwave Totem Cast Speed 2": {"enchant": "Enchantment Shockwave Totem Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Siege Ballista Attack Speed 2": {"enchant": "Enchantment Siege Ballista Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Sunder Attack Speed 2": {"enchant": "Enchantment Sunder Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Whirling Blades Attack Speed 2": {"enchant": "Enchantment Whirling Blades Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Burning Arrow Physical Damage Percent To Add As Fire Damage 2": {"enchant": "Enchantment Burning Arrow Physical Damage Percent To Add As Fire Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Hammer Physical Damage Percent To Add As Cold Damage 2": {"enchant": "Enchantment Glacial Hammer Physical Damage Percent To Add As Cold Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Crash Physical Damage Percent To Add As Cold Damage 2": {"enchant": "Enchantment Ice Crash Physical Damage Percent To Add As Cold Damage 2", "type": "currency very high"},
	"1 Enchantment Infernal Blow Physical Damage Percent To Add As Fire Damage 2": {"enchant": "Enchantment Infernal Blow Physical Damage Percent To Add As Fire Damage 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2": {"enchant": "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Golem Granted Buff Effect 2": {"enchant": "Enchantment Flame Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2": {"enchant": "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2", "type": "currency very high"},
	"1 Enchantment Lightning Golem Granted Buff Effect 2": {"enchant": "Enchantment Lightning Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Stone Golem Granted Buff Effect 2": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Molten Shell Armour 2": {"enchant": "Enchantment Molten Shell Armour 2", "type": "currency very high"},
	"1 Enchantment Discharge Consume Charges 1": {"enchant": "Enchantment Discharge Consume Charges 1", "type": "currency very high"},
	"1 Enchantment Phase Run Percent Chance To Not Consume Frenzy Charges 1": {"enchant": "Enchantment Phase Run Percent Chance To Not Consume Frenzy Charges 1", "type": "currency very high"},
	"1 Enchantment Blade Vortex Duration 1": {"enchant": "Enchantment Blade Vortex Duration 1", "type": "currency very high"},
	"1 Enchantment Frost Blades Projectile Speed 1": {"enchant": "Enchantment Frost Blades Projectile Speed 1", "type": "currency very high"},
	"1 Enchantment Warlords Mark Curse Effect 1": {"enchant": "Enchantment Warlords Mark Curse Effect 1", "type": "currency very high"},
	"1 Enchantment Earthquake Duration 1": {"enchant": "Enchantment Earthquake Duration 1", "type": "currency very high"},
	"1 Enchantment Lightning Warp Duration 1": {"enchant": "Enchantment Lightning Warp Duration 1", "type": "currency very high"},
	"1 Enchantment Animate Weapon Chance To Create Additional Copy 2": {"enchant": "Enchantment Animate Weapon Chance To Create Additional Copy 2", "type": "currency extremely high"},
	"1 Enchantment Incinerate Damage Per Stage 2": {"enchant": "Enchantment Incinerate Damage Per Stage 2", "type": "currency very high"},
	"1 Enchantment Wild Strike Area Of Effect 1": {"enchant": "Enchantment Wild Strike Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Ancestral Warchief Damage 1": {"enchant": "Enchantment Ancestral Warchief Damage 1", "type": "currency very high"},
	"1 Enchantment Arc Damage 1": {"enchant": "Enchantment Arc Damage 1", "type": "currency very high"},
	"1 Enchantment Barrage Damage 1": {"enchant": "Enchantment Barrage Damage 1", "type": "currency very high"},
	"1 Enchantment Blade Flurry Damage 1": {"enchant": "Enchantment Blade Flurry Damage 1", "type": "currency very high"},
	"1 Enchantment Blade Vortex Damage 1": {"enchant": "Enchantment Blade Vortex Damage 1", "type": "currency very high"},
	"1 Enchantment Blast Rain Damage 1": {"enchant": "Enchantment Blast Rain Damage 1", "type": "currency very high"},
	"1 Enchantment Dark Pact Damage 1": {"enchant": "Enchantment Dark Pact Damage 1", "type": "currency very high"},
	"1 Enchantment Double Strike Damage 1": {"enchant": "Enchantment Double Strike Damage 1", "type": "currency very high"},
	"1 Enchantment Earthquake Damage 1": {"enchant": "Enchantment Earthquake Damage 1", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Damage 1": {"enchant": "Enchantment Ethereal Knives Damage 1", "type": "currency very high"},
	"1 Enchantment Explosive Arrow Damage 1": {"enchant": "Enchantment Explosive Arrow Damage 1", "type": "currency very high"},
	"1 Enchantment Fire Nova Mine Damage 1": {"enchant": "Enchantment Fire Nova Mine Damage 1", "type": "currency very high"},
	"1 Enchantment Frost Blades Damage 1": {"enchant": "Enchantment Frost Blades Damage 1", "type": "currency very high"},
	"1 Enchantment Frost Bolt Damage 1": {"enchant": "Enchantment Frost Bolt Damage 1", "type": "currency very high"},
	"1 Enchantment Herald Of Ice Damage 1": {"enchant": "Enchantment Herald Of Ice Damage 1", "type": "currency very high"},
	"1 Enchantment Ice Shot Damage 1": {"enchant": "Enchantment Ice Shot Damage 1", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Damage 1": {"enchant": "Enchantment Kinetic Blast Damage 1", "type": "currency very high"},
	"1 Enchantment Lacerate Damage 1": {"enchant": "Enchantment Lacerate Damage 1", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Damage 1": {"enchant": "Enchantment Lightning Arrow Damage 1", "type": "currency very high"},
	"1 Enchantment Molten Strike Damage 1": {"enchant": "Enchantment Molten Strike Damage 1", "type": "currency very high"},
	"1 Enchantment Reave Damage 1": {"enchant": "Enchantment Reave Damage 1", "type": "currency very high"},
	"1 Enchantment Righteous Fire Damage 1": {"enchant": "Enchantment Righteous Fire Damage 1", "type": "currency very high"},
	"1 Enchantment Spectral Throw Damage 1": {"enchant": "Enchantment Spectral Throw Damage 1", "type": "currency very high"},
	"1 Enchantment Tornado Shot Damage 1": {"enchant": "Enchantment Tornado Shot Damage 1", "type": "currency very high"},
	"1 Enchantment Volatile Dead Damage 1": {"enchant": "Enchantment Volatile Dead Damage 1", "type": "currency very high"},
	"1 Enchantment Puncture Maim On Hit Percent Chance 2": {"enchant": "Enchantment Puncture Maim On Hit Percent Chance 2", "type": "currency very high"},
	"1 Enchantment Frenzy Percent Chance To Gain Additional Frenzy Charge 2": {"enchant": "Enchantment Frenzy Percent Chance To Gain Additional Frenzy Charge 2", "type": "currency very high"},
	"1 Enchantment Discharge Consume Charges 2": {"enchant": "Enchantment Discharge Consume Charges 2", "type": "currency extremely high"},
	"1 Enchantment Immortal Call Percent Chance To Not Consume Endurance Charges 2": {"enchant": "Enchantment Immortal Call Percent Chance To Not Consume Endurance Charges 2", "type": "currency very high"},
	"1 Enchantment Animate Weapon Duration 2": {"enchant": "Enchantment Animate Weapon Duration 2", "type": "currency very high"},
	"1 Enchantment Assassins Mark Curse Effect 2": {"enchant": "Enchantment Assassins Mark Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Duration 2": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "currency extremely high"},
	"1 Enchantment Blink Arrow Cooldown Speed 2": {"enchant": "Enchantment Blink Arrow Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Bone Offering Duration 1": {"enchant": "Enchantment Bone Offering Duration 1", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Duration 2": {"enchant": "Enchantment Caustic Arrow Duration 2", "type": "currency very high"},
	"1 Enchantment Cold Snap Cooldown Speed 2": {"enchant": "Enchantment Cold Snap Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Conductivity Curse Effect 2": {"enchant": "Enchantment Conductivity Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Contagion Duration 2": {"enchant": "Enchantment Contagion Duration 2", "type": "currency very high"},
	"1 Enchantment Conversion Trap Cooldown Speed 2": {"enchant": "Enchantment Conversion Trap Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Convocation Cooldown Speed 2": {"enchant": "Enchantment Convocation Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Desecrate Cooldown Speed 2": {"enchant": "Enchantment Desecrate Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Despair Effect 2": {"enchant": "Enchantment Despair Effect 2", "type": "currency very high"},
	"1 Enchantment Elemental Weakness Curse Effect 2": {"enchant": "Enchantment Elemental Weakness Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Elemental Weakness Duration 1": {"enchant": "Enchantment Elemental Weakness Duration 1", "type": "currency very high"},
	"1 Enchantment Enduring Cry Cooldown Speed 2": {"enchant": "Enchantment Enduring Cry Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Enfeeble Curse Effect 2": {"enchant": "Enchantment Enfeeble Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Essence Drain Duration 2": {"enchant": "Enchantment Essence Drain Duration 2", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Projectile Speed 2": {"enchant": "Enchantment Ethereal Knives Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Fire Nova Mine Cast Speed 2": {"enchant": "Enchantment Fire Nova Mine Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Firestorm Duration 2": {"enchant": "Enchantment Firestorm Duration 2", "type": "currency very high"},
	"1 Enchantment Flame Dash Cooldown Speed 2": {"enchant": "Enchantment Flame Dash Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Flammability Curse Effect 2": {"enchant": "Enchantment Flammability Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Cooldown Speed 2": {"enchant": "Enchantment Flicker Strike Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Projectile Speed 2": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Blades Projectile Speed 2": {"enchant": "Enchantment Frost Blades Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Bomb Cooldown Speed 2": {"enchant": "Enchantment Frost Bomb Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Wall Cooldown Speed 2": {"enchant": "Enchantment Frost Wall Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Frostbite Curse Effect 2": {"enchant": "Enchantment Frostbite Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Incinerate Projectile Speed 2": {"enchant": "Enchantment Incinerate Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Mirror Arrow Cooldown Speed 2": {"enchant": "Enchantment Mirror Arrow Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Poachers Mark Curse Effect 2": {"enchant": "Enchantment Poachers Mark Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Projectile Weakness Curse Effect 2": {"enchant": "Enchantment Projectile Weakness Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Punishment Curse Effect 2": {"enchant": "Enchantment Punishment Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Reckoning Cooldown Speed 2": {"enchant": "Enchantment Reckoning Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Dominating Blow Duration 2": {"enchant": "Enchantment Dominating Blow Duration 2", "type": "currency very high"},
	"1 Enchantment Smoke Mine Duration 2": {"enchant": "Enchantment Smoke Mine Duration 2", "type": "currency very high"},
	"1 Enchantment Spark Projectile Speed 2": {"enchant": "Enchantment Spark Projectile Speed 2", "type": "currency extremely high"},
	"1 Enchantment Spectral Shield Throw Projectile Speed 2": {"enchant": "Enchantment Spectral Shield Throw Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Spectral Throw Projectile Speed 2": {"enchant": "Enchantment Spectral Throw Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Summoned Raging Spirit Duration 2": {"enchant": "Enchantment Summoned Raging Spirit Duration 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Curse Effect 2": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "currency extremely high"},
	"1 Enchantment Temporal Chains Duration 1": {"enchant": "Enchantment Temporal Chains Duration 1", "type": "currency very high"},
	"1 Enchantment Vengeance Cooldown Speed 2": {"enchant": "Enchantment Vengeance Cooldown Speed 2", "type": "currency extremely high"},
	"1 Enchantment Viper Strike Poison Duration 2": {"enchant": "Enchantment Viper Strike Poison Duration 2", "type": "currency very high"},
	"1 Enchantment Vortex Duration 2": {"enchant": "Enchantment Vortex Duration 2", "type": "currency very high"},
	"1 Enchantment Vulnerability Curse Effect 2": {"enchant": "Enchantment Vulnerability Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Warlords Mark Curse Effect 2": {"enchant": "Enchantment Warlords Mark Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 1": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 1", "type": "currency very high"},
	"1 Enchantment Earthquake Duration 2": {"enchant": "Enchantment Earthquake Duration 2", "type": "currency extremely high"},
	"1 Enchantment Lightning Warp Duration 2": {"enchant": "Enchantment Lightning Warp Duration 2", "type": "currency extremely high"},
	"1 Enchantment Spectral Throw Projectile Deceleration 2": {"enchant": "Enchantment Spectral Throw Projectile Deceleration 2", "type": "currency very high"},
	"1 Enchantment Storm Call Duration 2": {"enchant": "Enchantment Storm Call Duration 2", "type": "currency extremely high"},
	"1 Enchantment Ice Spear Second Form Critical Strike Chance 2": {"enchant": "Enchantment Ice Spear Second Form Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Immortal Call Duration 1": {"enchant": "Enchantment Immortal Call Duration 1", "type": "currency very high"},
	"1 Enchantment Abyssal Cry Duration 2": {"enchant": "Enchantment Abyssal Cry Duration 2", "type": "currency very high"},
	"1 Enchantment Arctic Armour Buff Effect 2": {"enchant": "Enchantment Arctic Armour Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Arctic Breath Duration 2": {"enchant": "Enchantment Arctic Breath Duration 2", "type": "currency very high"},
	"1 Enchantment Convocation Life Regeneration 2": {"enchant": "Enchantment Convocation Life Regeneration 2", "type": "currency very high"},
	"1 Enchantment Enduring Cry Life Regeneration 2": {"enchant": "Enchantment Enduring Cry Life Regeneration 2", "type": "currency very high"},
	"1 Enchantment Frost Wall Duration 2": {"enchant": "Enchantment Frost Wall Duration 2", "type": "currency very high"},
	"1 Enchantment Ice Shot Duration 2": {"enchant": "Enchantment Ice Shot Duration 2", "type": "currency very high"},
	"1 Enchantment Immortal Call Duration 2": {"enchant": "Enchantment Immortal Call Duration 2", "type": "currency very high"},
	"1 Enchantment Phase Run Duration 2": {"enchant": "Enchantment Phase Run Duration 2", "type": "currency very high"},
	"1 Enchantment Searing Bond Totem Elemental Resistances 2": {"enchant": "Enchantment Searing Bond Totem Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Wild Strike Area Of Effect 2": {"enchant": "Enchantment Wild Strike Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Summon Skeletons Additional Warrior Skeletons 2": {"enchant": "Enchantment Summon Skeletons Additional Warrior Skeletons 2", "type": "currency very high"},
	"1 Enchantment Abyssal Cry Damage 2": {"enchant": "Enchantment Abyssal Cry Damage 2", "type": "currency very high"},
	"1 Enchantment Ancestral Warchief Damage 2": {"enchant": "Enchantment Ancestral Warchief Damage 2", "type": "currency very high"},
	"1 Enchantment Arc Damage 2": {"enchant": "Enchantment Arc Damage 2", "type": "currency extremely high"},
	"1 Enchantment Arctic Breath Damage 2": {"enchant": "Enchantment Arctic Breath Damage 2", "type": "currency very high"},
	"1 Enchantment Ball Lightning Damage 2": {"enchant": "Enchantment Ball Lightning Damage 2", "type": "currency very high"},
	"1 Enchantment Barrage Damage 2": {"enchant": "Enchantment Barrage Damage 2", "type": "currency very high"},
	"1 Enchantment Bear Trap Damage 2": {"enchant": "Enchantment Bear Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Blade Flurry Damage 2": {"enchant": "Enchantment Blade Flurry Damage 2", "type": "currency extremely high"},
	"1 Enchantment Blade Vortex Damage 2": {"enchant": "Enchantment Blade Vortex Damage 2", "type": "currency extremely high"},
	"1 Enchantment Bladefall Damage 2": {"enchant": "Enchantment Bladefall Damage 2", "type": "currency very high"},
	"1 Enchantment Blast Rain Damage 2": {"enchant": "Enchantment Blast Rain Damage 2", "type": "currency very high"},
	"1 Enchantment Blight Damage 2": {"enchant": "Enchantment Blight Damage 2", "type": "currency very high"},
	"1 Enchantment Body Swap Damage 2": {"enchant": "Enchantment Body Swap Damage 2", "type": "currency very high"},
	"1 Enchantment Burning Arrow Damage 2": {"enchant": "Enchantment Burning Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Damage 2": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "currency extremely high"},
	"1 Enchantment Charged Dash Damage 2": {"enchant": "Enchantment Charged Dash Damage 2", "type": "currency very high"},
	"1 Enchantment Cleave Damage 2": {"enchant": "Enchantment Cleave Damage 2", "type": "currency very high"},
	"1 Enchantment Cold Snap Damage 2": {"enchant": "Enchantment Cold Snap Damage 2", "type": "currency very high"},
	"1 Enchantment Contagion Damage 2": {"enchant": "Enchantment Contagion Damage 2", "type": "currency very high"},
	"1 Enchantment Cremation Damage 2": {"enchant": "Enchantment Cremation Damage 2", "type": "currency very high"},
	"1 Enchantment Cyclone Damage 2": {"enchant": "Enchantment Cyclone Damage 2", "type": "currency extremely high"},
	"1 Enchantment Dark Pact Damage 2": {"enchant": "Enchantment Dark Pact Damage 2", "type": "currency very high"},
	"1 Enchantment Detonate Dead Damage 2": {"enchant": "Enchantment Detonate Dead Damage 2", "type": "currency very high"},
	"1 Enchantment Discharge Damage 2": {"enchant": "Enchantment Discharge Damage 2", "type": "currency very high"},
	"1 Enchantment Double Strike Damage 2": {"enchant": "Enchantment Double Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Dual Strike Damage 2": {"enchant": "Enchantment Dual Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Earthquake Damage 2": {"enchant": "Enchantment Earthquake Damage 2", "type": "currency very high"},
	"1 Enchantment Essence Drain Damage 2": {"enchant": "Enchantment Essence Drain Damage 2", "type": "currency extremely high"},
	"1 Enchantment Ethereal Knives Damage 2": {"enchant": "Enchantment Ethereal Knives Damage 2", "type": "currency extremely high"},
	"1 Enchantment Explosive Arrow Damage 2": {"enchant": "Enchantment Explosive Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Fire Nova Mine Damage 2": {"enchant": "Enchantment Fire Nova Mine Damage 2", "type": "currency very high"},
	"1 Enchantment Fire Trap Burning Damage 1": {"enchant": "Enchantment Fire Trap Burning Damage 1", "type": "currency very high"},
	"1 Enchantment Fire Trap Damage 2": {"enchant": "Enchantment Fire Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Fireball Damage 2": {"enchant": "Enchantment Fireball Damage 2", "type": "currency very high"},
	"1 Enchantment Firestorm Damage 2": {"enchant": "Enchantment Firestorm Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Dash Damage 2": {"enchant": "Enchantment Flame Dash Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Surge Damage 2": {"enchant": "Enchantment Flame Surge Damage 2", "type": "currency very high"},
	"1 Enchantment Flameblast Damage 2": {"enchant": "Enchantment Flameblast Damage 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage 2": {"enchant": "Enchantment Flicker Strike Damage 2", "type": "currency extremely high"},
	"1 Enchantment Freezing Pulse Damage 2": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "currency very high"},
	"1 Enchantment Frenzy Damage 2": {"enchant": "Enchantment Frenzy Damage 2", "type": "currency very high"},
	"1 Enchantment Frost Blades Damage 2": {"enchant": "Enchantment Frost Blades Damage 2", "type": "currency extremely high"},
	"1 Enchantment Frost Bomb Damage 2": {"enchant": "Enchantment Frost Bomb Damage 2", "type": "currency very high"},
	"1 Enchantment Frost Bolt Damage 2": {"enchant": "Enchantment Frost Bolt Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Damage 2": {"enchant": "Enchantment Glacial Cascade Damage 2", "type": "currency extremely high"},
	"1 Enchantment Glacial Hammer Damage 2": {"enchant": "Enchantment Glacial Hammer Damage 2", "type": "currency very high"},
	"1 Enchantment Ground Slam Damage 2": {"enchant": "Enchantment Ground Slam Damage 2", "type": "currency very high"},
	"1 Enchantment Heavy Strike Damage 2": {"enchant": "Enchantment Heavy Strike Damage 2", "type": "currency extremely high"},
	"1 Enchantment Herald Of Ash Damage 2": {"enchant": "Enchantment Herald Of Ash Damage 2", "type": "currency very high"},
	"1 Enchantment Herald Of Ice Damage 2": {"enchant": "Enchantment Herald Of Ice Damage 2", "type": "currency extremely high"},
	"1 Enchantment Herald Of Thunder Damage 2": {"enchant": "Enchantment Herald Of Thunder Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Crash Damage 2": {"enchant": "Enchantment Ice Crash Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Damage 2": {"enchant": "Enchantment Ice Nova Damage 2", "type": "currency extremely high"},
	"1 Enchantment Ice Shot Damage 2": {"enchant": "Enchantment Ice Shot Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Damage 2": {"enchant": "Enchantment Ice Spear Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Trap Damage 2": {"enchant": "Enchantment Ice Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Incinerate Damage 2": {"enchant": "Enchantment Incinerate Damage 2", "type": "currency very high"},
	"1 Enchantment Infernal Blow Damage 2": {"enchant": "Enchantment Infernal Blow Damage 2", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Damage 2": {"enchant": "Enchantment Kinetic Blast Damage 2", "type": "currency very high"},
	"1 Enchantment Lacerate Damage 2": {"enchant": "Enchantment Lacerate Damage 2", "type": "currency extremely high"},
	"1 Enchantment Leap Slam Damage 2": {"enchant": "Enchantment Leap Slam Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Damage 2": {"enchant": "Enchantment Lightning Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Strike Damage 2": {"enchant": "Enchantment Lightning Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Tendrils Damage 2": {"enchant": "Enchantment Lightning Tendrils Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Damage 2": {"enchant": "Enchantment Lightning Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Shock Effect 2": {"enchant": "Enchantment Lightning Trap Shock Effect 2", "type": "currency very high"},
	"1 Enchantment Lightning Warp Damage 2": {"enchant": "Enchantment Lightning Warp Damage 2", "type": "currency very high"},
	"1 Enchantment Magma Orb Damage 2": {"enchant": "Enchantment Magma Orb Damage 2", "type": "currency very high"},
	"1 Enchantment Molten Shell Damage 2": {"enchant": "Enchantment Molten Shell Damage 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Damage 2": {"enchant": "Enchantment Molten Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Orb Of Storms Damage 2": {"enchant": "Enchantment Orb Of Storms Damage 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Damage 2": {"enchant": "Enchantment Power Siphon Damage 2", "type": "currency very high"},
	"1 Enchantment Puncture Damage 2": {"enchant": "Enchantment Puncture Damage 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Damage 2": {"enchant": "Enchantment Rain Of Arrows Damage 2", "type": "currency very high"},
	"1 Enchantment Reave Damage 2": {"enchant": "Enchantment Reave Damage 2", "type": "currency very high"},
	"1 Enchantment Reckoning Damage 2": {"enchant": "Enchantment Reckoning Damage 2", "type": "currency very high"},
	"1 Enchantment Righteous Fire Damage 2": {"enchant": "Enchantment Righteous Fire Damage 2", "type": "currency very high"},
	"1 Enchantment Riposte Damage 2": {"enchant": "Enchantment Riposte Damage 2", "type": "currency very high"},
	"1 Enchantment Scorching Ray Damage 2": {"enchant": "Enchantment Scorching Ray Damage 2", "type": "currency very high"},
	"1 Enchantment Shield Charge Damage 2": {"enchant": "Enchantment Shield Charge Damage 2", "type": "currency very high"},
	"1 Enchantment Shock Nova Damage 2": {"enchant": "Enchantment Shock Nova Damage 2", "type": "currency very high"},
	"1 Enchantment Shockwave Totem Damage 2": {"enchant": "Enchantment Shockwave Totem Damage 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Shot Damage 2": {"enchant": "Enchantment Shrapnel Shot Damage 2", "type": "currency very high"},
	"1 Enchantment Siege Ballista Damage 2": {"enchant": "Enchantment Siege Ballista Damage 2", "type": "currency very high"},
	"1 Enchantment Spark Damage 2": {"enchant": "Enchantment Spark Damage 2", "type": "currency very high"},
	"1 Enchantment Spectral Shield Throw Damage 2": {"enchant": "Enchantment Spectral Shield Throw Damage 2", "type": "currency very high"},
	"1 Enchantment Spectral Throw Damage 2": {"enchant": "Enchantment Spectral Throw Damage 2", "type": "currency very high"},
	"1 Enchantment Split Arrow Damage 2": {"enchant": "Enchantment Split Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Static Strike Damage 2": {"enchant": "Enchantment Static Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Storm Burst Damage 2": {"enchant": "Enchantment Storm Burst Damage 2", "type": "currency very high"},
	"1 Enchantment Storm Call Damage 2": {"enchant": "Enchantment Storm Call Damage 2", "type": "currency very high"},
	"1 Enchantment Sunder Damage 2": {"enchant": "Enchantment Sunder Damage 2", "type": "currency extremely high"},
	"1 Enchantment Sweep Damage 2": {"enchant": "Enchantment Sweep Damage 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Damage 2": {"enchant": "Enchantment Tectonic Slam Damage 2", "type": "currency extremely high"},
	"1 Enchantment Tempest Shield Damage 2": {"enchant": "Enchantment Tempest Shield Damage 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Damage 2": {"enchant": "Enchantment Tornado Shot Damage 2", "type": "currency extremely high"},
	"1 Enchantment Unearth Damage 2": {"enchant": "Enchantment Unearth Damage 2", "type": "currency very high"},
	"1 Enchantment Vengeance Damage 2": {"enchant": "Enchantment Vengeance Damage 2", "type": "currency very high"},
	"1 Enchantment Vigilant Strike Damage 2": {"enchant": "Enchantment Vigilant Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Viper Strike Damage 2": {"enchant": "Enchantment Viper Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Volatile Dead Damage 2": {"enchant": "Enchantment Volatile Dead Damage 2", "type": "currency very high"},
	"1 Enchantment Vortex Damage 2": {"enchant": "Enchantment Vortex Damage 2", "type": "currency very high"},
	"1 Enchantment Whirling Blades Damage 2": {"enchant": "Enchantment Whirling Blades Damage 2", "type": "currency very high"},
	"1 Enchantment Wild Strike Damage 2": {"enchant": "Enchantment Wild Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Percent Chance To Gain Power Charge On Kill 2": {"enchant": "Enchantment Power Siphon Percent Chance To Gain Power Charge On Kill 2", "type": "currency very high"},
	"1 Enchantment Assassins Mark Duration 2": {"enchant": "Enchantment Assassins Mark Duration 2", "type": "currency very high"},
	"1 Enchantment Bone Offering Duration 2": {"enchant": "Enchantment Bone Offering Duration 2", "type": "currency very high"},
	"1 Enchantment Conductivity Duration 2": {"enchant": "Enchantment Conductivity Duration 2", "type": "currency very high"},
	"1 Enchantment Despair Duration 2": {"enchant": "Enchantment Despair Duration 2", "type": "currency very high"},
	"1 Enchantment Elemental Weakness Duration 2": {"enchant": "Enchantment Elemental Weakness Duration 2", "type": "currency very high"},
	"1 Enchantment Enfeeble Duration 2": {"enchant": "Enchantment Enfeeble Duration 2", "type": "currency very high"},
	"1 Enchantment Flammability Duration 2": {"enchant": "Enchantment Flammability Duration 2", "type": "currency very high"},
	"1 Enchantment Flesh Offering Duration 2": {"enchant": "Enchantment Flesh Offering Duration 2", "type": "currency very high"},
	"1 Enchantment Frostbite Duration 2": {"enchant": "Enchantment Frostbite Duration 2", "type": "currency very high"},
	"1 Enchantment Poachers Mark Duration 2": {"enchant": "Enchantment Poachers Mark Duration 2", "type": "currency very high"},
	"1 Enchantment Projectile Weakness Duration 2": {"enchant": "Enchantment Projectile Weakness Duration 2", "type": "currency very high"},
	"1 Enchantment Puncture Duration 2": {"enchant": "Enchantment Puncture Duration 2", "type": "currency very high"},
	"1 Enchantment Punishment Duration 2": {"enchant": "Enchantment Punishment Duration 2", "type": "currency very high"},
	"1 Enchantment Rallying Cry Duration 2": {"enchant": "Enchantment Rallying Cry Duration 2", "type": "currency very high"},
	"1 Enchantment Siege Ballista Totem Placement Speed 2": {"enchant": "Enchantment Siege Ballista Totem Placement Speed 2", "type": "currency very high"},
	"1 Enchantment Spirit Offering Duration 2": {"enchant": "Enchantment Spirit Offering Duration 2", "type": "currency very high"},
	"1 Enchantment Static Strike Duration 2": {"enchant": "Enchantment Static Strike Duration 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Duration 2": {"enchant": "Enchantment Temporal Chains Duration 2", "type": "currency very high"},
	"1 Enchantment Vigilant Strike Fortify Duration 2": {"enchant": "Enchantment Vigilant Strike Fortify Duration 2", "type": "currency very high"},
	"1 Enchantment Vulnerability Duration 2": {"enchant": "Enchantment Vulnerability Duration 2", "type": "currency very high"},
	"1 Enchantment Warlords Mark Duration 2": {"enchant": "Enchantment Warlords Mark Duration 2", "type": "currency very high"},
	"1 Enchantment Blade Flurry Dodge Per Stack 1": {"enchant": "Enchantment Blade Flurry Dodge Per Stack 1", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage Per Frenzy Charge 1": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 1", "type": "currency very high"},
	"1 Enchantment Frenzy Damage Per Frenzy Charge 1": {"enchant": "Enchantment Frenzy Damage Per Frenzy Charge 1", "type": "currency very high"},
	"1 Enchantment Devouring Totem Percent Chance To Consume Additional Corpse 2": {"enchant": "Enchantment Devouring Totem Percent Chance To Consume Additional Corpse 2", "type": "currency very high"},
	"1 Enchantment Decoy Totem Life 2": {"enchant": "Enchantment Decoy Totem Life 2", "type": "currency very high"},
	"1 Enchantment Fire Trap Burning Damage 2": {"enchant": "Enchantment Fire Trap Burning Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Surge Vs Burning Enemies 2": {"enchant": "Enchantment Flame Surge Vs Burning Enemies 2", "type": "currency very high"},
	"1 Enchantment Double Slash Critical Strikes 2": {"enchant": "Enchantment Double Slash Critical Strikes 2", "type": "currency very high"},
	"1 Enchantment Lightning Tendrils Critical Strike Chance 2": {"enchant": "Enchantment Lightning Tendrils Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Searing Bond Totem Placement Speed 2": {"enchant": "Enchantment Searing Bond Totem Placement Speed 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Critical Strike Chance 1": {"enchant": "Enchantment Tornado Shot Critical Strike Chance 1", "type": "currency very high"},
	"1 Enchantment Rallying Cry Buff Effect 2": {"enchant": "Enchantment Rallying Cry Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Area Of Effect 1": {"enchant": "Enchantment Ancestor Warchief Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Blade Flurry Area Of Effect 1": {"enchant": "Enchantment Blade Flurry Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Blade Vortex Area Of Effect 1": {"enchant": "Enchantment Blade Vortex Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Discharge Area of Effect 2": {"enchant": "Enchantment Discharge Area of Effect 2", "type": "currency very high"},
	"1 Enchantment Explosive Arrow Area Of Effect 1": {"enchant": "Enchantment Explosive Arrow Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Magma Orb Area Of Effect 1": {"enchant": "Enchantment Magma Orb Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Blade Flurry Dodge Per Stack 2": {"enchant": "Enchantment Blade Flurry Dodge Per Stack 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage Per Frenzy Charge 2": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 2", "type": "currency extremely high"},
	"1 Enchantment Frenzy Damage Per Frenzy Charge 2": {"enchant": "Enchantment Frenzy Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 Enchantment Bladefall Critical Strike Chance 2": {"enchant": "Enchantment Bladefall Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Double Strike Critical Strike Chance 2": {"enchant": "Enchantment Double Strike Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Dual Strike Critical Strike Chance 2": {"enchant": "Enchantment Dual Strike Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Flame Surge Critical Strike Chance 2": {"enchant": "Enchantment Flame Surge Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Flameblast Critical Strike Chance 2": {"enchant": "Enchantment Flameblast Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Orb of Storms Critical Strike Chance 2": {"enchant": "Enchantment Orb of Storms Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Split Arrow Critical Strike Chance 2": {"enchant": "Enchantment Split Arrow Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Critical Strike Chance 2": {"enchant": "Enchantment Tornado Shot Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Viper Strike Critical Strike Chance 2": {"enchant": "Enchantment Viper Strike Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Ancestral Protector Damage 2": {"enchant": "Enchantment Ancestral Protector Damage 2", "type": "currency very high"},
	"1 Enchantment Ancestral Protector Attack Speed 1": {"enchant": "Enchantment Ancestral Protector Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Ancestral Protector Attack Speed 2": {"enchant": "Enchantment Ancestral Protector Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Melee Damage 1": {"enchant": "Enchantment Ancestor Warchief Melee Damage 1", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Melee Damage 2": {"enchant": "Enchantment Ancestor Warchief Melee Damage 2", "type": "currency very high"},
	"1 Enchantment Anger Reservation 2": {"enchant": "Enchantment Anger Reservation 2", "type": "currency very high"},
	"1 Enchantment Animate Guardian Damage 2": {"enchant": "Enchantment Animate Guardian Damage 2", "type": "currency very high"},
	"1 Enchantment Animate Weapon Damage 2": {"enchant": "Enchantment Animate Weapon Damage 2", "type": "currency very high"},
	"1 Enchantment Arc Num Of Additional Projectiles In Chain 1": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "currency extremely high"},
	"1 Enchantment Arc Damage Per Chain 2": {"enchant": "Enchantment Arc Damage Per Chain 2", "type": "currency very high"},
	"1 Enchantment Arc Damage Per Chain 1": {"enchant": "Enchantment Arc Damage Per Chain 1", "type": "currency very high"},
	"1 Enchantment Arc Shock Chance 2": {"enchant": "Enchantment Arc Shock Chance 2", "type": "currency extremely high"},
	"1 Enchantment Arctic Armour Mana Reservation 2": {"enchant": "Enchantment Arctic Armour Mana Reservation 2", "type": "currency very high"},
	"1 Armageddon Brand Attached Target Fire Penetration 2": {"enchant": "Armageddon Brand Attached Target Fire Penetration 2", "type": "currency extremely high"},
	"1 Enchantment Armageddon Brand Damage 2": {"enchant": "Enchantment Armageddon Brand Damage 2", "type": "currency extremely high"},
	"1 Armageddon Brand Repeat Frequency 2": {"enchant": "Armageddon Brand Repeat Frequency 2", "type": "currency very high"},
	"1 Enchantment Ball Lightning Additional Projectiles 1": {"enchant": "Enchantment Ball Lightning Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Bane Damage 2": {"enchant": "Enchantment Bane Damage 2", "type": "currency extremely high"},
	"1 Enchantment Bane Area Of Effect 2": {"enchant": "Enchantment Bane Area Of Effect 2", "type": "currency extremely high"},
	"1 Enchantment Barrage Num Of Additional Projectiles 1": {"enchant": "Enchantment Barrage Num Of Additional Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Blade Vortex Crit Multi Per Blade 1": {"enchant": "Enchantment Blade Vortex Crit Multi Per Blade 1", "type": "currency very high"},
	"1 Enchantment Blade Vortex Crit Multi Per Blade 2": {"enchant": "Enchantment Blade Vortex Crit Multi Per Blade 2", "type": "currency extremely high"},
	"1 Enchantment Bladefall Additional Volley": {"enchant": "Enchantment Bladefall Additional Volley", "type": "currency extremely high"},
	"1 Enchantment Blast Rain Additional Blast 1": {"enchant": "Enchantment Blast Rain Additional Blast 1", "type": "currency very high"},
	"1 Enchantment Blast Rain Additional Blast 2": {"enchant": "Enchantment Blast Rain Additional Blast 2", "type": "currency very high"},
	"1 Enchantment Blight Secondary Skill Duration 2": {"enchant": "Enchantment Blight Secondary Skill Duration 2", "type": "currency very high"},
	"1 Enchantment Blink Arrow Attack Speed 2": {"enchant": "Enchantment Blink Arrow Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Blink Arrow Damage 2": {"enchant": "Enchantment Blink Arrow Damage 2", "type": "currency extremely high"},
	"1 Enchantment Blood Rage Attack Speed 2": {"enchant": "Enchantment Blood Rage Attack Speed 2", "type": "currency extremely high"},
	"1 Enchantment Blood Rage Frenzy On Kill 2": {"enchant": "Enchantment Blood Rage Frenzy On Kill 2", "type": "currency very high"},
	"1 Enchantment Blood Rage Attack Speed 1": {"enchant": "Enchantment Blood Rage Attack Speed 1", "type": "currency very high"},
	"1 Enchantment Bone Offering Block Chance 2": {"enchant": "Enchantment Bone Offering Block Chance 2", "type": "currency very high"},
	"1 Enchantment Burning Arrow Ignite Chance 2": {"enchant": "Enchantment Burning Arrow Ignite Chance 2", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Wither On Hit 2": {"enchant": "Enchantment Caustic Arrow Wither On Hit 2", "type": "currency very high"},
	"1 Enchantment Sumon Chaos Golem Damage 2": {"enchant": "Enchantment Sumon Chaos Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Charged Dash Radius Final Explosion 2": {"enchant": "Enchantment Charged Dash Radius Final Explosion 2", "type": "currency very high"},
	"1 Enchantment Charged Dash Movement Speed 2": {"enchant": "Enchantment Charged Dash Movement Speed 2", "type": "currency very high"},
	"1 Enchantment Clarity Mana Reservation 2": {"enchant": "Enchantment Clarity Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Enchantment Consecrated Path Damage 2": {"enchant": "Enchantment Consecrated Path Damage 2", "type": "currency extremely high"},
	"1 Enchantment Consecrated Path Area Of Effect 2": {"enchant": "Enchantment Consecrated Path Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Consecrated Path Range 2": {"enchant": "Enchantment Consecrated Path Range 2", "type": "currency very high"},
	"1 Enchantment Conversion Trap Damage 2": {"enchant": "Enchantment Conversion Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Cremation Maximum Geysers 1": {"enchant": "Enchantment Cremation Maximum Geysers 1", "type": "currency very high"},
	"1 Enchantment Desecrate Additional Corpse 1": {"enchant": "Enchantment Desecrate Additional Corpse 1", "type": "currency very high"},
	"1 Enchantment Desecrate Additional Corpse 2": {"enchant": "Enchantment Desecrate Additional Corpse 2", "type": "currency very high"},
	"1 Enchantment Determination Mana Reservation 2": {"enchant": "Enchantment Determination Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Detonate Dead Percent Chance To Detonate Additional Corpse 2": {"enchant": "Enchantment Detonate Dead Percent Chance To Detonate Additional Corpse 2", "type": "currency very high"},
	"1 Enchantment Discipline Mana Reservation 2": {"enchant": "Enchantment Discipline Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2": {"enchant": "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2", "type": "currency extremely high"},
	"1 Enchantment Divine Ire Damage 2": {"enchant": "Enchantment Divine Ire Damage 2", "type": "currency extremely high"},
	"1 Enchantment Divine Ire Beam Width 2": {"enchant": "Enchantment Divine Ire Beam Width 2", "type": "currency extremely high"},
	"1 Enchantment Dominating Blow Additional Magic 2": {"enchant": "Enchantment Dominating Blow Additional Magic 2", "type": "currency very high"},
	"1 Enchantment Dominating Blow Additional Rare 1": {"enchant": "Enchantment Dominating Blow Additional Rare 1", "type": "currency very high"},
	"1 Enchantment Double Strike Double Damage Vs Bleeding 1": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 1", "type": "currency very high"},
	"1 Enchantment Double Strike Double Damage Vs Bleeding 2": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 2", "type": "currency extremely high"},
	"1 Enchantment Dread Banner Effect 2": {"enchant": "Enchantment Dread Banner Effect 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Damage 1": {"enchant": "Enchantment Elemental Hit Damage 1", "type": "currency very high"},
	"1 Enchantment Elemental Hit Damage 2": {"enchant": "Enchantment Elemental Hit Damage 2", "type": "currency extremely high"},
	"1 Enchantment Elemental Hit Chance To Freeze Shock Ignite 1": {"enchant": "Enchantment Elemental Hit Chance To Freeze Shock Ignite 1", "type": "currency very high"},
	"1 Enchantment Elemental Hit Chance To Freeze Shock Ignite 2": {"enchant": "Enchantment Elemental Hit Chance To Freeze Shock Ignite 2", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Number Of Targets To Pierce 1": {"enchant": "Enchantment Ethereal Knives Number Of Targets To Pierce 1", "type": "currency very high"},
	"1 Enchantment Shrapnel Trap Secondary Explosions 2": {"enchant": "Enchantment Shrapnel Trap Secondary Explosions 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Trap Damage 2": {"enchant": "Enchantment Shrapnel Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Trap Radius 2": {"enchant": "Enchantment Shrapnel Trap Radius 2", "type": "currency very high"},
	"1 Enchantment Fire Nova Mine Num Of Additional Repeats 2": {"enchant": "Enchantment Fire Nova Mine Num Of Additional Repeats 2", "type": "currency extremely high"},
	"1 Enchantment Summon Flame Golem Damage 1": {"enchant": "Enchantment Summon Flame Golem Damage 1", "type": "currency very high"},
	"1 Enchantment Summon Flame Golem Damage 2": {"enchant": "Enchantment Summon Flame Golem Damage 2", "type": "currency extremely high"},
	"1 Enchantment Flamethrower Trap Damage 2": {"enchant": "Enchantment Flamethrower Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Flamethrower Trap Cast Speed 2": {"enchant": "Enchantment Flamethrower Trap Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Flamethrower Additional Flamethrowers 2": {"enchant": "Enchantment Flamethrower Additional Flamethrowers 2", "type": "currency very high"},
	"1 Enchantment Flamethrower Trap Duration 2": {"enchant": "Enchantment Flamethrower Trap Duration 2", "type": "currency very high"},
	"1 Enchantment Flesh Offering Attack Speed 2": {"enchant": "Enchantment Flesh Offering Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Freeze Mine Cold Penetration 2": {"enchant": "Enchantment Freeze Mine Cold Penetration 2", "type": "currency very high"},
	"1 Enchantment Frost Bolt Freeze Chance 2": {"enchant": "Enchantment Frost Bolt Freeze Chance 2", "type": "currency very high"},
	"1 Enchantment Rejuvination Totem Percent Life Regeneration Added As Mana Regeneration 2": {"enchant": "Enchantment Rejuvination Totem Percent Life Regeneration Added As Mana Regeneration 2", "type": "currency very high"},
	"1 Enchantment Glacial Hammer Freeze Chance 2": {"enchant": "Enchantment Glacial Hammer Freeze Chance 2", "type": "currency very high"},
	"1 Enchantment Grace Mana Reservation 1": {"enchant": "Enchantment Grace Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Grace Mana Reservation 2": {"enchant": "Enchantment Grace Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Haste Mana Reservation 2": {"enchant": "Enchantment Haste Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Hatred Mana Reservation 2": {"enchant": "Enchantment Hatred Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Heavy Strike Double Damage 2": {"enchant": "Enchantment Heavy Strike Double Damage 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 1": {"enchant": "Enchantment Herald Of Agony Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 2": {"enchant": "Enchantment Herald Of Agony Mana Reservation 2", "type": "currency extremely high"},
	"1 Enchantment Herald Of Ash Mana Reservation 2": {"enchant": "Enchantment Herald Of Ash Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Herald Of Ice Mana Reservation 1": {"enchant": "Enchantment Herald Of Ice Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Herald Of Ice Mana Reservation 2": {"enchant": "Enchantment Herald Of Ice Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Herald Of Purity Mana Reservation 2": {"enchant": "Enchantment Herald Of Purity Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Herald Of Thunder Mana Reservation 1": {"enchant": "Enchantment Herald Of Thunder Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Herald Of Thunder Mana Reservation 2": {"enchant": "Enchantment Herald Of Thunder Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Damage 2": {"enchant": "Enchantment Flame Totem Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Num Of Additional Projectiles 2": {"enchant": "Enchantment Flame Totem Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Projectile Speed 2": {"enchant": "Enchantment Flame Totem Projectile Speed 2", "type": "currency extremely high"},
	"1 Enchantment Summon Ice Golem Damage 2": {"enchant": "Enchantment Summon Ice Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Freeze Chance 2": {"enchant": "Enchantment Ice Nova Freeze Chance 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Additional Projectile 1": {"enchant": "Enchantment Ice Spear Additional Projectile 1", "type": "currency extremely high"},
	"1 Enchantment Ice Spear Distance Before Form Change 2": {"enchant": "Enchantment Ice Spear Distance Before Form Change 2", "type": "currency very high"},
	"1 Enchantment Ice Trap Cold Penetration 2": {"enchant": "Enchantment Ice Trap Cold Penetration 2", "type": "currency very high"},
	"1 Enchantment Incinerate Maximum Stages 2": {"enchant": "Enchantment Incinerate Maximum Stages 2", "type": "currency very high"},
	"1 Enchantment Incinerate Area Of Effect 2": {"enchant": "Enchantment Incinerate Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Infernal Blow Increased Damage Per Stack 2": {"enchant": "Enchantment Infernal Blow Increased Damage Per Stack 2", "type": "currency extremely high"},
	"1 Enchantment Kinetic Blast Explosions 1": {"enchant": "Enchantment Kinetic Blast Explosions 1", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Explosions 2": {"enchant": "Enchantment Kinetic Blast Explosions 2", "type": "currency extremely high"},
	"1 Enchantment Double Slash Added Phys To Bleeding 2": {"enchant": "Enchantment Double Slash Added Phys To Bleeding 2", "type": "currency very high"},
	"1 Enchantment Lancing Steel Damage 2": {"enchant": "Enchantment Lancing Steel Damage 2", "type": "currency very high"},
	"1 Enchantment Lancing Steel Impale Chance 2": {"enchant": "Enchantment Lancing Steel Impale Chance 2", "type": "currency very high"},
	"1 Enchantment Lancing Steel Primary Proj Pierce Num 2": {"enchant": "Enchantment Lancing Steel Primary Proj Pierce Num 2", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Extra Targets 2": {"enchant": "Enchantment Lightning Arrow Extra Targets 2", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Extra Targets 1": {"enchant": "Enchantment Lightning Arrow Extra Targets 1", "type": "currency very high"},
	"1 Enchantment Summon Lightning Golem Damage 2": {"enchant": "Enchantment Summon Lightning Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Tower Trap Damage 2": {"enchant": "Enchantment Lightning Tower Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Tower Trap Duration 2": {"enchant": "Enchantment Lightning Tower Trap Duration 2", "type": "currency very high"},
	"1 Enchantment Lightning Tower Trap Additional Beams 1": {"enchant": "Enchantment Lightning Tower Trap Additional Beams 1", "type": "currency very high"},
	"1 Enchantment Lightning Strike Num Of Additional Projectiles 2": {"enchant": "Enchantment Lightning Strike Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Lightning Strike Additional Pierce 2": {"enchant": "Enchantment Lightning Strike Additional Pierce 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Penetration 2": {"enchant": "Enchantment Lightning Trap Penetration 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Additional Pierce 2": {"enchant": "Enchantment Lightning Trap Additional Pierce 2", "type": "currency very high"},
	"1 Enchantment Magma Orb Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2", "type": "currency extremely high"},
	"1 Enchantment Magma Orb Num Of Additional Projectiles In Chain 1": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 1", "type": "currency very high"},
	"1 Enchantment Mirror Arrow Attack Speed 2": {"enchant": "Enchantment Mirror Arrow Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 2": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 1": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Orb Of Storms Cast Speed 2": {"enchant": "Enchantment Orb Of Storms Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Additional Projectiles 2": {"enchant": "Enchantment Power Siphon Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Purifying Flame Damage 2": {"enchant": "Enchantment Purifying Flame Damage 2", "type": "currency extremely high"},
	"1 Enchantment Purity Of Elements Mana Reservation 2": {"enchant": "Enchantment Purity Of Elements Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Purity Of Fire Mana Reservation 2": {"enchant": "Enchantment Purity Of Fire Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Purity Of Ice Mana Reservation 2": {"enchant": "Enchantment Purity Of Ice Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Purity Of Lightning Mana Reservation 2": {"enchant": "Enchantment Purity Of Lightning Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Summon Raging Spirit Damage 1": {"enchant": "Enchantment Summon Raging Spirit Damage 1", "type": "currency very high"},
	"1 Enchantment Summon Raging Spirit Damage 2": {"enchant": "Enchantment Summon Raging Spirit Damage 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Repeat Count 2": {"enchant": "Enchantment Rain Of Arrows Repeat Count 2", "type": "currency extremely high"},
	"1 Enchantment Righteous Fire Spell Damage 1": {"enchant": "Enchantment Righteous Fire Spell Damage 1", "type": "currency very high"},
	"1 Enchantment Righteous Fire Spell Damage 2": {"enchant": "Enchantment Righteous Fire Spell Damage 2", "type": "currency very high"},
	"1 Enchantment Scourge Arrow Additional Spore 1": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "currency extremely high"},
	"1 Enchantment Scourge Arrow Damage 2": {"enchant": "Enchantment Scourge Arrow Damage 2", "type": "currency extremely high"},
	"1 Enchantment Scourge Arrow Chance To Poison 2": {"enchant": "Enchantment Scourge Arrow Chance To Poison 2", "type": "currency very high"},
	"1 Enchantment Physical Cascade Trap Damage 2": {"enchant": "Enchantment Physical Cascade Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Physical Cascade Cooldown Speed 2": {"enchant": "Enchantment Physical Cascade Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Physical Cascade Trap Duration 2": {"enchant": "Enchantment Physical Cascade Trap Duration 2", "type": "currency very high"},
	"1 Enchantment Physical Cascade Additional Cascades 1": {"enchant": "Enchantment Physical Cascade Additional Cascades 1", "type": "currency very high"},
	"1 Enchantment Shattering Steel Damage 2": {"enchant": "Enchantment Shattering Steel Damage 2", "type": "currency very high"},
	"1 Enchantment Shattering Steel Additional Projectile 1": {"enchant": "Enchantment Shattering Steel Additional Projectile 1", "type": "currency extremely high"},
	"1 Enchantment Shattering Steel Fortify On Hit Close Range 1": {"enchant": "Enchantment Shattering Steel Fortify On Hit Close Range 1", "type": "currency extremely high"},
	"1 Enchantment Shock Nova Larger Ring Damage 2": {"enchant": "Enchantment Shock Nova Larger Ring Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Siphon Trap Damage 2": {"enchant": "Enchantment Ice Siphon Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Siphon Trap Duration 2": {"enchant": "Enchantment Ice Siphon Trap Duration 2", "type": "currency extremely high"},
	"1 Enchantment Summon Skeletons Damage 2": {"enchant": "Enchantment Summon Skeletons Damage 2", "type": "currency very high"},
	"1 Enchantment Smite Damage 2": {"enchant": "Enchantment Smite Damage 2", "type": "currency very high"},
	"1 Enchantment Smite Aura Effect 2": {"enchant": "Enchantment Smite Aura Effect 2", "type": "currency very high"},
	"1 Enchantment Smite Additional Target Chance 2": {"enchant": "Enchantment Smite Additional Target Chance 2", "type": "currency very high"},
	"1 Enchantment Smoke Mine Movement Speed 2": {"enchant": "Enchantment Smoke Mine Movement Speed 2", "type": "currency very high"},
	"1 Enchantment Soulrend Applies Hinder Movement Speed 2": {"enchant": "Enchantment Soulrend Applies Hinder Movement Speed 2", "type": "currency extremely high"},
	"1 Enchantment Soulrend Damage 2": {"enchant": "Enchantment Soulrend Damage 2", "type": "currency very high"},
	"1 Enchantment Soulrend Number Of Additional Projectiles 1": {"enchant": "Enchantment Soulrend Number Of Additional Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Spark Num Of Additional Projectiles 1": {"enchant": "Enchantment Spark Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Spark Num Of Additional Projectiles 2": {"enchant": "Enchantment Spark Num Of Additional Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Spectral Shield Throw Num Of Additional Projectiles 2": {"enchant": "Enchantment Spectral Shield Throw Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Spectre Attack And Cast Speed 2": {"enchant": "Enchantment Spectre Attack And Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Raise Spectre Damage 2": {"enchant": "Enchantment Raise Spectre Damage 2", "type": "currency very high"},
	"1 Enchantment Spirit Offering Physical Added As Chaos 2": {"enchant": "Enchantment Spirit Offering Physical Added As Chaos 2", "type": "currency very high"},
	"1 Enchantment Split Arrow Num Of Additional Projectiles 1": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Split Arrow Num Of Additional Projectiles 2": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Static Strike Maximum Beam Targets 2": {"enchant": "Enchantment Static Strike Maximum Beam Targets 2", "type": "currency very high"},
	"1 Enchantment Summon Stone Golem Damage 2": {"enchant": "Enchantment Summon Stone Golem Damage 2", "type": "currency very high"},
	"1 Storm Brand Attached Target Lightning Penetration 2": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "currency extremely high"},
	"1 Storm Brand Attached Target Lightning Penetration 1": {"enchant": "Storm Brand Attached Target Lightning Penetration 1", "type": "currency extremely high"},
	"1 Enchantment Storm Brand Damage 2": {"enchant": "Enchantment Storm Brand Damage 2", "type": "currency extremely high"},
	"1 Storm Brand Additional Chain Chance 2": {"enchant": "Storm Brand Additional Chain Chance 2", "type": "currency very high"},
	"1 Enchantment Storm Burst Additional Object Chance 2": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "currency very high"},
	"1 Enchantment Summoned Raging Spirit Additional 2": {"enchant": "Enchantment Summoned Raging Spirit Additional 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Num Of Secondary Projectiles 1": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Holy Relic Damage 2": {"enchant": "Enchantment Holy Relic Damage 2", "type": "currency very high"},
	"1 Enchantment Holy Relic Buff Effect 2": {"enchant": "Enchantment Holy Relic Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Chance To Charged Slam 2": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 2", "type": "currency extremely high"},
	"1 Enchantment Tempest Shield Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Tempest Shield Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 2": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 1": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Toxic Rain Damage 2": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "currency very high"},
	"1 Enchantment Toxic Rain Num Of Additional Projectiles 1": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Toxic Rain Physical Added As Chaos 2": {"enchant": "Enchantment Toxic Rain Physical Added As Chaos 2", "type": "currency very high"},
	"1 Enchantment Unearth Corpse Level 2": {"enchant": "Enchantment Unearth Corpse Level 2", "type": "currency very high"},
	"1 Enchantment Vitality Mana Reservation 2": {"enchant": "Enchantment Vitality Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Volatile Dead Orbs 1": {"enchant": "Enchantment Volatile Dead Orbs 1", "type": "currency extremely high"},
	"1 Enchantment Volatile Dead Orbs 2": {"enchant": "Enchantment Volatile Dead Orbs 2", "type": "currency extremely high"},
	"1 Enchantment Volatile Dead Orbs 3": {"enchant": "Enchantment Volatile Dead Orbs 3", "type": "currency extremely high"},
	"1 Enchantment Vortex Cooldown Recovery 2": {"enchant": "Enchantment Vortex Cooldown Recovery 2", "type": "currency extremely high"},
	"1 Enchantment Vortex AoE On Frostbolt 2": {"enchant": "Enchantment Vortex AoE On Frostbolt 2", "type": "currency very high"},
	"1 Enchantment Wave Of Conviction Additional Enemy Resistance 2": {"enchant": "Enchantment Wave Of Conviction Additional Enemy Resistance 2", "type": "currency extremely high"},
	"1 Enchantment Wild Strike Num Of Additional Projectiles In Chain 1": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 1", "type": "currency very high"},
	"1 Enchantment Wild Strike Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 1": {"enchant": "Enchantment Winter Orb Damage 1", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 2": {"enchant": "Enchantment Winter Orb Damage 2", "type": "currency extremely high"},
	"1 Enchantment Frost Fury Additional Max Number Of Stages 1": {"enchant": "Enchantment Frost Fury Additional Max Number Of Stages 1", "type": "currency extremely high"},
	"1 Enchantment Frost Fury Area Of Effect Per Stage 2": {"enchant": "Enchantment Frost Fury Area Of Effect Per Stage 2", "type": "currency very high"},
	"1 Enchantment Wither Area Of Effect 2": {"enchant": "Enchantment Wither Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Wrath Mana Reservation 2": {"enchant": "Enchantment Wrath Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Zealotry Mana Reservation 2": {"enchant": "Enchantment Zealotry Mana Reservation 2", "type": "currency extremely high"},
	"1 Enchantment Raise Zombie Damage 2": {"enchant": "Enchantment Raise Zombie Damage 2", "type": "currency very high"},
	"1 Enchantment Zombie Attack Speed 2": {"enchant": "Enchantment Zombie Attack Speed 2", "type": "currency very high"},
}
