#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 12/20/2018(m/d/y) 08:04:55 UTC from "tmpstandard" data

desc = "Bases"

# Base type : settings pair
items = {
	"0 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Assassin's Garb": {"base": "Assassin's Garb", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Astral Plate": {"base": "Astral Plate", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Carnal Armour": {"base": "Carnal Armour", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Gutting Knife": {"base": "Gutting Knife", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Omen Wand": {"base": "Omen Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Paua Ring": {"base": "Paua Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Burgonet": {"base": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Saintly Chainmail": {"base": "Saintly Chainmail", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slaughter Knife": {"base": "Slaughter Knife", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Solaris Circlet": {"base": "Solaris Circlet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ambusher": {"base": "Ambusher", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Fluted Bascinet": {"base": "Fluted Bascinet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Harlequin Mask": {"base": "Harlequin Mask", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Imperial Claw": {"base": "Imperial Claw", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Magistrate Crown": {"base": "Magistrate Crown", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Necromancer Circlet": {"base": "Necromancer Circlet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Regicide Mask": {"base": "Regicide Mask", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Saint's Hauberk": {"base": "Saint's Hauberk", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Thicket Bow": {"base": "Thicket Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Titan Greaves": {"base": "Titan Greaves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Bone Helmet": {"base": "Bone Helmet", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Crystal Belt": {"base": "Crystal Belt", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Stygian Vise": {"base": "Stygian Vise", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ItemLevel >= 86"], "type": "base extremely high"},
	"0 Vaal Regalia": {"base": "Vaal Regalia", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"1 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Astral Plate": {"base": "Astral Plate", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Boot Blade": {"base": "Boot Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gutting Knife": {"base": "Gutting Knife", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lead Sceptre": {"base": "Lead Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Omen Wand": {"base": "Omen Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Prophecy Wand": {"base": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Skean": {"base": "Royal Skean", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Slaughter Knife": {"base": "Slaughter Knife", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Soldier Gloves": {"base": "Soldier Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Coral Amulet": {"base": "Coral Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gold Amulet": {"base": "Gold Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel 85"], "type": "base very high"},
	"2 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Burnished Foil": {"base": "Burnished Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Mind Cage": {"base": "Mind Cage", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Serpentscale Gauntlets": {"base": "Serpentscale Gauntlets", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Wyrmscale Gauntlets": {"base": "Wyrmscale Gauntlets", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Hypnotic Eye Jewel": {"base": "Hypnotic Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Murderous Eye Jewel": {"base": "Murderous Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Opal Ring": {"base": "Opal Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Searching Eye Jewel": {"base": "Searching Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"3 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Apex Rapier": {"base": "Apex Rapier", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Paua Ring": {"base": "Paua Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"4 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Thicket Bow": {"base": "Thicket Bow", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},

}
