#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 12/15/2019(m/d/y) 05:21:44 UTC from "tmpstandard" data

desc = "Bases"

# Base type : settings pair
items = {
	"0 Shaper Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Archon Kite Shield": {"baseexact": "Archon Kite Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Astral Plate": {"baseexact": "Astral Plate", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Behemoth Mace": {"baseexact": "Behemoth Mace", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Blunt Arrow Quiver": {"baseexact": "Blunt Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Brass Spirit Shield": {"baseexact": "Brass Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Broadhead Arrow Quiver": {"baseexact": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Bronzescale Gauntlets": {"baseexact": "Bronzescale Gauntlets", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Cardinal Round Shield": {"baseexact": "Cardinal Round Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Champion Kite Shield": {"baseexact": "Champion Kite Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Colossal Tower Shield": {"baseexact": "Colossal Tower Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Copper Kris": {"baseexact": "Copper Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Coral Amulet": {"baseexact": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Coral Ring": {"baseexact": "Coral Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crescent Staff": {"baseexact": "Crescent Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crusader Buckler": {"baseexact": "Crusader Buckler", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Dagger Axe": {"baseexact": "Dagger Axe", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Death Bow": {"baseexact": "Death Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Ebony Tower Shield": {"baseexact": "Ebony Tower Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Elegant Foil": {"baseexact": "Elegant Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eternal Burgonet": {"baseexact": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ezomyte Tower Shield": {"baseexact": "Ezomyte Tower Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Faun's Horn": {"baseexact": "Faun's Horn", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Festival Mask": {"baseexact": "Festival Mask", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Fire Arrow Quiver": {"baseexact": "Fire Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fossilised Spirit Shield": {"baseexact": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Gold Amulet": {"baseexact": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Golden Kris": {"baseexact": "Golden Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Great Helmet": {"baseexact": "Great Helmet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Grove Bow": {"baseexact": "Grove Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Harbinger Bow": {"baseexact": "Harbinger Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Harmonic Spirit Shield": {"baseexact": "Harmonic Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Heathen Wand": {"baseexact": "Heathen Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Highborn Bow": {"baseexact": "Highborn Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Horned Sceptre": {"baseexact": "Horned Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Hubris Circlet": {"baseexact": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Imbued Wand": {"baseexact": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Imperial Bow": {"baseexact": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Imperial Claw": {"baseexact": "Imperial Claw", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Iron Ring": {"baseexact": "Iron Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Jingling Spirit Shield": {"baseexact": "Jingling Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lacquered Buckler": {"baseexact": "Lacquered Buckler", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Leather Belt": {"baseexact": "Leather Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lion Pelt": {"baseexact": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Maraketh Bow": {"baseexact": "Maraketh Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Mesh Gloves": {"baseexact": "Mesh Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Military Staff": {"baseexact": "Military Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Moon Staff": {"baseexact": "Moon Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Nubuck Boots": {"baseexact": "Nubuck Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Nubuck Gloves": {"baseexact": "Nubuck Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Ring": {"baseexact": "Opal Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Sceptre": {"baseexact": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Wand": {"baseexact": "Opal Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Paua Amulet": {"baseexact": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Penetrating Arrow Quiver": {"baseexact": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Platinum Kris": {"baseexact": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Profane Wand": {"baseexact": "Profane Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Prophecy Wand": {"baseexact": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Reflex Bow": {"baseexact": "Reflex Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ritual Sceptre": {"baseexact": "Ritual Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Bow": {"baseexact": "Royal Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sadist Garb": {"baseexact": "Sadist Garb", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sambar Sceptre": {"baseexact": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Serrated Arrow Quiver": {"baseexact": "Serrated Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sharktooth Arrow Quiver": {"baseexact": "Sharktooth Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Silk Gloves": {"baseexact": "Silk Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slink Boots": {"baseexact": "Slink Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sorcerer Boots": {"baseexact": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Spike-Point Arrow Quiver": {"baseexact": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Steel Ring": {"baseexact": "Steel Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Supreme Spiked Shield": {"baseexact": "Supreme Spiked Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Thicket Bow": {"baseexact": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Thorn Rapier": {"baseexact": "Thorn Rapier", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titan Greaves": {"baseexact": "Titan Greaves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titanium Spirit Shield": {"baseexact": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Tornado Wand": {"baseexact": "Tornado Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Two-Point Arrow Quiver": {"baseexact": "Two-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Unset Ring": {"baseexact": "Unset Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Mask": {"baseexact": "Vaal Mask", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Regalia": {"baseexact": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Void Sceptre": {"baseexact": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Assassin's Garb": {"baseexact": "Assassin's Garb", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Astral Plate": {"baseexact": "Astral Plate", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Close Helmet": {"baseexact": "Close Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Colossal Tower Shield": {"baseexact": "Colossal Tower Shield", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Copper Kris": {"baseexact": "Copper Kris", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Coral Amulet": {"baseexact": "Coral Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Coral Ring": {"baseexact": "Coral Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Crescent Staff": {"baseexact": "Crescent Staff", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Curved Blade": {"baseexact": "Curved Blade", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Dagger Axe": {"baseexact": "Dagger Axe", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Eternal Burgonet": {"baseexact": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Fleshripper": {"baseexact": "Fleshripper", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Glorious Plate": {"baseexact": "Glorious Plate", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Gold Amulet": {"baseexact": "Gold Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Harbinger Bow": {"baseexact": "Harbinger Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Heavy Belt": {"baseexact": "Heavy Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Horned Sceptre": {"baseexact": "Horned Sceptre", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Hubris Circlet": {"baseexact": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Imp Dagger": {"baseexact": "Imp Dagger", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Leather Belt": {"baseexact": "Leather Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Lithe Blade": {"baseexact": "Lithe Blade", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Opal Ring": {"baseexact": "Opal Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Opal Wand": {"baseexact": "Opal Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ornate Spiked Shield": {"baseexact": "Ornate Spiked Shield", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Pagan Wand": {"baseexact": "Pagan Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Paua Amulet": {"baseexact": "Paua Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Quartz Wand": {"baseexact": "Quartz Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Slink Gloves": {"baseexact": "Slink Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sorcerer Boots": {"baseexact": "Sorcerer Boots", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Steel Ring": {"baseexact": "Steel Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Strapped Mitts": {"baseexact": "Strapped Mitts", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Titan Gauntlets": {"baseexact": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Titan Greaves": {"baseexact": "Titan Greaves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Unset Ring": {"baseexact": "Unset Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vaal Axe": {"baseexact": "Vaal Axe", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Vaal Gauntlets": {"baseexact": "Vaal Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Lacquered Buckler": {"baseexact": "Lacquered Buckler", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Opal Wand": {"baseexact": "Opal Wand", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Steel Ring": {"baseexact": "Steel Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Stygian Vise": {"baseexact": "Stygian Vise", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Titan Greaves": {"baseexact": "Titan Greaves", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"0 Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ItemLevel >= 86"], "type": "base extremely high"},
	"0 Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ItemLevel >= 86"], "type": "base very high"},
	"1 Shaper Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Broadhead Arrow Quiver": {"baseexact": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Clasped Mitts": {"baseexact": "Clasped Mitts", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Colossal Tower Shield": {"baseexact": "Colossal Tower Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Copper Kris": {"baseexact": "Copper Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Coral Amulet": {"baseexact": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Coral Ring": {"baseexact": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Crusader Gloves": {"baseexact": "Crusader Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Curved Blade": {"baseexact": "Curved Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Eelskin Tunic": {"baseexact": "Eelskin Tunic", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ezomyte Tower Shield": {"baseexact": "Ezomyte Tower Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Gold Amulet": {"baseexact": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Golden Kris": {"baseexact": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Grove Bow": {"baseexact": "Grove Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Harbinger Bow": {"baseexact": "Harbinger Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Highborn Bow": {"baseexact": "Highborn Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Hubris Circlet": {"baseexact": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imbued Wand": {"baseexact": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imperial Bow": {"baseexact": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Iron Ring": {"baseexact": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Leather Belt": {"baseexact": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Leather Hood": {"baseexact": "Leather Hood", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lion Pelt": {"baseexact": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Mahogany Tower Shield": {"baseexact": "Mahogany Tower Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Maraketh Bow": {"baseexact": "Maraketh Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Moon Staff": {"baseexact": "Moon Staff", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Nubuck Boots": {"baseexact": "Nubuck Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Opal Ring": {"baseexact": "Opal Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Opal Sceptre": {"baseexact": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Opal Wand": {"baseexact": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Pagan Wand": {"baseexact": "Pagan Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Paua Amulet": {"baseexact": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Penetrating Arrow Quiver": {"baseexact": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Platinum Kris": {"baseexact": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Profane Wand": {"baseexact": "Profane Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Prophecy Wand": {"baseexact": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Bow": {"baseexact": "Royal Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sambar Sceptre": {"baseexact": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sharktooth Arrow Quiver": {"baseexact": "Sharktooth Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Boots": {"baseexact": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Spike-Point Arrow Quiver": {"baseexact": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Steel Ring": {"baseexact": "Steel Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Thicket Bow": {"baseexact": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Thorn Rapier": {"baseexact": "Thorn Rapier", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titanium Spirit Shield": {"baseexact": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Tornado Wand": {"baseexact": "Tornado Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Two-Point Arrow Quiver": {"baseexact": "Two-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Unset Ring": {"baseexact": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vaal Mask": {"baseexact": "Vaal Mask", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Vaal Regalia": {"baseexact": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Void Sceptre": {"baseexact": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Archon Kite Shield": {"baseexact": "Archon Kite Shield", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Astral Plate": {"baseexact": "Astral Plate", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Coral Ring": {"baseexact": "Coral Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eelskin Gloves": {"baseexact": "Eelskin Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eternal Burgonet": {"baseexact": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Ezomyte Blade": {"baseexact": "Ezomyte Blade", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Fleshripper": {"baseexact": "Fleshripper", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Glorious Plate": {"baseexact": "Glorious Plate", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gold Amulet": {"baseexact": "Gold Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Harbinger Bow": {"baseexact": "Harbinger Bow", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Harpy Rapier": {"baseexact": "Harpy Rapier", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Heavy Belt": {"baseexact": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Leather Belt": {"baseexact": "Leather Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lion Pelt": {"baseexact": "Lion Pelt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Moon Staff": {"baseexact": "Moon Staff", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Opal Ring": {"baseexact": "Opal Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Opal Wand": {"baseexact": "Opal Wand", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Rustic Sash": {"baseexact": "Rustic Sash", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Siege Axe": {"baseexact": "Siege Axe", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Slink Gloves": {"baseexact": "Slink Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Soldier's Brigandine": {"baseexact": "Soldier's Brigandine", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Steel Gauntlets": {"baseexact": "Steel Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Steel Ring": {"baseexact": "Steel Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Titan Gauntlets": {"baseexact": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Unset Ring": {"baseexact": "Unset Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Vaal Axe": {"baseexact": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Lacquered Buckler": {"baseexact": "Lacquered Buckler", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Opal Wand": {"baseexact": "Opal Wand", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Searching Eye Jewel": {"baseexact": "Searching Eye Jewel", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ItemLevel 85"], "type": "base very high"},
	"1 Steel Ring": {"baseexact": "Steel Ring", "other": ["ItemLevel 85"], "type": "base very high"},
	"2 Shaper Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Ambusher": {"baseexact": "Ambusher", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Blunt Arrow Quiver": {"baseexact": "Blunt Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Broadhead Arrow Quiver": {"baseexact": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Colossal Tower Shield": {"baseexact": "Colossal Tower Shield", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Copper Kris": {"baseexact": "Copper Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Amulet": {"baseexact": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Ring": {"baseexact": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Gold Amulet": {"baseexact": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Grove Bow": {"baseexact": "Grove Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Hubris Circlet": {"baseexact": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Imperial Bow": {"baseexact": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Imperial Buckler": {"baseexact": "Imperial Buckler", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Leather Belt": {"baseexact": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lion Pelt": {"baseexact": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Moon Staff": {"baseexact": "Moon Staff", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Opal Ring": {"baseexact": "Opal Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Opal Sceptre": {"baseexact": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Opal Wand": {"baseexact": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Paua Amulet": {"baseexact": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Penetrating Arrow Quiver": {"baseexact": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Platinum Kris": {"baseexact": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Profane Wand": {"baseexact": "Profane Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Royal Bow": {"baseexact": "Royal Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Serrated Arrow Quiver": {"baseexact": "Serrated Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sharktooth Arrow Quiver": {"baseexact": "Sharktooth Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sorcerer Boots": {"baseexact": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Spike-Point Arrow Quiver": {"baseexact": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Stag Sceptre": {"baseexact": "Stag Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Steel Ring": {"baseexact": "Steel Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Thicket Bow": {"baseexact": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Titanium Spirit Shield": {"baseexact": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Vaal Mask": {"baseexact": "Vaal Mask", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Vaal Regalia": {"baseexact": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Void Sceptre": {"baseexact": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Astral Plate": {"baseexact": "Astral Plate", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Convoking Wand": {"baseexact": "Convoking Wand", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Coral Ring": {"baseexact": "Coral Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Death Bow": {"baseexact": "Death Bow", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Fleshripper": {"baseexact": "Fleshripper", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Full Dragonscale": {"baseexact": "Full Dragonscale", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Leather Belt": {"baseexact": "Leather Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Nubuck Gloves": {"baseexact": "Nubuck Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Opal Ring": {"baseexact": "Opal Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Pernarch": {"baseexact": "Pernarch", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Satin Gloves": {"baseexact": "Satin Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Slink Gloves": {"baseexact": "Slink Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Steel Ring": {"baseexact": "Steel Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Titan Gauntlets": {"baseexact": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Unset Ring": {"baseexact": "Unset Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Vaal Axe": {"baseexact": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Searching Eye Jewel": {"baseexact": "Searching Eye Jewel", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ItemLevel 84"], "type": "base very high"},
	"2 Steel Ring": {"baseexact": "Steel Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"3 Shaper Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Broadhead Arrow Quiver": {"baseexact": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Cerulean Ring": {"baseexact": "Cerulean Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Colossal Tower Shield": {"baseexact": "Colossal Tower Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Coral Ring": {"baseexact": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Grove Bow": {"baseexact": "Grove Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Harmonic Spirit Shield": {"baseexact": "Harmonic Spirit Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Hubris Circlet": {"baseexact": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Imperial Bow": {"baseexact": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Moon Staff": {"baseexact": "Moon Staff", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Opal Ring": {"baseexact": "Opal Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Opal Wand": {"baseexact": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Penetrating Arrow Quiver": {"baseexact": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Royal Bow": {"baseexact": "Royal Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Spike-Point Arrow Quiver": {"baseexact": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Steel Ring": {"baseexact": "Steel Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Thicket Bow": {"baseexact": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Titanium Spirit Shield": {"baseexact": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Vaal Mask": {"baseexact": "Vaal Mask", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Void Sceptre": {"baseexact": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Astral Plate": {"baseexact": "Astral Plate", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Cerulean Ring": {"baseexact": "Cerulean Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Coral Ring": {"baseexact": "Coral Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Ezomyte Staff": {"baseexact": "Ezomyte Staff", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Fleshripper": {"baseexact": "Fleshripper", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Heathen Wand": {"baseexact": "Heathen Wand", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jewelled Foil": {"baseexact": "Jewelled Foil", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Opal Ring": {"baseexact": "Opal Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Royal Burgonet": {"baseexact": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Steel Ring": {"baseexact": "Steel Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Vaal Axe": {"baseexact": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Vanguard Belt": {"baseexact": "Vanguard Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"4 Shaper Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Blue Pearl Amulet": {"baseexact": "Blue Pearl Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Broadhead Arrow Quiver": {"baseexact": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Burnished Foil": {"baseexact": "Burnished Foil", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Cerulean Ring": {"baseexact": "Cerulean Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Coral Ring": {"baseexact": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Eclipse Staff": {"baseexact": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Imperial Bow": {"baseexact": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Jade Amulet": {"baseexact": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Opal Ring": {"baseexact": "Opal Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Penetrating Arrow Quiver": {"baseexact": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Ruby Ring": {"baseexact": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Serrated Arrow Quiver": {"baseexact": "Serrated Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sharktooth Arrow Quiver": {"baseexact": "Sharktooth Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Spike-Point Arrow Quiver": {"baseexact": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Steel Ring": {"baseexact": "Steel Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Thicket Bow": {"baseexact": "Thicket Bow", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Titanium Spirit Shield": {"baseexact": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Topaz Ring": {"baseexact": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Point Arrow Quiver": {"baseexact": "Two-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Agate Amulet": {"baseexact": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Amber Amulet": {"baseexact": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Astral Plate": {"baseexact": "Astral Plate", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Bone Helmet": {"baseexact": "Bone Helmet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Cerulean Ring": {"baseexact": "Cerulean Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Citrine Amulet": {"baseexact": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Crystal Belt": {"baseexact": "Crystal Belt", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Dagger Axe": {"baseexact": "Dagger Axe", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Deerskin Gloves": {"baseexact": "Deerskin Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Diamond Ring": {"baseexact": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Exquisite Blade": {"baseexact": "Exquisite Blade", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Fingerless Silk Gloves": {"baseexact": "Fingerless Silk Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Gripped Gloves": {"baseexact": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Lapis Amulet": {"baseexact": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Marble Amulet": {"baseexact": "Marble Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Mesh Gloves": {"baseexact": "Mesh Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Onyx Amulet": {"baseexact": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Opal Ring": {"baseexact": "Opal Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Prismatic Ring": {"baseexact": "Prismatic Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Sapphire Ring": {"baseexact": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Sorcerer Gloves": {"baseexact": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Spiked Gloves": {"baseexact": "Spiked Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Steel Ring": {"baseexact": "Steel Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Turquoise Amulet": {"baseexact": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Two-Stone Ring": {"baseexact": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Two-Toned Boots": {"baseexact": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Vaal Axe": {"baseexact": "Vaal Axe", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Elder Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Vermillion Ring": {"baseexact": "Vermillion Ring", "other": ["ItemLevel 82"], "type": "base very high"},

}
