#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/28/2020(m/d/y) 00:57:02 UTC from "tmpstandard" data

desc = "Currency Autogen"

# Base type : settings pair
items = {
	"000 Scroll Fragment": {"baseexact": "Scroll Fragment", "class": "Currency", "type": "hide"},
	"1 Aberrant Fossil": {"baseexact": "Aberrant Fossil", "class": "Currency", "type": "currency high"},
	"09 Aberrant Fossil": {"baseexact": "Aberrant Fossil", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency very high"},
	"1 Abrasive Catalyst": {"baseexact": "Abrasive Catalyst", "class": "Currency", "type": "currency normal"},
	"1 Aetheric Fossil": {"baseexact": "Aetheric Fossil", "class": "Currency", "type": "currency high"},
	"09 Aetheric Fossil": {"baseexact": "Aetheric Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Alchemy Shard": {"baseexact": "Alchemy Shard", "class": "Currency", "type": "currency show"},
	"09 Alchemy Shard": {"baseexact": "Alchemy Shard", 'other': ['StackSize >= 8'], "class": "Currency", "type": "currency normal"},
	"1 Alteration Shard": {"baseexact": "Alteration Shard", "class": "Currency", "type": "currency show"},
	"1 Ancient Orb": {"baseexact": "Ancient Orb", "class": "Currency", "type": "currency very high"},
	"09 Ancient Orb": {"baseexact": "Ancient Orb", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency extremely high"},
	"1 Ancient Shard": {"baseexact": "Ancient Shard", "class": "Currency", "type": "currency high"},
	"09 Ancient Shard": {"baseexact": "Ancient Shard", 'other': ['StackSize >= 11'], "class": "Currency", "type": "currency very high"},
	"1 Annulment Shard": {"baseexact": "Annulment Shard", "class": "Currency", "type": "currency normal"},
	"09 Annulment Shard": {"baseexact": "Annulment Shard", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Armourer's Scrap": {"baseexact": "Armourer's Scrap", "class": "Currency", "type": "currency show"},
	"09 Armourer's Scrap": {"baseexact": "Armourer's Scrap", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Armourer's Scrap": {"baseexact": "Armourer's Scrap", 'other': ['StackSize >= 17'], "class": "Currency", "type": "currency high"},
	"1 Awakened Sextant": {"baseexact": "Awakened Sextant", "class": "Currency", "type": "currency high"},
	"09 Awakened Sextant": {"baseexact": "Awakened Sextant", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Awakener's Orb": {"baseexact": "Awakener's Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Binding Shard": {"baseexact": "Binding Shard", "class": "Currency", "type": "currency show"},
	"09 Binding Shard": {"baseexact": "Binding Shard", 'other': ['StackSize >= 12'], "class": "Currency", "type": "currency normal"},
	"1 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", "class": "Currency", "type": "currency show"},
	"09 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", 'other': ['StackSize >= 20'], "class": "Currency", "type": "currency high"},
	"1 Blessed Orb": {"baseexact": "Blessed Orb", "class": "Currency", "type": "currency show"},
	"09 Blessed Orb": {"baseexact": "Blessed Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Blessed Orb": {"baseexact": "Blessed Orb", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"1 Blessing of Chayula": {"baseexact": "Blessing of Chayula", "class": "Currency", "type": "currency very high"},
	"1 Blessing of Esh": {"baseexact": "Blessing of Esh", "class": "Currency", "type": "currency high"},
	"1 Blessing of Tul": {"baseexact": "Blessing of Tul", "class": "Currency", "type": "currency high"},
	"1 Blessing of Uul-Netol": {"baseexact": "Blessing of Uul-Netol", "class": "Currency", "type": "currency high"},
	"1 Blessing of Xoph": {"baseexact": "Blessing of Xoph", "class": "Currency", "type": "currency high"},
	"1 Bloodstained Fossil": {"baseexact": "Bloodstained Fossil", "class": "Currency", "type": "currency high"},
	"09 Bloodstained Fossil": {"baseexact": "Bloodstained Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Bloodstained Fossil": {"baseexact": "Bloodstained Fossil", 'other': ['StackSize >= 14'], "class": "Currency", "type": "currency extremely high"},
	"1 Bound Fossil": {"baseexact": "Bound Fossil", "class": "Currency", "type": "currency high"},
	"09 Bound Fossil": {"baseexact": "Bound Fossil", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Cartographer's Chisel": {"baseexact": "Cartographer's Chisel", "class": "Currency", "type": "currency normal"},
	"09 Cartographer's Chisel": {"baseexact": "Cartographer's Chisel", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Chaos Orb": {"baseexact": "Chaos Orb", "class": "Currency", "type": "currency high"},
	"1 Chaos Shard": {"baseexact": "Chaos Shard", "class": "Currency", "type": "currency show"},
	"09 Chaos Shard": {"baseexact": "Chaos Shard", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Chaos Shard": {"baseexact": "Chaos Shard", 'other': ['StackSize >= 20'], "class": "Currency", "type": "currency high"},
	"1 Chromatic Orb": {"baseexact": "Chromatic Orb", "class": "Currency", "type": "currency show"},
	"09 Chromatic Orb": {"baseexact": "Chromatic Orb", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Chromatic Orb": {"baseexact": "Chromatic Orb", 'other': ['StackSize >= 20'], "class": "Currency", "type": "currency high"},
	"1 Corroded Fossil": {"baseexact": "Corroded Fossil", "class": "Currency", "type": "currency very high"},
	"09 Corroded Fossil": {"baseexact": "Corroded Fossil", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency extremely high"},
	"1 Crusader's Exalted Orb": {"baseexact": "Crusader's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Deafening Essence of Anger": {"baseexact": "Deafening Essence of Anger", "class": "Currency", "type": "currency very high"},
	"09 Deafening Essence of Anger": {"baseexact": "Deafening Essence of Anger", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency extremely high"},
	"1 Deafening Essence of Anguish": {"baseexact": "Deafening Essence of Anguish", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Anguish": {"baseexact": "Deafening Essence of Anguish", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Contempt": {"baseexact": "Deafening Essence of Contempt", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Contempt": {"baseexact": "Deafening Essence of Contempt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Doubt": {"baseexact": "Deafening Essence of Doubt", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Doubt": {"baseexact": "Deafening Essence of Doubt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Dread": {"baseexact": "Deafening Essence of Dread", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Dread": {"baseexact": "Deafening Essence of Dread", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Envy": {"baseexact": "Deafening Essence of Envy", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Envy": {"baseexact": "Deafening Essence of Envy", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Fear": {"baseexact": "Deafening Essence of Fear", "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Greed": {"baseexact": "Deafening Essence of Greed", "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Hatred": {"baseexact": "Deafening Essence of Hatred", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Hatred": {"baseexact": "Deafening Essence of Hatred", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Loathing": {"baseexact": "Deafening Essence of Loathing", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Loathing": {"baseexact": "Deafening Essence of Loathing", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Misery": {"baseexact": "Deafening Essence of Misery", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Misery": {"baseexact": "Deafening Essence of Misery", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Rage": {"baseexact": "Deafening Essence of Rage", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Rage": {"baseexact": "Deafening Essence of Rage", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Scorn": {"baseexact": "Deafening Essence of Scorn", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Scorn": {"baseexact": "Deafening Essence of Scorn", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Sorrow": {"baseexact": "Deafening Essence of Sorrow", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Sorrow": {"baseexact": "Deafening Essence of Sorrow", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Spite": {"baseexact": "Deafening Essence of Spite", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Spite": {"baseexact": "Deafening Essence of Spite", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Suffering": {"baseexact": "Deafening Essence of Suffering", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Suffering": {"baseexact": "Deafening Essence of Suffering", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Torment": {"baseexact": "Deafening Essence of Torment", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Torment": {"baseexact": "Deafening Essence of Torment", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Woe": {"baseexact": "Deafening Essence of Woe", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Woe": {"baseexact": "Deafening Essence of Woe", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Wrath": {"baseexact": "Deafening Essence of Wrath", "class": "Currency", "type": "currency high"},
	"09 Deafening Essence of Wrath": {"baseexact": "Deafening Essence of Wrath", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Deafening Essence of Zeal": {"baseexact": "Deafening Essence of Zeal", "class": "Currency", "type": "currency very high"},
	"1 Dense Fossil": {"baseexact": "Dense Fossil", "class": "Currency", "type": "currency high"},
	"09 Dense Fossil": {"baseexact": "Dense Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Divine Orb": {"baseexact": "Divine Orb", "class": "Currency", "type": "currency high"},
	"09 Divine Orb": {"baseexact": "Divine Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Enchanted Fossil": {"baseexact": "Enchanted Fossil", "class": "Currency", "type": "currency high"},
	"09 Enchanted Fossil": {"baseexact": "Enchanted Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Enchanted Fossil": {"baseexact": "Enchanted Fossil", 'other': ['StackSize >= 15'], "class": "Currency", "type": "currency extremely high"},
	"1 Encrusted Fossil": {"baseexact": "Encrusted Fossil", "class": "Currency", "type": "currency high"},
	"09 Encrusted Fossil": {"baseexact": "Encrusted Fossil", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Engineer's Orb": {"baseexact": "Engineer's Orb", "class": "Currency", "type": "currency show"},
	"09 Engineer's Orb": {"baseexact": "Engineer's Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Engineer's Orb": {"baseexact": "Engineer's Orb", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"1 Engineer's Shard": {"baseexact": "Engineer's Shard", "class": "Currency", "type": "currency show"},
	"1 Essence of Delirium": {"baseexact": "Essence of Delirium", "class": "Currency", "type": "currency high"},
	"09 Essence of Delirium": {"baseexact": "Essence of Delirium", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Essence of Horror": {"baseexact": "Essence of Horror", "class": "Currency", "type": "currency high"},
	"09 Essence of Horror": {"baseexact": "Essence of Horror", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Essence of Hysteria": {"baseexact": "Essence of Hysteria", "class": "Currency", "type": "currency high"},
	"09 Essence of Hysteria": {"baseexact": "Essence of Hysteria", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Essence of Insanity": {"baseexact": "Essence of Insanity", "class": "Currency", "type": "currency very high"},
	"1 Exalted Orb": {"baseexact": "Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Exalted Shard": {"baseexact": "Exalted Shard", "class": "Currency", "type": "currency high"},
	"09 Exalted Shard": {"baseexact": "Exalted Shard", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Faceted Fossil": {"baseexact": "Faceted Fossil", "class": "Currency", "type": "currency very high"},
	"09 Faceted Fossil": {"baseexact": "Faceted Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency extremely high"},
	"1 Fertile Catalyst": {"baseexact": "Fertile Catalyst", "class": "Currency", "type": "currency high"},
	"1 Fractured Fossil": {"baseexact": "Fractured Fossil", "class": "Currency", "type": "currency extremely high"},
	"1 Frigid Fossil": {"baseexact": "Frigid Fossil", "class": "Currency", "type": "currency high"},
	"09 Frigid Fossil": {"baseexact": "Frigid Fossil", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency very high"},
	"1 Gemcutter's Prism": {"baseexact": "Gemcutter's Prism", "class": "Currency", "type": "currency high"},
	"1 Gilded Fossil": {"baseexact": "Gilded Fossil", "class": "Currency", "type": "currency high"},
	"09 Gilded Fossil": {"baseexact": "Gilded Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Glassblower's Bauble": {"baseexact": "Glassblower's Bauble", "class": "Currency", "type": "currency normal"},
	"09 Glassblower's Bauble": {"baseexact": "Glassblower's Bauble", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"1 Glyphic Fossil": {"baseexact": "Glyphic Fossil", "class": "Currency", "type": "currency very high"},
	"09 Glyphic Fossil": {"baseexact": "Glyphic Fossil", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency extremely high"},
	"1 Harbinger's Orb": {"baseexact": "Harbinger's Orb", "class": "Currency", "type": "currency high"},
	"09 Harbinger's Orb": {"baseexact": "Harbinger's Orb", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Harbinger's Shard": {"baseexact": "Harbinger's Shard", "class": "Currency", "type": "currency normal"},
	"09 Harbinger's Shard": {"baseexact": "Harbinger's Shard", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Hollow Fossil": {"baseexact": "Hollow Fossil", "class": "Currency", "type": "currency very high"},
	"09 Hollow Fossil": {"baseexact": "Hollow Fossil", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency extremely high"},
	"1 Horizon Shard": {"baseexact": "Horizon Shard", "class": "Currency", "type": "currency show"},
	"09 Horizon Shard": {"baseexact": "Horizon Shard", 'other': ['StackSize >= 12'], "class": "Currency", "type": "currency normal"},
	"1 Hunter's Exalted Orb": {"baseexact": "Hunter's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Imbued Catalyst": {"baseexact": "Imbued Catalyst", "class": "Currency", "type": "currency normal"},
	"1 Intrinsic Catalyst": {"baseexact": "Intrinsic Catalyst", "class": "Currency", "type": "currency normal"},
	"1 Jagged Fossil": {"baseexact": "Jagged Fossil", "class": "Currency", "type": "currency high"},
	"09 Jagged Fossil": {"baseexact": "Jagged Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Jeweller's Orb": {"baseexact": "Jeweller's Orb", "class": "Currency", "type": "currency very low"},
	"09 Jeweller's Orb": {"baseexact": "Jeweller's Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency low"},
	"08 Jeweller's Orb": {"baseexact": "Jeweller's Orb", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"07 Jeweller's Orb": {"baseexact": "Jeweller's Orb", 'other': ['StackSize >= 12'], "class": "Currency", "type": "currency high"},
	"1 Lucent Fossil": {"baseexact": "Lucent Fossil", "class": "Currency", "type": "currency high"},
	"09 Lucent Fossil": {"baseexact": "Lucent Fossil", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Metallic Fossil": {"baseexact": "Metallic Fossil", "class": "Currency", "type": "currency high"},
	"09 Metallic Fossil": {"baseexact": "Metallic Fossil", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency very high"},
	"1 Mirror Shard": {"baseexact": "Mirror Shard", "class": "Currency", "type": "currency mirror"},
	"1 Mirror of Kalandra": {"baseexact": "Mirror of Kalandra", "class": "Currency", "type": "currency mirror"},
	"1 Muttering Essence of Anger": {"baseexact": "Muttering Essence of Anger", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Anger": {"baseexact": "Muttering Essence of Anger", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Anger": {"baseexact": "Muttering Essence of Anger", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Anger": {"baseexact": "Muttering Essence of Anger", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Anger": {"baseexact": "Muttering Essence of Anger", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Contempt": {"baseexact": "Muttering Essence of Contempt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Contempt": {"baseexact": "Muttering Essence of Contempt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Contempt": {"baseexact": "Muttering Essence of Contempt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Contempt": {"baseexact": "Muttering Essence of Contempt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Contempt": {"baseexact": "Muttering Essence of Contempt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Fear": {"baseexact": "Muttering Essence of Fear", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Fear": {"baseexact": "Muttering Essence of Fear", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Fear": {"baseexact": "Muttering Essence of Fear", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Fear": {"baseexact": "Muttering Essence of Fear", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Fear": {"baseexact": "Muttering Essence of Fear", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Greed": {"baseexact": "Muttering Essence of Greed", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Greed": {"baseexact": "Muttering Essence of Greed", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Greed": {"baseexact": "Muttering Essence of Greed", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Greed": {"baseexact": "Muttering Essence of Greed", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Greed": {"baseexact": "Muttering Essence of Greed", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Hatred": {"baseexact": "Muttering Essence of Hatred", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Hatred": {"baseexact": "Muttering Essence of Hatred", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Hatred": {"baseexact": "Muttering Essence of Hatred", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Hatred": {"baseexact": "Muttering Essence of Hatred", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Hatred": {"baseexact": "Muttering Essence of Hatred", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Sorrow": {"baseexact": "Muttering Essence of Sorrow", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Sorrow": {"baseexact": "Muttering Essence of Sorrow", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Sorrow": {"baseexact": "Muttering Essence of Sorrow", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Sorrow": {"baseexact": "Muttering Essence of Sorrow", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Sorrow": {"baseexact": "Muttering Essence of Sorrow", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Torment": {"baseexact": "Muttering Essence of Torment", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Torment": {"baseexact": "Muttering Essence of Torment", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Torment": {"baseexact": "Muttering Essence of Torment", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Torment": {"baseexact": "Muttering Essence of Torment", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Torment": {"baseexact": "Muttering Essence of Torment", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Muttering Essence of Woe": {"baseexact": "Muttering Essence of Woe", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Muttering Essence of Woe": {"baseexact": "Muttering Essence of Woe", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Muttering Essence of Woe": {"baseexact": "Muttering Essence of Woe", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Muttering Essence of Woe": {"baseexact": "Muttering Essence of Woe", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Muttering Essence of Woe": {"baseexact": "Muttering Essence of Woe", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Orb of Alchemy": {"baseexact": "Orb of Alchemy", "class": "Currency", "type": "currency normal"},
	"09 Orb of Alchemy": {"baseexact": "Orb of Alchemy", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Orb of Alteration": {"baseexact": "Orb of Alteration", "class": "Currency", "type": "currency show"},
	"09 Orb of Alteration": {"baseexact": "Orb of Alteration", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Alteration": {"baseexact": "Orb of Alteration", 'other': ['StackSize >= 13'], "class": "Currency", "type": "currency high"},
	"1 Orb of Annulment": {"baseexact": "Orb of Annulment", "class": "Currency", "type": "currency high"},
	"09 Orb of Annulment": {"baseexact": "Orb of Annulment", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Orb of Augmentation": {"baseexact": "Orb of Augmentation", "class": "Currency", "type": "currency show"},
	"09 Orb of Augmentation": {"baseexact": "Orb of Augmentation", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Augmentation": {"baseexact": "Orb of Augmentation", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency high"},
	"1 Orb of Binding": {"baseexact": "Orb of Binding", "class": "Currency", "type": "currency normal"},
	"09 Orb of Binding": {"baseexact": "Orb of Binding", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Chance": {"baseexact": "Orb of Chance", "class": "Currency", "type": "currency show"},
	"09 Orb of Chance": {"baseexact": "Orb of Chance", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Chance": {"baseexact": "Orb of Chance", 'other': ['StackSize >= 12'], "class": "Currency", "type": "currency high"},
	"1 Orb of Fusing": {"baseexact": "Orb of Fusing", "class": "Currency", "type": "currency normal"},
	"09 Orb of Fusing": {"baseexact": "Orb of Fusing", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Horizons": {"baseexact": "Orb of Horizons", "class": "Currency", "type": "currency normal"},
	"09 Orb of Horizons": {"baseexact": "Orb of Horizons", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Regret": {"baseexact": "Orb of Regret", "class": "Currency", "type": "currency normal"},
	"09 Orb of Regret": {"baseexact": "Orb of Regret", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Orb of Regret": {"baseexact": "Orb of Regret", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency very high"},
	"1 Orb of Scouring": {"baseexact": "Orb of Scouring", "class": "Currency", "type": "currency normal"},
	"09 Orb of Scouring": {"baseexact": "Orb of Scouring", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Transmutation": {"baseexact": "Orb of Transmutation", "class": "Currency", "type": "currency show"},
	"09 Orb of Transmutation": {"baseexact": "Orb of Transmutation", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Transmutation": {"baseexact": "Orb of Transmutation", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency high"},
	"1 Perandus Coin": {"baseexact": "Perandus Coin", "class": "Currency", "type": "currency show"},
	"09 Perandus Coin": {"baseexact": "Perandus Coin", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency normal"},
	"08 Perandus Coin": {"baseexact": "Perandus Coin", 'other': ['StackSize >= 100'], "class": "Currency", "type": "currency high"},
	"1 Perfect Fossil": {"baseexact": "Perfect Fossil", "class": "Currency", "type": "currency high"},
	"09 Perfect Fossil": {"baseexact": "Perfect Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Perfect Fossil": {"baseexact": "Perfect Fossil", 'other': ['StackSize >= 16'], "class": "Currency", "type": "currency extremely high"},
	"1 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency low"},
	"07 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency normal"},
	"06 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency high"},
	"1 Potent Alchemical Resonator": {"baseexact": "Potent Alchemical Resonator", "class": "Currency", "type": "currency normal"},
	"09 Potent Alchemical Resonator": {"baseexact": "Potent Alchemical Resonator", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Potent Chaotic Resonator": {"baseexact": "Potent Chaotic Resonator", "class": "Currency", "type": "currency high"},
	"1 Powerful Alchemical Resonator": {"baseexact": "Powerful Alchemical Resonator", "class": "Currency", "type": "currency normal"},
	"09 Powerful Alchemical Resonator": {"baseexact": "Powerful Alchemical Resonator", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Powerful Chaotic Resonator": {"baseexact": "Powerful Chaotic Resonator", "class": "Currency", "type": "currency high"},
	"1 Prime Alchemical Resonator": {"baseexact": "Prime Alchemical Resonator", "class": "Currency", "type": "currency very high"},
	"09 Prime Alchemical Resonator": {"baseexact": "Prime Alchemical Resonator", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency extremely high"},
	"1 Prime Chaotic Resonator": {"baseexact": "Prime Chaotic Resonator", "class": "Currency", "type": "currency very high"},
	"09 Prime Chaotic Resonator": {"baseexact": "Prime Chaotic Resonator", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency extremely high"},
	"1 Prime Sextant": {"baseexact": "Prime Sextant", "class": "Currency", "type": "currency high"},
	"1 Primitive Alchemical Resonator": {"baseexact": "Primitive Alchemical Resonator", "class": "Currency", "type": "currency normal"},
	"09 Primitive Alchemical Resonator": {"baseexact": "Primitive Alchemical Resonator", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Primitive Chaotic Resonator": {"baseexact": "Primitive Chaotic Resonator", "class": "Currency", "type": "currency high"},
	"1 Prismatic Catalyst": {"baseexact": "Prismatic Catalyst", "class": "Currency", "type": "currency high"},
	"1 Prismatic Fossil": {"baseexact": "Prismatic Fossil", "class": "Currency", "type": "currency high"},
	"09 Prismatic Fossil": {"baseexact": "Prismatic Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Pristine Fossil": {"baseexact": "Pristine Fossil", "class": "Currency", "type": "currency high"},
	"09 Pristine Fossil": {"baseexact": "Pristine Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Redeemer's Exalted Orb": {"baseexact": "Redeemer's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Regal Orb": {"baseexact": "Regal Orb", "class": "Currency", "type": "currency high"},
	"1 Regal Shard": {"baseexact": "Regal Shard", "class": "Currency", "type": "currency show"},
	"09 Regal Shard": {"baseexact": "Regal Shard", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Regal Shard": {"baseexact": "Regal Shard", 'other': ['StackSize >= 19'], "class": "Currency", "type": "currency high"},
	"1 Remnant of Corruption": {"baseexact": "Remnant of Corruption", "class": "Currency", "type": "currency high"},
	"1 Sanctified Fossil": {"baseexact": "Sanctified Fossil", "class": "Currency", "type": "currency high"},
	"09 Sanctified Fossil": {"baseexact": "Sanctified Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Sanctified Fossil": {"baseexact": "Sanctified Fossil", 'other': ['StackSize >= 15'], "class": "Currency", "type": "currency extremely high"},
	"1 Scorched Fossil": {"baseexact": "Scorched Fossil", "class": "Currency", "type": "currency high"},
	"09 Scorched Fossil": {"baseexact": "Scorched Fossil", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency very high"},
	"1 Screaming Essence of Anger": {"baseexact": "Screaming Essence of Anger", "class": "Currency", "type": "currency high"},
	"09 Screaming Essence of Anger": {"baseexact": "Screaming Essence of Anger", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Screaming Essence of Anguish": {"baseexact": "Screaming Essence of Anguish", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Contempt": {"baseexact": "Screaming Essence of Contempt", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Doubt": {"baseexact": "Screaming Essence of Doubt", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Dread": {"baseexact": "Screaming Essence of Dread", "class": "Currency", "type": "currency high"},
	"09 Screaming Essence of Dread": {"baseexact": "Screaming Essence of Dread", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Screaming Essence of Envy": {"baseexact": "Screaming Essence of Envy", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Fear": {"baseexact": "Screaming Essence of Fear", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Greed": {"baseexact": "Screaming Essence of Greed", "class": "Currency", "type": "currency high"},
	"09 Screaming Essence of Greed": {"baseexact": "Screaming Essence of Greed", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Screaming Essence of Hatred": {"baseexact": "Screaming Essence of Hatred", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Loathing": {"baseexact": "Screaming Essence of Loathing", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Misery": {"baseexact": "Screaming Essence of Misery", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Rage": {"baseexact": "Screaming Essence of Rage", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Scorn": {"baseexact": "Screaming Essence of Scorn", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Sorrow": {"baseexact": "Screaming Essence of Sorrow", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Spite": {"baseexact": "Screaming Essence of Spite", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Suffering": {"baseexact": "Screaming Essence of Suffering", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Torment": {"baseexact": "Screaming Essence of Torment", "class": "Currency", "type": "currency normal"},
	"09 Screaming Essence of Torment": {"baseexact": "Screaming Essence of Torment", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Woe": {"baseexact": "Screaming Essence of Woe", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Wrath": {"baseexact": "Screaming Essence of Wrath", "class": "Currency", "type": "currency high"},
	"1 Screaming Essence of Zeal": {"baseexact": "Screaming Essence of Zeal", "class": "Currency", "type": "currency high"},
	"1 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency very low"},
	"08 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['StackSize >= 13'], "class": "Currency", "type": "currency low"},
	"07 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency normal"},
	"1 Serrated Fossil": {"baseexact": "Serrated Fossil", "class": "Currency", "type": "currency high"},
	"09 Serrated Fossil": {"baseexact": "Serrated Fossil", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Anger": {"baseexact": "Shrieking Essence of Anger", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Anger": {"baseexact": "Shrieking Essence of Anger", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Anguish": {"baseexact": "Shrieking Essence of Anguish", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Anguish": {"baseexact": "Shrieking Essence of Anguish", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Contempt": {"baseexact": "Shrieking Essence of Contempt", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Contempt": {"baseexact": "Shrieking Essence of Contempt", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Doubt": {"baseexact": "Shrieking Essence of Doubt", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Doubt": {"baseexact": "Shrieking Essence of Doubt", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Dread": {"baseexact": "Shrieking Essence of Dread", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Dread": {"baseexact": "Shrieking Essence of Dread", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Envy": {"baseexact": "Shrieking Essence of Envy", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Envy": {"baseexact": "Shrieking Essence of Envy", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Fear": {"baseexact": "Shrieking Essence of Fear", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Fear": {"baseexact": "Shrieking Essence of Fear", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Greed": {"baseexact": "Shrieking Essence of Greed", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Greed": {"baseexact": "Shrieking Essence of Greed", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Hatred": {"baseexact": "Shrieking Essence of Hatred", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Hatred": {"baseexact": "Shrieking Essence of Hatred", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Loathing": {"baseexact": "Shrieking Essence of Loathing", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Loathing": {"baseexact": "Shrieking Essence of Loathing", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Misery": {"baseexact": "Shrieking Essence of Misery", "class": "Currency", "type": "currency high"},
	"1 Shrieking Essence of Rage": {"baseexact": "Shrieking Essence of Rage", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Rage": {"baseexact": "Shrieking Essence of Rage", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Scorn": {"baseexact": "Shrieking Essence of Scorn", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Scorn": {"baseexact": "Shrieking Essence of Scorn", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Sorrow": {"baseexact": "Shrieking Essence of Sorrow", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Sorrow": {"baseexact": "Shrieking Essence of Sorrow", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Spite": {"baseexact": "Shrieking Essence of Spite", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Spite": {"baseexact": "Shrieking Essence of Spite", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Suffering": {"baseexact": "Shrieking Essence of Suffering", "class": "Currency", "type": "currency high"},
	"1 Shrieking Essence of Torment": {"baseexact": "Shrieking Essence of Torment", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Torment": {"baseexact": "Shrieking Essence of Torment", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Woe": {"baseexact": "Shrieking Essence of Woe", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Woe": {"baseexact": "Shrieking Essence of Woe", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Wrath": {"baseexact": "Shrieking Essence of Wrath", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Wrath": {"baseexact": "Shrieking Essence of Wrath", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency very high"},
	"1 Shrieking Essence of Zeal": {"baseexact": "Shrieking Essence of Zeal", "class": "Currency", "type": "currency high"},
	"09 Shrieking Essence of Zeal": {"baseexact": "Shrieking Essence of Zeal", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency very high"},
	"1 Shuddering Fossil": {"baseexact": "Shuddering Fossil", "class": "Currency", "type": "currency high"},
	"09 Shuddering Fossil": {"baseexact": "Shuddering Fossil", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Shuddering Fossil": {"baseexact": "Shuddering Fossil", 'other': ['StackSize >= 19'], "class": "Currency", "type": "currency extremely high"},
	"1 Silver Coin": {"baseexact": "Silver Coin", "class": "Currency", "type": "currency show"},
	"09 Silver Coin": {"baseexact": "Silver Coin", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Silver Coin": {"baseexact": "Silver Coin", 'other': ['StackSize >= 9'], "class": "Currency", "type": "currency high"},
	"1 Simple Sextant": {"baseexact": "Simple Sextant", "class": "Currency", "type": "currency high"},
	"1 Simulacrum Splinter": {"baseexact": "Simulacrum Splinter", "class": "Currency", "type": "currency high"},
	"09 Simulacrum Splinter": {"baseexact": "Simulacrum Splinter", 'other': ['StackSize >= 16'], "class": "Currency", "type": "currency very high"},
	"1 Splinter of Chayula": {"baseexact": "Splinter of Chayula", "class": "Currency", "type": "currency high"},
	"09 Splinter of Chayula": {"baseexact": "Splinter of Chayula", 'other': ['StackSize >= 8'], "class": "Currency", "type": "currency very high"},
	"08 Splinter of Chayula": {"baseexact": "Splinter of Chayula", 'other': ['StackSize >= 76'], "class": "Currency", "type": "currency extremely high"},
	"1 Splinter of Esh": {"baseexact": "Splinter of Esh", "class": "Currency", "type": "currency show"},
	"09 Splinter of Esh": {"baseexact": "Splinter of Esh", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Esh": {"baseexact": "Splinter of Esh", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency high"},
	"1 Splinter of Tul": {"baseexact": "Splinter of Tul", "class": "Currency", "type": "currency show"},
	"09 Splinter of Tul": {"baseexact": "Splinter of Tul", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Tul": {"baseexact": "Splinter of Tul", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency high"},
	"07 Splinter of Tul": {"baseexact": "Splinter of Tul", 'other': ['StackSize >= 95'], "class": "Currency", "type": "currency very high"},
	"1 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", "class": "Currency", "type": "currency normal"},
	"09 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"08 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", 'other': ['StackSize >= 60'], "class": "Currency", "type": "currency very high"},
	"1 Splinter of Xoph": {"baseexact": "Splinter of Xoph", "class": "Currency", "type": "currency show"},
	"09 Splinter of Xoph": {"baseexact": "Splinter of Xoph", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Xoph": {"baseexact": "Splinter of Xoph", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency high"},
	"1 Stacked Deck": {"baseexact": "Stacked Deck", "class": "Currency", "type": "currency high"},
	"1 Tangled Fossil": {"baseexact": "Tangled Fossil", "class": "Currency", "type": "currency high"},
	"09 Tangled Fossil": {"baseexact": "Tangled Fossil", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency very high"},
	"1 Tempering Catalyst": {"baseexact": "Tempering Catalyst", "class": "Currency", "type": "currency high"},
	"1 Timeless Eternal Empire Splinter": {"baseexact": "Timeless Eternal Empire Splinter", "class": "Currency", "type": "currency show"},
	"09 Timeless Eternal Empire Splinter": {"baseexact": "Timeless Eternal Empire Splinter", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Timeless Eternal Empire Splinter": {"baseexact": "Timeless Eternal Empire Splinter", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"07 Timeless Eternal Empire Splinter": {"baseexact": "Timeless Eternal Empire Splinter", 'other': ['StackSize >= 79'], "class": "Currency", "type": "currency very high"},
	"1 Timeless Karui Splinter": {"baseexact": "Timeless Karui Splinter", "class": "Currency", "type": "currency normal"},
	"09 Timeless Karui Splinter": {"baseexact": "Timeless Karui Splinter", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"08 Timeless Karui Splinter": {"baseexact": "Timeless Karui Splinter", 'other': ['StackSize >= 72'], "class": "Currency", "type": "currency very high"},
	"1 Timeless Maraketh Splinter": {"baseexact": "Timeless Maraketh Splinter", "class": "Currency", "type": "currency high"},
	"09 Timeless Maraketh Splinter": {"baseexact": "Timeless Maraketh Splinter", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency very high"},
	"1 Timeless Templar Splinter": {"baseexact": "Timeless Templar Splinter", "class": "Currency", "type": "currency normal"},
	"09 Timeless Templar Splinter": {"baseexact": "Timeless Templar Splinter", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Timeless Templar Splinter": {"baseexact": "Timeless Templar Splinter", 'other': ['StackSize >= 22'], "class": "Currency", "type": "currency very high"},
	"1 Timeless Vaal Splinter": {"baseexact": "Timeless Vaal Splinter", "class": "Currency", "type": "currency normal"},
	"09 Timeless Vaal Splinter": {"baseexact": "Timeless Vaal Splinter", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"08 Timeless Vaal Splinter": {"baseexact": "Timeless Vaal Splinter", 'other': ['StackSize >= 49'], "class": "Currency", "type": "currency very high"},
	"1 Transmutation Shard": {"baseexact": "Transmutation Shard", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Transmutation Shard": {"baseexact": "Transmutation Shard", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"1 Turbulent Catalyst": {"baseexact": "Turbulent Catalyst", "class": "Currency", "type": "currency high"},
	"1 Vaal Orb": {"baseexact": "Vaal Orb", "class": "Currency", "type": "currency normal"},
	"09 Vaal Orb": {"baseexact": "Vaal Orb", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Vial of Awakening": {"baseexact": "Vial of Awakening", "class": "Currency", "type": "currency very high"},
	"1 Vial of Consequence": {"baseexact": "Vial of Consequence", "class": "Currency", "type": "currency very high"},
	"1 Vial of Dominance": {"baseexact": "Vial of Dominance", "class": "Currency", "type": "currency very high"},
	"1 Vial of Fate": {"baseexact": "Vial of Fate", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Vial of Fate": {"baseexact": "Vial of Fate", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"1 Vial of Sacrifice": {"baseexact": "Vial of Sacrifice", "class": "Currency", "type": "currency very high"},
	"1 Vial of Summoning": {"baseexact": "Vial of Summoning", "class": "Currency", "type": "currency very high"},
	"1 Vial of Transcendence": {"baseexact": "Vial of Transcendence", "class": "Currency", "type": "currency very high"},
	"1 Vial of the Ghost": {"baseexact": "Vial of the Ghost", "class": "Currency", "type": "currency very high"},
	"1 Vial of the Ritual": {"baseexact": "Vial of the Ritual", "class": "Currency", "type": "currency very high"},
	"1 Wailing Essence of Anger": {"baseexact": "Wailing Essence of Anger", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Anger": {"baseexact": "Wailing Essence of Anger", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Anger": {"baseexact": "Wailing Essence of Anger", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Anger": {"baseexact": "Wailing Essence of Anger", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Anger": {"baseexact": "Wailing Essence of Anger", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Anguish": {"baseexact": "Wailing Essence of Anguish", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Anguish": {"baseexact": "Wailing Essence of Anguish", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Anguish": {"baseexact": "Wailing Essence of Anguish", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Anguish": {"baseexact": "Wailing Essence of Anguish", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Anguish": {"baseexact": "Wailing Essence of Anguish", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Contempt": {"baseexact": "Wailing Essence of Contempt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Contempt": {"baseexact": "Wailing Essence of Contempt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Contempt": {"baseexact": "Wailing Essence of Contempt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Contempt": {"baseexact": "Wailing Essence of Contempt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Contempt": {"baseexact": "Wailing Essence of Contempt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Doubt": {"baseexact": "Wailing Essence of Doubt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Doubt": {"baseexact": "Wailing Essence of Doubt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Doubt": {"baseexact": "Wailing Essence of Doubt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Doubt": {"baseexact": "Wailing Essence of Doubt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Doubt": {"baseexact": "Wailing Essence of Doubt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Fear": {"baseexact": "Wailing Essence of Fear", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Fear": {"baseexact": "Wailing Essence of Fear", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Fear": {"baseexact": "Wailing Essence of Fear", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Fear": {"baseexact": "Wailing Essence of Fear", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Fear": {"baseexact": "Wailing Essence of Fear", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Greed": {"baseexact": "Wailing Essence of Greed", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Greed": {"baseexact": "Wailing Essence of Greed", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Greed": {"baseexact": "Wailing Essence of Greed", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Greed": {"baseexact": "Wailing Essence of Greed", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Greed": {"baseexact": "Wailing Essence of Greed", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Hatred": {"baseexact": "Wailing Essence of Hatred", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Hatred": {"baseexact": "Wailing Essence of Hatred", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Hatred": {"baseexact": "Wailing Essence of Hatred", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Hatred": {"baseexact": "Wailing Essence of Hatred", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Hatred": {"baseexact": "Wailing Essence of Hatred", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Loathing": {"baseexact": "Wailing Essence of Loathing", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Loathing": {"baseexact": "Wailing Essence of Loathing", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Loathing": {"baseexact": "Wailing Essence of Loathing", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Loathing": {"baseexact": "Wailing Essence of Loathing", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Loathing": {"baseexact": "Wailing Essence of Loathing", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Rage": {"baseexact": "Wailing Essence of Rage", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Rage": {"baseexact": "Wailing Essence of Rage", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Rage": {"baseexact": "Wailing Essence of Rage", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Rage": {"baseexact": "Wailing Essence of Rage", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Rage": {"baseexact": "Wailing Essence of Rage", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Sorrow": {"baseexact": "Wailing Essence of Sorrow", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Sorrow": {"baseexact": "Wailing Essence of Sorrow", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Sorrow": {"baseexact": "Wailing Essence of Sorrow", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Sorrow": {"baseexact": "Wailing Essence of Sorrow", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Sorrow": {"baseexact": "Wailing Essence of Sorrow", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Spite": {"baseexact": "Wailing Essence of Spite", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Spite": {"baseexact": "Wailing Essence of Spite", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Spite": {"baseexact": "Wailing Essence of Spite", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Spite": {"baseexact": "Wailing Essence of Spite", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Spite": {"baseexact": "Wailing Essence of Spite", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Suffering": {"baseexact": "Wailing Essence of Suffering", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Suffering": {"baseexact": "Wailing Essence of Suffering", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Suffering": {"baseexact": "Wailing Essence of Suffering", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Suffering": {"baseexact": "Wailing Essence of Suffering", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Suffering": {"baseexact": "Wailing Essence of Suffering", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Torment": {"baseexact": "Wailing Essence of Torment", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Torment": {"baseexact": "Wailing Essence of Torment", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Torment": {"baseexact": "Wailing Essence of Torment", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Torment": {"baseexact": "Wailing Essence of Torment", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Torment": {"baseexact": "Wailing Essence of Torment", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Woe": {"baseexact": "Wailing Essence of Woe", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Woe": {"baseexact": "Wailing Essence of Woe", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Woe": {"baseexact": "Wailing Essence of Woe", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Woe": {"baseexact": "Wailing Essence of Woe", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Woe": {"baseexact": "Wailing Essence of Woe", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Wrath": {"baseexact": "Wailing Essence of Wrath", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Wrath": {"baseexact": "Wailing Essence of Wrath", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Wrath": {"baseexact": "Wailing Essence of Wrath", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Wrath": {"baseexact": "Wailing Essence of Wrath", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Wrath": {"baseexact": "Wailing Essence of Wrath", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Wailing Essence of Zeal": {"baseexact": "Wailing Essence of Zeal", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Wailing Essence of Zeal": {"baseexact": "Wailing Essence of Zeal", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Wailing Essence of Zeal": {"baseexact": "Wailing Essence of Zeal", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Wailing Essence of Zeal": {"baseexact": "Wailing Essence of Zeal", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Wailing Essence of Zeal": {"baseexact": "Wailing Essence of Zeal", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Warlord's Exalted Orb": {"baseexact": "Warlord's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Weeping Essence of Anger": {"baseexact": "Weeping Essence of Anger", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Anger": {"baseexact": "Weeping Essence of Anger", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Anger": {"baseexact": "Weeping Essence of Anger", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Anger": {"baseexact": "Weeping Essence of Anger", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Anger": {"baseexact": "Weeping Essence of Anger", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Contempt": {"baseexact": "Weeping Essence of Contempt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Contempt": {"baseexact": "Weeping Essence of Contempt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Contempt": {"baseexact": "Weeping Essence of Contempt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Contempt": {"baseexact": "Weeping Essence of Contempt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Contempt": {"baseexact": "Weeping Essence of Contempt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Doubt": {"baseexact": "Weeping Essence of Doubt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Doubt": {"baseexact": "Weeping Essence of Doubt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Doubt": {"baseexact": "Weeping Essence of Doubt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Doubt": {"baseexact": "Weeping Essence of Doubt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Doubt": {"baseexact": "Weeping Essence of Doubt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Fear": {"baseexact": "Weeping Essence of Fear", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Fear": {"baseexact": "Weeping Essence of Fear", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Fear": {"baseexact": "Weeping Essence of Fear", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Fear": {"baseexact": "Weeping Essence of Fear", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Fear": {"baseexact": "Weeping Essence of Fear", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Greed": {"baseexact": "Weeping Essence of Greed", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Greed": {"baseexact": "Weeping Essence of Greed", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Greed": {"baseexact": "Weeping Essence of Greed", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Greed": {"baseexact": "Weeping Essence of Greed", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Greed": {"baseexact": "Weeping Essence of Greed", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Hatred": {"baseexact": "Weeping Essence of Hatred", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Hatred": {"baseexact": "Weeping Essence of Hatred", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Hatred": {"baseexact": "Weeping Essence of Hatred", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Hatred": {"baseexact": "Weeping Essence of Hatred", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Hatred": {"baseexact": "Weeping Essence of Hatred", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Rage": {"baseexact": "Weeping Essence of Rage", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Rage": {"baseexact": "Weeping Essence of Rage", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Rage": {"baseexact": "Weeping Essence of Rage", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Rage": {"baseexact": "Weeping Essence of Rage", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Rage": {"baseexact": "Weeping Essence of Rage", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Sorrow": {"baseexact": "Weeping Essence of Sorrow", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Sorrow": {"baseexact": "Weeping Essence of Sorrow", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Sorrow": {"baseexact": "Weeping Essence of Sorrow", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Sorrow": {"baseexact": "Weeping Essence of Sorrow", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Sorrow": {"baseexact": "Weeping Essence of Sorrow", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Suffering": {"baseexact": "Weeping Essence of Suffering", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Suffering": {"baseexact": "Weeping Essence of Suffering", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Suffering": {"baseexact": "Weeping Essence of Suffering", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Suffering": {"baseexact": "Weeping Essence of Suffering", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Suffering": {"baseexact": "Weeping Essence of Suffering", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Torment": {"baseexact": "Weeping Essence of Torment", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Torment": {"baseexact": "Weeping Essence of Torment", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Torment": {"baseexact": "Weeping Essence of Torment", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Torment": {"baseexact": "Weeping Essence of Torment", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Torment": {"baseexact": "Weeping Essence of Torment", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Woe": {"baseexact": "Weeping Essence of Woe", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Woe": {"baseexact": "Weeping Essence of Woe", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Woe": {"baseexact": "Weeping Essence of Woe", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Woe": {"baseexact": "Weeping Essence of Woe", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Woe": {"baseexact": "Weeping Essence of Woe", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Weeping Essence of Wrath": {"baseexact": "Weeping Essence of Wrath", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Weeping Essence of Wrath": {"baseexact": "Weeping Essence of Wrath", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Weeping Essence of Wrath": {"baseexact": "Weeping Essence of Wrath", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Weeping Essence of Wrath": {"baseexact": "Weeping Essence of Wrath", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Weeping Essence of Wrath": {"baseexact": "Weeping Essence of Wrath", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Whispering Essence of Contempt": {"baseexact": "Whispering Essence of Contempt", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Whispering Essence of Contempt": {"baseexact": "Whispering Essence of Contempt", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Whispering Essence of Contempt": {"baseexact": "Whispering Essence of Contempt", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Whispering Essence of Contempt": {"baseexact": "Whispering Essence of Contempt", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Whispering Essence of Contempt": {"baseexact": "Whispering Essence of Contempt", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Whispering Essence of Greed": {"baseexact": "Whispering Essence of Greed", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Whispering Essence of Greed": {"baseexact": "Whispering Essence of Greed", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Whispering Essence of Greed": {"baseexact": "Whispering Essence of Greed", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Whispering Essence of Greed": {"baseexact": "Whispering Essence of Greed", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Whispering Essence of Greed": {"baseexact": "Whispering Essence of Greed", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Whispering Essence of Hatred": {"baseexact": "Whispering Essence of Hatred", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Whispering Essence of Hatred": {"baseexact": "Whispering Essence of Hatred", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Whispering Essence of Hatred": {"baseexact": "Whispering Essence of Hatred", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Whispering Essence of Hatred": {"baseexact": "Whispering Essence of Hatred", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Whispering Essence of Hatred": {"baseexact": "Whispering Essence of Hatred", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"1 Whispering Essence of Woe": {"baseexact": "Whispering Essence of Woe", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Whispering Essence of Woe": {"baseexact": "Whispering Essence of Woe", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "show level"},
	"09 Whispering Essence of Woe": {"baseexact": "Whispering Essence of Woe", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very low"},
	"08 Whispering Essence of Woe": {"baseexact": "Whispering Essence of Woe", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency low"},
	"07 Whispering Essence of Woe": {"baseexact": "Whispering Essence of Woe", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
}
