#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 03/13/2020(m/d/y) 20:39:54 UTC from "tmpstandard" data

desc = "Currency Autogen"

# Base type : settings pair
items = {
	"000 Scroll Fragment": {"baseexact": "Scroll Fragment", "class": "Currency", "type": "hide"},
	"1 Abrasive Catalyst": {"baseexact": "Abrasive Catalyst", "class": "Currency", "type": "currency high"},
	"1 Alchemy Shard": {"baseexact": "Alchemy Shard", "class": "Currency", "type": "currency show"},
	"09 Alchemy Shard": {"baseexact": "Alchemy Shard", 'other': ['StackSize >= 15'], "class": "Currency", "type": "currency normal"},
	"1 Alteration Shard": {"baseexact": "Alteration Shard", "class": "Currency", "type": "currency show"},
	"1 Ancient Orb": {"baseexact": "Ancient Orb", "class": "Currency", "type": "currency very high"},
	"09 Ancient Orb": {"baseexact": "Ancient Orb", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency extremely high"},
	"1 Ancient Shard": {"baseexact": "Ancient Shard", "class": "Currency", "type": "currency high"},
	"09 Ancient Shard": {"baseexact": "Ancient Shard", 'other': ['StackSize >= 8'], "class": "Currency", "type": "currency very high"},
	"1 Annulment Shard": {"baseexact": "Annulment Shard", "class": "Currency", "type": "currency normal"},
	"09 Annulment Shard": {"baseexact": "Annulment Shard", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Annulment Shard": {"baseexact": "Annulment Shard", 'other': ['StackSize >= 19'], "class": "Currency", "type": "currency very high"},
	"1 Armourer's Scrap": {"baseexact": "Armourer's Scrap", "class": "Currency", "type": "currency show"},
	"09 Armourer's Scrap": {"baseexact": "Armourer's Scrap", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency normal"},
	"08 Armourer's Scrap": {"baseexact": "Armourer's Scrap", 'other': ['StackSize >= 15'], "class": "Currency", "type": "currency high"},
	"1 Awakened Sextant": {"baseexact": "Awakened Sextant", "class": "Currency", "type": "currency high"},
	"09 Awakened Sextant": {"baseexact": "Awakened Sextant", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency very high"},
	"1 Awakener's Orb": {"baseexact": "Awakener's Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Binding Shard": {"baseexact": "Binding Shard", "class": "Currency", "type": "currency show"},
	"09 Binding Shard": {"baseexact": "Binding Shard", 'other': ['StackSize >= 13'], "class": "Currency", "type": "currency normal"},
	"1 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", "class": "Currency", "type": "currency show"},
	"09 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Blacksmith's Whetstone": {"baseexact": "Blacksmith's Whetstone", 'other': ['StackSize >= 17'], "class": "Currency", "type": "currency high"},
	"1 Blessed Orb": {"baseexact": "Blessed Orb", "class": "Currency", "type": "currency show"},
	"09 Blessed Orb": {"baseexact": "Blessed Orb", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Blessed Orb": {"baseexact": "Blessed Orb", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency high"},
	"1 Blessing of Chayula": {"baseexact": "Blessing of Chayula", "class": "Currency", "type": "currency extremely high"},
	"1 Blessing of Esh": {"baseexact": "Blessing of Esh", "class": "Currency", "type": "currency high"},
	"1 Blessing of Tul": {"baseexact": "Blessing of Tul", "class": "Currency", "type": "currency high"},
	"1 Blessing of Uul-Netol": {"baseexact": "Blessing of Uul-Netol", "class": "Currency", "type": "currency high"},
	"1 Blessing of Xoph": {"baseexact": "Blessing of Xoph", "class": "Currency", "type": "currency high"},
	"1 Cartographer's Chisel": {"baseexact": "Cartographer's Chisel", "class": "Currency", "type": "currency normal"},
	"09 Cartographer's Chisel": {"baseexact": "Cartographer's Chisel", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Chaos Orb": {"baseexact": "Chaos Orb", "class": "Currency", "type": "currency high"},
	"1 Chaos Shard": {"baseexact": "Chaos Shard", "class": "Currency", "type": "currency show"},
	"09 Chaos Shard": {"baseexact": "Chaos Shard", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Chaos Shard": {"baseexact": "Chaos Shard", 'other': ['StackSize >= 20'], "class": "Currency", "type": "currency high"},
	"1 Chromatic Orb": {"baseexact": "Chromatic Orb", "class": "Currency", "type": "currency show"},
	"09 Chromatic Orb": {"baseexact": "Chromatic Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Chromatic Orb": {"baseexact": "Chromatic Orb", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency high"},
	"1 Crusader's Exalted Orb": {"baseexact": "Crusader's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Divine Orb": {"baseexact": "Divine Orb", "class": "Currency", "type": "currency high"},
	"09 Divine Orb": {"baseexact": "Divine Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Engineer's Orb": {"baseexact": "Engineer's Orb", "class": "Currency", "type": "currency show"},
	"09 Engineer's Orb": {"baseexact": "Engineer's Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Engineer's Orb": {"baseexact": "Engineer's Orb", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"1 Engineer's Shard": {"baseexact": "Engineer's Shard", "class": "Currency", "type": "currency show"},
	"1 Exalted Orb": {"baseexact": "Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Exalted Shard": {"baseexact": "Exalted Shard", "class": "Currency", "type": "currency high"},
	"09 Exalted Shard": {"baseexact": "Exalted Shard", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"1 Fertile Catalyst": {"baseexact": "Fertile Catalyst", "class": "Currency", "type": "currency high"},
	"1 Gemcutter's Prism": {"baseexact": "Gemcutter's Prism", "class": "Currency", "type": "currency high"},
	"1 Glassblower's Bauble": {"baseexact": "Glassblower's Bauble", "class": "Currency", "type": "currency normal"},
	"09 Glassblower's Bauble": {"baseexact": "Glassblower's Bauble", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"1 Harbinger's Orb": {"baseexact": "Harbinger's Orb", "class": "Currency", "type": "currency high"},
	"09 Harbinger's Orb": {"baseexact": "Harbinger's Orb", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency very high"},
	"1 Harbinger's Shard": {"baseexact": "Harbinger's Shard", "class": "Currency", "type": "currency low"},
	"09 Harbinger's Shard": {"baseexact": "Harbinger's Shard", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Harbinger's Shard": {"baseexact": "Harbinger's Shard", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"1 Horizon Shard": {"baseexact": "Horizon Shard", "class": "Currency", "type": "currency show"},
	"09 Horizon Shard": {"baseexact": "Horizon Shard", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency normal"},
	"1 Hunter's Exalted Orb": {"baseexact": "Hunter's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Imbued Catalyst": {"baseexact": "Imbued Catalyst", "class": "Currency", "type": "currency normal"},
	"1 Intrinsic Catalyst": {"baseexact": "Intrinsic Catalyst", "class": "Currency", "type": "currency high"},
	"1 Jeweller's Orb": {"baseexact": "Jeweller's Orb", "class": "Currency", "type": "currency show"},
	"09 Jeweller's Orb": {"baseexact": "Jeweller's Orb", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Jeweller's Orb": {"baseexact": "Jeweller's Orb", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency high"},
	"1 Mirror Shard": {"baseexact": "Mirror Shard", "class": "Currency", "type": "currency mirror"},
	"1 Mirror of Kalandra": {"baseexact": "Mirror of Kalandra", "class": "Currency", "type": "currency mirror"},
	"1 Orb of Alchemy": {"baseexact": "Orb of Alchemy", "class": "Currency", "type": "currency normal"},
	"09 Orb of Alchemy": {"baseexact": "Orb of Alchemy", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Alteration": {"baseexact": "Orb of Alteration", "class": "Currency", "type": "currency show"},
	"09 Orb of Alteration": {"baseexact": "Orb of Alteration", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Alteration": {"baseexact": "Orb of Alteration", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency high"},
	"1 Orb of Annulment": {"baseexact": "Orb of Annulment", "class": "Currency", "type": "currency high"},
	"09 Orb of Annulment": {"baseexact": "Orb of Annulment", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency very high"},
	"08 Orb of Annulment": {"baseexact": "Orb of Annulment", 'other': ['StackSize >= 19'], "class": "Currency", "type": "currency extremely high"},
	"1 Orb of Augmentation": {"baseexact": "Orb of Augmentation", "class": "Currency", "type": "currency show"},
	"09 Orb of Augmentation": {"baseexact": "Orb of Augmentation", 'other': ['StackSize >= 7'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Augmentation": {"baseexact": "Orb of Augmentation", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency high"},
	"1 Orb of Binding": {"baseexact": "Orb of Binding", "class": "Currency", "type": "currency normal"},
	"09 Orb of Binding": {"baseexact": "Orb of Binding", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Chance": {"baseexact": "Orb of Chance", "class": "Currency", "type": "currency show"},
	"09 Orb of Chance": {"baseexact": "Orb of Chance", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Chance": {"baseexact": "Orb of Chance", 'other': ['StackSize >= 10'], "class": "Currency", "type": "currency high"},
	"1 Orb of Fusing": {"baseexact": "Orb of Fusing", "class": "Currency", "type": "currency normal"},
	"09 Orb of Fusing": {"baseexact": "Orb of Fusing", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Orb of Fusing": {"baseexact": "Orb of Fusing", 'other': ['StackSize >= 17'], "class": "Currency", "type": "currency very high"},
	"1 Orb of Horizons": {"baseexact": "Orb of Horizons", "class": "Currency", "type": "currency normal"},
	"09 Orb of Horizons": {"baseexact": "Orb of Horizons", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Orb of Horizons": {"baseexact": "Orb of Horizons", 'other': ['StackSize >= 15'], "class": "Currency", "type": "currency very high"},
	"1 Orb of Regret": {"baseexact": "Orb of Regret", "class": "Currency", "type": "currency normal"},
	"09 Orb of Regret": {"baseexact": "Orb of Regret", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency high"},
	"08 Orb of Regret": {"baseexact": "Orb of Regret", 'other': ['StackSize >= 19'], "class": "Currency", "type": "currency very high"},
	"1 Orb of Scouring": {"baseexact": "Orb of Scouring", "class": "Currency", "type": "currency normal"},
	"09 Orb of Scouring": {"baseexact": "Orb of Scouring", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency high"},
	"1 Orb of Transmutation": {"baseexact": "Orb of Transmutation", "class": "Currency", "type": "currency show"},
	"09 Orb of Transmutation": {"baseexact": "Orb of Transmutation", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Orb of Transmutation": {"baseexact": "Orb of Transmutation", 'other': ['StackSize >= 17'], "class": "Currency", "type": "currency high"},
	"1 Perandus Coin": {"baseexact": "Perandus Coin", "class": "Currency", "type": "currency show"},
	"09 Perandus Coin": {"baseexact": "Perandus Coin", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency normal"},
	"08 Perandus Coin": {"baseexact": "Perandus Coin", 'other': ['StackSize >= 100'], "class": "Currency", "type": "currency high"},
	"1 Portal Scroll": {"baseexact": "Portal Scroll", "class": "Currency", "type": "currency show"},
	"09 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency normal"},
	"08 Portal Scroll": {"baseexact": "Portal Scroll", 'other': ['StackSize >= 20'], "class": "Currency", "type": "currency high"},
	"1 Prime Sextant": {"baseexact": "Prime Sextant", "class": "Currency", "type": "currency high"},
	"1 Prismatic Catalyst": {"baseexact": "Prismatic Catalyst", "class": "Currency", "type": "currency high"},
	"1 Redeemer's Exalted Orb": {"baseexact": "Redeemer's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
	"1 Regal Orb": {"baseexact": "Regal Orb", "class": "Currency", "type": "currency normal"},
	"09 Regal Orb": {"baseexact": "Regal Orb", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"1 Regal Shard": {"baseexact": "Regal Shard", "class": "Currency", "type": "currency show"},
	"09 Regal Shard": {"baseexact": "Regal Shard", 'other': ['StackSize >= 18'], "class": "Currency", "type": "currency normal"},
	"1 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", "class": "Currency", "type": "currency show"},
	"09 Scroll of Wisdom": {"baseexact": "Scroll of Wisdom", 'other': ['StackSize >= 25'], "class": "Currency", "type": "currency normal"},
	"1 Silver Coin": {"baseexact": "Silver Coin", "class": "Currency", "type": "currency show"},
	"09 Silver Coin": {"baseexact": "Silver Coin", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Silver Coin": {"baseexact": "Silver Coin", 'other': ['StackSize >= 6'], "class": "Currency", "type": "currency high"},
	"1 Simple Sextant": {"baseexact": "Simple Sextant", "class": "Currency", "type": "currency high"},
	"1 Splinter of Chayula": {"baseexact": "Splinter of Chayula", "class": "Currency", "type": "currency high"},
	"09 Splinter of Chayula": {"baseexact": "Splinter of Chayula", 'other': ['StackSize >= 8'], "class": "Currency", "type": "currency very high"},
	"08 Splinter of Chayula": {"baseexact": "Splinter of Chayula", 'other': ['StackSize >= 78'], "class": "Currency", "type": "currency extremely high"},
	"1 Splinter of Esh": {"baseexact": "Splinter of Esh", "class": "Currency", "type": "currency show"},
	"09 Splinter of Esh": {"baseexact": "Splinter of Esh", 'other': ['StackSize >= 3'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Esh": {"baseexact": "Splinter of Esh", 'other': ['StackSize >= 12'], "class": "Currency", "type": "currency high"},
	"1 Splinter of Tul": {"baseexact": "Splinter of Tul", "class": "Currency", "type": "currency normal"},
	"09 Splinter of Tul": {"baseexact": "Splinter of Tul", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"08 Splinter of Tul": {"baseexact": "Splinter of Tul", 'other': ['StackSize >= 44'], "class": "Currency", "type": "currency very high"},
	"1 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", "class": "Currency", "type": "currency show"},
	"09 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", 'other': ['StackSize >= 5'], "class": "Currency", "type": "currency high"},
	"07 Splinter of Uul-Netol": {"baseexact": "Splinter of Uul-Netol", 'other': ['StackSize >= 53'], "class": "Currency", "type": "currency very high"},
	"1 Splinter of Xoph": {"baseexact": "Splinter of Xoph", "class": "Currency", "type": "currency show"},
	"09 Splinter of Xoph": {"baseexact": "Splinter of Xoph", 'other': ['StackSize >= 2'], "class": "Currency", "type": "currency normal"},
	"08 Splinter of Xoph": {"baseexact": "Splinter of Xoph", 'other': ['StackSize >= 8'], "class": "Currency", "type": "currency high"},
	"07 Splinter of Xoph": {"baseexact": "Splinter of Xoph", 'other': ['StackSize >= 79'], "class": "Currency", "type": "currency very high"},
	"1 Stacked Deck": {"baseexact": "Stacked Deck", "class": "Currency", "type": "currency high"},
	"1 Tempering Catalyst": {"baseexact": "Tempering Catalyst", "class": "Currency", "type": "currency high"},
	"1 Transmutation Shard": {"baseexact": "Transmutation Shard", 'other': ['AreaLevel > 67'], "class": "Currency", "type": "hide"},
	"11 Transmutation Shard": {"baseexact": "Transmutation Shard", 'other': ['AreaLevel <= 67'], "class": "Currency", "type": "currency show"},
	"1 Turbulent Catalyst": {"baseexact": "Turbulent Catalyst", "class": "Currency", "type": "currency high"},
	"1 Vaal Orb": {"baseexact": "Vaal Orb", "class": "Currency", "type": "currency normal"},
	"09 Vaal Orb": {"baseexact": "Vaal Orb", 'other': ['StackSize >= 4'], "class": "Currency", "type": "currency high"},
	"1 Vial of Awakening": {"baseexact": "Vial of Awakening", "class": "Currency", "type": "currency very high"},
	"1 Vial of Consequence": {"baseexact": "Vial of Consequence", "class": "Currency", "type": "currency extremely high"},
	"1 Vial of Dominance": {"baseexact": "Vial of Dominance", "class": "Currency", "type": "currency very high"},
	"1 Vial of Fate": {"baseexact": "Vial of Fate", "class": "Currency", "type": "currency very high"},
	"1 Vial of Sacrifice": {"baseexact": "Vial of Sacrifice", "class": "Currency", "type": "currency very high"},
	"1 Vial of Summoning": {"baseexact": "Vial of Summoning", "class": "Currency", "type": "currency extremely high"},
	"1 Vial of Transcendence": {"baseexact": "Vial of Transcendence", "class": "Currency", "type": "currency very high"},
	"1 Vial of the Ghost": {"baseexact": "Vial of the Ghost", "class": "Currency", "type": "currency extremely high"},
	"1 Vial of the Ritual": {"baseexact": "Vial of the Ritual", "class": "Currency", "type": "currency extremely high"},
	"1 Warlord's Exalted Orb": {"baseexact": "Warlord's Exalted Orb", "class": "Currency", "type": "currency extremely high"},
}
