#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 07/17/2019(m/d/y) 21:51:32 UTC from "tmpstandard" data

desc = "Essence Autogen"

# Base type : settings pair
items = {
	"0 Aberrant Fossil": {"base": "Aberrant Fossil", "class": "Currency", "type": "currency show"},
	"0 Aetheric Fossil": {"base": "Aetheric Fossil", "class": "Currency", "type": "currency show"},
	"0 Bloodstained Fossil": {"base": "Bloodstained Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Bound Fossil": {"base": "Bound Fossil", "class": "Currency", "type": "currency show"},
	"0 Corroded Fossil": {"base": "Corroded Fossil", "class": "Currency", "type": "currency show"},
	"0 Deafening Essence of Anger": {"base": "Deafening Essence of Anger", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Contempt": {"base": "Deafening Essence of Contempt", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Dread": {"base": "Deafening Essence of Dread", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Envy": {"base": "Deafening Essence of Envy", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Fear": {"base": "Deafening Essence of Fear", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Greed": {"base": "Deafening Essence of Greed", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Hatred": {"base": "Deafening Essence of Hatred", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Loathing": {"base": "Deafening Essence of Loathing", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Misery": {"base": "Deafening Essence of Misery", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Rage": {"base": "Deafening Essence of Rage", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Scorn": {"base": "Deafening Essence of Scorn", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Sorrow": {"base": "Deafening Essence of Sorrow", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Spite": {"base": "Deafening Essence of Spite", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Suffering": {"base": "Deafening Essence of Suffering", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Woe": {"base": "Deafening Essence of Woe", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Wrath": {"base": "Deafening Essence of Wrath", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Zeal": {"base": "Deafening Essence of Zeal", "class": "Currency", "type": "currency very high"},
	"0 Dense Fossil": {"base": "Dense Fossil", "class": "Currency", "type": "currency show"},
	"0 Enchanted Fossil": {"base": "Enchanted Fossil", "class": "Currency", "type": "currency high"},
	"0 Encrusted Fossil": {"base": "Encrusted Fossil", "class": "Currency", "type": "currency show"},
	"0 Essence of Delirium": {"base": "Essence of Delirium", "class": "Currency", "type": "currency normal"},
	"0 Essence of Horror": {"base": "Essence of Horror", "class": "Currency", "type": "currency high"},
	"0 Essence of Hysteria": {"base": "Essence of Hysteria", "class": "Currency", "type": "currency high"},
	"0 Essence of Insanity": {"base": "Essence of Insanity", "class": "Currency", "type": "currency high"},
	"0 Faceted Fossil": {"base": "Faceted Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Fractured Fossil": {"base": "Fractured Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Frigid Fossil": {"base": "Frigid Fossil", "class": "Currency", "type": "currency show"},
	"0 Gilded Fossil": {"base": "Gilded Fossil", "class": "Currency", "type": "currency high"},
	"0 Glyphic Fossil": {"base": "Glyphic Fossil", "class": "Currency", "type": "currency very high"},
	"0 Hollow Fossil": {"base": "Hollow Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Jagged Fossil": {"base": "Jagged Fossil", "class": "Currency", "type": "currency show"},
	"0 Lucent Fossil": {"base": "Lucent Fossil", "class": "Currency", "type": "currency show"},
	"0 Metallic Fossil": {"base": "Metallic Fossil", "class": "Currency", "type": "currency show"},
	"0 Perfect Fossil": {"base": "Perfect Fossil", "class": "Currency", "type": "currency high"},
	"0 Potent Alchemical Resonator": {"base": "Potent Alchemical Resonator", "class": "Currency", "type": "currency normal"},
	"0 Potent Chaotic Resonator": {"base": "Potent Chaotic Resonator", "class": "Currency", "type": "currency normal"},
	"0 Powerful Alchemical Resonator": {"base": "Powerful Alchemical Resonator", "class": "Currency", "type": "currency show"},
	"0 Powerful Chaotic Resonator": {"base": "Powerful Chaotic Resonator", "class": "Currency", "type": "currency show"},
	"0 Prime Alchemical Resonator": {"base": "Prime Alchemical Resonator", "class": "Currency", "type": "currency high"},
	"0 Prime Chaotic Resonator": {"base": "Prime Chaotic Resonator", "class": "Currency", "type": "currency very high"},
	"0 Primitive Alchemical Resonator": {"base": "Primitive Alchemical Resonator", "class": "Currency", "type": "currency show"},
	"0 Primitive Chaotic Resonator": {"base": "Primitive Chaotic Resonator", "class": "Currency", "type": "currency show"},
	"0 Prismatic Fossil": {"base": "Prismatic Fossil", "class": "Currency", "type": "currency high"},
	"0 Pristine Fossil": {"base": "Pristine Fossil", "class": "Currency", "type": "currency normal"},
	"0 Sanctified Fossil": {"base": "Sanctified Fossil", "class": "Currency", "type": "currency very high"},
	"0 Scorched Fossil": {"base": "Scorched Fossil", "class": "Currency", "type": "currency show"},
	"0 Screaming Essence of Dread": {"base": "Screaming Essence of Dread", "class": "Currency", "type": "currency high"},
	"0 Screaming Essence of Envy": {"base": "Screaming Essence of Envy", "class": "Currency", "type": "currency normal"},
	"0 Screaming Essence of Zeal": {"base": "Screaming Essence of Zeal", "class": "Currency", "type": "currency normal"},
	"0 Serrated Fossil": {"base": "Serrated Fossil", "class": "Currency", "type": "currency very high"},
	"0 Shrieking Essence of Anger": {"base": "Shrieking Essence of Anger", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Contempt": {"base": "Shrieking Essence of Contempt", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Dread": {"base": "Shrieking Essence of Dread", "class": "Currency", "type": "currency very high"},
	"0 Shrieking Essence of Envy": {"base": "Shrieking Essence of Envy", "class": "Currency", "type": "currency high"},
	"0 Shrieking Essence of Greed": {"base": "Shrieking Essence of Greed", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Rage": {"base": "Shrieking Essence of Rage", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Scorn": {"base": "Shrieking Essence of Scorn", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Spite": {"base": "Shrieking Essence of Spite", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Wrath": {"base": "Shrieking Essence of Wrath", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Zeal": {"base": "Shrieking Essence of Zeal", "class": "Currency", "type": "currency high"},
	"0 Shuddering Fossil": {"base": "Shuddering Fossil", "class": "Currency", "type": "currency high"},
	"0 Tangled Fossil": {"base": "Tangled Fossil", "class": "Currency", "type": "currency high"},
	"7 Essence default": {"base": "Essence", "class": "Currency", "type": "currency low"}}
