#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 03/13/2020(m/d/y) 20:39:54 UTC from "tmpstandard" data

desc = "Essence Autogen"

# Base type : settings pair
items = {
	"0 Aberrant Fossil": {"baseexact": "Aberrant Fossil", "class": "Currency", "type": "currency show"},
	"0 Aetheric Fossil": {"baseexact": "Aetheric Fossil", "class": "Currency", "type": "currency high"},
	"0 Bloodstained Fossil": {"baseexact": "Bloodstained Fossil", "class": "Currency", "type": "currency very high"},
	"0 Bound Fossil": {"baseexact": "Bound Fossil", "class": "Currency", "type": "currency high"},
	"0 Corroded Fossil": {"baseexact": "Corroded Fossil", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Anger": {"baseexact": "Deafening Essence of Anger", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Anguish": {"baseexact": "Deafening Essence of Anguish", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Contempt": {"baseexact": "Deafening Essence of Contempt", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Doubt": {"baseexact": "Deafening Essence of Doubt", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Dread": {"baseexact": "Deafening Essence of Dread", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Envy": {"baseexact": "Deafening Essence of Envy", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Fear": {"baseexact": "Deafening Essence of Fear", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Greed": {"baseexact": "Deafening Essence of Greed", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Hatred": {"baseexact": "Deafening Essence of Hatred", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Loathing": {"baseexact": "Deafening Essence of Loathing", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Misery": {"baseexact": "Deafening Essence of Misery", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Rage": {"baseexact": "Deafening Essence of Rage", "class": "Currency", "type": "currency very high"},
	"0 Deafening Essence of Scorn": {"baseexact": "Deafening Essence of Scorn", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Sorrow": {"baseexact": "Deafening Essence of Sorrow", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Spite": {"baseexact": "Deafening Essence of Spite", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Suffering": {"baseexact": "Deafening Essence of Suffering", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Torment": {"baseexact": "Deafening Essence of Torment", "class": "Currency", "type": "currency normal"},
	"0 Deafening Essence of Woe": {"baseexact": "Deafening Essence of Woe", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Wrath": {"baseexact": "Deafening Essence of Wrath", "class": "Currency", "type": "currency high"},
	"0 Deafening Essence of Zeal": {"baseexact": "Deafening Essence of Zeal", "class": "Currency", "type": "currency very high"},
	"0 Dense Fossil": {"baseexact": "Dense Fossil", "class": "Currency", "type": "currency normal"},
	"0 Enchanted Fossil": {"baseexact": "Enchanted Fossil", "class": "Currency", "type": "currency normal"},
	"0 Encrusted Fossil": {"baseexact": "Encrusted Fossil", "class": "Currency", "type": "currency normal"},
	"0 Essence of Delirium": {"baseexact": "Essence of Delirium", "class": "Currency", "type": "currency normal"},
	"0 Essence of Horror": {"baseexact": "Essence of Horror", "class": "Currency", "type": "currency high"},
	"0 Essence of Hysteria": {"baseexact": "Essence of Hysteria", "class": "Currency", "type": "currency normal"},
	"0 Essence of Insanity": {"baseexact": "Essence of Insanity", "class": "Currency", "type": "currency high"},
	"0 Faceted Fossil": {"baseexact": "Faceted Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Fractured Fossil": {"baseexact": "Fractured Fossil", "class": "Currency", "type": "currency extremely high"},
	"0 Frigid Fossil": {"baseexact": "Frigid Fossil", "class": "Currency", "type": "currency show"},
	"0 Gilded Fossil": {"baseexact": "Gilded Fossil", "class": "Currency", "type": "currency high"},
	"0 Glyphic Fossil": {"baseexact": "Glyphic Fossil", "class": "Currency", "type": "currency very high"},
	"0 Hollow Fossil": {"baseexact": "Hollow Fossil", "class": "Currency", "type": "currency very high"},
	"0 Jagged Fossil": {"baseexact": "Jagged Fossil", "class": "Currency", "type": "currency show"},
	"0 Lucent Fossil": {"baseexact": "Lucent Fossil", "class": "Currency", "type": "currency show"},
	"0 Metallic Fossil": {"baseexact": "Metallic Fossil", "class": "Currency", "type": "currency show"},
	"0 Perfect Fossil": {"baseexact": "Perfect Fossil", "class": "Currency", "type": "currency high"},
	"0 Potent Alchemical Resonator": {"baseexact": "Potent Alchemical Resonator", "class": "Currency", "type": "currency normal"},
	"0 Potent Chaotic Resonator": {"baseexact": "Potent Chaotic Resonator", "class": "Currency", "type": "currency normal"},
	"0 Powerful Alchemical Resonator": {"baseexact": "Powerful Alchemical Resonator", "class": "Currency", "type": "currency show"},
	"0 Powerful Chaotic Resonator": {"baseexact": "Powerful Chaotic Resonator", "class": "Currency", "type": "currency normal"},
	"0 Prime Alchemical Resonator": {"baseexact": "Prime Alchemical Resonator", "class": "Currency", "type": "currency very high"},
	"0 Prime Chaotic Resonator": {"baseexact": "Prime Chaotic Resonator", "class": "Currency", "type": "currency very high"},
	"0 Primitive Alchemical Resonator": {"baseexact": "Primitive Alchemical Resonator", "class": "Currency", "type": "currency show"},
	"0 Primitive Chaotic Resonator": {"baseexact": "Primitive Chaotic Resonator", "class": "Currency", "type": "currency normal"},
	"0 Prismatic Fossil": {"baseexact": "Prismatic Fossil", "class": "Currency", "type": "currency high"},
	"0 Pristine Fossil": {"baseexact": "Pristine Fossil", "class": "Currency", "type": "currency normal"},
	"0 Sanctified Fossil": {"baseexact": "Sanctified Fossil", "class": "Currency", "type": "currency very high"},
	"0 Scorched Fossil": {"baseexact": "Scorched Fossil", "class": "Currency", "type": "currency show"},
	"0 Screaming Essence of Fear": {"baseexact": "Screaming Essence of Fear", "class": "Currency", "type": "currency normal"},
	"0 Screaming Essence of Greed": {"baseexact": "Screaming Essence of Greed", "class": "Currency", "type": "currency normal"},
	"0 Serrated Fossil": {"baseexact": "Serrated Fossil", "class": "Currency", "type": "currency high"},
	"0 Shrieking Essence of Anger": {"baseexact": "Shrieking Essence of Anger", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Contempt": {"baseexact": "Shrieking Essence of Contempt", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Dread": {"baseexact": "Shrieking Essence of Dread", "class": "Currency", "type": "currency high"},
	"0 Shrieking Essence of Envy": {"baseexact": "Shrieking Essence of Envy", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Fear": {"baseexact": "Shrieking Essence of Fear", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Greed": {"baseexact": "Shrieking Essence of Greed", "class": "Currency", "type": "currency high"},
	"0 Shrieking Essence of Hatred": {"baseexact": "Shrieking Essence of Hatred", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Rage": {"baseexact": "Shrieking Essence of Rage", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Scorn": {"baseexact": "Shrieking Essence of Scorn", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Sorrow": {"baseexact": "Shrieking Essence of Sorrow", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Spite": {"baseexact": "Shrieking Essence of Spite", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Torment": {"baseexact": "Shrieking Essence of Torment", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Woe": {"baseexact": "Shrieking Essence of Woe", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Wrath": {"baseexact": "Shrieking Essence of Wrath", "class": "Currency", "type": "currency normal"},
	"0 Shrieking Essence of Zeal": {"baseexact": "Shrieking Essence of Zeal", "class": "Currency", "type": "currency high"},
	"0 Shuddering Fossil": {"baseexact": "Shuddering Fossil", "class": "Currency", "type": "currency high"},
	"0 Tangled Fossil": {"baseexact": "Tangled Fossil", "class": "Currency", "type": "currency very high"},
	"7 Essence default": {"base": "Essence", "class": "Currency", "type": "currency low"}}
