#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 03/21/2020(m/d/y) 03:11:44 UTC from "tmpstandard" data

desc = "Fragment Autogen"

# Base type : settings pair
items = {
	"1 Ancient Reliquary Key": {"baseexact": "Ancient Reliquary Key", "class": "Map Fragments", "type": "fragment extremely high"},
	"1 Chayula's Breachstone": {"baseexact": "Chayula's Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Chayula's Charged Breachstone": {"baseexact": "Chayula's Charged Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Chayula's Enriched Breachstone": {"baseexact": "Chayula's Enriched Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Chayula's Pure Breachstone": {"baseexact": "Chayula's Pure Breachstone", "class": "Map Fragments", "type": "fragment extremely high"},
	"1 Divine Vessel": {"baseexact": "Divine Vessel", "class": "Map Fragments", "type": "fragment normal"},
	"1 Eber's Key": {"baseexact": "Eber's Key", "class": "Map Fragments", "type": "fragment high"},
	"1 Esh's Breachstone": {"baseexact": "Esh's Breachstone", "class": "Map Fragments", "type": "fragment normal"},
	"1 Esh's Charged Breachstone": {"baseexact": "Esh's Charged Breachstone", "class": "Map Fragments", "type": "fragment normal"},
	"1 Esh's Enriched Breachstone": {"baseexact": "Esh's Enriched Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Esh's Pure Breachstone": {"baseexact": "Esh's Pure Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Constriction": {"baseexact": "Fragment of Constriction", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Emptiness": {"baseexact": "Fragment of Emptiness", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Enslavement": {"baseexact": "Fragment of Enslavement", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Eradication": {"baseexact": "Fragment of Eradication", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Knowledge": {"baseexact": "Fragment of Knowledge", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Purification": {"baseexact": "Fragment of Purification", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Shape": {"baseexact": "Fragment of Shape", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of Terror": {"baseexact": "Fragment of Terror", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of the Chimera": {"baseexact": "Fragment of the Chimera", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of the Hydra": {"baseexact": "Fragment of the Hydra", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of the Minotaur": {"baseexact": "Fragment of the Minotaur", "class": "Map Fragments", "type": "fragment very high"},
	"1 Fragment of the Phoenix": {"baseexact": "Fragment of the Phoenix", "class": "Map Fragments", "type": "fragment very high"},
	"1 Inya's Key": {"baseexact": "Inya's Key", "class": "Map Fragments", "type": "fragment high"},
	"1 Mortal Grief": {"baseexact": "Mortal Grief", "class": "Map Fragments", "type": "fragment high"},
	"1 Mortal Hope": {"baseexact": "Mortal Hope", "class": "Map Fragments", "type": "fragment very high"},
	"1 Mortal Ignorance": {"baseexact": "Mortal Ignorance", "class": "Map Fragments", "type": "fragment very high"},
	"1 Mortal Rage": {"baseexact": "Mortal Rage", "class": "Map Fragments", "type": "fragment high"},
	"1 Offering to the Goddess": {"baseexact": "Offering to the Goddess", "class": "Map Fragments", "type": "fragment normal"},
	"1 Sacrifice at Dawn": {"baseexact": "Sacrifice at Dawn", "class": "Map Fragments", "type": "fragment normal"},
	"1 Sacrifice at Dusk": {"baseexact": "Sacrifice at Dusk", "class": "Map Fragments", "type": "fragment normal"},
	"1 Sacrifice at Midnight": {"baseexact": "Sacrifice at Midnight", "class": "Map Fragments", "type": "fragment normal"},
	"1 Sacrifice at Noon": {"baseexact": "Sacrifice at Noon", "class": "Map Fragments", "type": "fragment normal"},
	"1 Simulacrum": {"baseexact": "Simulacrum", "class": "Map Fragments", "type": "fragment very high"},
	"1 Simulacrum Splinter": {"baseexact": "Simulacrum Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeless Eternal Emblem": {"baseexact": "Timeless Eternal Emblem", "class": "Map Fragments", "type": "fragment very high"},
	"1 Timeless Eternal Empire Splinter": {"baseexact": "Timeless Eternal Empire Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeless Karui Emblem": {"baseexact": "Timeless Karui Emblem", "class": "Map Fragments", "type": "fragment very high"},
	"1 Timeless Karui Splinter": {"baseexact": "Timeless Karui Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeless Maraketh Emblem": {"baseexact": "Timeless Maraketh Emblem", "class": "Map Fragments", "type": "fragment extremely high"},
	"1 Timeless Maraketh Splinter": {"baseexact": "Timeless Maraketh Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeless Templar Emblem": {"baseexact": "Timeless Templar Emblem", "class": "Map Fragments", "type": "fragment extremely high"},
	"1 Timeless Templar Splinter": {"baseexact": "Timeless Templar Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeless Vaal Emblem": {"baseexact": "Timeless Vaal Emblem", "class": "Map Fragments", "type": "fragment very high"},
	"1 Timeless Vaal Splinter": {"baseexact": "Timeless Vaal Splinter", "class": "Map Fragments", "type": "fragment normal"},
	"1 Timeworn Reliquary Key": {"baseexact": "Timeworn Reliquary Key", "class": "Map Fragments", "type": "fragment extremely high"},
	"1 Tul's Breachstone": {"baseexact": "Tul's Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Tul's Charged Breachstone": {"baseexact": "Tul's Charged Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Tul's Enriched Breachstone": {"baseexact": "Tul's Enriched Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Tul's Pure Breachstone": {"baseexact": "Tul's Pure Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Uul-Netol's Breachstone": {"baseexact": "Uul-Netol's Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Uul-Netol's Charged Breachstone": {"baseexact": "Uul-Netol's Charged Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Uul-Netol's Enriched Breachstone": {"baseexact": "Uul-Netol's Enriched Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Uul-Netol's Pure Breachstone": {"baseexact": "Uul-Netol's Pure Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Volkuur's Key": {"baseexact": "Volkuur's Key", "class": "Map Fragments", "type": "fragment high"},
	"1 Xoph's Breachstone": {"baseexact": "Xoph's Breachstone", "class": "Map Fragments", "type": "fragment normal"},
	"1 Xoph's Charged Breachstone": {"baseexact": "Xoph's Charged Breachstone", "class": "Map Fragments", "type": "fragment normal"},
	"1 Xoph's Enriched Breachstone": {"baseexact": "Xoph's Enriched Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Xoph's Pure Breachstone": {"baseexact": "Xoph's Pure Breachstone", "class": "Map Fragments", "type": "fragment very high"},
	"1 Yriel's Key": {"baseexact": "Yriel's Key", "class": "Map Fragments", "type": "fragment high"},
}
