#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/25/2019(m/d/y) 21:27:35 UTC from "tmphardcore" data

desc = "Bases"

# Base type : settings pair
items = {
	"0 Shaper Abyssal Axe": {"base": "Abyssal Axe", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ambusher": {"base": "Ambusher", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Arcanist Gloves": {"base": "Arcanist Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Arcanist Slippers": {"base": "Arcanist Slippers", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Archon Kite Shield": {"base": "Archon Kite Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Assassin's Mitts": {"base": "Assassin's Mitts", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Astral Plate": {"base": "Astral Plate", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Aventail Helmet": {"base": "Aventail Helmet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Behemoth Mace": {"base": "Behemoth Mace", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Blood Raiment": {"base": "Blood Raiment", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Bone Helmet": {"base": "Bone Helmet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Boot Blade": {"base": "Boot Blade", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Burnished Foil": {"base": "Burnished Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Butcher Knife": {"base": "Butcher Knife", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Carnal Armour": {"base": "Carnal Armour", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Carnal Boots": {"base": "Carnal Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Carnal Mitts": {"base": "Carnal Mitts", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Clasped Mitts": {"base": "Clasped Mitts", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Conjurer Boots": {"base": "Conjurer Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Conjurer Gloves": {"base": "Conjurer Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Conjurer's Vestment": {"base": "Conjurer's Vestment", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crusader Boots": {"base": "Crusader Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crusader Gloves": {"base": "Crusader Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Crystal Sceptre": {"base": "Crystal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Crystal Wand": {"base": "Crystal Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Demon's Horn": {"base": "Demon's Horn", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Devout Chainmail": {"base": "Devout Chainmail", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eelskin Boots": {"base": "Eelskin Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Engraved Wand": {"base": "Engraved Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Exquisite Blade": {"base": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ezomyte Dagger": {"base": "Ezomyte Dagger", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ezomyte Tower Shield": {"base": "Ezomyte Tower Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fencer Helm": {"base": "Fencer Helm", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Flanged Mace": {"base": "Flanged Mace", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Fossilised Spirit Shield": {"base": "Fossilised Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Harbinger Bow": {"base": "Harbinger Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Imperial Bow": {"base": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Imperial Claw": {"base": "Imperial Claw", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ivory Spirit Shield": {"base": "Ivory Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lead Sceptre": {"base": "Lead Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Legion Boots": {"base": "Legion Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Lunaris Circlet": {"base": "Lunaris Circlet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Maelström Staff": {"base": "Maelström Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Moon Staff": {"base": "Moon Staff", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Moonstone Ring": {"base": "Moonstone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Murder Boots": {"base": "Murder Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Murder Mitts": {"base": "Murder Mitts", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Nubuck Boots": {"base": "Nubuck Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Nubuck Gloves": {"base": "Nubuck Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Omen Wand": {"base": "Omen Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Ring": {"base": "Opal Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Opal Wand": {"base": "Opal Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Platinum Sceptre": {"base": "Platinum Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Poignard": {"base": "Poignard", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Profane Wand": {"base": "Profane Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Prophecy Wand": {"base": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Ranger Bow": {"base": "Ranger Bow", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Raven Mask": {"base": "Raven Mask", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Burgonet": {"base": "Royal Burgonet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Royal Skean": {"base": "Royal Skean", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sadist Garb": {"base": "Sadist Garb", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sai": {"base": "Sai", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Samite Gloves": {"base": "Samite Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Samite Slippers": {"base": "Samite Slippers", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Satin Gloves": {"base": "Satin Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Satin Slippers": {"base": "Satin Slippers", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sekhem": {"base": "Sekhem", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Serpent Wand": {"base": "Serpent Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Shackled Boots": {"base": "Shackled Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Shagreen Boots": {"base": "Shagreen Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sharkskin Boots": {"base": "Sharkskin Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sharkskin Gloves": {"base": "Sharkskin Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slaughter Knife": {"base": "Slaughter Knife", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slink Boots": {"base": "Slink Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Slink Gloves": {"base": "Slink Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Stag Sceptre": {"base": "Stag Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Stealth Boots": {"base": "Stealth Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Stealth Gloves": {"base": "Stealth Gloves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Steelscale Boots": {"base": "Steelscale Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Supreme Spiked Shield": {"base": "Supreme Spiked Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titan Greaves": {"base": "Titan Greaves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Tornado Wand": {"base": "Tornado Wand", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Trapper Boots": {"base": "Trapper Boots", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Trisula": {"base": "Trisula", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Greaves": {"base": "Vaal Greaves", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Mask": {"base": "Vaal Mask", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Vaal Sceptre": {"base": "Vaal Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Vanguard Belt": {"base": "Vanguard Belt", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Shaper Zodiac Leather": {"base": "Zodiac Leather", "other": ["ShaperItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Amethyst Ring": {"base": "Amethyst Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Assassin's Garb": {"base": "Assassin's Garb", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base extremely high"},
	"0 Elder Aventail Helmet": {"base": "Aventail Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Bone Circlet": {"base": "Bone Circlet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Chain Hauberk": {"base": "Chain Hauberk", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Coral Amulet": {"base": "Coral Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Deicide Mask": {"base": "Deicide Mask", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Eye Gouger": {"base": "Eye Gouger", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Fencer Helm": {"base": "Fencer Helm", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Gladiator Plate": {"base": "Gladiator Plate", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Glorious Plate": {"base": "Glorious Plate", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Gold Amulet": {"base": "Gold Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Goliath Gauntlets": {"base": "Goliath Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Imperial Claw": {"base": "Imperial Claw", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Lion Pelt": {"base": "Lion Pelt", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Maraketh Bow": {"base": "Maraketh Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Mind Cage": {"base": "Mind Cage", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Nightmare Bascinet": {"base": "Nightmare Bascinet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Opal Wand": {"base": "Opal Wand", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Praetor Crown": {"base": "Praetor Crown", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Prophet Crown": {"base": "Prophet Crown", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Raven Mask": {"base": "Raven Mask", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Reaver Helmet": {"base": "Reaver Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sadist Garb": {"base": "Sadist Garb", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Samite Helmet": {"base": "Samite Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Samite Slippers": {"base": "Samite Slippers", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sentinel Jacket": {"base": "Sentinel Jacket", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Serpentscale Gauntlets": {"base": "Serpentscale Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sharkskin Boots": {"base": "Sharkskin Boots", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Siege Helmet": {"base": "Siege Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sinner Tricorne": {"base": "Sinner Tricorne", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Slink Gloves": {"base": "Slink Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Stealth Boots": {"base": "Stealth Boots", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Steelwood Bow": {"base": "Steelwood Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Thicket Bow": {"base": "Thicket Bow", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vaal Axe": {"base": "Vaal Axe", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Vaal Regalia": {"base": "Vaal Regalia", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"0 Elder Zealot Helmet": {"base": "Zealot Helmet", "other": ["ElderItem True", "ItemLevel >= 86"], "type": "base very high"},
	"1 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ambush Mitts": {"base": "Ambush Mitts", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ambusher": {"base": "Ambusher", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Arcanist Gloves": {"base": "Arcanist Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Arcanist Slippers": {"base": "Arcanist Slippers", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Behemoth Mace": {"base": "Behemoth Mace", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Blood Sceptre": {"base": "Blood Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Bone Helmet": {"base": "Bone Helmet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Branded Kite Shield": {"base": "Branded Kite Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Butcher Knife": {"base": "Butcher Knife", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Crystal Sceptre": {"base": "Crystal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Crystal Wand": {"base": "Crystal Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Deicide Mask": {"base": "Deicide Mask", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Demon Dagger": {"base": "Demon Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Demon's Horn": {"base": "Demon's Horn", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Engraved Wand": {"base": "Engraved Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Exquisite Blade": {"base": "Exquisite Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Faun's Horn": {"base": "Faun's Horn", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Fiend Dagger": {"base": "Fiend Dagger", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Golden Buckler": {"base": "Golden Buckler", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Grinning Fetish": {"base": "Grinning Fetish", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Harmonic Spirit Shield": {"base": "Harmonic Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Heathen Wand": {"base": "Heathen Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Heavy Belt": {"base": "Heavy Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Highborn Bow": {"base": "Highborn Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Imbued Wand": {"base": "Imbued Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imperial Bow": {"base": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ivory Spirit Shield": {"base": "Ivory Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Karui Sceptre": {"base": "Karui Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lead Sceptre": {"base": "Lead Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Lithe Blade": {"base": "Lithe Blade", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Mind Cage": {"base": "Mind Cage", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Moon Staff": {"base": "Moon Staff", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Murder Mitts": {"base": "Murder Mitts", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Necromancer Circlet": {"base": "Necromancer Circlet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Nubuck Gloves": {"base": "Nubuck Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Omen Wand": {"base": "Omen Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Opal Wand": {"base": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Platinum Sceptre": {"base": "Platinum Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Poignard": {"base": "Poignard", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Profane Wand": {"base": "Profane Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Prophecy Wand": {"base": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Royal Sceptre": {"base": "Royal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sai": {"base": "Sai", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Satin Gloves": {"base": "Satin Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sekhem": {"base": "Sekhem", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Serpent Wand": {"base": "Serpent Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Serpentscale Gauntlets": {"base": "Serpentscale Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sinner Tricorne": {"base": "Sinner Tricorne", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Slink Boots": {"base": "Slink Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Slink Gloves": {"base": "Slink Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Stag Sceptre": {"base": "Stag Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Steel Gauntlets": {"base": "Steel Gauntlets", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Tornado Wand": {"base": "Tornado Wand", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Trisula": {"base": "Trisula", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Tyrant's Sekhem": {"base": "Tyrant's Sekhem", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Unset Ring": {"base": "Unset Ring", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vaal Regalia": {"base": "Vaal Regalia", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Shaper Vaal Sceptre": {"base": "Vaal Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Arcanist Gloves": {"base": "Arcanist Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Grove Bow": {"base": "Grove Bow", "other": ["ElderItem True", "ItemLevel 85"], "type": "base extremely high"},
	"1 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Lapis Amulet": {"base": "Lapis Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Opal Wand": {"base": "Opal Wand", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Prophet Crown": {"base": "Prophet Crown", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Steel Gauntlets": {"base": "Steel Gauntlets", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"1 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 85"], "type": "base very high"},
	"2 Shaper Abyssal Sceptre": {"base": "Abyssal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Ambusher": {"base": "Ambusher", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Arcanist Gloves": {"base": "Arcanist Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Carnal Sceptre": {"base": "Carnal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Amulet": {"base": "Coral Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Engraved Wand": {"base": "Engraved Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Gold Amulet": {"base": "Gold Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Golden Kris": {"base": "Golden Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Heathen Wand": {"base": "Heathen Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Imperial Bow": {"base": "Imperial Bow", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Imperial Skean": {"base": "Imperial Skean", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Leather Belt": {"base": "Leather Belt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Lion Pelt": {"base": "Lion Pelt", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Mind Cage": {"base": "Mind Cage", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Murder Mitts": {"base": "Murder Mitts", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Opal Wand": {"base": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Paua Amulet": {"base": "Paua Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Profane Wand": {"base": "Profane Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Prophecy Wand": {"base": "Prophecy Wand", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sadist Garb": {"base": "Sadist Garb", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Satin Gloves": {"base": "Satin Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Shagreen Gloves": {"base": "Shagreen Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sharkskin Gloves": {"base": "Sharkskin Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Slink Gloves": {"base": "Slink Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Stealth Gloves": {"base": "Stealth Gloves", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Topaz Ring": {"base": "Topaz Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Shaper Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Bone Helmet": {"base": "Bone Helmet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base extremely high"},
	"2 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Hubris Circlet": {"base": "Hubris Circlet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Murder Boots": {"base": "Murder Boots", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Titan Gauntlets": {"base": "Titan Gauntlets", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 84"], "type": "base very high"},
	"2 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel 84"], "type": "base very high"},
	"3 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Coral Ring": {"base": "Coral Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Crystal Belt": {"base": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Crystal Sceptre": {"base": "Crystal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Eelskin Gloves": {"base": "Eelskin Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Gripped Gloves": {"base": "Gripped Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Jewelled Foil": {"base": "Jewelled Foil", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Maraketh Bow": {"base": "Maraketh Bow", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Opal Wand": {"base": "Opal Wand", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Poignard": {"base": "Poignard", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Profane Wand": {"base": "Profane Wand", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Ruby Ring": {"base": "Ruby Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sambar Sceptre": {"base": "Sambar Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Spiked Gloves": {"base": "Spiked Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Stag Sceptre": {"base": "Stag Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Stealth Gloves": {"base": "Stealth Gloves", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Astral Plate": {"base": "Astral Plate", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Crystal Belt": {"base": "Crystal Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base extremely high"},
	"3 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Glorious Leather": {"base": "Glorious Leather", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Gripped Gloves": {"base": "Gripped Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Heavy Belt": {"base": "Heavy Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Leather Belt": {"base": "Leather Belt", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Silken Hood": {"base": "Silken Hood", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"3 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 83"], "type": "base very high"},
	"4 Shaper Agate Amulet": {"base": "Agate Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Amber Amulet": {"base": "Amber Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Citrine Amulet": {"base": "Citrine Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Crystal Belt": {"base": "Crystal Belt", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Diamond Ring": {"base": "Diamond Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Eclipse Staff": {"base": "Eclipse Staff", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Hubris Circlet": {"base": "Hubris Circlet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base extremely high"},
	"4 Shaper Iron Ring": {"base": "Iron Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Jade Amulet": {"base": "Jade Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Lapis Amulet": {"base": "Lapis Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Moon Staff": {"base": "Moon Staff", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Onyx Amulet": {"base": "Onyx Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Opal Sceptre": {"base": "Opal Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Platinum Kris": {"base": "Platinum Kris", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sapphire Ring": {"base": "Sapphire Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sorcerer Boots": {"base": "Sorcerer Boots", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Sorcerer Gloves": {"base": "Sorcerer Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Stealth Gloves": {"base": "Stealth Gloves", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Turquoise Amulet": {"base": "Turquoise Amulet", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Stone Ring": {"base": "Two-Stone Ring", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Two-Toned Boots": {"base": "Two-Toned Boots", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Shaper Void Sceptre": {"base": "Void Sceptre", "other": ["ShaperItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Agate Amulet": {"base": "Agate Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Amber Amulet": {"base": "Amber Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Citrine Amulet": {"base": "Citrine Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Coral Ring": {"base": "Coral Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Diamond Ring": {"base": "Diamond Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Eternal Burgonet": {"base": "Eternal Burgonet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Gold Ring": {"base": "Gold Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Iron Ring": {"base": "Iron Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Jade Amulet": {"base": "Jade Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Moonstone Ring": {"base": "Moonstone Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Onyx Amulet": {"base": "Onyx Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Paua Amulet": {"base": "Paua Amulet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Royal Burgonet": {"base": "Royal Burgonet", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Ruby Ring": {"base": "Ruby Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Sapphire Ring": {"base": "Sapphire Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Soldier Gloves": {"base": "Soldier Gloves", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Topaz Ring": {"base": "Topaz Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Elder Unset Ring": {"base": "Unset Ring", "other": ["ElderItem True", "ItemLevel 82"], "type": "base very high"},
	"4 Steel Ring": {"base": "Steel Ring", "other": ["ItemLevel 82"], "type": "base very high"},

}
