#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:24:53 UTC from "tmphardcore" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 Enchantment Flame Surge Vs Burning Enemies 1": {"enchant": "Enchantment Flame Surge Vs Burning Enemies 1", "type": "ignore"},
	"1 +36% to Raised Zombie Elemental Resistances": {"enchant": "Enchantment Zombie Elemental Resistances 2", "type": "currency very high"},
	"1 10% Chance to gain a Power Charge on Critical Strike with Ice Spear": {"enchant": "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 1", "type": "currency very high"},
	"1 10% increased Incinerate Damage for each stage": {"enchant": "Enchantment Incinerate Damage Per Stage 3", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Chaos Golems": {"enchant": "Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Flame Golems": {"enchant": "Enchantment Flame Golem Granted Buff Effect 1", "type": "currency very high"},
	"1 12% increased Ancestral Warchief Totem Area of Effect": {"enchant": "Enchantment Ancestor Warchief Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Blade Vortex Area of Effect": {"enchant": "Enchantment Blade Vortex Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Blight Area of Effect": {"enchant": "Enchantment Blight Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Contagion Area of Effect": {"enchant": "Enchantment Contagion Radius 2", "type": "currency very high"},
	"1 12% increased Fireball Cast Speed": {"enchant": "Enchantment Fireball Cast Speed 2", "type": "currency very high"},
	"1 12% increased Freezing Pulse Cast Speed": {"enchant": "Enchantment Freezing Pulse Cast Speed 2", "type": "currency very high"},
	"1 12% increased Infernal Blow Area of Effect": {"enchant": "Enchantment Infernal Blow Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Lightning Arrow Area of Effect": {"enchant": "Enchantment Lightning Arrow Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Rain of Arrows Area of Effect": {"enchant": "Enchantment Rain Of Arrows Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Reave Radius": {"enchant": "Enchantment Reave Area Of Effect 2", "type": "currency very high"},
	"1 12% increased Scorching Ray Cast Speed": {"enchant": "Enchantment Fire Beam Cast Speed 2", "type": "currency very high"},
	"1 12% increased Tectonic Slam Area of Effect": {"enchant": "Enchantment Tectonic Slam Area Of Effect 2", "type": "currency very high"},
	"1 15% increased Cleave Attack Speed": {"enchant": "Enchantment Cleave Attack Speed 2", "type": "currency very high"},
	"1 15% increased Cyclone Attack Speed": {"enchant": "Enchantment Cyclone Attack Speed 2", "type": "currency very high"},
	"1 15% increased Double Strike Attack Speed": {"enchant": "Enchantment Double Strike Attack Speed 2", "type": "currency very high"},
	"1 15% increased Elemental Hit Attack Speed": {"enchant": "Enchantment Elemental Hit Attack Speed 2", "type": "currency very high"},
	"1 15% increased Explosive Arrow Attack Speed": {"enchant": "Enchantment Explosive Arrow Attack Speed 2", "type": "currency very high"},
	"1 15% increased Power Siphon Attack Speed": {"enchant": "Enchantment Power Siphon Attack Speed 2", "type": "currency very high"},
	"1 15% of Shrapnel Shot Physical Damage gained as extra Lightning Damage": {"enchant": "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Ice Golems": {"enchant": "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Stone Golems": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 20% increased Temporal Chains Curse Effect": {"enchant": "Enchantment Temporal Chains Curse Effect 1", "type": "currency very high"},
	"1 20% reduced Storm Call Duration": {"enchant": "Enchantment Storm Call Duration 1", "type": "currency very high"},
	"1 24% increased Decoy Totem Area of Effect": {"enchant": "Enchantment Decoy Totem Area Of Effect 2", "type": "currency very high"},
	"1 25% increased Freezing Pulse Damage": {"enchant": "Enchantment Freezing Pulse Damage 1", "type": "currency very high"},
	"1 30% chance for Discharge to deal Damage without removing Charges": {"enchant": "Enchantment Discharge Consume Charges 2", "type": "currency very high"},
	"1 30% increased Assassin's Mark Curse Effect": {"enchant": "Enchantment Assassins Mark Curse Effect 2", "type": "currency very high"},
	"1 30% increased Blade Vortex Duration": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "currency very high"},
	"1 30% increased Convocation Cooldown Recovery Speed": {"enchant": "Enchantment Convocation Cooldown Speed 2", "type": "currency very high"},
	"1 30% increased Despair Curse Effect": {"enchant": "Enchantment Despair Effect 2", "type": "currency very high"},
	"1 30% increased Enduring Cry Cooldown Recovery Speed": {"enchant": "Enchantment Enduring Cry Cooldown Speed 2", "type": "currency very high"},
	"1 30% increased Ethereal Knives Projectile Speed": {"enchant": "Enchantment Ethereal Knives Projectile Speed 2", "type": "currency very high"},
	"1 30% increased Flame Dash Cooldown Recovery Speed": {"enchant": "Enchantment Flame Dash Cooldown Speed 2", "type": "currency very high"},
	"1 30% increased Freezing Pulse Projectile Speed": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "currency very high"},
	"1 30% increased Poacher's Mark Curse Effect": {"enchant": "Enchantment Poachers Mark Curse Effect 2", "type": "currency very high"},
	"1 30% increased Spark Projectile Speed": {"enchant": "Enchantment Spark Projectile Speed 2", "type": "currency very high"},
	"1 30% increased Temporal Chains Curse Effect": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "currency extremely high"},
	"1 30% increased Vortex Duration": {"enchant": "Enchantment Vortex Duration 2", "type": "currency very high"},
	"1 30% reduced Earthquake Duration": {"enchant": "Enchantment Earthquake Duration 2", "type": "currency very high"},
	"1 30% reduced Lightning Warp Duration": {"enchant": "Enchantment Lightning Warp Duration 2", "type": "currency very high"},
	"1 30% reduced Spectral Throw Projectile Deceleration": {"enchant": "Enchantment Spectral Throw Projectile Deceleration 2", "type": "currency very high"},
	"1 30% reduced Storm Call Duration": {"enchant": "Enchantment Storm Call Duration 2", "type": "currency extremely high"},
	"1 300% increased Ice Spear Critical Strike Chance in second form": {"enchant": "Enchantment Ice Spear Second Form Critical Strike Chance 2", "type": "currency very high"},
	"1 36% increased Convocation Buff Effect": {"enchant": "Enchantment Convocation Life Regeneration 2", "type": "currency very high"},
	"1 36% increased Devouring Totem Leech per second": {"enchant": "Enchantment Devouring Totem Leech Per Second 2", "type": "currency very high"},
	"1 36% increased Searing Bond Totem Elemental Resistances": {"enchant": "Enchantment Searing Bond Totem Elemental Resistances 2", "type": "currency very high"},
	"1 40% increased Ancestral Warchief Totem Damage": {"enchant": "Enchantment Ancestral Warchief Damage 2", "type": "currency very high"},
	"1 40% increased Arc Damage": {"enchant": "Enchantment Arc Damage 2", "type": "currency very high"},
	"1 40% increased Arctic Breath Damage": {"enchant": "Enchantment Arctic Breath Damage 2", "type": "currency very high"},
	"1 40% increased Ball Lightning Damage": {"enchant": "Enchantment Ball Lightning Damage 2", "type": "currency very high"},
	"1 40% increased Blade Flurry Damage": {"enchant": "Enchantment Blade Flurry Damage 2", "type": "currency very high"},
	"1 40% increased Blade Vortex Spell Damage": {"enchant": "Enchantment Blade Vortex Damage 2", "type": "currency very high"},
	"1 40% increased Blast Rain Damage": {"enchant": "Enchantment Blast Rain Damage 2", "type": "currency very high"},
	"1 40% increased Caustic Arrow Damage": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "currency very high"},
	"1 40% increased Cyclone Damage": {"enchant": "Enchantment Cyclone Damage 2", "type": "currency very high"},
	"1 40% increased Detonate Dead Damage": {"enchant": "Enchantment Detonate Dead Damage 2", "type": "currency very high"},
	"1 40% increased Double Strike Damage": {"enchant": "Enchantment Double Strike Damage 2", "type": "currency very high"},
	"1 40% increased Essence Drain Damage": {"enchant": "Enchantment Essence Drain Damage 2", "type": "currency very high"},
	"1 40% increased Ethereal Knives Damage": {"enchant": "Enchantment Ethereal Knives Damage 2", "type": "currency very high"},
	"1 40% increased Fireball Damage": {"enchant": "Enchantment Fireball Damage 2", "type": "currency very high"},
	"1 40% increased Flicker Strike Damage": {"enchant": "Enchantment Flicker Strike Damage 2", "type": "currency very high"},
	"1 40% increased Freezing Pulse Damage": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "currency very high"},
	"1 40% increased Frost Blades Damage": {"enchant": "Enchantment Frost Blades Damage 2", "type": "currency extremely high"},
	"1 40% increased Glacial Cascade Damage": {"enchant": "Enchantment Glacial Cascade Damage 2", "type": "currency very high"},
	"1 40% increased Ice Nova Damage": {"enchant": "Enchantment Ice Nova Damage 2", "type": "currency extremely high"},
	"1 40% increased Ice Shot Damage": {"enchant": "Enchantment Ice Shot Damage 2", "type": "currency very high"},
	"1 40% increased Incinerate Damage": {"enchant": "Enchantment Incinerate Damage 2", "type": "currency very high"},
	"1 40% increased Kinetic Blast Damage": {"enchant": "Enchantment Kinetic Blast Damage 2", "type": "currency very high"},
	"1 40% increased Lacerate Damage": {"enchant": "Enchantment Lacerate Damage 2", "type": "currency very high"},
	"1 40% increased Lightning Trap Damage": {"enchant": "Enchantment Lightning Trap Damage 2", "type": "currency very high"},
	"1 40% increased Lightning Warp Damage": {"enchant": "Enchantment Lightning Warp Damage 2", "type": "currency very high"},
	"1 40% increased Molten Strike Damage": {"enchant": "Enchantment Molten Strike Damage 2", "type": "currency very high"},
	"1 40% increased Orb of Storms Damage": {"enchant": "Enchantment Orb Of Storms Damage 2", "type": "currency very high"},
	"1 40% increased Power Siphon Damage": {"enchant": "Enchantment Power Siphon Damage 2", "type": "currency very high"},
	"1 40% increased Righteous Fire Damage": {"enchant": "Enchantment Righteous Fire Damage 2", "type": "currency very high"},
	"1 40% increased Shockwave Totem Damage": {"enchant": "Enchantment Shockwave Totem Damage 2", "type": "currency very high"},
	"1 40% increased Spark Damage": {"enchant": "Enchantment Spark Damage 2", "type": "currency very high"},
	"1 40% increased Spectral Throw Damage": {"enchant": "Enchantment Spectral Throw Damage 2", "type": "currency very high"},
	"1 40% increased Sweep Damage": {"enchant": "Enchantment Sweep Damage 2", "type": "currency very high"},
	"1 40% increased Tectonic Slam Damage": {"enchant": "Enchantment Tectonic Slam Damage 2", "type": "currency very high"},
	"1 40% increased Tornado Shot Damage": {"enchant": "Enchantment Tornado Shot Damage 2", "type": "currency very high"},
	"1 40% increased Volatile Dead Damage": {"enchant": "Enchantment Volatile Dead Damage 2", "type": "currency very high"},
	"1 40% increased Vortex Damage": {"enchant": "Enchantment Vortex Damage 2", "type": "currency very high"},
	"1 40% increased Wild Strike Damage": {"enchant": "Enchantment Wild Strike Damage 2", "type": "currency very high"},
	"1 40% of Glacial Cascade Physical Damage Converted to Cold Damage": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2", "type": "currency very high"},
	"1 45% increased Conductivity Duration": {"enchant": "Enchantment Conductivity Duration 2", "type": "currency very high"},
	"1 45% increased Static Strike Duration": {"enchant": "Enchantment Static Strike Duration 2", "type": "currency very high"},
	"1 45% increased Temporal Chains Duration": {"enchant": "Enchantment Temporal Chains Duration 2", "type": "currency very high"},
	"1 6% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 1", "type": "currency very high"},
	"1 8% increased Blade Flurry Area of Effect": {"enchant": "Enchantment Blade Flurry Area Of Effect 1", "type": "currency very high"},
	"1 8% increased Freeze Mine Area of Effect": {"enchant": "Enchantment Freeze Mine Area Of Effect 1", "type": "currency very high"},
	"1 8% increased Glacial Cascade Area of Effect": {"enchant": "Enchantment Glacial Cascade Area Of Effect 1", "type": "currency very high"},
	"1 8% increased Lightning Warp Cast Speed": {"enchant": "Enchantment Lightning Warp Cast Speed 1", "type": "currency very high"},
	"1 9% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 9% increased Frenzy Damage per Frenzy Charge": {"enchant": "Enchantment Frenzy Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 90% increased Double Strike Critical Strike Chance": {"enchant": "Enchantment Double Strike Critical Strike Chance 2", "type": "currency very high"},
	"1 Ancestral Warchief Totem grants 30% increased Melee Damage while Active": {"enchant": "Enchantment Ancestor Warchief Melee Damage 2", "type": "currency very high"},
	"1 Arc Chains an additional time": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "currency very high"},
	"1 Arc has +30% chance to Shock": {"enchant": "Enchantment Arc Shock Chance 2", "type": "currency very high"},
	"1 Arctic Breath's Chilling Area has 38% increased Movement Speed": {"enchant": "Enchantment Arctic Breath Chilling Area Movement Velocity 1", "type": "currency very high"},
	"1 Armageddon Brand deals 40% increased Damage": {"enchant": "Enchantment Armageddon Brand Damage 2", "type": "currency very high"},
	"1 Bane deals 25% increased Damage": {"enchant": "Enchantment Bane Damage 1", "type": "currency very high"},
	"1 Bane deals 40% increased Damage": {"enchant": "Enchantment Bane Damage 2", "type": "currency very high"},
	"1 Bane has 15% increased Area of Effect": {"enchant": "Enchantment Bane Area Of Effect 2", "type": "currency very high"},
	"1 Barrage fires an additional Projectile": {"enchant": "Enchantment Barrage Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Blade Vortex has +3% to Critical Strike Multiplier for each blade": {"enchant": "Enchantment Blade Vortex Crit Multi Per Blade 2", "type": "currency very high"},
	"1 Bladefall has an additional Volley": {"enchant": "Enchantment Bladefall Additional Volley", "type": "currency very high"},
	"1 Blast Rain has a 75% chance for an additional blast": {"enchant": "Enchantment Blast Rain Additional Blast 2", "type": "currency very high"},
	"1 Blink Arrow and Blink Arrow Clones have 25% increased Damage": {"enchant": "Enchantment Blink Arrow Damage 1", "type": "currency very high"},
	"1 Blood Rage grants additional 12% increased Attack Speed": {"enchant": "Enchantment Blood Rage Attack Speed 2", "type": "currency very high"},
	"1 Blood Rage grants additional 30% chance to gain a Frenzy Charge on Kill": {"enchant": "Enchantment Blood Rage Frenzy On Kill 2", "type": "currency very high"},
	"1 Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration": {"enchant": "Enchantment Caustic Arrow Wither On Hit 2", "type": "currency very high"},
	"1 Chaos Golems deal 40% increased Damage": {"enchant": "Enchantment Sumon Chaos Golem Damage 2", "type": "currency very high"},
	"1 Chills from Ice Nova Hits always reduce Action Speed by at least 6%": {"enchant": "Enchantment Ice Nova Minimum Chill 1", "type": "currency very high"},
	"1 Clarity has 30% reduced Mana Reservation": {"enchant": "Enchantment Clarity Mana Reservation 2", "type": "currency very high"},
	"1 Consecrated Ground from Holy Flame Totem applies 9% increased Damage taken to Enemies": {"enchant": "Enchantment Flame Totem Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Consecrated Path deals 40% increased Damage": {"enchant": "Enchantment Consecrated Path Damage 2", "type": "currency very high"},
	"1 Consecrated Path has 12% increased Area of Effect": {"enchant": "Enchantment Consecrated Path Area Of Effect 2", "type": "currency very high"},
	"1 Converted Enemies have 40% increased Damage": {"enchant": "Enchantment Conversion Trap Damage 2", "type": "currency very high"},
	"1 Discipline has 20% reduced Mana Reservation": {"enchant": "Enchantment Discipline Mana Reservation 2", "type": "currency very high"},
	"1 Divine Ire Damages 2 additional nearby Enemies when gaining Stages": {"enchant": "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2", "type": "currency very high"},
	"1 Divine Ire deals 40% increased Damage": {"enchant": "Enchantment Divine Ire Damage 2", "type": "currency very high"},
	"1 Divine Ire's beam has 15% increased width": {"enchant": "Enchantment Divine Ire Beam Width 2", "type": "currency very high"},
	"1 Dominating Blow can summon 3 additional Magic Sentinels of Dominance": {"enchant": "Enchantment Dominating Blow Additional Magic 2", "type": "currency very high"},
	"1 Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 1", "type": "currency very high"},
	"1 Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 2", "type": "currency very high"},
	"1 Dread Banner has 25% increased Aura Effect": {"enchant": "Enchantment Dread Banner Effect 1", "type": "currency very high"},
	"1 Dread Banner has 40% increased Aura Effect": {"enchant": "Enchantment Dread Banner Effect 2", "type": "currency very high"},
	"1 Elemental Hit deals 40% increased Damage": {"enchant": "Enchantment Elemental Hit Damage 2", "type": "currency very high"},
	"1 Fire Nova Mine repeats an additional 2 times": {"enchant": "Enchantment Fire Nova Mine Num Of Additional Repeats 2", "type": "currency very high"},
	"1 Fireball has +30% chance to Ignite": {"enchant": "Enchantment Fireball Ignite Chance 2", "type": "currency very high"},
	"1 Flamethrower Trap has 2 additional Flames": {"enchant": "Enchantment Flamethrower Additional Flamethrowers 2", "type": "currency very high"},
	"1 Flesh Offering grants an additional 21% increased Attack Speed": {"enchant": "Enchantment Flesh Offering Attack Speed 2", "type": "currency very high"},
	"1 Frost Bomb has 30% increased Debuff Duration": {"enchant": "Enchantment Frost Bomb Increased Duration 2", "type": "currency very high"},
	"1 Hatred has 15% reduced Mana Reservation": {"enchant": "Enchantment Hatred Mana Reservation 2", "type": "currency very high"},
	"1 Heavy Strike has a 12% chance to deal Double Damage": {"enchant": "Enchantment Heavy Strike Double Damage 2", "type": "currency very high"},
	"1 Herald of Agony has 20% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Agony Mana Reservation 1", "type": "currency very high"},
	"1 Herald of Agony has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Agony Mana Reservation 2", "type": "currency extremely high"},
	"1 Herald of Ash has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Ash Mana Reservation 2", "type": "currency very high"},
	"1 Herald of Ice has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Ice Mana Reservation 2", "type": "currency very high"},
	"1 Herald of Purity has 30% reduced Mana Reservation": {"enchant": "Enchantment Herald Of Purity Mana Reservation 2", "type": "currency very high"},
	"1 Holy Flame Totem deals 40% increased Damage": {"enchant": "Enchantment Flame Totem Damage 2", "type": "currency very high"},
	"1 Holy Flame Totem fires 2 additional Projectiles": {"enchant": "Enchantment Flame Totem Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Holy Flame Totem has 30% increased Projectile Speed": {"enchant": "Enchantment Flame Totem Projectile Speed 2", "type": "currency very high"},
	"1 Ice Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Ice Golem Damage 2", "type": "currency very high"},
	"1 Ice Spear fires an additional Projectile": {"enchant": "Enchantment Ice Spear Additional Projectile 1", "type": "currency extremely high"},
	"1 Ice Spear travels 30% reduced distance before changing forms": {"enchant": "Enchantment Ice Spear Distance Before Form Change 2", "type": "currency very high"},
	"1 Ice Trap Damage Penetrates 10% Cold Resistance": {"enchant": "Enchantment Ice Trap Cold Penetration 2", "type": "currency very high"},
	"1 Incinerate has +2 to maximum stages": {"enchant": "Enchantment Incinerate Maximum Stages 2", "type": "currency very high"},
	"1 Kinetic Blast has a 75% chance for an additional explosion": {"enchant": "Enchantment Kinetic Blast Explosions 2", "type": "currency very high"},
	"1 Lightning Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Lightning Golem Damage 2", "type": "currency very high"},
	"1 Lightning Trap Damage Penetrates 10% Lightning Resistance": {"enchant": "Enchantment Lightning Trap Penetration 2", "type": "currency very high"},
	"1 Lightning Trap Damage Penetrates 6% Lightning Resistance": {"enchant": "Enchantment Lightning Trap Penetration 1", "type": "currency very high"},
	"1 Lightning Trap pierces 3 additional Targets": {"enchant": "Enchantment Lightning Trap Additional Pierce 2", "type": "currency very high"},
	"1 Magma Orb Chains an additional 2 times": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Malevolence has 15% reduced Mana Reservation": {"enchant": "Enchantment Malevolence Mana Reservation 2", "type": "currency very high"},
	"1 Molten Strike fires 2 additional Projectiles": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 2", "type": "currency extremely high"},
	"1 Molten Strike fires an additional Projectile": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Purifying Flame deals 40% increased Damage": {"enchant": "Enchantment Purifying Flame Damage 2", "type": "currency very high"},
	"1 Purity of Fire has 20% reduced Mana Reservation": {"enchant": "Enchantment Purity Of Fire Mana Reservation 2", "type": "currency very high"},
	"1 Purity of Lightning has 20% reduced Mana Reservation": {"enchant": "Enchantment Purity Of Lightning Mana Reservation 2", "type": "currency very high"},
	"1 Rain of Arrows has 15% chance to fire an additional sequence of arrows": {"enchant": "Enchantment Rain Of Arrows Repeat Count 2", "type": "currency very high"},
	"1 Righteous Fire grants 30% increased Spell Damage": {"enchant": "Enchantment Righteous Fire Spell Damage 2", "type": "currency very high"},
	"1 Scourge Arrow creates an additional spore pod at Maximum Stages": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "currency very high"},
	"1 Scourge Arrow deals 40% increased Damage": {"enchant": "Enchantment Scourge Arrow Damage 2", "type": "currency very high"},
	"1 Scourge Arrow has 8% chance to Poison per Stage": {"enchant": "Enchantment Scourge Arrow Chance To Poison 2", "type": "currency very high"},
	"1 Shattering Steel fires an additional Projectile": {"enchant": "Enchantment Shattering Steel Additional Projectile 1", "type": "currency very high"},
	"1 Shattering Steel grants Fortify on Hitting an Enemy at Close Range": {"enchant": "Enchantment Shattering Steel Fortify On Hit Close Range 1", "type": "currency very high"},
	"1 Shock Nova ring deals 60% increased Damage": {"enchant": "Enchantment Shock Nova Larger Ring Damage 2", "type": "currency very high"},
	"1 Siphoning Trap has 45% increased Skill Effect Duration": {"enchant": "Enchantment Ice Siphon Trap Duration 2", "type": "currency very high"},
	"1 Smoke Mine grants additional 30% increased Movement Speed": {"enchant": "Enchantment Smoke Mine Movement Speed 2", "type": "currency very high"},
	"1 Soulrend deals 40% increased Damage": {"enchant": "Enchantment Soulrend Damage 2", "type": "currency very high"},
	"1 Soulrend fires an additional Projectile": {"enchant": "Enchantment Soulrend Number Of Additional Projectiles 1", "type": "currency very high"},
	"1 Spark fires 2 additional Projectiles": {"enchant": "Enchantment Spark Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Spark fires 3 additional Projectiles": {"enchant": "Enchantment Spark Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Spectres have 40% increased Damage": {"enchant": "Enchantment Raise Spectre Damage 2", "type": "currency very high"},
	"1 Split Arrow fires 3 additional Projectiles": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Stone Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Stone Golem Damage 2", "type": "currency very high"},
	"1 Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "currency very high"},
	"1 Storm Brand deals 25% increased Damage": {"enchant": "Enchantment Storm Brand Damage 1", "type": "currency very high"},
	"1 Storm Brand deals 40% increased Damage": {"enchant": "Enchantment Storm Brand Damage 2", "type": "currency very high"},
	"1 Storm Brand has a 18% chance to Chain an additional time": {"enchant": "Storm Brand Additional Chain Chance 2", "type": "currency very high"},
	"1 Storm Burst has a 15% chance to create an additional Orb": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "currency very high"},
	"1 Summoned Agony Crawler fires 2 additional Projectiles": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "currency extremely high"},
	"1 Tectonic Slam has 20% chance to create a Charged Slam": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 2", "type": "currency very high"},
	"1 Tornado Shot fires 2 additional secondary Projectiles": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 2", "type": "currency extremely high"},
	"1 Tornado Shot fires an additional secondary Projectile": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 1", "type": "currency very high"},
	"1 Toxic Rain deals 40% increased Damage": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "currency very high"},
	"1 Toxic Rain fires 1 additional Arrow": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Vortex has 30% increased Cooldown Recovery Speed": {"enchant": "Enchantment Vortex Cooldown Recovery 2", "type": "currency very high"},
	"1 Wave of Conviction deals 40% increased Damage": {"enchant": "Enchantment Wave Of Conviction Damage 2", "type": "currency very high"},
	"1 Wave of Conviction has 30% increased Duration": {"enchant": "Enchantment Wave Of Conviction Duration 2", "type": "currency very high"},
	"1 Wave of Conviction's Exposure applies -6% Elemental Resistance": {"enchant": "Enchantment Wave Of Conviction Additional Enemy Resistance 2", "type": "currency very high"},
	"1 Wild Strike Chains an additional 6 times": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Winter Orb deals 25% increased Damage": {"enchant": "Enchantment Winter Orb Damage 1", "type": "currency very high"},
	"1 Winter Orb deals 40% increased Damage": {"enchant": "Enchantment Winter Orb Damage 2", "type": "currency extremely high"},
	"1 Winter Orb has +2 Maximum Stages": {"enchant": "Enchantment Frost Fury Additional Max Number Of Stages 1", "type": "currency extremely high"},
	"1 Winter Orb has 3% increased Area of Effect per Stage": {"enchant": "Enchantment Frost Fury Area Of Effect Per Stage 2", "type": "currency very high"},
	"1 Wither has 12% increased Area of Effect": {"enchant": "Enchantment Wither Area Of Effect 2", "type": "currency very high"},
	"1 Zealotry has 15% reduced Mana Reservation": {"enchant": "Enchantment Zealotry Mana Reservation 2", "type": "currency very high"},
}
