#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:17:19 UTC from "tmphardcore" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 Enchantment Flame Surge Vs Burning Enemies 1": {"enchant": "Enchantment Flame Surge Vs Burning Enemies 1", "type": "ignore"},
	"1 Enchantment Zombie Elemental Resistances 2": {"enchant": "Enchantment Zombie Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 1": {"enchant": "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 1", "type": "currency very high"},
	"1 Enchantment Incinerate Damage Per Stage 3": {"enchant": "Enchantment Incinerate Damage Per Stage 3", "type": "currency very high"},
	"1 Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2": {"enchant": "Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2", "type": "currency very high"},
	"1 Enchantment Flame Golem Granted Buff Effect 1": {"enchant": "Enchantment Flame Golem Granted Buff Effect 1", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Area Of Effect 2": {"enchant": "Enchantment Ancestor Warchief Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Area Of Effect 2": {"enchant": "Enchantment Blade Vortex Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Blight Area Of Effect 2": {"enchant": "Enchantment Blight Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Contagion Radius 2": {"enchant": "Enchantment Contagion Radius 2", "type": "currency very high"},
	"1 Enchantment Fireball Cast Speed 2": {"enchant": "Enchantment Fireball Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Cast Speed 2": {"enchant": "Enchantment Freezing Pulse Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Infernal Blow Area Of Effect 2": {"enchant": "Enchantment Infernal Blow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Lightning Arrow Area Of Effect 2": {"enchant": "Enchantment Lightning Arrow Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Area Of Effect 2": {"enchant": "Enchantment Rain Of Arrows Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Reave Area Of Effect 2": {"enchant": "Enchantment Reave Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Fire Beam Cast Speed 2": {"enchant": "Enchantment Fire Beam Cast Speed 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Area Of Effect 2": {"enchant": "Enchantment Tectonic Slam Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Cleave Attack Speed 2": {"enchant": "Enchantment Cleave Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Cyclone Attack Speed 2": {"enchant": "Enchantment Cyclone Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Double Strike Attack Speed 2": {"enchant": "Enchantment Double Strike Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Attack Speed 2": {"enchant": "Enchantment Elemental Hit Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Explosive Arrow Attack Speed 2": {"enchant": "Enchantment Explosive Arrow Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Attack Speed 2": {"enchant": "Enchantment Power Siphon Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2": {"enchant": "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2": {"enchant": "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2", "type": "currency very high"},
	"1 Enchantment Stone Golem Granted Buff Effect 2": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Curse Effect 1": {"enchant": "Enchantment Temporal Chains Curse Effect 1", "type": "currency very high"},
	"1 Enchantment Storm Call Duration 1": {"enchant": "Enchantment Storm Call Duration 1", "type": "currency very high"},
	"1 Enchantment Decoy Totem Area Of Effect 2": {"enchant": "Enchantment Decoy Totem Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Damage 1": {"enchant": "Enchantment Freezing Pulse Damage 1", "type": "currency very high"},
	"1 Enchantment Discharge Consume Charges 2": {"enchant": "Enchantment Discharge Consume Charges 2", "type": "currency very high"},
	"1 Enchantment Assassins Mark Curse Effect 2": {"enchant": "Enchantment Assassins Mark Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Duration 2": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "currency very high"},
	"1 Enchantment Convocation Cooldown Speed 2": {"enchant": "Enchantment Convocation Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Despair Effect 2": {"enchant": "Enchantment Despair Effect 2", "type": "currency very high"},
	"1 Enchantment Enduring Cry Cooldown Speed 2": {"enchant": "Enchantment Enduring Cry Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Projectile Speed 2": {"enchant": "Enchantment Ethereal Knives Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Flame Dash Cooldown Speed 2": {"enchant": "Enchantment Flame Dash Cooldown Speed 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Projectile Speed 2": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Poachers Mark Curse Effect 2": {"enchant": "Enchantment Poachers Mark Curse Effect 2", "type": "currency very high"},
	"1 Enchantment Spark Projectile Speed 2": {"enchant": "Enchantment Spark Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Curse Effect 2": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "currency extremely high"},
	"1 Enchantment Vortex Duration 2": {"enchant": "Enchantment Vortex Duration 2", "type": "currency very high"},
	"1 Enchantment Earthquake Duration 2": {"enchant": "Enchantment Earthquake Duration 2", "type": "currency very high"},
	"1 Enchantment Lightning Warp Duration 2": {"enchant": "Enchantment Lightning Warp Duration 2", "type": "currency very high"},
	"1 Enchantment Spectral Throw Projectile Deceleration 2": {"enchant": "Enchantment Spectral Throw Projectile Deceleration 2", "type": "currency very high"},
	"1 Enchantment Storm Call Duration 2": {"enchant": "Enchantment Storm Call Duration 2", "type": "currency extremely high"},
	"1 Enchantment Ice Spear Second Form Critical Strike Chance 2": {"enchant": "Enchantment Ice Spear Second Form Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Convocation Life Regeneration 2": {"enchant": "Enchantment Convocation Life Regeneration 2", "type": "currency very high"},
	"1 Enchantment Devouring Totem Leech Per Second 2": {"enchant": "Enchantment Devouring Totem Leech Per Second 2", "type": "currency very high"},
	"1 Enchantment Searing Bond Totem Elemental Resistances 2": {"enchant": "Enchantment Searing Bond Totem Elemental Resistances 2", "type": "currency very high"},
	"1 Enchantment Ancestral Warchief Damage 2": {"enchant": "Enchantment Ancestral Warchief Damage 2", "type": "currency very high"},
	"1 Enchantment Arc Damage 2": {"enchant": "Enchantment Arc Damage 2", "type": "currency very high"},
	"1 Enchantment Arctic Breath Damage 2": {"enchant": "Enchantment Arctic Breath Damage 2", "type": "currency very high"},
	"1 Enchantment Ball Lightning Damage 2": {"enchant": "Enchantment Ball Lightning Damage 2", "type": "currency very high"},
	"1 Enchantment Blade Flurry Damage 2": {"enchant": "Enchantment Blade Flurry Damage 2", "type": "currency very high"},
	"1 Enchantment Blade Vortex Damage 2": {"enchant": "Enchantment Blade Vortex Damage 2", "type": "currency very high"},
	"1 Enchantment Blast Rain Damage 2": {"enchant": "Enchantment Blast Rain Damage 2", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Damage 2": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Cyclone Damage 2": {"enchant": "Enchantment Cyclone Damage 2", "type": "currency very high"},
	"1 Enchantment Detonate Dead Damage 2": {"enchant": "Enchantment Detonate Dead Damage 2", "type": "currency very high"},
	"1 Enchantment Double Strike Damage 2": {"enchant": "Enchantment Double Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Essence Drain Damage 2": {"enchant": "Enchantment Essence Drain Damage 2", "type": "currency very high"},
	"1 Enchantment Ethereal Knives Damage 2": {"enchant": "Enchantment Ethereal Knives Damage 2", "type": "currency very high"},
	"1 Enchantment Fireball Damage 2": {"enchant": "Enchantment Fireball Damage 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage 2": {"enchant": "Enchantment Flicker Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Freezing Pulse Damage 2": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "currency very high"},
	"1 Enchantment Frost Blades Damage 2": {"enchant": "Enchantment Frost Blades Damage 2", "type": "currency extremely high"},
	"1 Enchantment Glacial Cascade Damage 2": {"enchant": "Enchantment Glacial Cascade Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Damage 2": {"enchant": "Enchantment Ice Nova Damage 2", "type": "currency extremely high"},
	"1 Enchantment Ice Shot Damage 2": {"enchant": "Enchantment Ice Shot Damage 2", "type": "currency very high"},
	"1 Enchantment Incinerate Damage 2": {"enchant": "Enchantment Incinerate Damage 2", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Damage 2": {"enchant": "Enchantment Kinetic Blast Damage 2", "type": "currency very high"},
	"1 Enchantment Lacerate Damage 2": {"enchant": "Enchantment Lacerate Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Damage 2": {"enchant": "Enchantment Lightning Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Warp Damage 2": {"enchant": "Enchantment Lightning Warp Damage 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Damage 2": {"enchant": "Enchantment Molten Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Orb Of Storms Damage 2": {"enchant": "Enchantment Orb Of Storms Damage 2", "type": "currency very high"},
	"1 Enchantment Power Siphon Damage 2": {"enchant": "Enchantment Power Siphon Damage 2", "type": "currency very high"},
	"1 Enchantment Righteous Fire Damage 2": {"enchant": "Enchantment Righteous Fire Damage 2", "type": "currency very high"},
	"1 Enchantment Shockwave Totem Damage 2": {"enchant": "Enchantment Shockwave Totem Damage 2", "type": "currency very high"},
	"1 Enchantment Spark Damage 2": {"enchant": "Enchantment Spark Damage 2", "type": "currency very high"},
	"1 Enchantment Spectral Throw Damage 2": {"enchant": "Enchantment Spectral Throw Damage 2", "type": "currency very high"},
	"1 Enchantment Sweep Damage 2": {"enchant": "Enchantment Sweep Damage 2", "type": "currency very high"},
	"1 Enchantment Tectonic Slam Damage 2": {"enchant": "Enchantment Tectonic Slam Damage 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Damage 2": {"enchant": "Enchantment Tornado Shot Damage 2", "type": "currency very high"},
	"1 Enchantment Volatile Dead Damage 2": {"enchant": "Enchantment Volatile Dead Damage 2", "type": "currency very high"},
	"1 Enchantment Vortex Damage 2": {"enchant": "Enchantment Vortex Damage 2", "type": "currency very high"},
	"1 Enchantment Wild Strike Damage 2": {"enchant": "Enchantment Wild Strike Damage 2", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2": {"enchant": "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2", "type": "currency very high"},
	"1 Enchantment Conductivity Duration 2": {"enchant": "Enchantment Conductivity Duration 2", "type": "currency very high"},
	"1 Enchantment Static Strike Duration 2": {"enchant": "Enchantment Static Strike Duration 2", "type": "currency very high"},
	"1 Enchantment Temporal Chains Duration 2": {"enchant": "Enchantment Temporal Chains Duration 2", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage Per Frenzy Charge 1": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 1", "type": "currency very high"},
	"1 Enchantment Blade Flurry Area Of Effect 1": {"enchant": "Enchantment Blade Flurry Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Freeze Mine Area Of Effect 1": {"enchant": "Enchantment Freeze Mine Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Glacial Cascade Area Of Effect 1": {"enchant": "Enchantment Glacial Cascade Area Of Effect 1", "type": "currency very high"},
	"1 Enchantment Lightning Warp Cast Speed 1": {"enchant": "Enchantment Lightning Warp Cast Speed 1", "type": "currency very high"},
	"1 Enchantment Flicker Strike Damage Per Frenzy Charge 2": {"enchant": "Enchantment Flicker Strike Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 Enchantment Frenzy Damage Per Frenzy Charge 2": {"enchant": "Enchantment Frenzy Damage Per Frenzy Charge 2", "type": "currency very high"},
	"1 Enchantment Double Strike Critical Strike Chance 2": {"enchant": "Enchantment Double Strike Critical Strike Chance 2", "type": "currency very high"},
	"1 Enchantment Ancestor Warchief Melee Damage 2": {"enchant": "Enchantment Ancestor Warchief Melee Damage 2", "type": "currency very high"},
	"1 Enchantment Arc Num Of Additional Projectiles In Chain 1": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "currency very high"},
	"1 Enchantment Arc Shock Chance 2": {"enchant": "Enchantment Arc Shock Chance 2", "type": "currency very high"},
	"1 Enchantment Arctic Breath Chilling Area Movement Velocity 1": {"enchant": "Enchantment Arctic Breath Chilling Area Movement Velocity 1", "type": "currency very high"},
	"1 Enchantment Armageddon Brand Damage 2": {"enchant": "Enchantment Armageddon Brand Damage 2", "type": "currency very high"},
	"1 Enchantment Bane Damage 1": {"enchant": "Enchantment Bane Damage 1", "type": "currency very high"},
	"1 Enchantment Bane Damage 2": {"enchant": "Enchantment Bane Damage 2", "type": "currency very high"},
	"1 Enchantment Bane Area Of Effect 2": {"enchant": "Enchantment Bane Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Barrage Num Of Additional Projectiles 1": {"enchant": "Enchantment Barrage Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Blade Vortex Crit Multi Per Blade 2": {"enchant": "Enchantment Blade Vortex Crit Multi Per Blade 2", "type": "currency very high"},
	"1 Enchantment Bladefall Additional Volley": {"enchant": "Enchantment Bladefall Additional Volley", "type": "currency very high"},
	"1 Enchantment Blast Rain Additional Blast 2": {"enchant": "Enchantment Blast Rain Additional Blast 2", "type": "currency very high"},
	"1 Enchantment Blink Arrow Damage 1": {"enchant": "Enchantment Blink Arrow Damage 1", "type": "currency very high"},
	"1 Enchantment Blood Rage Attack Speed 2": {"enchant": "Enchantment Blood Rage Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Blood Rage Frenzy On Kill 2": {"enchant": "Enchantment Blood Rage Frenzy On Kill 2", "type": "currency very high"},
	"1 Enchantment Caustic Arrow Wither On Hit 2": {"enchant": "Enchantment Caustic Arrow Wither On Hit 2", "type": "currency very high"},
	"1 Enchantment Sumon Chaos Golem Damage 2": {"enchant": "Enchantment Sumon Chaos Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Nova Minimum Chill 1": {"enchant": "Enchantment Ice Nova Minimum Chill 1", "type": "currency very high"},
	"1 Enchantment Clarity Mana Reservation 2": {"enchant": "Enchantment Clarity Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Consecrated Ground Enemy Damage Taken 2": {"enchant": "Enchantment Flame Totem Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "currency very high"},
	"1 Enchantment Consecrated Path Damage 2": {"enchant": "Enchantment Consecrated Path Damage 2", "type": "currency very high"},
	"1 Enchantment Consecrated Path Area Of Effect 2": {"enchant": "Enchantment Consecrated Path Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Conversion Trap Damage 2": {"enchant": "Enchantment Conversion Trap Damage 2", "type": "currency very high"},
	"1 Enchantment Discipline Mana Reservation 2": {"enchant": "Enchantment Discipline Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2": {"enchant": "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Damage 2": {"enchant": "Enchantment Divine Ire Damage 2", "type": "currency very high"},
	"1 Enchantment Divine Ire Beam Width 2": {"enchant": "Enchantment Divine Ire Beam Width 2", "type": "currency very high"},
	"1 Enchantment Dominating Blow Additional Magic 2": {"enchant": "Enchantment Dominating Blow Additional Magic 2", "type": "currency very high"},
	"1 Enchantment Double Strike Double Damage Vs Bleeding 1": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 1", "type": "currency very high"},
	"1 Enchantment Double Strike Double Damage Vs Bleeding 2": {"enchant": "Enchantment Double Strike Double Damage Vs Bleeding 2", "type": "currency very high"},
	"1 Enchantment Dread Banner Effect 1": {"enchant": "Enchantment Dread Banner Effect 1", "type": "currency very high"},
	"1 Enchantment Dread Banner Effect 2": {"enchant": "Enchantment Dread Banner Effect 2", "type": "currency very high"},
	"1 Enchantment Elemental Hit Damage 2": {"enchant": "Enchantment Elemental Hit Damage 2", "type": "currency very high"},
	"1 Enchantment Fire Nova Mine Num Of Additional Repeats 2": {"enchant": "Enchantment Fire Nova Mine Num Of Additional Repeats 2", "type": "currency very high"},
	"1 Enchantment Fireball Ignite Chance 2": {"enchant": "Enchantment Fireball Ignite Chance 2", "type": "currency very high"},
	"1 Enchantment Flamethrower Additional Flamethrowers 2": {"enchant": "Enchantment Flamethrower Additional Flamethrowers 2", "type": "currency very high"},
	"1 Enchantment Flesh Offering Attack Speed 2": {"enchant": "Enchantment Flesh Offering Attack Speed 2", "type": "currency very high"},
	"1 Enchantment Frost Bomb Increased Duration 2": {"enchant": "Enchantment Frost Bomb Increased Duration 2", "type": "currency very high"},
	"1 Enchantment Hatred Mana Reservation 2": {"enchant": "Enchantment Hatred Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Heavy Strike Double Damage 2": {"enchant": "Enchantment Heavy Strike Double Damage 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 1": {"enchant": "Enchantment Herald Of Agony Mana Reservation 1", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Mana Reservation 2": {"enchant": "Enchantment Herald Of Agony Mana Reservation 2", "type": "currency extremely high"},
	"1 Enchantment Herald Of Ash Mana Reservation 2": {"enchant": "Enchantment Herald Of Ash Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Herald Of Ice Mana Reservation 2": {"enchant": "Enchantment Herald Of Ice Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Herald Of Purity Mana Reservation 2": {"enchant": "Enchantment Herald Of Purity Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Damage 2": {"enchant": "Enchantment Flame Totem Damage 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Num Of Additional Projectiles 2": {"enchant": "Enchantment Flame Totem Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Flame Totem Projectile Speed 2": {"enchant": "Enchantment Flame Totem Projectile Speed 2", "type": "currency very high"},
	"1 Enchantment Summon Ice Golem Damage 2": {"enchant": "Enchantment Summon Ice Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Spear Additional Projectile 1": {"enchant": "Enchantment Ice Spear Additional Projectile 1", "type": "currency extremely high"},
	"1 Enchantment Ice Spear Distance Before Form Change 2": {"enchant": "Enchantment Ice Spear Distance Before Form Change 2", "type": "currency very high"},
	"1 Enchantment Ice Trap Cold Penetration 2": {"enchant": "Enchantment Ice Trap Cold Penetration 2", "type": "currency very high"},
	"1 Enchantment Incinerate Maximum Stages 2": {"enchant": "Enchantment Incinerate Maximum Stages 2", "type": "currency very high"},
	"1 Enchantment Kinetic Blast Explosions 2": {"enchant": "Enchantment Kinetic Blast Explosions 2", "type": "currency very high"},
	"1 Enchantment Summon Lightning Golem Damage 2": {"enchant": "Enchantment Summon Lightning Golem Damage 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Penetration 2": {"enchant": "Enchantment Lightning Trap Penetration 2", "type": "currency very high"},
	"1 Enchantment Lightning Trap Penetration 1": {"enchant": "Enchantment Lightning Trap Penetration 1", "type": "currency very high"},
	"1 Enchantment Lightning Trap Additional Pierce 2": {"enchant": "Enchantment Lightning Trap Additional Pierce 2", "type": "currency very high"},
	"1 Enchantment Magma Orb Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Malevolence Mana Reservation 2": {"enchant": "Enchantment Malevolence Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 2": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Molten Strike Num Of Additional Projectiles 1": {"enchant": "Enchantment Molten Strike Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Purifying Flame Damage 2": {"enchant": "Enchantment Purifying Flame Damage 2", "type": "currency very high"},
	"1 Enchantment Purity Of Fire Mana Reservation 2": {"enchant": "Enchantment Purity Of Fire Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Purity Of Lightning Mana Reservation 2": {"enchant": "Enchantment Purity Of Lightning Mana Reservation 2", "type": "currency very high"},
	"1 Enchantment Rain Of Arrows Repeat Count 2": {"enchant": "Enchantment Rain Of Arrows Repeat Count 2", "type": "currency very high"},
	"1 Enchantment Righteous Fire Spell Damage 2": {"enchant": "Enchantment Righteous Fire Spell Damage 2", "type": "currency very high"},
	"1 Enchantment Scourge Arrow Additional Spore 1": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "currency very high"},
	"1 Enchantment Scourge Arrow Damage 2": {"enchant": "Enchantment Scourge Arrow Damage 2", "type": "currency very high"},
	"1 Enchantment Scourge Arrow Chance To Poison 2": {"enchant": "Enchantment Scourge Arrow Chance To Poison 2", "type": "currency very high"},
	"1 Enchantment Shattering Steel Additional Projectile 1": {"enchant": "Enchantment Shattering Steel Additional Projectile 1", "type": "currency very high"},
	"1 Enchantment Shattering Steel Fortify On Hit Close Range 1": {"enchant": "Enchantment Shattering Steel Fortify On Hit Close Range 1", "type": "currency very high"},
	"1 Enchantment Shock Nova Larger Ring Damage 2": {"enchant": "Enchantment Shock Nova Larger Ring Damage 2", "type": "currency very high"},
	"1 Enchantment Ice Siphon Trap Duration 2": {"enchant": "Enchantment Ice Siphon Trap Duration 2", "type": "currency very high"},
	"1 Enchantment Smoke Mine Movement Speed 2": {"enchant": "Enchantment Smoke Mine Movement Speed 2", "type": "currency very high"},
	"1 Enchantment Soulrend Damage 2": {"enchant": "Enchantment Soulrend Damage 2", "type": "currency very high"},
	"1 Enchantment Soulrend Number Of Additional Projectiles 1": {"enchant": "Enchantment Soulrend Number Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Spark Num Of Additional Projectiles 1": {"enchant": "Enchantment Spark Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Spark Num Of Additional Projectiles 2": {"enchant": "Enchantment Spark Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Raise Spectre Damage 2": {"enchant": "Enchantment Raise Spectre Damage 2", "type": "currency very high"},
	"1 Enchantment Split Arrow Num Of Additional Projectiles 2": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 2", "type": "currency very high"},
	"1 Enchantment Summon Stone Golem Damage 2": {"enchant": "Enchantment Summon Stone Golem Damage 2", "type": "currency very high"},
	"1 Storm Brand Attached Target Lightning Penetration 2": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "currency very high"},
	"1 Enchantment Storm Brand Damage 1": {"enchant": "Enchantment Storm Brand Damage 1", "type": "currency very high"},
	"1 Enchantment Storm Brand Damage 2": {"enchant": "Enchantment Storm Brand Damage 2", "type": "currency very high"},
	"1 Storm Brand Additional Chain Chance 2": {"enchant": "Storm Brand Additional Chain Chance 2", "type": "currency very high"},
	"1 Enchantment Storm Burst Additional Object Chance 2": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "currency very high"},
	"1 Enchantment Herald Of Agony Num Of Secondary Projectiles 1": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "currency extremely high"},
	"1 Enchantment Tectonic Slam Chance To Charged Slam 2": {"enchant": "Enchantment Tectonic Slam Chance To Charged Slam 2", "type": "currency very high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 2": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 2", "type": "currency extremely high"},
	"1 Enchantment Tornado Shot Num Of Secondary Projectiles 1": {"enchant": "Enchantment Tornado Shot Num Of Secondary Projectiles 1", "type": "currency very high"},
	"1 Enchantment Toxic Rain Damage 2": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "currency very high"},
	"1 Enchantment Toxic Rain Num Of Additional Projectiles 1": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "currency very high"},
	"1 Enchantment Vortex Cooldown Recovery 2": {"enchant": "Enchantment Vortex Cooldown Recovery 2", "type": "currency very high"},
	"1 Enchantment Wave Of Conviction Damage 2": {"enchant": "Enchantment Wave Of Conviction Damage 2", "type": "currency very high"},
	"1 Enchantment Wave Of Conviction Duration 2": {"enchant": "Enchantment Wave Of Conviction Duration 2", "type": "currency very high"},
	"1 Enchantment Wave Of Conviction Additional Enemy Resistance 2": {"enchant": "Enchantment Wave Of Conviction Additional Enemy Resistance 2", "type": "currency very high"},
	"1 Enchantment Wild Strike Num Of Additional Projectiles In Chain 2": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 1": {"enchant": "Enchantment Winter Orb Damage 1", "type": "currency very high"},
	"1 Enchantment Winter Orb Damage 2": {"enchant": "Enchantment Winter Orb Damage 2", "type": "currency extremely high"},
	"1 Enchantment Frost Fury Additional Max Number Of Stages 1": {"enchant": "Enchantment Frost Fury Additional Max Number Of Stages 1", "type": "currency extremely high"},
	"1 Enchantment Frost Fury Area Of Effect Per Stage 2": {"enchant": "Enchantment Frost Fury Area Of Effect Per Stage 2", "type": "currency very high"},
	"1 Enchantment Wither Area Of Effect 2": {"enchant": "Enchantment Wither Area Of Effect 2", "type": "currency very high"},
	"1 Enchantment Zealotry Mana Reservation 2": {"enchant": "Enchantment Zealotry Mana Reservation 2", "type": "currency very high"},
}
