#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 05/15/2019(m/d/y) 09:08:01 UTC from "tmphardcore" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"000 40% increased Flame Surge Damage against Burning Enemies": {"enchant": "40% increased Flame Surge Damage against Burning Enemies", "type": "ignore"},
	"1 +36% to Raised Zombie Elemental Resistances": {"enchant": "+36% to Raised Zombie Elemental Resistances", "type": "currency very high"},
	"1 10% Chance to gain a Power Charge on Critical Strike with Ice Spear": {"enchant": "10% Chance to gain a Power Charge on Critical Strike with Ice Spear", "type": "currency very high"},
	"1 10% increased Incinerate Damage for each stage": {"enchant": "10% increased Incinerate Damage for each stage", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Chaos Golems": {"enchant": "100% increased Effect of the Buff granted by your Chaos Golems", "type": "currency very high"},
	"1 100% increased Effect of the Buff granted by your Flame Golems": {"enchant": "100% increased Effect of the Buff granted by your Flame Golems", "type": "currency very high"},
	"1 12% increased Ancestral Warchief Totem Area of Effect": {"enchant": "12% increased Ancestral Warchief Totem Area of Effect", "type": "currency very high"},
	"1 12% increased Blade Vortex Area of Effect": {"enchant": "12% increased Blade Vortex Area of Effect", "type": "currency very high"},
	"1 12% increased Blight Area of Effect": {"enchant": "12% increased Blight Area of Effect", "type": "currency very high"},
	"1 12% increased Contagion Area of Effect": {"enchant": "12% increased Contagion Area of Effect", "type": "currency very high"},
	"1 12% increased Fireball Cast Speed": {"enchant": "12% increased Fireball Cast Speed", "type": "currency very high"},
	"1 12% increased Freezing Pulse Cast Speed": {"enchant": "12% increased Freezing Pulse Cast Speed", "type": "currency very high"},
	"1 12% increased Infernal Blow Area of Effect": {"enchant": "12% increased Infernal Blow Area of Effect", "type": "currency very high"},
	"1 12% increased Lightning Arrow Area of Effect": {"enchant": "12% increased Lightning Arrow Area of Effect", "type": "currency very high"},
	"1 12% increased Rain of Arrows Area of Effect": {"enchant": "12% increased Rain of Arrows Area of Effect", "type": "currency very high"},
	"1 12% increased Reave Radius": {"enchant": "12% increased Reave Radius", "type": "currency very high"},
	"1 12% increased Scorching Ray Cast Speed": {"enchant": "12% increased Scorching Ray Cast Speed", "type": "currency very high"},
	"1 12% increased Tectonic Slam Area of Effect": {"enchant": "12% increased Tectonic Slam Area of Effect", "type": "currency very high"},
	"1 15% increased Cleave Attack Speed": {"enchant": "15% increased Cleave Attack Speed", "type": "currency very high"},
	"1 15% increased Cyclone Attack Speed": {"enchant": "15% increased Cyclone Attack Speed", "type": "currency very high"},
	"1 15% increased Double Strike Attack Speed": {"enchant": "15% increased Double Strike Attack Speed", "type": "currency very high"},
	"1 15% increased Elemental Hit Attack Speed": {"enchant": "15% increased Elemental Hit Attack Speed", "type": "currency very high"},
	"1 15% increased Explosive Arrow Attack Speed": {"enchant": "15% increased Explosive Arrow Attack Speed", "type": "currency very high"},
	"1 15% increased Power Siphon Attack Speed": {"enchant": "15% increased Power Siphon Attack Speed", "type": "currency very high"},
	"1 15% of Shrapnel Shot Physical Damage gained as extra Lightning Damage": {"enchant": "15% of Shrapnel Shot Physical Damage gained as extra Lightning Damage", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Ice Golems": {"enchant": "150% increased Effect of the Buff granted by your Ice Golems", "type": "currency very high"},
	"1 150% increased Effect of the Buff granted by your Stone Golems": {"enchant": "150% increased Effect of the Buff granted by your Stone Golems", "type": "currency very high"},
	"1 20% increased Temporal Chains Curse Effect": {"enchant": "20% increased Temporal Chains Curse Effect", "type": "currency very high"},
	"1 20% reduced Storm Call Duration": {"enchant": "20% reduced Storm Call Duration", "type": "currency very high"},
	"1 24% increased Decoy Totem Area of Effect": {"enchant": "24% increased Decoy Totem Area of Effect", "type": "currency very high"},
	"1 25% increased Freezing Pulse Damage": {"enchant": "25% increased Freezing Pulse Damage", "type": "currency very high"},
	"1 30% chance for Discharge to deal Damage without removing Charges": {"enchant": "30% chance for Discharge to deal Damage without removing Charges", "type": "currency very high"},
	"1 30% increased Assassin's Mark Curse Effect": {"enchant": "30% increased Assassin's Mark Curse Effect", "type": "currency very high"},
	"1 30% increased Blade Vortex Duration": {"enchant": "30% increased Blade Vortex Duration", "type": "currency very high"},
	"1 30% increased Convocation Cooldown Recovery Speed": {"enchant": "30% increased Convocation Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Despair Curse Effect": {"enchant": "30% increased Despair Curse Effect", "type": "currency very high"},
	"1 30% increased Enduring Cry Cooldown Recovery Speed": {"enchant": "30% increased Enduring Cry Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Ethereal Knives Projectile Speed": {"enchant": "30% increased Ethereal Knives Projectile Speed", "type": "currency very high"},
	"1 30% increased Flame Dash Cooldown Recovery Speed": {"enchant": "30% increased Flame Dash Cooldown Recovery Speed", "type": "currency very high"},
	"1 30% increased Freezing Pulse Projectile Speed": {"enchant": "30% increased Freezing Pulse Projectile Speed", "type": "currency very high"},
	"1 30% increased Poacher's Mark Curse Effect": {"enchant": "30% increased Poacher's Mark Curse Effect", "type": "currency very high"},
	"1 30% increased Spark Projectile Speed": {"enchant": "30% increased Spark Projectile Speed", "type": "currency very high"},
	"1 30% increased Temporal Chains Curse Effect": {"enchant": "30% increased Temporal Chains Curse Effect", "type": "currency extremely high"},
	"1 30% increased Vortex Duration": {"enchant": "30% increased Vortex Duration", "type": "currency very high"},
	"1 30% reduced Earthquake Duration": {"enchant": "30% reduced Earthquake Duration", "type": "currency very high"},
	"1 30% reduced Lightning Warp Duration": {"enchant": "30% reduced Lightning Warp Duration", "type": "currency very high"},
	"1 30% reduced Spectral Throw Projectile Deceleration": {"enchant": "30% reduced Spectral Throw Projectile Deceleration", "type": "currency very high"},
	"1 30% reduced Storm Call Duration": {"enchant": "30% reduced Storm Call Duration", "type": "currency extremely high"},
	"1 300% increased Ice Spear Critical Strike Chance in second form": {"enchant": "300% increased Ice Spear Critical Strike Chance in second form", "type": "currency very high"},
	"1 36% increased Convocation Buff Effect": {"enchant": "36% increased Convocation Buff Effect", "type": "currency very high"},
	"1 36% increased Devouring Totem Leech per second": {"enchant": "36% increased Devouring Totem Leech per second", "type": "currency very high"},
	"1 36% increased Searing Bond Totem Elemental Resistances": {"enchant": "36% increased Searing Bond Totem Elemental Resistances", "type": "currency very high"},
	"1 40% increased Ancestral Warchief Totem Damage": {"enchant": "40% increased Ancestral Warchief Totem Damage", "type": "currency very high"},
	"1 40% increased Arc Damage": {"enchant": "40% increased Arc Damage", "type": "currency very high"},
	"1 40% increased Arctic Breath Damage": {"enchant": "40% increased Arctic Breath Damage", "type": "currency very high"},
	"1 40% increased Ball Lightning Damage": {"enchant": "40% increased Ball Lightning Damage", "type": "currency very high"},
	"1 40% increased Blade Flurry Damage": {"enchant": "40% increased Blade Flurry Damage", "type": "currency very high"},
	"1 40% increased Blade Vortex Spell Damage": {"enchant": "40% increased Blade Vortex Spell Damage", "type": "currency very high"},
	"1 40% increased Blast Rain Damage": {"enchant": "40% increased Blast Rain Damage", "type": "currency very high"},
	"1 40% increased Caustic Arrow Damage": {"enchant": "40% increased Caustic Arrow Damage", "type": "currency very high"},
	"1 40% increased Cyclone Damage": {"enchant": "40% increased Cyclone Damage", "type": "currency very high"},
	"1 40% increased Detonate Dead Damage": {"enchant": "40% increased Detonate Dead Damage", "type": "currency very high"},
	"1 40% increased Double Strike Damage": {"enchant": "40% increased Double Strike Damage", "type": "currency very high"},
	"1 40% increased Essence Drain Damage": {"enchant": "40% increased Essence Drain Damage", "type": "currency very high"},
	"1 40% increased Ethereal Knives Damage": {"enchant": "40% increased Ethereal Knives Damage", "type": "currency very high"},
	"1 40% increased Fireball Damage": {"enchant": "40% increased Fireball Damage", "type": "currency very high"},
	"1 40% increased Flicker Strike Damage": {"enchant": "40% increased Flicker Strike Damage", "type": "currency very high"},
	"1 40% increased Freezing Pulse Damage": {"enchant": "40% increased Freezing Pulse Damage", "type": "currency very high"},
	"1 40% increased Frost Blades Damage": {"enchant": "40% increased Frost Blades Damage", "type": "currency extremely high"},
	"1 40% increased Glacial Cascade Damage": {"enchant": "40% increased Glacial Cascade Damage", "type": "currency very high"},
	"1 40% increased Ice Nova Damage": {"enchant": "40% increased Ice Nova Damage", "type": "currency extremely high"},
	"1 40% increased Ice Shot Damage": {"enchant": "40% increased Ice Shot Damage", "type": "currency very high"},
	"1 40% increased Incinerate Damage": {"enchant": "40% increased Incinerate Damage", "type": "currency very high"},
	"1 40% increased Kinetic Blast Damage": {"enchant": "40% increased Kinetic Blast Damage", "type": "currency very high"},
	"1 40% increased Lacerate Damage": {"enchant": "40% increased Lacerate Damage", "type": "currency very high"},
	"1 40% increased Lightning Trap Damage": {"enchant": "40% increased Lightning Trap Damage", "type": "currency very high"},
	"1 40% increased Lightning Warp Damage": {"enchant": "40% increased Lightning Warp Damage", "type": "currency very high"},
	"1 40% increased Molten Strike Damage": {"enchant": "40% increased Molten Strike Damage", "type": "currency very high"},
	"1 40% increased Orb of Storms Damage": {"enchant": "40% increased Orb of Storms Damage", "type": "currency very high"},
	"1 40% increased Power Siphon Damage": {"enchant": "40% increased Power Siphon Damage", "type": "currency very high"},
	"1 40% increased Righteous Fire Damage": {"enchant": "40% increased Righteous Fire Damage", "type": "currency very high"},
	"1 40% increased Shockwave Totem Damage": {"enchant": "40% increased Shockwave Totem Damage", "type": "currency very high"},
	"1 40% increased Spark Damage": {"enchant": "40% increased Spark Damage", "type": "currency very high"},
	"1 40% increased Spectral Throw Damage": {"enchant": "40% increased Spectral Throw Damage", "type": "currency very high"},
	"1 40% increased Sweep Damage": {"enchant": "40% increased Sweep Damage", "type": "currency very high"},
	"1 40% increased Tectonic Slam Damage": {"enchant": "40% increased Tectonic Slam Damage", "type": "currency very high"},
	"1 40% increased Tornado Shot Damage": {"enchant": "40% increased Tornado Shot Damage", "type": "currency very high"},
	"1 40% increased Volatile Dead Damage": {"enchant": "40% increased Volatile Dead Damage", "type": "currency very high"},
	"1 40% increased Vortex Damage": {"enchant": "40% increased Vortex Damage", "type": "currency very high"},
	"1 40% increased Wild Strike Damage": {"enchant": "40% increased Wild Strike Damage", "type": "currency very high"},
	"1 40% of Glacial Cascade Physical Damage Converted to Cold Damage": {"enchant": "40% of Glacial Cascade Physical Damage Converted to Cold Damage", "type": "currency very high"},
	"1 45% increased Conductivity Duration": {"enchant": "45% increased Conductivity Duration", "type": "currency very high"},
	"1 45% increased Static Strike Duration": {"enchant": "45% increased Static Strike Duration", "type": "currency very high"},
	"1 45% increased Temporal Chains Duration": {"enchant": "45% increased Temporal Chains Duration", "type": "currency very high"},
	"1 6% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "6% increased Flicker Strike Damage per Frenzy Charge", "type": "currency very high"},
	"1 8% increased Blade Flurry Area of Effect": {"enchant": "8% increased Blade Flurry Area of Effect", "type": "currency very high"},
	"1 8% increased Freeze Mine Area of Effect": {"enchant": "8% increased Freeze Mine Area of Effect", "type": "currency very high"},
	"1 8% increased Glacial Cascade Area of Effect": {"enchant": "8% increased Glacial Cascade Area of Effect", "type": "currency very high"},
	"1 8% increased Lightning Warp Cast Speed": {"enchant": "8% increased Lightning Warp Cast Speed", "type": "currency very high"},
	"1 9% increased Flicker Strike Damage per Frenzy Charge": {"enchant": "9% increased Flicker Strike Damage per Frenzy Charge", "type": "currency very high"},
	"1 9% increased Frenzy Damage per Frenzy Charge": {"enchant": "9% increased Frenzy Damage per Frenzy Charge", "type": "currency very high"},
	"1 90% increased Double Strike Critical Strike Chance": {"enchant": "90% increased Double Strike Critical Strike Chance", "type": "currency very high"},
	"1 Ancestral Warchief Totem grants 30% increased Melee Damage while Active": {"enchant": "Ancestral Warchief Totem grants 30% increased Melee Damage while Active", "type": "currency very high"},
	"1 Arc Chains an additional time": {"enchant": "Arc Chains an additional time", "type": "currency very high"},
	"1 Arc has +30% chance to Shock": {"enchant": "Arc has +30% chance to Shock", "type": "currency very high"},
	"1 Arctic Breath's Chilling Area has 38% increased Movement Speed": {"enchant": "Arctic Breath's Chilling Area has 38% increased Movement Speed", "type": "currency very high"},
	"1 Armageddon Brand deals 40% increased Damage": {"enchant": "Armageddon Brand deals 40% increased Damage", "type": "currency very high"},
	"1 Bane deals 25% increased Damage": {"enchant": "Bane deals 25% increased Damage", "type": "currency very high"},
	"1 Bane deals 40% increased Damage": {"enchant": "Bane deals 40% increased Damage", "type": "currency very high"},
	"1 Bane has 15% increased Area of Effect": {"enchant": "Bane has 15% increased Area of Effect", "type": "currency very high"},
	"1 Barrage fires an additional Projectile": {"enchant": "Barrage fires an additional Projectile", "type": "currency very high"},
	"1 Blade Vortex has +3% to Critical Strike Multiplier for each blade": {"enchant": "Blade Vortex has +3% to Critical Strike Multiplier for each blade", "type": "currency very high"},
	"1 Bladefall has an additional Volley": {"enchant": "Bladefall has an additional Volley", "type": "currency very high"},
	"1 Blast Rain has a 75% chance for an additional blast": {"enchant": "Blast Rain has a 75% chance for an additional blast", "type": "currency very high"},
	"1 Blink Arrow and Blink Arrow Clones have 25% increased Damage": {"enchant": "Blink Arrow and Blink Arrow Clones have 25% increased Damage", "type": "currency very high"},
	"1 Blood Rage grants additional 12% increased Attack Speed": {"enchant": "Blood Rage grants additional 12% increased Attack Speed", "type": "currency very high"},
	"1 Blood Rage grants additional 30% chance to gain a Frenzy Charge on Kill": {"enchant": "Blood Rage grants additional 30% chance to gain a Frenzy Charge on Kill", "type": "currency very high"},
	"1 Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration": {"enchant": "Caustic Arrow has 20% chance to inflict Withered on Hit for 2 seconds base Duration", "type": "currency very high"},
	"1 Chaos Golems deal 40% increased Damage": {"enchant": "Chaos Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Chills from Ice Nova Hits always reduce Action Speed by at least 6%": {"enchant": "Chills from Ice Nova Hits always reduce Action Speed by at least 6%", "type": "currency very high"},
	"1 Clarity has 30% reduced Mana Reservation": {"enchant": "Clarity has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Consecrated Ground from Holy Flame Totem applies 9% increased Damage taken to Enemies": {"enchant": "Consecrated Ground from Holy Flame Totem applies 9% increased Damage taken to Enemies", "type": "currency very high"},
	"1 Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies": {"enchant": "Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies", "type": "currency very high"},
	"1 Consecrated Path deals 40% increased Damage": {"enchant": "Consecrated Path deals 40% increased Damage", "type": "currency very high"},
	"1 Consecrated Path has 12% increased Area of Effect": {"enchant": "Consecrated Path has 12% increased Area of Effect", "type": "currency very high"},
	"1 Converted Enemies have 40% increased Damage": {"enchant": "Converted Enemies have 40% increased Damage", "type": "currency very high"},
	"1 Discipline has 20% reduced Mana Reservation": {"enchant": "Discipline has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Divine Ire Damages 2 additional nearby Enemies when gaining Stages": {"enchant": "Divine Ire Damages 2 additional nearby Enemies when gaining Stages", "type": "currency very high"},
	"1 Divine Ire deals 40% increased Damage": {"enchant": "Divine Ire deals 40% increased Damage", "type": "currency very high"},
	"1 Divine Ire's beam has 15% increased width": {"enchant": "Divine Ire's beam has 15% increased width", "type": "currency very high"},
	"1 Dominating Blow can summon 3 additional Magic Sentinels of Dominance": {"enchant": "Dominating Blow can summon 3 additional Magic Sentinels of Dominance", "type": "currency very high"},
	"1 Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Double Strike has a 10% chance to deal Double Damage to Bleeding Enemies", "type": "currency very high"},
	"1 Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies": {"enchant": "Double Strike has a 15% chance to deal Double Damage to Bleeding Enemies", "type": "currency very high"},
	"1 Dread Banner has 25% increased Aura Effect": {"enchant": "Dread Banner has 25% increased Aura Effect", "type": "currency very high"},
	"1 Dread Banner has 40% increased Aura Effect": {"enchant": "Dread Banner has 40% increased Aura Effect", "type": "currency very high"},
	"1 Elemental Hit deals 40% increased Damage": {"enchant": "Elemental Hit deals 40% increased Damage", "type": "currency very high"},
	"1 Fire Nova Mine repeats an additional 2 times": {"enchant": "Fire Nova Mine repeats an additional 2 times", "type": "currency very high"},
	"1 Fireball has +30% chance to Ignite": {"enchant": "Fireball has +30% chance to Ignite", "type": "currency very high"},
	"1 Flamethrower Trap has 2 additional Flames": {"enchant": "Flamethrower Trap has 2 additional Flames", "type": "currency very high"},
	"1 Flesh Offering grants an additional 21% increased Attack Speed": {"enchant": "Flesh Offering grants an additional 21% increased Attack Speed", "type": "currency very high"},
	"1 Frost Bomb has 30% increased Debuff Duration": {"enchant": "Frost Bomb has 30% increased Debuff Duration", "type": "currency very high"},
	"1 Hatred has 15% reduced Mana Reservation": {"enchant": "Hatred has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Heavy Strike has a 12% chance to deal Double Damage": {"enchant": "Heavy Strike has a 12% chance to deal Double Damage", "type": "currency very high"},
	"1 Herald of Agony has 20% reduced Mana Reservation": {"enchant": "Herald of Agony has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Agony has 30% reduced Mana Reservation": {"enchant": "Herald of Agony has 30% reduced Mana Reservation", "type": "currency extremely high"},
	"1 Herald of Ash has 30% reduced Mana Reservation": {"enchant": "Herald of Ash has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Ice has 30% reduced Mana Reservation": {"enchant": "Herald of Ice has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Herald of Purity has 30% reduced Mana Reservation": {"enchant": "Herald of Purity has 30% reduced Mana Reservation", "type": "currency very high"},
	"1 Holy Flame Totem deals 40% increased Damage": {"enchant": "Holy Flame Totem deals 40% increased Damage", "type": "currency very high"},
	"1 Holy Flame Totem fires 2 additional Projectiles": {"enchant": "Holy Flame Totem fires 2 additional Projectiles", "type": "currency very high"},
	"1 Holy Flame Totem has 30% increased Projectile Speed": {"enchant": "Holy Flame Totem has 30% increased Projectile Speed", "type": "currency very high"},
	"1 Ice Golems deal 40% increased Damage": {"enchant": "Ice Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Ice Spear fires an additional Projectile": {"enchant": "Ice Spear fires an additional Projectile", "type": "currency extremely high"},
	"1 Ice Spear travels 30% reduced distance before changing forms": {"enchant": "Ice Spear travels 30% reduced distance before changing forms", "type": "currency very high"},
	"1 Ice Trap Damage Penetrates 10% Cold Resistance": {"enchant": "Ice Trap Damage Penetrates 10% Cold Resistance", "type": "currency very high"},
	"1 Incinerate has +2 to maximum stages": {"enchant": "Incinerate has +2 to maximum stages", "type": "currency very high"},
	"1 Kinetic Blast has a 75% chance for an additional explosion": {"enchant": "Kinetic Blast has a 75% chance for an additional explosion", "type": "currency very high"},
	"1 Lightning Golems deal 40% increased Damage": {"enchant": "Lightning Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Lightning Trap Damage Penetrates 10% Lightning Resistance": {"enchant": "Lightning Trap Damage Penetrates 10% Lightning Resistance", "type": "currency very high"},
	"1 Lightning Trap Damage Penetrates 6% Lightning Resistance": {"enchant": "Lightning Trap Damage Penetrates 6% Lightning Resistance", "type": "currency very high"},
	"1 Lightning Trap pierces 3 additional Targets": {"enchant": "Lightning Trap pierces 3 additional Targets", "type": "currency very high"},
	"1 Magma Orb Chains an additional 2 times": {"enchant": "Magma Orb Chains an additional 2 times", "type": "currency very high"},
	"1 Malevolence has 15% reduced Mana Reservation": {"enchant": "Malevolence has 15% reduced Mana Reservation", "type": "currency very high"},
	"1 Molten Strike fires 2 additional Projectiles": {"enchant": "Molten Strike fires 2 additional Projectiles", "type": "currency extremely high"},
	"1 Molten Strike fires an additional Projectile": {"enchant": "Molten Strike fires an additional Projectile", "type": "currency very high"},
	"1 Purifying Flame deals 40% increased Damage": {"enchant": "Purifying Flame deals 40% increased Damage", "type": "currency very high"},
	"1 Purity of Fire has 20% reduced Mana Reservation": {"enchant": "Purity of Fire has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Purity of Lightning has 20% reduced Mana Reservation": {"enchant": "Purity of Lightning has 20% reduced Mana Reservation", "type": "currency very high"},
	"1 Rain of Arrows has 15% chance to fire an additional sequence of arrows": {"enchant": "Rain of Arrows has 15% chance to fire an additional sequence of arrows", "type": "currency very high"},
	"1 Righteous Fire grants 30% increased Spell Damage": {"enchant": "Righteous Fire grants 30% increased Spell Damage", "type": "currency very high"},
	"1 Scourge Arrow creates an additional spore pod at Maximum Stages": {"enchant": "Scourge Arrow creates an additional spore pod at Maximum Stages", "type": "currency very high"},
	"1 Scourge Arrow deals 40% increased Damage": {"enchant": "Scourge Arrow deals 40% increased Damage", "type": "currency very high"},
	"1 Scourge Arrow has 8% chance to Poison per Stage": {"enchant": "Scourge Arrow has 8% chance to Poison per Stage", "type": "currency very high"},
	"1 Shattering Steel fires an additional Projectile": {"enchant": "Shattering Steel fires an additional Projectile", "type": "currency very high"},
	"1 Shattering Steel grants Fortify on Hitting an Enemy at Close Range": {"enchant": "Shattering Steel grants Fortify on Hitting an Enemy at Close Range", "type": "currency very high"},
	"1 Shock Nova ring deals 60% increased Damage": {"enchant": "Shock Nova ring deals 60% increased Damage", "type": "currency very high"},
	"1 Siphoning Trap has 45% increased Skill Effect Duration": {"enchant": "Siphoning Trap has 45% increased Skill Effect Duration", "type": "currency very high"},
	"1 Smoke Mine grants additional 30% increased Movement Speed": {"enchant": "Smoke Mine grants additional 30% increased Movement Speed", "type": "currency very high"},
	"1 Soulrend deals 40% increased Damage": {"enchant": "Soulrend deals 40% increased Damage", "type": "currency very high"},
	"1 Soulrend fires an additional Projectile": {"enchant": "Soulrend fires an additional Projectile", "type": "currency very high"},
	"1 Spark fires 2 additional Projectiles": {"enchant": "Spark fires 2 additional Projectiles", "type": "currency very high"},
	"1 Spark fires 3 additional Projectiles": {"enchant": "Spark fires 3 additional Projectiles", "type": "currency very high"},
	"1 Spectres have 40% increased Damage": {"enchant": "Spectres have 40% increased Damage", "type": "currency very high"},
	"1 Split Arrow fires 3 additional Projectiles": {"enchant": "Split Arrow fires 3 additional Projectiles", "type": "currency very high"},
	"1 Stone Golems deal 40% increased Damage": {"enchant": "Stone Golems deal 40% increased Damage", "type": "currency very high"},
	"1 Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance", "type": "currency very high"},
	"1 Storm Brand deals 25% increased Damage": {"enchant": "Storm Brand deals 25% increased Damage", "type": "currency very high"},
	"1 Storm Brand deals 40% increased Damage": {"enchant": "Storm Brand deals 40% increased Damage", "type": "currency very high"},
	"1 Storm Brand has a 18% chance to Chain an additional time": {"enchant": "Storm Brand has a 18% chance to Chain an additional time", "type": "currency very high"},
	"1 Storm Burst has a 15% chance to create an additional Orb": {"enchant": "Storm Burst has a 15% chance to create an additional Orb", "type": "currency very high"},
	"1 Summoned Agony Crawler fires 2 additional Projectiles": {"enchant": "Summoned Agony Crawler fires 2 additional Projectiles", "type": "currency extremely high"},
	"1 Tectonic Slam has 20% chance to create a Charged Slam": {"enchant": "Tectonic Slam has 20% chance to create a Charged Slam", "type": "currency very high"},
	"1 Tornado Shot fires 2 additional secondary Projectiles": {"enchant": "Tornado Shot fires 2 additional secondary Projectiles", "type": "currency extremely high"},
	"1 Tornado Shot fires an additional secondary Projectile": {"enchant": "Tornado Shot fires an additional secondary Projectile", "type": "currency very high"},
	"1 Toxic Rain deals 40% increased Damage": {"enchant": "Toxic Rain deals 40% increased Damage", "type": "currency very high"},
	"1 Toxic Rain fires 1 additional Arrow": {"enchant": "Toxic Rain fires 1 additional Arrow", "type": "currency very high"},
	"1 Vortex has 30% increased Cooldown Recovery Speed": {"enchant": "Vortex has 30% increased Cooldown Recovery Speed", "type": "currency very high"},
	"1 Wave of Conviction deals 40% increased Damage": {"enchant": "Wave of Conviction deals 40% increased Damage", "type": "currency very high"},
	"1 Wave of Conviction has 30% increased Duration": {"enchant": "Wave of Conviction has 30% increased Duration", "type": "currency very high"},
	"1 Wave of Conviction's Exposure applies -6% Elemental Resistance": {"enchant": "Wave of Conviction's Exposure applies -6% Elemental Resistance", "type": "currency very high"},
	"1 Wild Strike Chains an additional 6 times": {"enchant": "Wild Strike Chains an additional 6 times", "type": "currency very high"},
	"1 Winter Orb deals 25% increased Damage": {"enchant": "Winter Orb deals 25% increased Damage", "type": "currency very high"},
	"1 Winter Orb deals 40% increased Damage": {"enchant": "Winter Orb deals 40% increased Damage", "type": "currency extremely high"},
	"1 Winter Orb has +2 Maximum Stages": {"enchant": "Winter Orb has +2 Maximum Stages", "type": "currency extremely high"},
	"1 Winter Orb has 3% increased Area of Effect per Stage": {"enchant": "Winter Orb has 3% increased Area of Effect per Stage", "type": "currency very high"},
	"1 Wither has 12% increased Area of Effect": {"enchant": "Wither has 12% increased Area of Effect", "type": "currency very high"},
	"1 Zealotry has 15% reduced Mana Reservation": {"enchant": "Zealotry has 15% reduced Mana Reservation", "type": "currency very high"},
}
