#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 07/02/2019(m/d/y) 04:49:35 UTC from "tmphardcore" data

desc = "Skill Gems Autogen"

# Base type : settings pair
items = {
	"00 True 000 Vaal Cold Snap": {"base": "Vaal Cold Snap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Cold Snap": {"base": "Cold Snap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem high"},
	"00 True 1 Vaal Blade Vortex": {"base": "Vaal Blade Vortex", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem extremely high"},
	"00 True 1 Vaal Burning Arrow": {"base": "Vaal Burning Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Detonate Dead": {"base": "Vaal Detonate Dead", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem high"},
	"00 True 1 Vaal Fireball": {"base": "Vaal Fireball", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Flameblast": {"base": "Vaal Flameblast", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Ground Slam": {"base": "Vaal Ground Slam", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Impurity of Fire": {"base": "Vaal Impurity of Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Impurity of Ice": {"base": "Vaal Impurity of Ice", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Lightning Strike": {"base": "Vaal Lightning Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Power Siphon": {"base": "Vaal Power Siphon", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Rain of Arrows": {"base": "Vaal Rain of Arrows", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Righteous Fire": {"base": "Vaal Righteous Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Vaal Spectral Throw": {"base": "Vaal Spectral Throw", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"00 True 1 Wither": {"base": "Wither", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"01 True 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 20", "Corrupted True"], "type": "gem extremely high"},
	"02 True 000 Vaal Ancestral Warchief": {"base": "Vaal Ancestral Warchief", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 001 Vaal Summon Skeletons": {"base": "Vaal Summon Skeletons", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 002 Vaal Righteous Fire": {"base": "Vaal Righteous Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 003 Vaal Detonate Dead": {"base": "Vaal Detonate Dead", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 004 Vaal Double Strike": {"base": "Vaal Double Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 005 Vaal Burning Arrow": {"base": "Vaal Burning Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 006 Vaal Blade Vortex": {"base": "Vaal Blade Vortex", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 007 Vaal Power Siphon": {"base": "Vaal Power Siphon", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 008 Vaal Ground Slam": {"base": "Vaal Ground Slam", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 009 Vaal Earthquake": {"base": "Vaal Earthquake", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 010 Vaal Flameblast": {"base": "Vaal Flameblast", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 011 Vaal Storm Call": {"base": "Vaal Storm Call", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 012 Vaal Fireball": {"base": "Vaal Fireball", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 013 Vaal Cyclone": {"base": "Vaal Cyclone", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 014 Blade Vortex": {"base": "Blade Vortex", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 015 Vaal Spark": {"base": "Vaal Spark", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Ancestral Protector": {"base": "Ancestral Protector", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Ancestral Warchief": {"base": "Ancestral Warchief", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Animate Weapon": {"base": "Animate Weapon", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Arctic Breath": {"base": "Arctic Breath", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Armageddon Brand": {"base": "Armageddon Brand", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Assassin's Mark": {"base": "Assassin's Mark", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Barrage": {"base": "Barrage", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Bear Trap": {"base": "Bear Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Berserk": {"base": "Berserk", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Blade Flurry": {"base": "Blade Flurry", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Bladefall": {"base": "Bladefall", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Bladestorm": {"base": "Bladestorm", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Blasphemy Support": {"base": "Blasphemy Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Blood Rage": {"base": "Blood Rage", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Bodyswap": {"base": "Bodyswap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Bone Offering": {"base": "Bone Offering", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Bonechill Support": {"base": "Bonechill Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Burning Arrow": {"base": "Burning Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Cast on Melee Kill Support": {"base": "Cast on Melee Kill Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Chain Hook": {"base": "Chain Hook", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Cleave": {"base": "Cleave", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Conductivity": {"base": "Conductivity", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Conversion Trap": {"base": "Conversion Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Convocation": {"base": "Convocation", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Cremation": {"base": "Cremation", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Curse On Hit Support": {"base": "Curse On Hit Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Despair": {"base": "Despair", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Detonate Dead": {"base": "Detonate Dead", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Dominating Blow": {"base": "Dominating Blow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Double Strike": {"base": "Double Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Dread Banner": {"base": "Dread Banner", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Dual Strike": {"base": "Dual Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Earthquake": {"base": "Earthquake", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Elemental Hit": {"base": "Elemental Hit", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Enduring Cry": {"base": "Enduring Cry", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Enfeeble": {"base": "Enfeeble", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Ethereal Knives": {"base": "Ethereal Knives", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Explosive Arrow": {"base": "Explosive Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Explosive Trap": {"base": "Explosive Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Fire Nova Mine": {"base": "Fire Nova Mine", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Fire Trap": {"base": "Fire Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Fireball": {"base": "Fireball", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Firestorm": {"base": "Firestorm", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Flame Dash": {"base": "Flame Dash", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Flame Surge": {"base": "Flame Surge", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Flameblast": {"base": "Flameblast", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Flammability": {"base": "Flammability", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Flesh Offering": {"base": "Flesh Offering", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Flicker Strike": {"base": "Flicker Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Frenzy": {"base": "Frenzy", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Frost Blades": {"base": "Frost Blades", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Frostblink": {"base": "Frostblink", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Frostbolt": {"base": "Frostbolt", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Glacial Cascade": {"base": "Glacial Cascade", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Ground Slam": {"base": "Ground Slam", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Hatred": {"base": "Hatred", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Heavy Strike": {"base": "Heavy Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem extremely high"},
	"02 True 1 Herald of Purity": {"base": "Herald of Purity", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Ice Crash": {"base": "Ice Crash", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Ice Trap": {"base": "Ice Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Increased Critical Damage Support": {"base": "Increased Critical Damage Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Infernal Blow": {"base": "Infernal Blow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Intensify Support": {"base": "Intensify Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Kinetic Blast": {"base": "Kinetic Blast", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Lacerate": {"base": "Lacerate", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Lancing Steel": {"base": "Lancing Steel", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Leap Slam": {"base": "Leap Slam", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Less Duration Support": {"base": "Less Duration Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Lightning Penetration Support": {"base": "Lightning Penetration Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Lightning Spire Trap": {"base": "Lightning Spire Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Lightning Tendrils": {"base": "Lightning Tendrils", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Malevolence": {"base": "Malevolence", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Molten Shell": {"base": "Molten Shell", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Molten Strike": {"base": "Molten Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Perforate": {"base": "Perforate", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Phase Run": {"base": "Phase Run", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Power Siphon": {"base": "Power Siphon", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Precision": {"base": "Precision", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Pride": {"base": "Pride", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Projectile Weakness": {"base": "Projectile Weakness", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Puncture": {"base": "Puncture", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Purity of Fire": {"base": "Purity of Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Purity of Lightning": {"base": "Purity of Lightning", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Raise Spectre": {"base": "Raise Spectre", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Rejuvenation Totem": {"base": "Rejuvenation Totem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Righteous Fire": {"base": "Righteous Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Scourge Arrow": {"base": "Scourge Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Searing Bond": {"base": "Searing Bond", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Seismic Trap": {"base": "Seismic Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Shattering Steel": {"base": "Shattering Steel", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Shock Nova": {"base": "Shock Nova", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Shrapnel Shot": {"base": "Shrapnel Shot", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Siege Ballista": {"base": "Siege Ballista", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Smite": {"base": "Smite", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Smoke Mine": {"base": "Smoke Mine", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Soulrend": {"base": "Soulrend", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Spark": {"base": "Spark", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Spell Cascade Support": {"base": "Spell Cascade Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Spirit Offering": {"base": "Spirit Offering", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Split Arrow": {"base": "Split Arrow", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Static Strike": {"base": "Static Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Steelskin": {"base": "Steelskin", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Storm Brand": {"base": "Storm Brand", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Storm Call": {"base": "Storm Call", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Summon Chaos Golem": {"base": "Summon Chaos Golem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Summon Flame Golem": {"base": "Summon Flame Golem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Summon Ice Golem": {"base": "Summon Ice Golem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Summon Lightning Golem": {"base": "Summon Lightning Golem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Summon Raging Spirit": {"base": "Summon Raging Spirit", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Summon Skeleton": {"base": "Summon Skeleton", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Summon Stone Golem": {"base": "Summon Stone Golem", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Sunder": {"base": "Sunder", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Sweep": {"base": "Sweep", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Tectonic Slam": {"base": "Tectonic Slam", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Tornado Shot": {"base": "Tornado Shot", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Toxic Rain": {"base": "Toxic Rain", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Clarity": {"base": "Vaal Clarity", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Cold Snap": {"base": "Vaal Cold Snap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Haste": {"base": "Vaal Haste", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Ice Nova": {"base": "Vaal Ice Nova", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Impurity of Fire": {"base": "Vaal Impurity of Fire", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Impurity of Ice": {"base": "Vaal Impurity of Ice", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Impurity of Lightning": {"base": "Vaal Impurity of Lightning", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vaal Lightning Strike": {"base": "Vaal Lightning Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Lightning Trap": {"base": "Vaal Lightning Trap", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Rain of Arrows": {"base": "Vaal Rain of Arrows", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Reave": {"base": "Vaal Reave", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vaal Spectral Throw": {"base": "Vaal Spectral Throw", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vengeance": {"base": "Vengeance", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Vigilant Strike": {"base": "Vigilant Strike", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"02 True 1 Void Manipulation Support": {"base": "Void Manipulation Support", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vortex": {"base": "Vortex", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Vulnerability": {"base": "Vulnerability", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Winter Orb": {"base": "Winter Orb", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Wither": {"base": "Wither", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"02 True 1 Zealotry": {"base": "Zealotry", "class": "Gems", "other": ["GemLevel >= 21", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"10 True 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"10 True 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 23", "Corrupted True"], "type": "gem high"},
	"10 True 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 23", "Corrupted True"], "type": "gem very high"},
	"11 False 1 Blight": {"base": "Blight", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"11 False 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"11 False 1 Increased Duration Support": {"base": "Increased Duration Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"11 True 000 Vaal Cyclone": {"base": "Vaal Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Added Cold Damage Support": {"base": "Added Cold Damage Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Caustic Arrow": {"base": "Caustic Arrow", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Close Combat Support": {"base": "Close Combat Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Controlled Destruction Support": {"base": "Controlled Destruction Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Efficacy Support": {"base": "Efficacy Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Elemental Hit": {"base": "Elemental Hit", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Faster Attacks Support": {"base": "Faster Attacks Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Soulrend": {"base": "Soulrend", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Spectral Shield Throw": {"base": "Spectral Shield Throw", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Storm Burst": {"base": "Storm Burst", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem high"},
	"11 True 1 Tornado Shot": {"base": "Tornado Shot", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"11 True 1 Void Manipulation Support": {"base": "Void Manipulation Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"12 True 000 Vaal Discipline": {"base": "Vaal Discipline", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 001 Vaal Cyclone": {"base": "Vaal Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 002 Vaal Blight": {"base": "Vaal Blight", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 1 Anger": {"base": "Anger", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Blight": {"base": "Blight", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Caustic Arrow": {"base": "Caustic Arrow", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Discipline": {"base": "Discipline", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 1 Elemental Hit": {"base": "Elemental Hit", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Malevolence": {"base": "Malevolence", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 1 Precision": {"base": "Precision", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 1 Pride": {"base": "Pride", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Purity of Fire": {"base": "Purity of Fire", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Purity of Lightning": {"base": "Purity of Lightning", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 True 1 Spectral Shield Throw": {"base": "Spectral Shield Throw", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Summon Phantasm Support": {"base": "Summon Phantasm Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Toxic Rain": {"base": "Toxic Rain", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Vaal Double Strike": {"base": "Vaal Double Strike", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Vaal Impurity of Fire": {"base": "Vaal Impurity of Fire", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Vaal Impurity of Ice": {"base": "Vaal Impurity of Ice", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Vaal Impurity of Lightning": {"base": "Vaal Impurity of Lightning", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"12 True 1 Wrath": {"base": "Wrath", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"12 False 1 Ancestral Warchief": {"base": "Ancestral Warchief", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"12 False 1 Blight": {"base": "Blight", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Blood Magic Support": {"base": "Blood Magic Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Controlled Destruction Support": {"base": "Controlled Destruction Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Determination": {"base": "Determination", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Faster Attacks Support": {"base": "Faster Attacks Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Faster Casting Support": {"base": "Faster Casting Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"12 False 1 Fortify Support": {"base": "Fortify Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"12 False 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Increased Duration Support": {"base": "Increased Duration Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Infused Channelling Support": {"base": "Infused Channelling Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Leap Slam": {"base": "Leap Slam", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"12 False 1 Maim Support": {"base": "Maim Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Melee Physical Damage Support": {"base": "Melee Physical Damage Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Minion Damage Support": {"base": "Minion Damage Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Rage Support": {"base": "Rage Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"12 False 1 Ruthless Support": {"base": "Ruthless Support", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"12 False 1 Steelskin": {"base": "Steelskin", "class": "Gems", "other": ["GemLevel >= 20", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"20 True 1 Brand Recall": {"base": "Brand Recall", "class": "Gems", "other": ["GemLevel >= 7", "Quality >= 20", "Corrupted True"], "type": "gem very high"},
	"30 True 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 4", "Quality >= 0", "Corrupted True"], "type": "gem extremely high"},
	"40 False 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted False"], "type": "gem extremely high"},
	"40 False 1 Enhance Support": {"base": "Enhance Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"40 False 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted False"], "type": "gem extremely high"},
	"40 True 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"40 True 1 Enhance Support": {"base": "Enhance Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"40 True 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 3", "Quality >= 0", "Corrupted True"], "type": "gem extremely high"},
	"50 False 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"50 False 1 Enhance Support": {"base": "Enhance Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"50 False 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"50 True 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"50 True 1 Enhance Support": {"base": "Enhance Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted True"], "type": "gem high"},
	"50 True 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 2", "Quality >= 0", "Corrupted True"], "type": "gem very high"},
	"60 False 000 Arctic Breath": {"base": "Arctic Breath", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 001 Arctic Armour": {"base": "Arctic Armour", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Abyssal Cry": {"base": "Abyssal Cry", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ancestral Protector": {"base": "Ancestral Protector", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ancestral Warchief": {"base": "Ancestral Warchief", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Animate Guardian": {"base": "Animate Guardian", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Animate Weapon": {"base": "Animate Weapon", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Arc": {"base": "Arc", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Armageddon Brand": {"base": "Armageddon Brand", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Assassin's Mark": {"base": "Assassin's Mark", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ball Lightning": {"base": "Ball Lightning", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Bane": {"base": "Bane", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Barrage": {"base": "Barrage", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Berserk": {"base": "Berserk", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Blade Flurry": {"base": "Blade Flurry", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Bladestorm": {"base": "Bladestorm", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Blast Rain": {"base": "Blast Rain", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Blight": {"base": "Blight", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Blink Arrow": {"base": "Blink Arrow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Blood and Sand": {"base": "Blood and Sand", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Bone Offering": {"base": "Bone Offering", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Brand Recall": {"base": "Brand Recall", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Burning Arrow": {"base": "Burning Arrow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Caustic Arrow": {"base": "Caustic Arrow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Chain Hook": {"base": "Chain Hook", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Chance to Bleed Support": {"base": "Chance to Bleed Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Charged Dash": {"base": "Charged Dash", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Cleave": {"base": "Cleave", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Close Combat Support": {"base": "Close Combat Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Cold Snap": {"base": "Cold Snap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Conductivity": {"base": "Conductivity", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Consecrated Path": {"base": "Consecrated Path", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Cremation": {"base": "Cremation", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Cyclone": {"base": "Cyclone", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Dark Pact": {"base": "Dark Pact", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Decoy Totem": {"base": "Decoy Totem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Desecrate": {"base": "Desecrate", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Despair": {"base": "Despair", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Detonate Dead": {"base": "Detonate Dead", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Discharge": {"base": "Discharge", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Divine Ire": {"base": "Divine Ire", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Dominating Blow": {"base": "Dominating Blow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Double Strike": {"base": "Double Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Dual Strike": {"base": "Dual Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Earthquake": {"base": "Earthquake", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Elemental Hit": {"base": "Elemental Hit", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Enduring Cry": {"base": "Enduring Cry", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Enfeeble": {"base": "Enfeeble", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Essence Drain": {"base": "Essence Drain", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Explosive Arrow": {"base": "Explosive Arrow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Explosive Trap": {"base": "Explosive Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Fire Nova Mine": {"base": "Fire Nova Mine", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Fire Trap": {"base": "Fire Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Fireball": {"base": "Fireball", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Firestorm": {"base": "Firestorm", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Flame Dash": {"base": "Flame Dash", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Flameblast": {"base": "Flameblast", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Flesh Offering": {"base": "Flesh Offering", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Flesh and Stone": {"base": "Flesh and Stone", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Flicker Strike": {"base": "Flicker Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Freezing Pulse": {"base": "Freezing Pulse", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Frenzy": {"base": "Frenzy", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Frost Blades": {"base": "Frost Blades", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Frostbite": {"base": "Frostbite", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Frostblink": {"base": "Frostblink", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Glacial Cascade": {"base": "Glacial Cascade", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Glacial Hammer": {"base": "Glacial Hammer", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ground Slam": {"base": "Ground Slam", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Haste": {"base": "Haste", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Hatred": {"base": "Hatred", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Heavy Strike": {"base": "Heavy Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Herald of Agony": {"base": "Herald of Agony", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Herald of Purity": {"base": "Herald of Purity", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Holy Flame Totem": {"base": "Holy Flame Totem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ice Crash": {"base": "Ice Crash", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ice Nova": {"base": "Ice Nova", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ice Shot": {"base": "Ice Shot", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ice Spear": {"base": "Ice Spear", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Ice Trap": {"base": "Ice Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Incinerate": {"base": "Incinerate", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Increased Critical Damage Support": {"base": "Increased Critical Damage Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Infernal Blow": {"base": "Infernal Blow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lacerate": {"base": "Lacerate", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lancing Steel": {"base": "Lancing Steel", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Leap Slam": {"base": "Leap Slam", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lightning Spire Trap": {"base": "Lightning Spire Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lightning Strike": {"base": "Lightning Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lightning Trap": {"base": "Lightning Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Lightning Warp": {"base": "Lightning Warp", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Magma Orb": {"base": "Magma Orb", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Malevolence": {"base": "Malevolence", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Minion Life Support": {"base": "Minion Life Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Molten Strike": {"base": "Molten Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Multistrike Support": {"base": "Multistrike Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Orb of Storms": {"base": "Orb of Storms", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Poacher's Mark": {"base": "Poacher's Mark", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Power Siphon": {"base": "Power Siphon", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Pride": {"base": "Pride", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Projectile Weakness": {"base": "Projectile Weakness", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Puncture": {"base": "Puncture", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Purifying Flame": {"base": "Purifying Flame", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Purity of Elements": {"base": "Purity of Elements", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Purity of Fire": {"base": "Purity of Fire", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Purity of Lightning": {"base": "Purity of Lightning", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Rage Support": {"base": "Rage Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Rain of Arrows": {"base": "Rain of Arrows", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Rallying Cry": {"base": "Rallying Cry", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Reave": {"base": "Reave", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Righteous Fire": {"base": "Righteous Fire", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Riposte": {"base": "Riposte", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Scorching Ray": {"base": "Scorching Ray", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Seismic Trap": {"base": "Seismic Trap", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Shattering Steel": {"base": "Shattering Steel", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Shock Nova": {"base": "Shock Nova", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Shockwave Totem": {"base": "Shockwave Totem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Shrapnel Shot": {"base": "Shrapnel Shot", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Smite": {"base": "Smite", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Soulrend": {"base": "Soulrend", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Spectral Shield Throw": {"base": "Spectral Shield Throw", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Spectral Throw": {"base": "Spectral Throw", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Spirit Offering": {"base": "Spirit Offering", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Split Arrow": {"base": "Split Arrow", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Steelskin": {"base": "Steelskin", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Storm Burst": {"base": "Storm Burst", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Storm Call": {"base": "Storm Call", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Chaos Golem": {"base": "Summon Chaos Golem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Flame Golem": {"base": "Summon Flame Golem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Holy Relic": {"base": "Summon Holy Relic", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Ice Golem": {"base": "Summon Ice Golem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Lightning Golem": {"base": "Summon Lightning Golem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Phantasm Support": {"base": "Summon Phantasm Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Raging Spirit": {"base": "Summon Raging Spirit", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Skeleton": {"base": "Summon Skeleton", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Summon Stone Golem": {"base": "Summon Stone Golem", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Sunder": {"base": "Sunder", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Sweep": {"base": "Sweep", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Tectonic Slam": {"base": "Tectonic Slam", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Temporal Chains": {"base": "Temporal Chains", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Tornado Shot": {"base": "Tornado Shot", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Unearth": {"base": "Unearth", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Vicious Projectiles Support": {"base": "Vicious Projectiles Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem very high"},
	"60 False 1 Viper Strike": {"base": "Viper Strike", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Volatile Dead": {"base": "Volatile Dead", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Vortex": {"base": "Vortex", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Warlord's Mark": {"base": "Warlord's Mark", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Wave of Conviction": {"base": "Wave of Conviction", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Winter Orb": {"base": "Winter Orb", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Wither": {"base": "Wither", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Wrath": {"base": "Wrath", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"60 False 1 Zealotry": {"base": "Zealotry", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 20", "Corrupted False"], "type": "gem high"},
	"61 False 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"61 False 1 Enlighten Support": {"base": "Enlighten Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 0", "Corrupted False"], "type": "gem very high"},
	"61 False 1 Portal": {"base": "Portal", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 0", "Corrupted False"], "type": "gem high"},
	"61 True 1 Empower Support": {"base": "Empower Support", "class": "Gems", "other": ["GemLevel >= 1", "Quality >= 0", "Corrupted True"], "type": "gem high"},
}
