#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 11/28/2018(m/d/y) 02:21:06 UTC from "tmphardcore" data

desc = "Unique"

# Base type : settings pair
items = {
	"0 Ambush Mitts": {"base": "Ambush Mitts", "type": "unique extremely high"},
	"0 Assassin's Boots": {"base": "Assassin's Boots", "type": "unique extremely high"},
	"0 Callous Mask": {"base": "Callous Mask", "type": "unique extremely high"},
	"0 Carnal Boots": {"base": "Carnal Boots", "type": "unique extremely high"},
	"0 Chateau Map": {"base": "Chateau Map", "type": "unique extremely high"},
	"0 Clutching Talisman": {"base": "Clutching Talisman", "type": "unique extremely high"},
	"0 Crusader Boots": {"base": "Crusader Boots", "type": "unique extremely high"},
	"0 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique extremely high"},
	"0 Ezomyte Tower Shield": {"base": "Ezomyte Tower Shield", "type": "unique extremely high"},
	"0 Gemstone Sword": {"base": "Gemstone Sword", "type": "unique extremely high"},
	"0 Glorious Plate": {"base": "Glorious Plate", "type": "unique extremely high"},
	"0 Golden Bracers": {"base": "Golden Bracers", "type": "unique extremely high"},
	"0 Golden Hoop": {"base": "Golden Hoop", "type": "unique extremely high"},
	"0 Golden Mantle": {"base": "Golden Mantle", "type": "unique extremely high"},
	"0 Golden Obi": {"base": "Golden Obi", "type": "unique extremely high"},
	"0 Golden Wreath": {"base": "Golden Wreath", "type": "unique extremely high"},
	"0 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique extremely high"},
	"0 Greatwolf Talisman": {"base": "Greatwolf Talisman", "type": "unique extremely high"},
	"0 Harbinger Map": {"base": "Harbinger Map", "type": "unique extremely high"},
	"0 Harlequin Mask": {"base": "Harlequin Mask", "type": "unique extremely high"},
	"0 Heavy Quiver": {"base": "Heavy Quiver", "type": "unique extremely high"},
	"0 Hydrascale Gauntlets": {"base": "Hydrascale Gauntlets", "type": "unique extremely high"},
	"0 Jet Amulet": {"base": "Jet Amulet", "type": "unique extremely high"},
	"0 Legion Gloves": {"base": "Legion Gloves", "type": "unique extremely high"},
	"0 Maze Map": {"base": "Maze Map", "type": "unique extremely high"},
	"0 Museum Map": {"base": "Museum Map", "type": "unique extremely high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique extremely high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique extremely high"},
	"0 Rotfeather Talisman": {"base": "Rotfeather Talisman", "type": "unique extremely high"},
	"0 Royal Axe": {"base": "Royal Axe", "type": "unique extremely high"},
	"1 Ancient Spirit Shield": {"base": "Ancient Spirit Shield", "type": "unique very high"},
	"1 Arcanist Gloves": {"base": "Arcanist Gloves", "type": "unique very high"},
	"1 Arcanist Slippers": {"base": "Arcanist Slippers", "type": "unique very high"},
	"1 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique very high"},
	"1 Blood Raiment": {"base": "Blood Raiment", "type": "unique very high"},
	"1 Blunt Arrow Quiver Piece": {"base": "Blunt Arrow Quiver Piece", "type": "unique very high"},
	"1 Callous Mask Piece": {"base": "Callous Mask Piece", "type": "unique very high"},
	"1 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique very high"},
	"1 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique very high"},
	"1 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique very high"},
	"1 Close Helmet": {"base": "Close Helmet", "type": "unique very high"},
	"1 Courtyard Map": {"base": "Courtyard Map", "type": "unique very high"},
	"1 Crusader Helmet": {"base": "Crusader Helmet", "type": "unique very high"},
	"1 Deicide Mask": {"base": "Deicide Mask", "type": "unique very high"},
	"1 Destiny Leather": {"base": "Destiny Leather", "type": "unique very high"},
	"1 Eternal Sword": {"base": "Eternal Sword", "type": "unique very high"},
	"1 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique very high"},
	"1 Gladiator Plate": {"base": "Gladiator Plate", "type": "unique very high"},
	"1 Granite Flask": {"base": "Granite Flask", "type": "unique very high"},
	"1 Hellion's Paw": {"base": "Hellion's Paw", "type": "unique very high"},
	"1 Hydrascale Boots": {"base": "Hydrascale Boots", "type": "unique very high"},
	"1 Imperial Maul": {"base": "Imperial Maul", "type": "unique very high"},
	"1 Jewelled Foil": {"base": "Jewelled Foil", "type": "unique very high"},
	"1 Jingling Spirit Shield": {"base": "Jingling Spirit Shield", "type": "unique very high"},
	"1 Karui Sceptre": {"base": "Karui Sceptre", "type": "unique very high"},
	"1 Leather Cap": {"base": "Leather Cap", "type": "unique very high"},
	"1 Magistrate Crown": {"base": "Magistrate Crown", "type": "unique very high"},
	"1 Midnight Blade": {"base": "Midnight Blade", "type": "unique very high"},
	"1 Moon Temple Map": {"base": "Moon Temple Map", "type": "unique very high"},
	"1 Nightmare Mace": {"base": "Nightmare Mace", "type": "unique very high"},
	"1 Nubuck Gloves": {"base": "Nubuck Gloves", "type": "unique very high"},
	"1 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique very high"},
	"1 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique very high"},
	"1 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique very high"},
	"1 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"1 Promenade Map": {"base": "Promenade Map", "type": "unique very high"},
	"1 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique very high"},
	"1 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique very high"},
	"1 Riveted Gloves": {"base": "Riveted Gloves", "type": "unique very high"},
	"1 Ruby Amulet": {"base": "Ruby Amulet", "type": "unique very high"},
	"1 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique very high"},
	"1 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique very high"},
	"1 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique very high"},
	"1 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"1 Satin Gloves": {"base": "Satin Gloves", "type": "unique very high"},
	"1 Shackled Boots": {"base": "Shackled Boots", "type": "unique very high"},
	"1 Sharkskin Tunic": {"base": "Sharkskin Tunic", "type": "unique very high"},
	"1 Shore Map": {"base": "Shore Map", "type": "unique very high"},
	"1 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"1 Slink Boots": {"base": "Slink Boots", "type": "unique very high"},
	"1 Steel Ring": {"base": "Steel Ring", "type": "unique very high"},
	"1 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique very high"},
	"1 Temple Map": {"base": "Temple Map", "type": "unique very high"},
	"1 Thorium Spirit Shield": {"base": "Thorium Spirit Shield", "type": "unique very high"},
	"1 Titan Greaves": {"base": "Titan Greaves", "type": "unique very high"},
	"1 Topaz Flask": {"base": "Topaz Flask", "type": "unique very high"},
	"1 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique very high"},
	"1 Vaal Mask": {"base": "Vaal Mask", "type": "unique very high"},
	"1 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique very high"},
	"1 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique very high"},
	"1 Vaal Spirit Shield": {"base": "Vaal Spirit Shield", "type": "unique very high"},
	"1 Variscite Blade": {"base": "Variscite Blade", "type": "unique very high"},
	"1 Void Axe": {"base": "Void Axe", "type": "unique very high"},
	"1 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique very high"},
	"1 Wyrmscale Doublet": {"base": "Wyrmscale Doublet", "type": "unique very high"},
	"1 Zealot Gloves": {"base": "Zealot Gloves", "type": "unique very high"},
	"2 Ancient Spirit Shield": {"base": "Ancient Spirit Shield", "type": "unique high"},
	"2 Arcanist Gloves": {"base": "Arcanist Gloves", "type": "unique high"},
	"2 Arcanist Slippers": {"base": "Arcanist Slippers", "type": "unique high"},
	"2 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique high"},
	"2 Blood Raiment": {"base": "Blood Raiment", "type": "unique high"},
	"2 Blunt Arrow Quiver Piece": {"base": "Blunt Arrow Quiver Piece", "type": "unique high"},
	"2 Callous Mask Piece": {"base": "Callous Mask Piece", "type": "unique high"},
	"2 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique high"},
	"2 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique high"},
	"2 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique high"},
	"2 Close Helmet": {"base": "Close Helmet", "type": "unique high"},
	"2 Courtyard Map": {"base": "Courtyard Map", "type": "unique high"},
	"2 Crusader Helmet": {"base": "Crusader Helmet", "type": "unique high"},
	"2 Deicide Mask": {"base": "Deicide Mask", "type": "unique high"},
	"2 Destiny Leather": {"base": "Destiny Leather", "type": "unique high"},
	"2 Eternal Sword": {"base": "Eternal Sword", "type": "unique high"},
	"2 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique high"},
	"2 Gladiator Plate": {"base": "Gladiator Plate", "type": "unique high"},
	"2 Granite Flask": {"base": "Granite Flask", "type": "unique high"},
	"2 Hellion's Paw": {"base": "Hellion's Paw", "type": "unique high"},
	"2 Hydrascale Boots": {"base": "Hydrascale Boots", "type": "unique high"},
	"2 Imperial Maul": {"base": "Imperial Maul", "type": "unique high"},
	"2 Jewelled Foil": {"base": "Jewelled Foil", "type": "unique high"},
	"2 Jingling Spirit Shield": {"base": "Jingling Spirit Shield", "type": "unique high"},
	"2 Karui Sceptre": {"base": "Karui Sceptre", "type": "unique high"},
	"2 Leather Cap": {"base": "Leather Cap", "type": "unique high"},
	"2 Magistrate Crown": {"base": "Magistrate Crown", "type": "unique high"},
	"2 Midnight Blade": {"base": "Midnight Blade", "type": "unique high"},
	"2 Moon Temple Map": {"base": "Moon Temple Map", "type": "unique high"},
	"2 Nightmare Mace": {"base": "Nightmare Mace", "type": "unique high"},
	"2 Nubuck Gloves": {"base": "Nubuck Gloves", "type": "unique high"},
	"2 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique high"},
	"2 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique high"},
	"2 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique high"},
	"2 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique high"},
	"2 Promenade Map": {"base": "Promenade Map", "type": "unique high"},
	"2 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique high"},
	"2 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique high"},
	"2 Riveted Gloves": {"base": "Riveted Gloves", "type": "unique high"},
	"2 Ruby Amulet": {"base": "Ruby Amulet", "type": "unique high"},
	"2 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique high"},
	"2 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique high"},
	"2 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique high"},
	"2 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique high"},
	"2 Satin Gloves": {"base": "Satin Gloves", "type": "unique high"},
	"2 Shackled Boots": {"base": "Shackled Boots", "type": "unique high"},
	"2 Sharkskin Tunic": {"base": "Sharkskin Tunic", "type": "unique high"},
	"2 Shore Map": {"base": "Shore Map", "type": "unique high"},
	"2 Siege Axe": {"base": "Siege Axe", "type": "unique high"},
	"2 Slink Boots": {"base": "Slink Boots", "type": "unique high"},
	"2 Steel Ring": {"base": "Steel Ring", "type": "unique high"},
	"2 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique high"},
	"2 Temple Map": {"base": "Temple Map", "type": "unique high"},
	"2 Thorium Spirit Shield": {"base": "Thorium Spirit Shield", "type": "unique high"},
	"2 Titan Greaves": {"base": "Titan Greaves", "type": "unique high"},
	"2 Topaz Flask": {"base": "Topaz Flask", "type": "unique high"},
	"2 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique high"},
	"2 Vaal Mask": {"base": "Vaal Mask", "type": "unique high"},
	"2 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique high"},
	"2 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique high"},
	"2 Vaal Spirit Shield": {"base": "Vaal Spirit Shield", "type": "unique high"},
	"2 Variscite Blade": {"base": "Variscite Blade", "type": "unique high"},
	"2 Void Axe": {"base": "Void Axe", "type": "unique high"},
	"2 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique high"},
	"2 Wyrmscale Doublet": {"base": "Wyrmscale Doublet", "type": "unique high"},
	"2 Zealot Gloves": {"base": "Zealot Gloves", "type": "unique high"},
	"6 Archon Kite Shield Piece": {"base": "Archon Kite Shield Piece", "type": "unique special"},
	"6 Blunt Arrow Quiver": {"base": "Blunt Arrow Quiver", "type": "unique special"},
	"6 Carved Wand": {"base": "Carved Wand", "type": "unique special"},
	"6 Cloth Belt Piece": {"base": "Cloth Belt Piece", "type": "unique special"},
	"6 Cobalt Jewel": {"base": "Cobalt Jewel", "type": "unique special"},
	"6 Coral Amulet": {"base": "Coral Amulet", "type": "unique special"},
	"6 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique special"},
	"6 Cutlass": {"base": "Cutlass", "type": "unique special"},
	"6 Elegant Ringmail": {"base": "Elegant Ringmail", "type": "unique special"},
	"6 Exquisite Leather": {"base": "Exquisite Leather", "type": "unique special"},
	"6 Ezomyte Staff": {"base": "Ezomyte Staff", "type": "unique special"},
	"6 Gold Amulet": {"base": "Gold Amulet", "type": "unique special"},
	"6 Goliath Greaves": {"base": "Goliath Greaves", "type": "unique special"},
	"6 Great Crown": {"base": "Great Crown", "type": "unique special"},
	"6 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique special"},
	"6 Imperial Skean": {"base": "Imperial Skean", "type": "unique special"},
	"6 Iron Ring": {"base": "Iron Ring", "type": "unique special"},
	"6 Maelström Staff": {"base": "Maelström Staff", "type": "unique special"},
	"6 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique special"},
	"6 Opal Ring": {"base": "Opal Ring", "type": "unique special"},
	"6 Prismatic Ring": {"base": "Prismatic Ring", "type": "unique special"},
	"6 Ruby Flask": {"base": "Ruby Flask", "type": "unique special"},
	"6 Sadist Garb": {"base": "Sadist Garb", "type": "unique special"},
	"6 Sapphire Ring": {"base": "Sapphire Ring", "type": "unique special"},
	"6 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique special"},
	"6 Steelscale Gauntlets": {"base": "Steelscale Gauntlets", "type": "unique special"},
	"6 Unset Ring": {"base": "Unset Ring", "type": "unique special"},
	"7 Antique Rapier": {"base": "Antique Rapier", "type": "unique low"},
	"7 Awl": {"base": "Awl", "type": "unique low"},
	"7 Decimation Bow": {"base": "Decimation Bow", "type": "unique low"},
	"7 Ezomyte Axe": {"base": "Ezomyte Axe", "type": "unique low"},
	"7 Gnarled Branch": {"base": "Gnarled Branch", "type": "unique low"},
	"7 Great Helmet": {"base": "Great Helmet", "type": "unique low"},
	"7 Harbinger Bow": {"base": "Harbinger Bow", "type": "unique low"},
	"7 Harmonic Spirit Shield": {"base": "Harmonic Spirit Shield", "type": "unique low"},
	"7 Holy Chainmail": {"base": "Holy Chainmail", "type": "unique low"},
	"7 Imbued Wand": {"base": "Imbued Wand", "type": "unique low"},
	"7 Iron Staff": {"base": "Iron Staff", "type": "unique low"},
	"7 Leatherscale Boots": {"base": "Leatherscale Boots", "type": "unique low"},
	"7 Military Staff": {"base": "Military Staff", "type": "unique low"},
	"7 Regicide Mask": {"base": "Regicide Mask", "type": "unique low"},
	"7 Serrated Arrow Quiver": {"base": "Serrated Arrow Quiver", "type": "unique low"},
	"7 Simple Robe": {"base": "Simple Robe", "type": "unique low"},
	"7 Skinning Knife": {"base": "Skinning Knife", "type": "unique low"},
	"7 Sledgehammer": {"base": "Sledgehammer", "type": "unique low"},
	"7 Stiletto": {"base": "Stiletto", "type": "unique low"},
	"7 Sundering Axe": {"base": "Sundering Axe", "type": "unique low"},
	"7 Velvet Slippers": {"base": "Velvet Slippers", "type": "unique low"},
	"7 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique low"},
	"7 War Buckler": {"base": "War Buckler", "type": "unique low"},
	"9 Other uniques": {"type": "unique normal"}
}
