#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 10/26/2018(m/d/y) 18:12:06 UTC from "tmphardcore" data

desc = "Unique"

# Base type : settings pair
items = {
	"0 Arcanist Gloves": {"base": "Arcanist Gloves", "type": "unique extremely high"},
	"0 Blood Raiment": {"base": "Blood Raiment", "type": "unique extremely high"},
	"0 Callous Mask": {"base": "Callous Mask", "type": "unique extremely high"},
	"0 Chateau Map": {"base": "Chateau Map", "type": "unique extremely high"},
	"0 Clutching Talisman": {"base": "Clutching Talisman", "type": "unique extremely high"},
	"0 Crusader Boots": {"base": "Crusader Boots", "type": "unique extremely high"},
	"0 Ezomyte Tower Shield": {"base": "Ezomyte Tower Shield", "type": "unique extremely high"},
	"0 Glorious Plate": {"base": "Glorious Plate", "type": "unique extremely high"},
	"0 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique extremely high"},
	"0 Greatwolf Talisman": {"base": "Greatwolf Talisman", "type": "unique extremely high"},
	"0 Ironscale Gauntlets": {"base": "Ironscale Gauntlets", "type": "unique extremely high"},
	"0 Legion Gloves": {"base": "Legion Gloves", "type": "unique extremely high"},
	"0 Magistrate Crown": {"base": "Magistrate Crown", "type": "unique extremely high"},
	"0 Maze Map": {"base": "Maze Map", "type": "unique extremely high"},
	"0 Nightmare Mace": {"base": "Nightmare Mace", "type": "unique extremely high"},
	"0 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique extremely high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique extremely high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique extremely high"},
	"0 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique extremely high"},
	"0 Riveted Gloves": {"base": "Riveted Gloves", "type": "unique extremely high"},
	"0 Rotfeather Talisman": {"base": "Rotfeather Talisman", "type": "unique extremely high"},
	"0 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique extremely high"},
	"1 Archon Kite Shield Piece": {"base": "Archon Kite Shield Piece", "type": "unique very high"},
	"1 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique very high"},
	"1 Blinder": {"base": "Blinder", "type": "unique very high"},
	"1 Blood Sceptre": {"base": "Blood Sceptre", "type": "unique very high"},
	"1 Blunt Arrow Quiver Piece": {"base": "Blunt Arrow Quiver Piece", "type": "unique very high"},
	"1 Callous Mask Piece": {"base": "Callous Mask Piece", "type": "unique very high"},
	"1 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique very high"},
	"1 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique very high"},
	"1 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique very high"},
	"1 Corsair Sword": {"base": "Corsair Sword", "type": "unique very high"},
	"1 Courtyard Map": {"base": "Courtyard Map", "type": "unique very high"},
	"1 Cutlass": {"base": "Cutlass", "type": "unique very high"},
	"1 Deicide Mask": {"base": "Deicide Mask", "type": "unique very high"},
	"1 Destiny Leather": {"base": "Destiny Leather", "type": "unique very high"},
	"1 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique very high"},
	"1 Gladiator Plate": {"base": "Gladiator Plate", "type": "unique very high"},
	"1 Granite Flask": {"base": "Granite Flask", "type": "unique very high"},
	"1 Harbinger Map": {"base": "Harbinger Map", "type": "unique very high"},
	"1 Harlequin Mask": {"base": "Harlequin Mask", "type": "unique very high"},
	"1 Highborn Staff": {"base": "Highborn Staff", "type": "unique very high"},
	"1 Hydrascale Boots": {"base": "Hydrascale Boots", "type": "unique very high"},
	"1 Imperial Maul": {"base": "Imperial Maul", "type": "unique very high"},
	"1 Jewelled Foil": {"base": "Jewelled Foil", "type": "unique very high"},
	"1 Leather Cap": {"base": "Leather Cap", "type": "unique very high"},
	"1 Moon Temple Map": {"base": "Moon Temple Map", "type": "unique very high"},
	"1 Museum Map": {"base": "Museum Map", "type": "unique very high"},
	"1 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique very high"},
	"1 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"1 Raven Mask": {"base": "Raven Mask", "type": "unique very high"},
	"1 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique very high"},
	"1 Royal Burgonet": {"base": "Royal Burgonet", "type": "unique very high"},
	"1 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique very high"},
	"1 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique very high"},
	"1 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique very high"},
	"1 Shore Map": {"base": "Shore Map", "type": "unique very high"},
	"1 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"1 Steel Ring": {"base": "Steel Ring", "type": "unique very high"},
	"1 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique very high"},
	"1 Titan Greaves": {"base": "Titan Greaves", "type": "unique very high"},
	"1 Vaal Mask": {"base": "Vaal Mask", "type": "unique very high"},
	"1 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique very high"},
	"1 Void Axe": {"base": "Void Axe", "type": "unique very high"},
	"1 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique very high"},
	"1 Wyrmscale Doublet": {"base": "Wyrmscale Doublet", "type": "unique very high"},
	"2 Archon Kite Shield Piece": {"base": "Archon Kite Shield Piece", "type": "unique high"},
	"2 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique high"},
	"2 Blinder": {"base": "Blinder", "type": "unique high"},
	"2 Blood Sceptre": {"base": "Blood Sceptre", "type": "unique high"},
	"2 Blunt Arrow Quiver Piece": {"base": "Blunt Arrow Quiver Piece", "type": "unique high"},
	"2 Callous Mask Piece": {"base": "Callous Mask Piece", "type": "unique high"},
	"2 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique high"},
	"2 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique high"},
	"2 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique high"},
	"2 Corsair Sword": {"base": "Corsair Sword", "type": "unique high"},
	"2 Courtyard Map": {"base": "Courtyard Map", "type": "unique high"},
	"2 Cutlass": {"base": "Cutlass", "type": "unique high"},
	"2 Deicide Mask": {"base": "Deicide Mask", "type": "unique high"},
	"2 Destiny Leather": {"base": "Destiny Leather", "type": "unique high"},
	"2 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique high"},
	"2 Gladiator Plate": {"base": "Gladiator Plate", "type": "unique high"},
	"2 Granite Flask": {"base": "Granite Flask", "type": "unique high"},
	"2 Harbinger Map": {"base": "Harbinger Map", "type": "unique high"},
	"2 Harlequin Mask": {"base": "Harlequin Mask", "type": "unique high"},
	"2 Highborn Staff": {"base": "Highborn Staff", "type": "unique high"},
	"2 Hydrascale Boots": {"base": "Hydrascale Boots", "type": "unique high"},
	"2 Imperial Maul": {"base": "Imperial Maul", "type": "unique high"},
	"2 Jewelled Foil": {"base": "Jewelled Foil", "type": "unique high"},
	"2 Leather Cap": {"base": "Leather Cap", "type": "unique high"},
	"2 Moon Temple Map": {"base": "Moon Temple Map", "type": "unique high"},
	"2 Museum Map": {"base": "Museum Map", "type": "unique high"},
	"2 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique high"},
	"2 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique high"},
	"2 Raven Mask": {"base": "Raven Mask", "type": "unique high"},
	"2 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique high"},
	"2 Royal Burgonet": {"base": "Royal Burgonet", "type": "unique high"},
	"2 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique high"},
	"2 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique high"},
	"2 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique high"},
	"2 Shore Map": {"base": "Shore Map", "type": "unique high"},
	"2 Siege Axe": {"base": "Siege Axe", "type": "unique high"},
	"2 Steel Ring": {"base": "Steel Ring", "type": "unique high"},
	"2 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique high"},
	"2 Titan Greaves": {"base": "Titan Greaves", "type": "unique high"},
	"2 Vaal Mask": {"base": "Vaal Mask", "type": "unique high"},
	"2 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique high"},
	"2 Void Axe": {"base": "Void Axe", "type": "unique high"},
	"2 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique high"},
	"2 Wyrmscale Doublet": {"base": "Wyrmscale Doublet", "type": "unique high"},
	"6 Agate Amulet": {"base": "Agate Amulet", "type": "unique special"},
	"6 Amber Amulet": {"base": "Amber Amulet", "type": "unique special"},
	"6 Archon Kite Shield": {"base": "Archon Kite Shield", "type": "unique special"},
	"6 Blunt Arrow Quiver": {"base": "Blunt Arrow Quiver", "type": "unique special"},
	"6 Carnal Armour": {"base": "Carnal Armour", "type": "unique special"},
	"6 Carved Wand": {"base": "Carved Wand", "type": "unique special"},
	"6 Chain Belt": {"base": "Chain Belt", "type": "unique special"},
	"6 Cloth Belt": {"base": "Cloth Belt", "type": "unique special"},
	"6 Cobalt Jewel": {"base": "Cobalt Jewel", "type": "unique special"},
	"6 Coral Amulet": {"base": "Coral Amulet", "type": "unique special"},
	"6 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique special"},
	"6 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique special"},
	"6 Despot Axe": {"base": "Despot Axe", "type": "unique special"},
	"6 Ebony Tower Shield": {"base": "Ebony Tower Shield", "type": "unique special"},
	"6 Elegant Ringmail": {"base": "Elegant Ringmail", "type": "unique special"},
	"6 Elegant Sword": {"base": "Elegant Sword", "type": "unique special"},
	"6 Ezomyte Staff": {"base": "Ezomyte Staff", "type": "unique special"},
	"6 Gavel": {"base": "Gavel", "type": "unique special"},
	"6 Goathide Boots": {"base": "Goathide Boots", "type": "unique special"},
	"6 Gold Amulet": {"base": "Gold Amulet", "type": "unique special"},
	"6 Golden Plate": {"base": "Golden Plate", "type": "unique special"},
	"6 Goliath Greaves": {"base": "Goliath Greaves", "type": "unique special"},
	"6 Heavy Belt": {"base": "Heavy Belt", "type": "unique special"},
	"6 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique special"},
	"6 Imperial Bow": {"base": "Imperial Bow", "type": "unique special"},
	"6 Imperial Claw": {"base": "Imperial Claw", "type": "unique special"},
	"6 Imperial Staff": {"base": "Imperial Staff", "type": "unique special"},
	"6 Infernal Sword": {"base": "Infernal Sword", "type": "unique special"},
	"6 Iron Ring": {"base": "Iron Ring", "type": "unique special"},
	"6 Jade Amulet": {"base": "Jade Amulet", "type": "unique special"},
	"6 Lacquered Garb": {"base": "Lacquered Garb", "type": "unique special"},
	"6 Lapis Amulet": {"base": "Lapis Amulet", "type": "unique special"},
	"6 Leather Belt": {"base": "Leather Belt", "type": "unique special"},
	"6 Legion Sword": {"base": "Legion Sword", "type": "unique special"},
	"6 Maelström Staff": {"base": "Maelström Staff", "type": "unique special"},
	"6 Moonstone Ring": {"base": "Moonstone Ring", "type": "unique special"},
	"6 Murder Boots": {"base": "Murder Boots", "type": "unique special"},
	"6 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique special"},
	"6 Opal Ring": {"base": "Opal Ring", "type": "unique special"},
	"6 Paua Amulet": {"base": "Paua Amulet", "type": "unique special"},
	"6 Paua Ring": {"base": "Paua Ring", "type": "unique special"},
	"6 Prismatic Ring": {"base": "Prismatic Ring", "type": "unique special"},
	"6 Quartz Flask": {"base": "Quartz Flask", "type": "unique special"},
	"6 Ruby Flask": {"base": "Ruby Flask", "type": "unique special"},
	"6 Ruby Ring": {"base": "Ruby Ring", "type": "unique special"},
	"6 Rustic Sash": {"base": "Rustic Sash", "type": "unique special"},
	"6 Sadist Garb": {"base": "Sadist Garb", "type": "unique special"},
	"6 Sage Wand": {"base": "Sage Wand", "type": "unique special"},
	"6 Saintly Chainmail": {"base": "Saintly Chainmail", "type": "unique special"},
	"6 Sapphire Ring": {"base": "Sapphire Ring", "type": "unique special"},
	"6 Silken Hood": {"base": "Silken Hood", "type": "unique special"},
	"6 Slink Boots": {"base": "Slink Boots", "type": "unique special"},
	"6 Soldier Gloves": {"base": "Soldier Gloves", "type": "unique special"},
	"6 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique special"},
	"6 Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "type": "unique special"},
	"6 Steelscale Gauntlets": {"base": "Steelscale Gauntlets", "type": "unique special"},
	"6 Terror Claw": {"base": "Terror Claw", "type": "unique special"},
	"6 Titan Gauntlets": {"base": "Titan Gauntlets", "type": "unique special"},
	"6 Topaz Flask": {"base": "Topaz Flask", "type": "unique special"},
	"6 Topaz Ring": {"base": "Topaz Ring", "type": "unique special"},
	"6 Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "type": "unique special"},
	"6 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique special"},
	"6 Unset Ring": {"base": "Unset Ring", "type": "unique special"},
	"6 Vaal Axe": {"base": "Vaal Axe", "type": "unique special"},
	"6 Vaal Blade": {"base": "Vaal Blade", "type": "unique special"},
	"6 Vaal Gauntlets": {"base": "Vaal Gauntlets", "type": "unique special"},
	"6 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique special"},
	"6 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique special"},
	"6 Zealot Gloves": {"base": "Zealot Gloves", "type": "unique special"},
	"6 Zodiac Leather": {"base": "Zodiac Leather", "type": "unique special"},
	"7 Ambusher": {"base": "Ambusher", "type": "unique low"},
	"7 Assassin Bow": {"base": "Assassin Bow", "type": "unique low"},
	"7 Assassin's Mitts": {"base": "Assassin's Mitts", "type": "unique low"},
	"7 Awl": {"base": "Awl", "type": "unique low"},
	"7 Baroque Round Shield": {"base": "Baroque Round Shield", "type": "unique low"},
	"7 Bastard Sword": {"base": "Bastard Sword", "type": "unique low"},
	"7 Boot Blade": {"base": "Boot Blade", "type": "unique low"},
	"7 Boot Knife": {"base": "Boot Knife", "type": "unique low"},
	"7 Brass Spirit Shield": {"base": "Brass Spirit Shield", "type": "unique low"},
	"7 Bronze Gauntlets": {"base": "Bronze Gauntlets", "type": "unique low"},
	"7 Carnal Mitts": {"base": "Carnal Mitts", "type": "unique low"},
	"7 Chain Gloves": {"base": "Chain Gloves", "type": "unique low"},
	"7 Cleaver": {"base": "Cleaver", "type": "unique low"},
	"7 Compound Spiked Shield": {"base": "Compound Spiked Shield", "type": "unique low"},
	"7 Conquest Chainmail": {"base": "Conquest Chainmail", "type": "unique low"},
	"7 Death Bow": {"base": "Death Bow", "type": "unique low"},
	"7 Decimation Bow": {"base": "Decimation Bow", "type": "unique low"},
	"7 Demon's Horn": {"base": "Demon's Horn", "type": "unique low"},
	"7 Dragonscale Boots": {"base": "Dragonscale Boots", "type": "unique low"},
	"7 Dread Maul": {"base": "Dread Maul", "type": "unique low"},
	"7 Enameled Buckler": {"base": "Enameled Buckler", "type": "unique low"},
	"7 Gnarled Branch": {"base": "Gnarled Branch", "type": "unique low"},
	"7 Goat's Horn": {"base": "Goat's Horn", "type": "unique low"},
	"7 Golden Mask": {"base": "Golden Mask", "type": "unique low"},
	"7 Great Crown": {"base": "Great Crown", "type": "unique low"},
	"7 Great Helmet": {"base": "Great Helmet", "type": "unique low"},
	"7 Greater Mana Flask": {"base": "Greater Mana Flask", "type": "unique low"},
	"7 Harbinger Bow": {"base": "Harbinger Bow", "type": "unique low"},
	"7 Holy Chainmail": {"base": "Holy Chainmail", "type": "unique low"},
	"7 Imbued Wand": {"base": "Imbued Wand", "type": "unique low"},
	"7 Iron Hat": {"base": "Iron Hat", "type": "unique low"},
	"7 Iron Mask": {"base": "Iron Mask", "type": "unique low"},
	"7 Iron Staff": {"base": "Iron Staff", "type": "unique low"},
	"7 Ivory Spirit Shield": {"base": "Ivory Spirit Shield", "type": "unique low"},
	"7 Latticed Ringmail": {"base": "Latticed Ringmail", "type": "unique low"},
	"7 Leather Hood": {"base": "Leather Hood", "type": "unique low"},
	"7 Legion Boots": {"base": "Legion Boots", "type": "unique low"},
	"7 Long Staff": {"base": "Long Staff", "type": "unique low"},
	"7 Military Staff": {"base": "Military Staff", "type": "unique low"},
	"7 Mind Cage": {"base": "Mind Cage", "type": "unique low"},
	"7 Nailed Fist": {"base": "Nailed Fist", "type": "unique low"},
	"7 Necromancer Circlet": {"base": "Necromancer Circlet", "type": "unique low"},
	"7 Ornate Ringmail": {"base": "Ornate Ringmail", "type": "unique low"},
	"7 Ornate Sword": {"base": "Ornate Sword", "type": "unique low"},
	"7 Plague Mask": {"base": "Plague Mask", "type": "unique low"},
	"7 Platinum Kris": {"base": "Platinum Kris", "type": "unique low"},
	"7 Praetor Crown": {"base": "Praetor Crown", "type": "unique low"},
	"7 Prophet Crown": {"base": "Prophet Crown", "type": "unique low"},
	"7 Quartz Wand": {"base": "Quartz Wand", "type": "unique low"},
	"7 Recurve Bow": {"base": "Recurve Bow", "type": "unique low"},
	"7 Riveted Boots": {"base": "Riveted Boots", "type": "unique low"},
	"7 Rotted Round Shield": {"base": "Rotted Round Shield", "type": "unique low"},
	"7 Scholar Boots": {"base": "Scholar Boots", "type": "unique low"},
	"7 Scholar's Robe": {"base": "Scholar's Robe", "type": "unique low"},
	"7 Serrated Arrow Quiver": {"base": "Serrated Arrow Quiver", "type": "unique low"},
	"7 Shagreen Boots": {"base": "Shagreen Boots", "type": "unique low"},
	"7 Skinning Knife": {"base": "Skinning Knife", "type": "unique low"},
	"7 Sledgehammer": {"base": "Sledgehammer", "type": "unique low"},
	"7 Stiletto": {"base": "Stiletto", "type": "unique low"},
	"7 Studded Round Shield": {"base": "Studded Round Shield", "type": "unique low"},
	"7 Supreme Spiked Shield": {"base": "Supreme Spiked Shield", "type": "unique low"},
	"7 Timeworn Claw": {"base": "Timeworn Claw", "type": "unique low"},
	"7 Tricorne": {"base": "Tricorne", "type": "unique low"},
	"7 Turquoise Amulet": {"base": "Turquoise Amulet", "type": "unique low"},
	"7 Vaal Buckler": {"base": "Vaal Buckler", "type": "unique low"},
	"7 Velvet Slippers": {"base": "Velvet Slippers", "type": "unique low"},
	"7 War Buckler": {"base": "War Buckler", "type": "unique low"},
	"7 Zealot Helmet": {"base": "Zealot Helmet", "type": "unique low"},
	"9 Other uniques": {"type": "unique normal"}
}
