#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 06/28/2020(m/d/y) 00:57:02 UTC from "tmpstandard" data

desc = "Helm Enchant Autogen"

# Base type : settings pair
items = {
	"1 +1 to maximum number of Sentinels of Purity": {"enchant": "Enchantment Herald Of Purity Additional Minion 1", "type": "base very high"},
	"1 12% increased Freezing Pulse Cast Speed": {"enchant": "Enchantment Freezing Pulse Cast Speed 2", "type": "base very high"},
	"1 15% increased Cyclone Attack Speed": {"enchant": "Enchantment Cyclone Attack Speed 2", "type": "base very high"},
	"1 150% increased Effect of the Buff granted by your Stone Golems": {"enchant": "Enchantment Stone Golem Granted Buff Effect 2", "type": "base very high"},
	"1 24% increased Ball Lightning Area of Effect": {"enchant": "Enchantment Ball Lightning Area Of Effect 2", "type": "base very high"},
	"1 24% increased Blade Vortex Area of Effect": {"enchant": "Enchantment Blade Vortex Area Of Effect 2", "type": "base very high"},
	"1 25% increased Ball Lightning Damage": {"enchant": "Enchantment Ball Lightning Damage 1", "type": "base very high"},
	"1 30% increased Blade Vortex Duration": {"enchant": "Enchantment Blade Vortex Duration 2", "type": "base very high"},
	"1 30% increased Freezing Pulse Projectile Speed": {"enchant": "Enchantment Freezing Pulse Projectile Speed 2", "type": "base very high"},
	"1 30% increased Temporal Chains Curse Effect": {"enchant": "Enchantment Temporal Chains Curse Effect 2", "type": "base very high"},
	"1 40% increased Ball Lightning Damage": {"enchant": "Enchantment Ball Lightning Damage 2", "type": "base very high"},
	"1 40% increased Blade Vortex Spell Damage": {"enchant": "Enchantment Blade Vortex Damage 2", "type": "base very high"},
	"1 40% increased Caustic Arrow Damage": {"enchant": "Enchantment Caustic Arrow Damage 2", "type": "base very high"},
	"1 40% increased Cyclone Damage": {"enchant": "Enchantment Cyclone Damage 2", "type": "base very high"},
	"1 40% increased Essence Drain Damage": {"enchant": "Enchantment Essence Drain Damage 2", "type": "base very high"},
	"1 40% increased Fireball Damage": {"enchant": "Enchantment Fireball Damage 2", "type": "base very high"},
	"1 40% increased Freezing Pulse Damage": {"enchant": "Enchantment Freezing Pulse Damage 2", "type": "base very high"},
	"1 40% increased Ice Crash Damage": {"enchant": "Enchantment Ice Crash Damage 2", "type": "base very high"},
	"1 40% increased Ice Nova Damage": {"enchant": "Enchantment Ice Nova Damage 2", "type": "base extremely high"},
	"1 40% increased Ice Shot Damage": {"enchant": "Enchantment Ice Shot Damage 2", "type": "base very high"},
	"1 40% increased Lacerate Damage": {"enchant": "Enchantment Lacerate Damage 2", "type": "base very high"},
	"1 40% increased Puncture Damage": {"enchant": "Enchantment Puncture Damage 2", "type": "base very high"},
	"1 40% increased Volatile Dead Damage": {"enchant": "Enchantment Volatile Dead Damage 2", "type": "base very high"},
	"1 Arc Chains an additional time": {"enchant": "Enchantment Arc Num Of Additional Projectiles In Chain 1", "type": "base very high"},
	"1 Ball Lightning fires an additional Projectile": {"enchant": "Enchantment Ball Lightning Additional Projectiles 1", "type": "base extremely high"},
	"1 Blade Blast has 24% increased Area of Effect": {"enchant": "Enchantment Blade Blast Area of Effect 2", "type": "base very high"},
	"1 Bladefall has an additional Volley": {"enchant": "Enchantment Bladefall Additional Volley", "type": "base very high"},
	"1 Cobra Lash Chains 3 additional times": {"enchant": "Enchantment Cobra Lash Number Of Additional Chains 2", "type": "base very high"},
	"1 Consecrated Ground from Purifying Flame applies 9% increased Damage taken to Enemies": {"enchant": "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2", "type": "base very high"},
	"1 Cremation can have up to 1 additional Geyser at a time": {"enchant": "Enchantment Cremation Maximum Geysers 1", "type": "base very high"},
	"1 Dash travels 100% increased distance": {"enchant": "Enchantment Dash Travel Distance 2", "type": "base very high"},
	"1 Explosive Trap causes 2 additional smaller explosions": {"enchant": "Enchantment Shrapnel Trap Secondary Explosions 2", "type": "base very high"},
	"1 Flesh Offering grants an additional 21% increased Attack Speed": {"enchant": "Enchantment Flesh Offering Attack Speed 2", "type": "base very high"},
	"1 Flesh and Stone has 30% reduced Mana Reservation": {"enchant": "Enchantment Flesh and Stone Mana Reservation 2", "type": "base very high"},
	"1 Kinetic Blast has a 75% chance for an additional explosion": {"enchant": "Enchantment Kinetic Blast Explosions 2", "type": "base very high"},
	"1 Lacerate deals 14 to 25 added Physical Damage against Bleeding Enemies": {"enchant": "Enchantment Double Slash Added Phys To Bleeding 2", "type": "base very high"},
	"1 Malevolence has 15% reduced Mana Reservation": {"enchant": "Enchantment Malevolence Mana Reservation 2", "type": "base very high"},
	"1 Perforate creates +2 Spikes": {"enchant": "Enchantment Perforate Number Of Spikes 2", "type": "base very high"},
	"1 Power Siphon fires 2 additional Projectiles": {"enchant": "Enchantment Power Siphon Additional Projectiles 2", "type": "base very high"},
	"1 Pride has 15% reduced Mana Reservation": {"enchant": "Enchantment Pride Mana Reservation 2", "type": "base very high"},
	"1 Pyroclast Mine fires 2 additional Projectiles": {"enchant": "Enchantment Pyroclast Mine Additional Projectiles 2", "type": "base very high"},
	"1 Scourge Arrow creates an additional spore pod at Maximum Stages": {"enchant": "Enchantment Scourge Arrow Additional Spore 1", "type": "base very high"},
	"1 Skills Supported by Spellslinger have 10% reduced Mana Reservation": {"enchant": "Enchantment Spellslinger Reservation 1", "type": "base very high"},
	"1 Skills Supported by Spellslinger have 15% reduced Mana Reservation": {"enchant": "Enchantment Spellslinger Reservation 2", "type": "base extremely high"},
	"1 Skills Supported by Spellslinger have 20% increased Cooldown Recovery Speed": {"enchant": "Enchantment Spellslinger Cooldown Recovery 1", "type": "base extremely high"},
	"1 Skills Supported by Spellslinger have 30% increased Cooldown Recovery Speed": {"enchant": "Enchantment Spellslinger Cooldown Recovery 2", "type": "base extremely high"},
	"1 Spectres have 40% increased Damage": {"enchant": "Enchantment Raise Spectre Damage 2", "type": "base very high"},
	"1 Split Arrow fires 3 additional Projectiles": {"enchant": "Enchantment Split Arrow Num Of Additional Projectiles 2", "type": "base very high"},
	"1 Stone Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Stone Golem Damage 2", "type": "base very high"},
	"1 Storm Brand Damage Penetrates 12% of Branded Enemy's Lightning Resistance": {"enchant": "Storm Brand Attached Target Lightning Penetration 2", "type": "base very high"},
	"1 Storm Burst has a 15% chance to create an additional Orb": {"enchant": "Enchantment Storm Burst Additional Object Chance 2", "type": "base very high"},
	"1 Summoned Agony Crawler fires 2 additional Projectiles": {"enchant": "Enchantment Herald Of Agony Num Of Secondary Projectiles 1", "type": "base very high"},
	"1 Summoned Carrion Golems deal 40% increased Damage": {"enchant": "Enchantment Summon Carrion Golem Damage 2", "type": "base very high"},
	"1 Toxic Rain deals 40% increased Damage": {"enchant": "Enchantment Toxic Rain Damage 2", "type": "base very high"},
	"1 Toxic Rain fires 1 additional Arrow": {"enchant": "Enchantment Toxic Rain Num Of Additional Projectiles 1", "type": "base very high"},
	"1 0 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 1", "type": "base extremely high"},
	"1 1 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 2", "type": "base extremely high"},
	"1 2 Volatile Dead Consumes up to 1 additional corpse": {"enchant": "Enchantment Volatile Dead Orbs 3", "type": "base extremely high"},
	"1 Wild Strike's Beam Chains an additional 6 times": {"enchant": "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2", "type": "base very high"},
	"1 Wrath has 15% reduced Mana Reservation": {"enchant": "Enchantment Wrath Mana Reservation 2", "type": "base very high"},
	"7 enchant default": {"class": "Helmet", "other": ["AnyEnchantment True"], "type": "item mod"}
}
