#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 03/31/2019(m/d/y) 00:06:14 UTC from "Synthesis" data

desc = "Prophecy Autogen"

# Base type : settings pair
items = {
	"000 Thaumaturgical History III": {"prophecy": "Thaumaturgical History III", "class": "Currency", "type": "currency low"},
	"001 Thaumaturgical History II": {"prophecy": "Thaumaturgical History II", "class": "Currency", "type": "currency low"},
	"002 The Unbreathing Queen III": {"prophecy": "The Unbreathing Queen III", "class": "Currency", "type": "currency low"},
	"003 Thaumaturgical History IV": {"prophecy": "Thaumaturgical History IV", "class": "Currency", "type": "currency low"},
	"004 The Ambitious Bandit III": {"prophecy": "The Ambitious Bandit III", "class": "Currency", "type": "currency high"},
	"005 The Unbreathing Queen IV": {"prophecy": "The Unbreathing Queen IV", "class": "Currency", "type": "currency high"},
	"006 The Unbreathing Queen II": {"prophecy": "The Unbreathing Queen II", "class": "Currency", "type": "currency low"},
	"007 The Ambitious Bandit II": {"prophecy": "The Ambitious Bandit II", "class": "Currency", "type": "currency low"},
	"008 Unbearable Whispers III": {"prophecy": "Unbearable Whispers III", "class": "Currency", "type": "currency low"},
	"009 Unbearable Whispers II": {"prophecy": "Unbearable Whispers II", "class": "Currency", "type": "currency low"},
	"010 Unbearable Whispers IV": {"prophecy": "Unbearable Whispers IV", "class": "Currency", "type": "currency low"},
	"011 Ancient Rivalries III": {"prophecy": "Ancient Rivalries III", "class": "Currency", "type": "currency very high"},
	"012 Ancient Rivalries II": {"prophecy": "Ancient Rivalries II", "class": "Currency", "type": "currency very high"},
	"013 Ancient Rivalries IV": {"prophecy": "Ancient Rivalries IV", "class": "Currency", "type": "currency very high"},
	"014 Day of Sacrifice III": {"prophecy": "Day of Sacrifice III", "class": "Currency", "type": "currency low"},
	"015 Day of Sacrifice IV": {"prophecy": "Day of Sacrifice IV", "class": "Currency", "type": "currency low"},
	"016 Day of Sacrifice II": {"prophecy": "Day of Sacrifice II", "class": "Currency", "type": "currency low"},
	"017 Deadly Rivalry III": {"prophecy": "Deadly Rivalry III", "class": "Currency", "type": "currency low"},
	"018 The Feral Lord III": {"prophecy": "The Feral Lord III", "class": "Currency", "type": "currency low"},
	"019 The Warmongers III": {"prophecy": "The Warmongers III", "class": "Currency", "type": "currency low"},
	"020 Anarchy's End III": {"prophecy": "Anarchy's End III", "class": "Currency", "type": "currency low"},
	"021 Deadly Rivalry IV": {"prophecy": "Deadly Rivalry IV", "class": "Currency", "type": "currency low"},
	"022 The Warmongers IV": {"prophecy": "The Warmongers IV", "class": "Currency", "type": "currency low"},
	"023 The Feral Lord IV": {"prophecy": "The Feral Lord IV", "class": "Currency", "type": "currency high"},
	"024 Deadly Rivalry II": {"prophecy": "Deadly Rivalry II", "class": "Currency", "type": "currency low"},
	"025 The Warmongers II": {"prophecy": "The Warmongers II", "class": "Currency", "type": "currency low"},
	"026 The Plaguemaw III": {"prophecy": "The Plaguemaw III", "class": "Currency", "type": "currency low"},
	"027 The Feral Lord II": {"prophecy": "The Feral Lord II", "class": "Currency", "type": "currency low"},
	"028 The Plaguemaw IV": {"prophecy": "The Plaguemaw IV", "class": "Currency", "type": "currency high"},
	"029 The Plaguemaw II": {"prophecy": "The Plaguemaw II", "class": "Currency", "type": "currency low"},
	"030 Anarchy's End II": {"prophecy": "Anarchy's End II", "class": "Currency", "type": "currency low"},
	"031 Beyond Sight III": {"prophecy": "Beyond Sight III", "class": "Currency", "type": "currency low"},
	"032 Anarchy's End IV": {"prophecy": "Anarchy's End IV", "class": "Currency", "type": "currency low"},
	"033 Beyond Sight IV": {"prophecy": "Beyond Sight IV", "class": "Currency", "type": "currency low"},
	"034 Beyond Sight II": {"prophecy": "Beyond Sight II", "class": "Currency", "type": "currency low"},
	"1 A Dishonourable Death": {"prophecy": "A Dishonourable Death", "class": "Currency", "type": "currency high"},
	"1 A Master Seeks Help": {"prophecy": "A Master Seeks Help", "class": "Currency", "type": "currency high"},
	"1 A Vision of Ice and Fire": {"prophecy": "A Vision of Ice and Fire", "class": "Currency", "type": "currency high"},
	"1 Agony at Dusk": {"prophecy": "Agony at Dusk", "class": "Currency", "type": "currency very low"},
	"1 Battle Hardened": {"prophecy": "Battle Hardened", "class": "Currency", "type": "currency very low"},
	"1 Black Devotion": {"prophecy": "Black Devotion", "class": "Currency", "type": "currency very low"},
	"1 Blinding Light": {"prophecy": "Blinding Light", "class": "Currency", "type": "currency very low"},
	"1 Bountiful Traps": {"prophecy": "Bountiful Traps", "class": "Currency", "type": "currency high"},
	"1 Burning Dread": {"prophecy": "Burning Dread", "class": "Currency", "type": "currency very low"},
	"1 Cleanser of Sins": {"prophecy": "Cleanser of Sins", "class": "Currency", "type": "currency high"},
	"1 Cold Blooded Fury": {"prophecy": "Cold Blooded Fury", "class": "Currency", "type": "currency very low"},
	"1 Crimson Hues": {"prophecy": "Crimson Hues", "class": "Currency", "type": "currency very low"},
	"1 Crushing Squall": {"prophecy": "Crushing Squall", "class": "Currency", "type": "currency high"},
	"1 Darktongue's Shriek": {"prophecy": "Darktongue's Shriek", "class": "Currency", "type": "currency high"},
	"1 End of the Light": {"prophecy": "End of the Light", "class": "Currency", "type": "currency very low"},
	"1 Faith Exhumed": {"prophecy": "Faith Exhumed", "class": "Currency", "type": "currency very low"},
	"1 Fallow At Last": {"prophecy": "Fallow At Last", "class": "Currency", "type": "currency high"},
	"1 Fated Connections": {"prophecy": "Fated Connections", "class": "Currency", "type": "currency extremely high"},
	"1 Fire from the Sky": {"prophecy": "Fire from the Sky", "class": "Currency", "type": "currency high"},
	"1 Fire, Wood and Stone": {"prophecy": "Fire, Wood and Stone", "class": "Currency", "type": "currency very low"},
	"1 Flesh of the Beast": {"prophecy": "Flesh of the Beast", "class": "Currency", "type": "currency high"},
	"1 From The Void": {"prophecy": "From The Void", "class": "Currency", "type": "currency very low"},
	"1 Gilded Within": {"prophecy": "Gilded Within", "class": "Currency", "type": "currency very low"},
	"1 Heavy Blows": {"prophecy": "Heavy Blows", "class": "Currency", "type": "currency very low"},
	"1 Hunter's Lesson": {"prophecy": "Hunter's Lesson", "class": "Currency", "type": "currency very low"},
	"1 Ice from Above": {"prophecy": "Ice from Above", "class": "Currency", "type": "currency high"},
	"1 Kalandra's Craft": {"prophecy": "Kalandra's Craft", "class": "Currency", "type": "currency high"},
	"1 Lightning Falls": {"prophecy": "Lightning Falls", "class": "Currency", "type": "currency high"},
	"1 Lost in the Pages": {"prophecy": "Lost in the Pages", "class": "Currency", "type": "currency high"},
	"1 Monstrous Treasure": {"prophecy": "Monstrous Treasure", "class": "Currency", "type": "currency very high"},
	"1 Mouth of Horrors": {"prophecy": "Mouth of Horrors", "class": "Currency", "type": "currency very low"},
	"1 Plague of Frogs": {"prophecy": "Plague of Frogs", "class": "Currency", "type": "currency high"},
	"1 Plague of Rats": {"prophecy": "Plague of Rats", "class": "Currency", "type": "currency high"},
	"1 Pools of Wealth": {"prophecy": "Pools of Wealth", "class": "Currency", "type": "currency high"},
	"1 Power Magnified": {"prophecy": "Power Magnified", "class": "Currency", "type": "currency very low"},
	"1 Sun's Punishment": {"prophecy": "Sun's Punishment", "class": "Currency", "type": "currency very low"},
	"1 The Beautiful Guide": {"prophecy": "The Beautiful Guide", "class": "Currency", "type": "currency high"},
	"1 The Bloody Flowers Redux": {"prophecy": "The Bloody Flowers Redux", "class": "Currency", "type": "currency very low"},
	"1 The Bowstring's Music": {"prophecy": "The Bowstring's Music", "class": "Currency", "type": "currency high"},
	"1 The Brothers of Necromancy": {"prophecy": "The Brothers of Necromancy", "class": "Currency", "type": "currency very low"},
	"1 The Corrupt": {"prophecy": "The Corrupt", "class": "Currency", "type": "currency very low"},
	"1 The Dreamer's Dream": {"prophecy": "The Dreamer's Dream", "class": "Currency", "type": "currency high"},
	"1 The Feral Lord V": {"prophecy": "The Feral Lord V", "class": "Currency", "type": "currency high"},
	"1 The Jeweller's Touch": {"prophecy": "The Jeweller's Touch", "class": "Currency", "type": "currency high"},
	"1 The King's Path": {"prophecy": "The King's Path", "class": "Currency", "type": "currency very high"},
	"1 The Lost Undying": {"prophecy": "The Lost Undying", "class": "Currency", "type": "currency high"},
	"1 The Malevolent Witch": {"prophecy": "The Malevolent Witch", "class": "Currency", "type": "currency very low"},
	"1 The Plaguemaw I": {"prophecy": "The Plaguemaw I", "class": "Currency", "type": "currency very low"},
	"1 The Plaguemaw V": {"prophecy": "The Plaguemaw V", "class": "Currency", "type": "currency high"},
	"1 The Prison Key": {"prophecy": "The Prison Key", "class": "Currency", "type": "currency very low"},
	"1 The Queen's Sacrifice": {"prophecy": "The Queen's Sacrifice", "class": "Currency", "type": "currency extremely high"},
	"1 The Queen's Vaults": {"prophecy": "The Queen's Vaults", "class": "Currency", "type": "currency high"},
	"1 The Scout": {"prophecy": "The Scout", "class": "Currency", "type": "currency very low"},
	"1 The Servant's Heart": {"prophecy": "The Servant's Heart", "class": "Currency", "type": "currency high"},
	"1 The Singular Spirit": {"prophecy": "The Singular Spirit", "class": "Currency", "type": "currency very low"},
	"1 The Snuffed Flame": {"prophecy": "The Snuffed Flame", "class": "Currency", "type": "currency very low"},
	"1 The Stockkeeper": {"prophecy": "The Stockkeeper", "class": "Currency", "type": "currency very low"},
	"1 The Unbreathing Queen V": {"prophecy": "The Unbreathing Queen V", "class": "Currency", "type": "currency high"},
	"1 The Undead Storm": {"prophecy": "The Undead Storm", "class": "Currency", "type": "currency high"},
	"1 Trapped in the Tower": {"prophecy": "Trapped in the Tower", "class": "Currency", "type": "currency very low"},
	"1 Trash to Treasure": {"prophecy": "Trash to Treasure", "class": "Currency", "type": "currency extremely high"},
	"1 Twice Enchanted": {"prophecy": "Twice Enchanted", "class": "Currency", "type": "currency high"},
	"1 Unbearable Whispers V": {"prophecy": "Unbearable Whispers V", "class": "Currency", "type": "currency high"},
	"1 Vaal Winds": {"prophecy": "Vaal Winds", "class": "Currency", "type": "currency high"},
	"1 Wind and Thunder": {"prophecy": "Wind and Thunder", "class": "Currency", "type": "currency very high"},
	"1 Winter's Mournful Melodies": {"prophecy": "Winter's Mournful Melodies", "class": "Currency", "type": "currency very low"},
	"7 Prophecy default": {"Prophecy": "", "class": "Currency", "type": "currency low"}
}
