#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 07/07/2019(m/d/y) 21:23:01 UTC from "tmpstandard" data

desc = "Unique"

# Base type : settings pair
items = {
	"000 Reinforced Tower Shield": {"other": ["ItemLevel <= 60"], "base": "Reinforced Tower Shield", "type": "unique high"},
	"001 Blunt Arrow Quiver Piece": {"base": "Blunt Arrow Quiver Piece", "type": "unique high"},
	"002 Archon Kite Shield Piece": {"base": "Archon Kite Shield Piece", "type": "unique high"},
	"003 Cloth Belt Piece": {"base": "Cloth Belt Piece", "type": "unique very high"},
	"004 Sinner Tricorne": {"base": "Sinner Tricorne", "type": "unique normal"},
	"005 Moon Temple Map": {"base": "Moon Temple Map", "type": "unique very high"},
	"1 Amber Amulet": {"base": "Amber Amulet", "type": "unique special"},
	"1 Assassin's Boots": {"base": "Assassin's Boots", "type": "unique high"},
	"1 Assassin's Mitts": {"base": "Assassin's Mitts", "type": "unique low"},
	"1 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique high"},
	"1 Blood Raiment": {"base": "Blood Raiment", "type": "unique special"},
	"1 Blood Sceptre": {"base": "Blood Sceptre", "type": "unique high"},
	"1 Blue Pearl Amulet": {"base": "Blue Pearl Amulet", "type": "unique high"},
	"1 Boot Knife": {"base": "Boot Knife", "type": "unique low"},
	"1 Bronze Gauntlets": {"base": "Bronze Gauntlets", "type": "unique low"},
	"1 Buckskin Tunic": {"base": "Buckskin Tunic", "type": "unique low"},
	"1 Callous Mask Piece": {"base": "Callous Mask Piece", "type": "unique very high"},
	"1 Cardinal Round Shield": {"base": "Cardinal Round Shield", "type": "unique high"},
	"1 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique high"},
	"1 Cemetery Map": {"base": "Cemetery Map", "type": "unique high"},
	"1 Chateau Map": {"base": "Chateau Map", "type": "unique very high"},
	"1 Chiming Spirit Shield": {"base": "Chiming Spirit Shield", "type": "unique low"},
	"1 Cleaver": {"base": "Cleaver", "type": "unique low"},
	"1 Coral Amulet": {"base": "Coral Amulet", "type": "unique low"},
	"1 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique special"},
	"1 Crusader Boots": {"base": "Crusader Boots", "type": "unique extremely high"},
	"1 Cursed Crypt Map": {"base": "Cursed Crypt Map", "type": "unique high"},
	"1 Cutlass": {"base": "Cutlass", "type": "unique high"},
	"1 Death Bow": {"base": "Death Bow", "type": "unique low"},
	"1 Deerskin Gloves": {"base": "Deerskin Gloves", "type": "unique high"},
	"1 Destiny Leather": {"base": "Destiny Leather", "type": "unique high"},
	"1 Dream Mace": {"base": "Dream Mace", "type": "unique low"},
	"1 Elegant Foil": {"base": "Elegant Foil", "type": "unique high"},
	"1 Ezomyte Tower Shield": {"base": "Ezomyte Tower Shield", "type": "unique very high"},
	"1 Full Dragonscale": {"base": "Full Dragonscale", "type": "unique high"},
	"1 Gavel": {"base": "Gavel", "type": "unique low"},
	"1 Gilded Sallet": {"base": "Gilded Sallet", "type": "unique low"},
	"1 Glorious Plate": {"base": "Glorious Plate", "type": "unique extremely high"},
	"1 Gnarled Branch": {"base": "Gnarled Branch", "type": "unique low"},
	"1 Goat's Horn": {"base": "Goat's Horn", "type": "unique low"},
	"1 Gold Amulet": {"base": "Gold Amulet", "type": "unique special"},
	"1 Gold Ring": {"base": "Gold Ring", "type": "unique special"},
	"1 Golden Mantle": {"base": "Golden Mantle", "type": "unique extremely high"},
	"1 Golden Mask": {"base": "Golden Mask", "type": "unique low"},
	"1 Golden Plate": {"base": "Golden Plate", "type": "unique special"},
	"1 Golden Visage": {"base": "Golden Visage", "type": "unique extremely high"},
	"1 Great Helmet": {"base": "Great Helmet", "type": "unique low"},
	"1 Greater Mana Flask": {"base": "Greater Mana Flask", "type": "unique low"},
	"1 Greatwolf Talisman": {"base": "Greatwolf Talisman", "type": "unique very high"},
	"1 Harbinger Map": {"base": "Harbinger Map", "type": "unique very high"},
	"1 Heavy Belt": {"base": "Heavy Belt", "type": "unique special"},
	"1 Hydrascale Gauntlets": {"base": "Hydrascale Gauntlets", "type": "unique high"},
	"1 Imperial Bow": {"base": "Imperial Bow", "type": "unique special"},
	"1 Imperial Maul": {"base": "Imperial Maul", "type": "unique high"},
	"1 Imperial Staff": {"base": "Imperial Staff", "type": "unique high"},
	"1 Infernal Axe": {"base": "Infernal Axe", "type": "unique low"},
	"1 Infernal Sword": {"base": "Infernal Sword", "type": "unique special"},
	"1 Iron Hat": {"base": "Iron Hat", "type": "unique low"},
	"1 Iron Staff": {"base": "Iron Staff", "type": "unique low"},
	"1 Ironscale Boots": {"base": "Ironscale Boots", "type": "unique low"},
	"1 Ivory Spirit Shield": {"base": "Ivory Spirit Shield", "type": "unique low"},
	"1 Jade Amulet": {"base": "Jade Amulet", "type": "unique special"},
	"1 Jewelled Foil": {"base": "Jewelled Foil", "type": "unique very high"},
	"1 Jingling Spirit Shield": {"base": "Jingling Spirit Shield", "type": "unique very high"},
	"1 Latticed Ringmail": {"base": "Latticed Ringmail", "type": "unique low"},
	"1 Leather Belt": {"base": "Leather Belt", "type": "unique special"},
	"1 Legion Gloves": {"base": "Legion Gloves", "type": "unique very high"},
	"1 Magistrate Crown": {"base": "Magistrate Crown", "type": "unique special"},
	"1 Maze Map": {"base": "Maze Map", "type": "unique extremely high"},
	"1 Midnight Blade": {"base": "Midnight Blade", "type": "unique special"},
	"1 Museum Map": {"base": "Museum Map", "type": "unique very high"},
	"1 Nailed Fist": {"base": "Nailed Fist", "type": "unique low"},
	"1 Necromancer Circlet": {"base": "Necromancer Circlet", "type": "unique special"},
	"1 Nightmare Bascinet": {"base": "Nightmare Bascinet", "type": "unique special"},
	"1 Nubuck Boots": {"base": "Nubuck Boots", "type": "unique extremely high"},
	"1 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique high"},
	"1 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique special"},
	"1 Ornate Quiver": {"base": "Ornate Quiver", "type": "unique extremely high"},
	"1 Ornate Sword": {"base": "Ornate Sword", "type": "unique low"},
	"1 Painted Buckler": {"base": "Painted Buckler", "type": "unique low"},
	"1 Paua Amulet": {"base": "Paua Amulet", "type": "unique low"},
	"1 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique special"},
	"1 Pine Buckler": {"base": "Pine Buckler", "type": "unique low"},
	"1 Plague Mask": {"base": "Plague Mask", "type": "unique low"},
	"1 Plank Kite Shield": {"base": "Plank Kite Shield", "type": "unique low"},
	"1 Plate Vest": {"base": "Plate Vest", "type": "unique low"},
	"1 Platinum Kris": {"base": "Platinum Kris", "type": "unique low"},
	"1 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"1 Promenade Map": {"base": "Promenade Map", "type": "unique high"},
	"1 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique very high"},
	"1 Quartz Wand": {"base": "Quartz Wand", "type": "unique low"},
	"1 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique extremely high"},
	"1 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique high"},
	"1 Recurve Bow": {"base": "Recurve Bow", "type": "unique low"},
	"1 Reef Map": {"base": "Reef Map", "type": "unique high"},
	"1 Riveted Gloves": {"base": "Riveted Gloves", "type": "unique very high"},
	"1 Royal Axe": {"base": "Royal Axe", "type": "unique very high"},
	"1 Royal Staff": {"base": "Royal Staff", "type": "unique low"},
	"1 Ruby Flask": {"base": "Ruby Flask", "type": "unique special"},
	"1 Ruby Ring": {"base": "Ruby Ring", "type": "unique special"},
	"1 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique high"},
	"1 Sage's Robe": {"base": "Sage's Robe", "type": "unique low"},
	"1 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique high"},
	"1 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"1 Sapphire Ring": {"base": "Sapphire Ring", "type": "unique special"},
	"1 Savant's Robe": {"base": "Savant's Robe", "type": "unique high"},
	"1 Scholar Boots": {"base": "Scholar Boots", "type": "unique low"},
	"1 Scholar's Robe": {"base": "Scholar's Robe", "type": "unique low"},
	"1 Sentinel Jacket": {"base": "Sentinel Jacket", "type": "unique low"},
	"1 Shadow Sceptre": {"base": "Shadow Sceptre", "type": "unique low"},
	"1 Siege Axe": {"base": "Siege Axe", "type": "unique high"},
	"1 Silk Gloves": {"base": "Silk Gloves", "type": "unique high"},
	"1 Silver Flask": {"base": "Silver Flask", "type": "unique special"},
	"1 Simple Robe": {"base": "Simple Robe", "type": "unique low"},
	"1 Skinning Knife": {"base": "Skinning Knife", "type": "unique low"},
	"1 Sledgehammer": {"base": "Sledgehammer", "type": "unique low"},
	"1 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique special"},
	"1 Spiked Club": {"base": "Spiked Club", "type": "unique low"},
	"1 Spiraled Wand": {"base": "Spiraled Wand", "type": "unique low"},
	"1 Steel Ring": {"base": "Steel Ring", "type": "unique high"},
	"1 Steelwood Bow": {"base": "Steelwood Bow", "type": "unique high"},
	"1 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique special"},
	"1 Stiletto": {"base": "Stiletto", "type": "unique low"},
	"1 Strapped Boots": {"base": "Strapped Boots", "type": "unique low"},
	"1 Strapped Leather": {"base": "Strapped Leather", "type": "unique low"},
	"1 Studded Belt": {"base": "Studded Belt", "type": "unique special"},
	"1 Studded Round Shield": {"base": "Studded Round Shield", "type": "unique low"},
	"1 Temple Map": {"base": "Temple Map", "type": "unique high"},
	"1 Thorium Spirit Shield": {"base": "Thorium Spirit Shield", "type": "unique high"},
	"1 Timeless Jewel": {"base": "Timeless Jewel", "type": "unique special"},
	"1 Titan Gauntlets": {"base": "Titan Gauntlets", "type": "unique low"},
	"1 Tomahawk": {"base": "Tomahawk", "type": "unique low"},
	"1 Topaz Ring": {"base": "Topaz Ring", "type": "unique special"},
	"1 Triumphant Lamellar": {"base": "Triumphant Lamellar", "type": "unique special"},
	"1 Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "type": "unique special"},
	"1 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique special"},
	"1 Unset Ring": {"base": "Unset Ring", "type": "unique special"},
	"1 Vaal Axe": {"base": "Vaal Axe", "type": "unique special"},
	"1 Vaal Blade": {"base": "Vaal Blade", "type": "unique high"},
	"1 Vaal Buckler": {"base": "Vaal Buckler", "type": "unique low"},
	"1 Vaal Gauntlets": {"base": "Vaal Gauntlets", "type": "unique special"},
	"1 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique high"},
	"1 Vaal Rapier": {"base": "Vaal Rapier", "type": "unique very high"},
	"1 Varnished Coat": {"base": "Varnished Coat", "type": "unique high"},
	"1 Vile Staff": {"base": "Vile Staff", "type": "unique low"},
	"1 Vine Circlet": {"base": "Vine Circlet", "type": "unique low"},
	"1 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique special"},
	"1 Void Axe": {"base": "Void Axe", "type": "unique high"},
	"1 War Buckler": {"base": "War Buckler", "type": "unique low"},
	"1 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique high"},
	"1 Wild Leather": {"base": "Wild Leather", "type": "unique low"},
	"1 Wyrmscale Doublet": {"base": "Wyrmscale Doublet", "type": "unique very high"},
	"1 Zodiac Leather": {"base": "Zodiac Leather", "type": "unique very high"},
	"9 Other uniques": {"type": "unique normal"}
}
