#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 09/04/2016(m/d/y) 12:28:55 UTC from "Standard" data
"""
* Copyright (c) 2016 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Purpose: Create an item filter based on config files
Note: Requires Python 3.4.x
"""

desc = "Unique"

# Base type : settings pair
items = {
	"0 Ancient Greaves": {"base": "Ancient Greaves", "type": "unique very high"},
	"0 Assassin Bow": {"base": "Assassin Bow", "type": "unique very high"},
	"0 Assassin's Garb": {"base": "Assassin's Garb", "type": "unique very high"},
	"0 Astral Plate": {"base": "Astral Plate", "type": "unique very high"},
	"0 Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "type": "unique very high"},
	"0 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique very high"},
	"0 Cedar Tower Shield": {"base": "Cedar Tower Shield", "type": "unique very high"},
	"0 Champion Kite Shield": {"base": "Champion Kite Shield", "type": "unique very high"},
	"0 Chateau Map": {"base": "Chateau Map", "type": "unique very high"},
	"0 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique very high"},
	"0 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique very high"},
	"0 Copper Plate": {"base": "Copper Plate", "type": "unique very high"},
	"0 Corrugated Buckler": {"base": "Corrugated Buckler", "type": "unique very high"},
	"0 Courtyard Map": {"base": "Courtyard Map", "type": "unique very high"},
	"0 Crusader Boots": {"base": "Crusader Boots", "type": "unique very high"},
	"0 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique very high"},
	"0 Deerskin Gloves": {"base": "Deerskin Gloves", "type": "unique very high"},
	"0 Deicide Mask": {"base": "Deicide Mask", "type": "unique very high"},
	"0 Desert Brigandine": {"base": "Desert Brigandine", "type": "unique very high"},
	"0 Despot Axe": {"base": "Despot Axe", "type": "unique very high"},
	"0 Etched Greatsword": {"base": "Etched Greatsword", "type": "unique very high"},
	"0 Exquisite Leather": {"base": "Exquisite Leather", "type": "unique very high"},
	"0 Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "type": "unique very high"},
	"0 Festival Mask": {"base": "Festival Mask", "type": "unique very high"},
	"0 Fishing Rod": {"base": "Fishing Rod", "type": "unique very high"},
	"0 Full Dragonscale": {"base": "Full Dragonscale", "type": "unique very high"},
	"0 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique very high"},
	"0 Glorious Plate": {"base": "Glorious Plate", "type": "unique very high"},
	"0 Golden Flame": {"base": "Golden Flame", "type": "unique very high"},
	"0 Golden Hoop": {"base": "Golden Hoop", "type": "unique very high"},
	"0 Golden Mantle": {"base": "Golden Mantle", "type": "unique very high"},
	"0 Golden Plate": {"base": "Golden Plate", "type": "unique very high"},
	"0 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique very high"},
	"0 Granite Flask": {"base": "Granite Flask", "type": "unique very high"},
	"0 Graveyard Map": {"base": "Graveyard Map", "type": "unique very high"},
	"0 Harbinger Bow": {"base": "Harbinger Bow", "type": "unique very high"},
	"0 Holy Chainmail": {"base": "Holy Chainmail", "type": "unique very high"},
	"0 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique very high"},
	"0 Imperial Bow": {"base": "Imperial Bow", "type": "unique very high"},
	"0 Imperial Staff": {"base": "Imperial Staff", "type": "unique very high"},
	"0 Infernal Sword": {"base": "Infernal Sword", "type": "unique very high"},
	"0 Ironscale Gauntlets": {"base": "Ironscale Gauntlets", "type": "unique very high"},
	"0 Jasper Chopper": {"base": "Jasper Chopper", "type": "unique very high"},
	"0 Jet Amulet": {"base": "Jet Amulet", "type": "unique very high"},
	"0 Judgement Staff": {"base": "Judgement Staff", "type": "unique very high"},
	"0 Karui Sceptre": {"base": "Karui Sceptre", "type": "unique very high"},
	"0 Lacquered Garb": {"base": "Lacquered Garb", "type": "unique very high"},
	"0 Legion Gloves": {"base": "Legion Gloves", "type": "unique very high"},
	"0 Lion Pelt": {"base": "Lion Pelt", "type": "unique very high"},
	"0 Long Bow": {"base": "Long Bow", "type": "unique very high"},
	"0 Long Staff": {"base": "Long Staff", "type": "unique very high"},
	"0 Meatgrinder": {"base": "Meatgrinder", "type": "unique very high"},
	"0 Midnight Blade": {"base": "Midnight Blade", "type": "unique very high"},
	"0 Mind Cage": {"base": "Mind Cage", "type": "unique very high"},
	"0 Moonstone Ring": {"base": "Moonstone Ring", "type": "unique very high"},
	"0 Murder Mitts": {"base": "Murder Mitts", "type": "unique very high"},
	"0 Nightmare Bascinet": {"base": "Nightmare Bascinet", "type": "unique very high"},
	"0 Nubuck Boots": {"base": "Nubuck Boots", "type": "unique very high"},
	"0 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique very high"},
	"0 Paua Ring": {"base": "Paua Ring", "type": "unique very high"},
	"0 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique very high"},
	"0 Pine Buckler": {"base": "Pine Buckler", "type": "unique very high"},
	"0 Primordial Staff": {"base": "Primordial Staff", "type": "unique very high"},
	"0 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique very high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique very high"},
	"0 Rotfeather Talisman": {"base": "Rotfeather Talisman", "type": "unique very high"},
	"0 Royal Axe": {"base": "Royal Axe", "type": "unique very high"},
	"0 Royal Bow": {"base": "Royal Bow", "type": "unique very high"},
	"0 Ruby Amulet": {"base": "Ruby Amulet", "type": "unique very high"},
	"0 Rustic Sash": {"base": "Rustic Sash", "type": "unique very high"},
	"0 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique very high"},
	"0 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"0 Savant's Robe": {"base": "Savant's Robe", "type": "unique very high"},
	"0 Scholar Boots": {"base": "Scholar Boots", "type": "unique very high"},
	"0 Serpentine Staff": {"base": "Serpentine Staff", "type": "unique very high"},
	"0 Sharkskin Tunic": {"base": "Sharkskin Tunic", "type": "unique very high"},
	"0 Short Bow": {"base": "Short Bow", "type": "unique very high"},
	"0 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"0 Silk Gloves": {"base": "Silk Gloves", "type": "unique very high"},
	"0 Silk Slippers": {"base": "Silk Slippers", "type": "unique very high"},
	"0 Silver Flask": {"base": "Silver Flask", "type": "unique very high"},
	"0 Soldier Gloves": {"base": "Soldier Gloves", "type": "unique very high"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique very high"},
	"0 Spine Bow": {"base": "Spine Bow", "type": "unique very high"},
	"0 Steelhead": {"base": "Steelhead", "type": "unique very high"},
	"0 Steelscale Gauntlets": {"base": "Steelscale Gauntlets", "type": "unique very high"},
	"0 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique very high"},
	"0 Studded Belt": {"base": "Studded Belt", "type": "unique very high"},
	"0 Temple Map": {"base": "Temple Map", "type": "unique very high"},
	"0 Terror Claw": {"base": "Terror Claw", "type": "unique very high"},
	"0 Titan Gauntlets": {"base": "Titan Gauntlets", "type": "unique very high"},
	"0 Topaz Flask": {"base": "Topaz Flask", "type": "unique very high"},
	"0 Tornado Wand": {"base": "Tornado Wand", "type": "unique very high"},
	"0 Triumphant Lamellar": {"base": "Triumphant Lamellar", "type": "unique very high"},
	"0 Turquoise Amulet": {"base": "Turquoise Amulet", "type": "unique very high"},
	"0 Ursine Pelt": {"base": "Ursine Pelt", "type": "unique very high"},
	"0 Vaal Blade": {"base": "Vaal Blade", "type": "unique very high"},
	"0 Vaal Mask": {"base": "Vaal Mask", "type": "unique very high"},
	"0 Vaal Regalia": {"base": "Vaal Regalia", "type": "unique very high"},
	"0 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique very high"},
	"0 Void Sceptre": {"base": "Void Sceptre", "type": "unique very high"},
	"0 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique very high"},
	"0 Zealot Helmet": {"base": "Zealot Helmet", "type": "unique very high"},
	"0 Zodiac Leather": {"base": "Zodiac Leather", "type": "unique very high"},
	"1 Ancient Gauntlets": {"base": "Ancient Gauntlets", "type": "unique high"},
	"1 Arcanist Gloves": {"base": "Arcanist Gloves", "type": "unique high"},
	"1 Baroque Round Shield": {"base": "Baroque Round Shield", "type": "unique high"},
	"1 Black Maw Talisman": {"base": "Black Maw Talisman", "type": "unique high"},
	"1 Branded Kite Shield": {"base": "Branded Kite Shield", "type": "unique high"},
	"1 Bronzescale Gauntlets": {"base": "Bronzescale Gauntlets", "type": "unique high"},
	"1 Burnished Spiked Shield": {"base": "Burnished Spiked Shield", "type": "unique high"},
	"1 Coiled Staff": {"base": "Coiled Staff", "type": "unique high"},
	"1 Conjurer Gloves": {"base": "Conjurer Gloves", "type": "unique high"},
	"1 Conquest Chainmail": {"base": "Conquest Chainmail", "type": "unique high"},
	"1 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique high"},
	"1 Cutthroat's Garb": {"base": "Cutthroat's Garb", "type": "unique high"},
	"1 Death Bow": {"base": "Death Bow", "type": "unique high"},
	"1 Demon's Horn": {"base": "Demon's Horn", "type": "unique high"},
	"1 Diamond Ring": {"base": "Diamond Ring", "type": "unique high"},
	"1 Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "type": "unique high"},
	"1 Dread Maul": {"base": "Dread Maul", "type": "unique high"},
	"1 Elegant Foil": {"base": "Elegant Foil", "type": "unique high"},
	"1 Elegant Sword": {"base": "Elegant Sword", "type": "unique high"},
	"1 Engraved Wand": {"base": "Engraved Wand", "type": "unique high"},
	"1 Eternal Sword": {"base": "Eternal Sword", "type": "unique high"},
	"1 Eye Gouger": {"base": "Eye Gouger", "type": "unique high"},
	"1 Ezomyte Blade": {"base": "Ezomyte Blade", "type": "unique high"},
	"1 Fiend Dagger": {"base": "Fiend Dagger", "type": "unique high"},
	"1 Flaying Knife": {"base": "Flaying Knife", "type": "unique high"},
	"1 Gladius": {"base": "Gladius", "type": "unique high"},
	"1 Great Crown": {"base": "Great Crown", "type": "unique high"},
	"1 Greater Mana Flask": {"base": "Greater Mana Flask", "type": "unique high"},
	"1 Imperial Claw": {"base": "Imperial Claw", "type": "unique high"},
	"1 Imperial Skean": {"base": "Imperial Skean", "type": "unique high"},
	"1 Iron Circlet": {"base": "Iron Circlet", "type": "unique high"},
	"1 Iron Ring": {"base": "Iron Ring", "type": "unique high"},
	"1 Ivory Spirit Shield": {"base": "Ivory Spirit Shield", "type": "unique high"},
	"1 Karui Chopper": {"base": "Karui Chopper", "type": "unique high"},
	"1 Laminated Kite Shield": {"base": "Laminated Kite Shield", "type": "unique high"},
	"1 Leather Cap": {"base": "Leather Cap", "type": "unique high"},
	"1 Legion Sword": {"base": "Legion Sword", "type": "unique high"},
	"1 Mosaic Kite Shield": {"base": "Mosaic Kite Shield", "type": "unique high"},
	"1 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique high"},
	"1 Opal Wand": {"base": "Opal Wand", "type": "unique high"},
	"1 Painted Tower Shield": {"base": "Painted Tower Shield", "type": "unique high"},
	"1 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique high"},
	"1 Quartz Wand": {"base": "Quartz Wand", "type": "unique high"},
	"1 Raven Mask": {"base": "Raven Mask", "type": "unique high"},
	"1 Reef Map": {"base": "Reef Map", "type": "unique high"},
	"1 Regicide Mask": {"base": "Regicide Mask", "type": "unique high"},
	"1 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique high"},
	"1 Ruby Ring": {"base": "Ruby Ring", "type": "unique high"},
	"1 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique high"},
	"1 Saintly Chainmail": {"base": "Saintly Chainmail", "type": "unique high"},
	"1 Samite Helmet": {"base": "Samite Helmet", "type": "unique high"},
	"1 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique high"},
	"1 Serpentscale Boots": {"base": "Serpentscale Boots", "type": "unique high"},
	"1 Shadow Sceptre": {"base": "Shadow Sceptre", "type": "unique high"},
	"1 Sinner Tricorne": {"base": "Sinner Tricorne", "type": "unique high"},
	"1 Slaughter Knife": {"base": "Slaughter Knife", "type": "unique high"},
	"1 Sledgehammer": {"base": "Sledgehammer", "type": "unique high"},
	"1 Slink Boots": {"base": "Slink Boots", "type": "unique high"},
	"1 Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "type": "unique high"},
	"1 Strapped Mitts": {"base": "Strapped Mitts", "type": "unique high"},
	"1 Sulphur Flask": {"base": "Sulphur Flask", "type": "unique high"},
	"1 Trapper Boots": {"base": "Trapper Boots", "type": "unique high"},
	"1 Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "type": "unique high"},
	"1 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique high"},
	"1 Unset Ring": {"base": "Unset Ring", "type": "unique high"},
	"1 Vaal Buckler": {"base": "Vaal Buckler", "type": "unique high"},
	"1 Vaal Hatchet": {"base": "Vaal Hatchet", "type": "unique high"},
	"1 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique high"},
	"1 Whalebone Rapier": {"base": "Whalebone Rapier", "type": "unique high"},
	"1 Widowsilk Robe": {"base": "Widowsilk Robe", "type": "unique high"},
	"1 Wool Shoes": {"base": "Wool Shoes", "type": "unique high"},
	"9 Other uniques": {"type": "unique normal"}
}
