#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 09/05/2016(m/d/y) 00:10:44 UTC from "Standard" data
"""
* Copyright (c) 2016 Jeremy Parks. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.

Author: Jeremy Parks
Purpose: Create an item filter based on config files
Note: Requires Python 3.4.x
"""

desc = "Unique"

# Base type : settings pair
items = {
	"0 Amber Amulet": {"base": "Amber Amulet", "type": "unique very high"},
	"0 Arcanist Gloves": {"base": "Arcanist Gloves", "type": "unique very high"},
	"0 Archon Kite Shield": {"base": "Archon Kite Shield", "type": "unique very high"},
	"0 Assassin's Garb": {"base": "Assassin's Garb", "type": "unique very high"},
	"0 Broadhead Arrow Quiver": {"base": "Broadhead Arrow Quiver", "type": "unique very high"},
	"0 Carnal Sceptre": {"base": "Carnal Sceptre", "type": "unique very high"},
	"0 Cedar Tower Shield": {"base": "Cedar Tower Shield", "type": "unique very high"},
	"0 Champion Kite Shield": {"base": "Champion Kite Shield", "type": "unique very high"},
	"0 Chateau Map": {"base": "Chateau Map", "type": "unique very high"},
	"0 Citrine Amulet": {"base": "Citrine Amulet", "type": "unique very high"},
	"0 Clasped Boots": {"base": "Clasped Boots", "type": "unique very high"},
	"0 Clasped Mitts": {"base": "Clasped Mitts", "type": "unique very high"},
	"0 Cobalt Jewel": {"base": "Cobalt Jewel", "type": "unique very high"},
	"0 Conjurer Gloves": {"base": "Conjurer Gloves", "type": "unique very high"},
	"0 Corrugated Buckler": {"base": "Corrugated Buckler", "type": "unique very high"},
	"0 Courtyard Map": {"base": "Courtyard Map", "type": "unique very high"},
	"0 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique very high"},
	"0 Crusader Boots": {"base": "Crusader Boots", "type": "unique very high"},
	"0 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique very high"},
	"0 Crusader Plate": {"base": "Crusader Plate", "type": "unique very high"},
	"0 Deicide Mask": {"base": "Deicide Mask", "type": "unique very high"},
	"0 Despot Axe": {"base": "Despot Axe", "type": "unique very high"},
	"0 Destiny Leather": {"base": "Destiny Leather", "type": "unique very high"},
	"0 Diamond Ring": {"base": "Diamond Ring", "type": "unique very high"},
	"0 Dragonscale Boots": {"base": "Dragonscale Boots", "type": "unique very high"},
	"0 Enameled Buckler": {"base": "Enameled Buckler", "type": "unique very high"},
	"0 Etched Greatsword": {"base": "Etched Greatsword", "type": "unique very high"},
	"0 Eternal Sword": {"base": "Eternal Sword", "type": "unique very high"},
	"0 Exquisite Leather": {"base": "Exquisite Leather", "type": "unique very high"},
	"0 Fiend Dagger": {"base": "Fiend Dagger", "type": "unique very high"},
	"0 Fishing Rod": {"base": "Fishing Rod", "type": "unique very high"},
	"0 Gilded Sallet": {"base": "Gilded Sallet", "type": "unique very high"},
	"0 Glorious Plate": {"base": "Glorious Plate", "type": "unique very high"},
	"0 Golden Flame": {"base": "Golden Flame", "type": "unique very high"},
	"0 Golden Hoop": {"base": "Golden Hoop", "type": "unique very high"},
	"0 Golden Mantle": {"base": "Golden Mantle", "type": "unique very high"},
	"0 Goliath Gauntlets": {"base": "Goliath Gauntlets", "type": "unique very high"},
	"0 Graveyard Map": {"base": "Graveyard Map", "type": "unique very high"},
	"0 Greater Mana Flask": {"base": "Greater Mana Flask", "type": "unique very high"},
	"0 Harlequin Mask": {"base": "Harlequin Mask", "type": "unique very high"},
	"0 Hellion's Paw": {"base": "Hellion's Paw", "type": "unique very high"},
	"0 Holy Chainmail": {"base": "Holy Chainmail", "type": "unique very high"},
	"0 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique very high"},
	"0 Infernal Sword": {"base": "Infernal Sword", "type": "unique very high"},
	"0 Jasper Chopper": {"base": "Jasper Chopper", "type": "unique very high"},
	"0 Jet Amulet": {"base": "Jet Amulet", "type": "unique very high"},
	"0 Karui Sceptre": {"base": "Karui Sceptre", "type": "unique very high"},
	"0 Legion Gloves": {"base": "Legion Gloves", "type": "unique very high"},
	"0 Lion Pelt": {"base": "Lion Pelt", "type": "unique very high"},
	"0 Long Bow": {"base": "Long Bow", "type": "unique very high"},
	"0 Meatgrinder": {"base": "Meatgrinder", "type": "unique very high"},
	"0 Midnight Blade": {"base": "Midnight Blade", "type": "unique very high"},
	"0 Mind Cage": {"base": "Mind Cage", "type": "unique very high"},
	"0 Nightmare Bascinet": {"base": "Nightmare Bascinet", "type": "unique very high"},
	"0 Occultist's Vestment": {"base": "Occultist's Vestment", "type": "unique very high"},
	"0 Opal Wand": {"base": "Opal Wand", "type": "unique very high"},
	"0 Paua Amulet": {"base": "Paua Amulet", "type": "unique very high"},
	"0 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique very high"},
	"0 Ranger Bow": {"base": "Ranger Bow", "type": "unique very high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique very high"},
	"0 Reaver Sword": {"base": "Reaver Sword", "type": "unique very high"},
	"0 Regicide Mask": {"base": "Regicide Mask", "type": "unique very high"},
	"0 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique very high"},
	"0 Rotfeather Talisman": {"base": "Rotfeather Talisman", "type": "unique very high"},
	"0 Royal Axe": {"base": "Royal Axe", "type": "unique very high"},
	"0 Royal Bow": {"base": "Royal Bow", "type": "unique very high"},
	"0 Ruby Amulet": {"base": "Ruby Amulet", "type": "unique very high"},
	"0 Rustic Sash": {"base": "Rustic Sash", "type": "unique very high"},
	"0 Sanctified Life Flask": {"base": "Sanctified Life Flask", "type": "unique very high"},
	"0 Sanctified Mana Flask": {"base": "Sanctified Mana Flask", "type": "unique very high"},
	"0 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"0 Sharkskin Boots": {"base": "Sharkskin Boots", "type": "unique very high"},
	"0 Sharkskin Tunic": {"base": "Sharkskin Tunic", "type": "unique very high"},
	"0 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"0 Silver Flask": {"base": "Silver Flask", "type": "unique very high"},
	"0 Simple Robe": {"base": "Simple Robe", "type": "unique very high"},
	"0 Sinner Tricorne": {"base": "Sinner Tricorne", "type": "unique very high"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique very high"},
	"0 Spine Bow": {"base": "Spine Bow", "type": "unique very high"},
	"0 Steelhead": {"base": "Steelhead", "type": "unique very high"},
	"0 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique very high"},
	"0 Strapped Mitts": {"base": "Strapped Mitts", "type": "unique very high"},
	"0 Terror Maul": {"base": "Terror Maul", "type": "unique very high"},
	"0 Topaz Flask": {"base": "Topaz Flask", "type": "unique very high"},
	"0 Trapper Boots": {"base": "Trapper Boots", "type": "unique very high"},
	"0 Triumphant Lamellar": {"base": "Triumphant Lamellar", "type": "unique very high"},
	"0 Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "type": "unique very high"},
	"0 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique very high"},
	"0 Ursine Pelt": {"base": "Ursine Pelt", "type": "unique very high"},
	"0 Vaal Axe": {"base": "Vaal Axe", "type": "unique very high"},
	"0 Vaal Blade": {"base": "Vaal Blade", "type": "unique very high"},
	"0 Vaal Mask": {"base": "Vaal Mask", "type": "unique very high"},
	"0 Vaal Regalia": {"base": "Vaal Regalia", "type": "unique very high"},
	"0 Varnished Coat": {"base": "Varnished Coat", "type": "unique very high"},
	"0 Vile Staff": {"base": "Vile Staff", "type": "unique very high"},
	"0 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique very high"},
	"0 Zealot Helmet": {"base": "Zealot Helmet", "type": "unique very high"},
	"1 Amethyst Ring": {"base": "Amethyst Ring", "type": "unique high"},
	"1 Ancient Greaves": {"base": "Ancient Greaves", "type": "unique high"},
	"1 Auric Mace": {"base": "Auric Mace", "type": "unique high"},
	"1 Black Maw Talisman": {"base": "Black Maw Talisman", "type": "unique high"},
	"1 Burnished Spiked Shield": {"base": "Burnished Spiked Shield", "type": "unique high"},
	"1 Chain Belt": {"base": "Chain Belt", "type": "unique high"},
	"1 Conjurer Boots": {"base": "Conjurer Boots", "type": "unique high"},
	"1 Conquest Chainmail": {"base": "Conquest Chainmail", "type": "unique high"},
	"1 Deerskin Gloves": {"base": "Deerskin Gloves", "type": "unique high"},
	"1 Demon's Horn": {"base": "Demon's Horn", "type": "unique high"},
	"1 Desert Brigandine": {"base": "Desert Brigandine", "type": "unique high"},
	"1 Dragonscale Gauntlets": {"base": "Dragonscale Gauntlets", "type": "unique high"},
	"1 Driftwood Wand": {"base": "Driftwood Wand", "type": "unique high"},
	"1 Dusk Blade": {"base": "Dusk Blade", "type": "unique high"},
	"1 Elder Sword": {"base": "Elder Sword", "type": "unique high"},
	"1 Engraved Wand": {"base": "Engraved Wand", "type": "unique high"},
	"1 Ezomyte Blade": {"base": "Ezomyte Blade", "type": "unique high"},
	"1 Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "type": "unique high"},
	"1 Full Scale Armour": {"base": "Full Scale Armour", "type": "unique high"},
	"1 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique high"},
	"1 Gold Amulet": {"base": "Gold Amulet", "type": "unique high"},
	"1 Gold Ring": {"base": "Gold Ring", "type": "unique high"},
	"1 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique high"},
	"1 Granite Flask": {"base": "Granite Flask", "type": "unique high"},
	"1 Great Mallet": {"base": "Great Mallet", "type": "unique high"},
	"1 Hallowed Hybrid Flask": {"base": "Hallowed Hybrid Flask", "type": "unique high"},
	"1 Imperial Claw": {"base": "Imperial Claw", "type": "unique high"},
	"1 Imperial Skean": {"base": "Imperial Skean", "type": "unique high"},
	"1 Imperial Staff": {"base": "Imperial Staff", "type": "unique high"},
	"1 Iron Ring": {"base": "Iron Ring", "type": "unique high"},
	"1 Ironscale Gauntlets": {"base": "Ironscale Gauntlets", "type": "unique high"},
	"1 Jade Amulet": {"base": "Jade Amulet", "type": "unique high"},
	"1 Jagged Foil": {"base": "Jagged Foil", "type": "unique high"},
	"1 Judgement Staff": {"base": "Judgement Staff", "type": "unique high"},
	"1 Karui Maul": {"base": "Karui Maul", "type": "unique high"},
	"1 Lacquered Garb": {"base": "Lacquered Garb", "type": "unique high"},
	"1 Laminated Kite Shield": {"base": "Laminated Kite Shield", "type": "unique high"},
	"1 Large Hybrid Flask": {"base": "Large Hybrid Flask", "type": "unique high"},
	"1 Lathi": {"base": "Lathi", "type": "unique high"},
	"1 Leather Belt": {"base": "Leather Belt", "type": "unique high"},
	"1 Legion Sword": {"base": "Legion Sword", "type": "unique high"},
	"1 Long Staff": {"base": "Long Staff", "type": "unique high"},
	"1 Maelström Staff": {"base": "Maelström Staff", "type": "unique high"},
	"1 Maze Map": {"base": "Maze Map", "type": "unique high"},
	"1 Necromancer Silks": {"base": "Necromancer Silks", "type": "unique high"},
	"1 Nubuck Boots": {"base": "Nubuck Boots", "type": "unique high"},
	"1 Ornate Sword": {"base": "Ornate Sword", "type": "unique high"},
	"1 Painted Tower Shield": {"base": "Painted Tower Shield", "type": "unique high"},
	"1 Paua Ring": {"base": "Paua Ring", "type": "unique high"},
	"1 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique high"},
	"1 Plate Vest": {"base": "Plate Vest", "type": "unique high"},
	"1 Platinum Sceptre": {"base": "Platinum Sceptre", "type": "unique high"},
	"1 Quicksilver Flask": {"base": "Quicksilver Flask", "type": "unique high"},
	"1 Raven Mask": {"base": "Raven Mask", "type": "unique high"},
	"1 Reef Map": {"base": "Reef Map", "type": "unique high"},
	"1 Reinforced Greaves": {"base": "Reinforced Greaves", "type": "unique high"},
	"1 Ruby Ring": {"base": "Ruby Ring", "type": "unique high"},
	"1 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique high"},
	"1 Saintly Chainmail": {"base": "Saintly Chainmail", "type": "unique high"},
	"1 Savant's Robe": {"base": "Savant's Robe", "type": "unique high"},
	"1 Serpentine Staff": {"base": "Serpentine Staff", "type": "unique high"},
	"1 Slaughter Knife": {"base": "Slaughter Knife", "type": "unique high"},
	"1 Sledgehammer": {"base": "Sledgehammer", "type": "unique high"},
	"1 Slink Boots": {"base": "Slink Boots", "type": "unique high"},
	"1 Soldier Boots": {"base": "Soldier Boots", "type": "unique high"},
	"1 Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "type": "unique high"},
	"1 Studded Belt": {"base": "Studded Belt", "type": "unique high"},
	"1 Sulphur Flask": {"base": "Sulphur Flask", "type": "unique high"},
	"1 Tarnished Spirit Shield": {"base": "Tarnished Spirit Shield", "type": "unique high"},
	"1 Temple Map": {"base": "Temple Map", "type": "unique high"},
	"1 Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "type": "unique high"},
	"1 Topaz Ring": {"base": "Topaz Ring", "type": "unique high"},
	"1 Tornado Wand": {"base": "Tornado Wand", "type": "unique high"},
	"1 Unset Ring": {"base": "Unset Ring", "type": "unique high"},
	"1 Vaal Pyramid Map": {"base": "Vaal Pyramid Map", "type": "unique high"},
	"1 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique high"},
	"1 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique high"},
	"1 Whalebone Rapier": {"base": "Whalebone Rapier", "type": "unique high"},
	"1 Widowsilk Robe": {"base": "Widowsilk Robe", "type": "unique high"},
	"1 Woodsplitter": {"base": "Woodsplitter", "type": "unique high"},
	"1 Wyrmscale Gauntlets": {"base": "Wyrmscale Gauntlets", "type": "unique high"},
	"9 Other uniques": {"type": "unique normal"}
}
